using System.Text.Json;
using CreatorPay.Application.Notifications;
using CreatorPay.Domain.Entities;
using CreatorPay.Domain.Enums;
using CreatorPay.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace CreatorPay.Infrastructure.Notifications;

public sealed class NotificationOutboxProcessor(ApplicationDbContext db, INotificationTemplateRenderer renderer, INotificationDispatcher dispatcher, IOptions<NotificationOptions> configured) : INotificationOutboxProcessor
{
    readonly NotificationOptions options = configured.Value;
    public async Task<int> ProcessBatchAsync(string worker, CancellationToken ct) { var now = DateTime.UtcNow; var candidates = await db.NotificationOutboxMessages.Where(x => (x.Status == NotificationOutboxStatus.Pending || x.Status == NotificationOutboxStatus.Failed || (x.Status == NotificationOutboxStatus.Processing && x.LockedAtUtc < now.AddMinutes(-options.LockTimeoutMinutes))) && x.AvailableAtUtc <= now).OrderBy(x => x.AvailableAtUtc).Take(options.BatchSize).Select(x => x.Id).ToListAsync(ct); var processed = 0; foreach (var id in candidates) { if (!await Claim(id, worker, ct)) continue; await Process(id, ct); processed++; } return processed; }
    async Task<bool> Claim(Guid id, string worker, CancellationToken ct) { var now = DateTime.UtcNow; var count = await db.NotificationOutboxMessages.Where(x => x.Id == id && (x.Status == NotificationOutboxStatus.Pending || x.Status == NotificationOutboxStatus.Failed || (x.Status == NotificationOutboxStatus.Processing && x.LockedAtUtc < now.AddMinutes(-options.LockTimeoutMinutes)))).ExecuteUpdateAsync(s => s.SetProperty(x => x.Status, NotificationOutboxStatus.Processing).SetProperty(x => x.LockedAtUtc, now).SetProperty(x => x.LockedBy, worker).SetProperty(x => x.LastAttemptAtUtc, now).SetProperty(x => x.AttemptCount, x => x.AttemptCount + 1), ct); return count == 1; }
    async Task Process(Guid id, CancellationToken ct)
    {
        db.ChangeTracker.Clear(); var m = await db.NotificationOutboxMessages.Include(x => x.Notification).ThenInclude(x => x.Recipients).SingleAsync(x => x.Id == id, ct); var n = m.Notification; if (n.ExpiresAtUtc <= DateTime.UtcNow) { m.Status = NotificationOutboxStatus.Cancelled; n.Status = NotificationStatus.Expired; await db.SaveChangesAsync(ct); return; }
        var data = JsonSerializer.Deserialize<Dictionary<string, string>>(n.DataJson) ?? []; var failed = false; var transient = false; foreach (var r in n.Recipients.Where(x => x.Status is NotificationRecipientStatus.Pending or NotificationRecipientStatus.Failed)) { var attemptNumber = await db.NotificationDeliveryAttempts.CountAsync(x => x.NotificationRecipientId == r.Id, ct) + 1; var template = await FindTemplate(n.NotificationType, r.Channel, r.LanguageCode, ct); var allowed = template is null ? data.Keys.ToArray() : JsonSerializer.Deserialize<string[]>(template.AllowedPlaceholdersJson) ?? []; var subject = template is null ? n.Title : renderer.Render(template.SubjectTemplate ?? n.Title, data, allowed); var body = template is null ? n.Body : renderer.Render(template.BodyTemplate, data, allowed); var a = new NotificationDeliveryAttempt { Id = Guid.NewGuid(), NotificationRecipientId = r.Id, Channel = r.Channel, ProviderName = $"Development{r.Channel}", AttemptNumber = attemptNumber, Status = DeliveryAttemptStatus.Processing, StartedAtUtc = DateTime.UtcNow, CreatedAtUtc = DateTime.UtcNow }; db.Add(a); r.Status = NotificationRecipientStatus.Processing; await db.SaveChangesAsync(ct); NotificationProviderResult result; try { result = await dispatcher.DispatchAsync(r.Channel, new(n.PublicNotificationId, n.NotificationType, subject, body, r.DestinationReference, r.MaskedDestination, data), ct); } catch (Exception e) { result = new(false, null, DeliveryAttemptStatus.Failed, "PROVIDER_EXCEPTION", e.Message, true); } a.Status = result.DeliveryStatus; a.ProviderMessageReference = result.ProviderReference; a.ErrorCode = result.ErrorCode; a.ErrorMessage = Safe(result.ErrorMessage); a.IsTransientFailure = result.IsTransient; a.CompletedAtUtc = DateTime.UtcNow; if (result.Accepted) { r.Status = result.DeliveryStatus == DeliveryAttemptStatus.Delivered ? NotificationRecipientStatus.Delivered : NotificationRecipientStatus.Submitted; r.DeliveredAtUtc = result.DeliveryStatus == DeliveryAttemptStatus.Delivered ? DateTime.UtcNow : null; } else { failed = true; transient |= result.IsTransient; r.Status = NotificationRecipientStatus.Failed; r.FailedAtUtc = DateTime.UtcNow; r.FailureReason = Safe(result.ErrorMessage); } db.NotificationAuditEvents.Add(new() { Id = Guid.NewGuid(), NotificationId = n.Id, EventType = result.Accepted ? "DeliverySubmitted" : "DeliveryFailed", SafeDetail = $"Channel={r.Channel};Code={result.ErrorCode}", CreatedAtUtc = DateTime.UtcNow }); await db.SaveChangesAsync(ct); }
        foreach (var invalidDevice in n.Recipients.Where(x => x.PushDeviceRegistrationId.HasValue && x.FailureReason == "The push device is no longer registered.")) { var device = await db.PushDeviceRegistrations.FindAsync([invalidDevice.PushDeviceRegistrationId!.Value], ct); if (device is not null) { device.IsActive = false; device.RevokedAtUtc = DateTime.UtcNow; device.FailureCode = "FCM_TOKEN_INVALID"; device.FailureAtUtc = DateTime.UtcNow; } }
        if (!failed) { m.Status = NotificationOutboxStatus.Completed; m.ProcessedAtUtc = DateTime.UtcNow; m.LockedAtUtc = null; m.LockedBy = null; n.Status = NotificationStatus.Delivered; n.SentAtUtc ??= DateTime.UtcNow; n.CompletedAtUtc = DateTime.UtcNow; }
        else if (transient && m.AttemptCount < options.MaximumAttempts) { m.Status = NotificationOutboxStatus.Failed; m.AvailableAtUtc = DateTime.UtcNow.AddSeconds(Math.Min(options.InitialRetryDelaySeconds * Math.Pow(2, m.AttemptCount - 1), options.MaximumRetryDelayMinutes * 60)); m.LastError = "One or more transient delivery failures."; m.LockedAtUtc = null; m.LockedBy = null; }
        else { m.Status = NotificationOutboxStatus.DeadLettered; n.Status = n.Recipients.Any(x => x.Status is NotificationRecipientStatus.Delivered or NotificationRecipientStatus.Submitted) ? NotificationStatus.PartiallySent : NotificationStatus.Failed; var dead = await db.NotificationDeadLetters.SingleOrDefaultAsync(x => x.OutboxMessageId == m.Id, ct); if (dead is null) db.NotificationDeadLetters.Add(new() { Id = Guid.NewGuid(), OutboxMessageId = m.Id, Status = NotificationDeadLetterStatus.Open, Reason = transient ? "Maximum attempts exhausted." : "Permanent provider failure.", DeadLetteredAtUtc = DateTime.UtcNow, CreatedAtUtc = DateTime.UtcNow }); else { dead.Status = NotificationDeadLetterStatus.Open; dead.Reason = transient ? "Maximum attempts exhausted." : "Permanent provider failure."; dead.DeadLetteredAtUtc = DateTime.UtcNow; dead.ResolvedAtUtc = null; dead.ResolvedByUserId = null; } db.NotificationAuditEvents.Add(new() { Id = Guid.NewGuid(), NotificationId = n.Id, EventType = "MessageDeadLettered", SafeDetail = $"OutboxMessageId={m.Id}", CreatedAtUtc = DateTime.UtcNow }); }
        await db.SaveChangesAsync(ct);
    }
    async Task<NotificationTemplate?> FindTemplate(NotificationType type, NotificationChannel channel, string language, CancellationToken ct) { var now = DateTime.UtcNow; var x = await db.NotificationTemplates.AsNoTracking().Where(x => x.NotificationType == type && x.Channel == channel && x.LanguageCode == language && x.IsActive && x.EffectiveFromUtc <= now && (x.EffectiveToUtc == null || x.EffectiveToUtc > now)).OrderByDescending(x => x.VersionNumber).FirstOrDefaultAsync(ct); if (x is null && language != "en") x = await db.NotificationTemplates.AsNoTracking().Where(x => x.NotificationType == type && x.Channel == channel && x.LanguageCode == "en" && x.IsActive && x.EffectiveFromUtc <= now && (x.EffectiveToUtc == null || x.EffectiveToUtc > now)).OrderByDescending(x => x.VersionNumber).FirstOrDefaultAsync(ct); return x; }
    static string? Safe(string? x) => x is null ? null : x[..Math.Min(500, x.Length)];
}
public sealed class NotificationOutboxBackgroundService(IServiceScopeFactory scopes, IOptions<NotificationOptions> configured, ILogger<NotificationOutboxBackgroundService> logger) : BackgroundService
{
    readonly NotificationOptions options = configured.Value;
    protected override async Task ExecuteAsync(CancellationToken stoppingToken) { var worker = $"api-{Environment.MachineName}-{Guid.NewGuid():N}"; while (!stoppingToken.IsCancellationRequested) { try { using var scope = scopes.CreateScope(); await scope.ServiceProvider.GetRequiredService<INotificationOutboxProcessor>().ProcessBatchAsync(worker, stoppingToken); } catch (OperationCanceledException) when (stoppingToken.IsCancellationRequested) { break; } catch (Exception e) { logger.LogError(e, "Notification outbox processing failed."); } await Task.Delay(TimeSpan.FromSeconds(Math.Max(1, options.PollIntervalSeconds)), stoppingToken); } }
}
