using System.Data;
using CreatorPay.Application.Earnings;
using CreatorPay.Application.Notifications;
using CreatorPay.Domain.Entities;
using CreatorPay.Domain.Enums;
using CreatorPay.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace CreatorPay.Infrastructure.Earnings;

public sealed class CreatorEarningsService(ApplicationDbContext db, IPayoutProvider provider, IOptions<CreatorPayoutOptions> options, INotificationService notifications) : ICreatorEarningsService
{
    private readonly CreatorPayoutOptions settings = options.Value;
    public async Task RecordConfirmedPurchaseAsync(Guid transactionId, Guid creatorId, Guid snapshotId, decimal amount, string currency, DateTime confirmedAt, string correlationId, CancellationToken ct) { if (await db.CreatorEarnings.AnyAsync(x => x.PurchaseTransactionId == transactionId, ct)) return; var account = await Account(creatorId, currency, confirmedAt, ct); var earning = new CreatorEarning { Id = Guid.NewGuid(), CreatorId = creatorId, PurchaseTransactionId = transactionId, CommissionCalculationSnapshotId = snapshotId, Amount = amount, CurrencyCode = currency, EarnedAtUtc = confirmedAt, AvailableAtUtc = confirmedAt.AddDays(settings.CreatorEarningHoldingPeriodDays), CreatedAtUtc = confirmedAt, CorrelationId = correlationId }; var b = account.CreditPending(amount, confirmedAt); db.Add(earning); db.Add(Entry(account, CreatorBalanceEntryType.EarningPendingCredit, CreatorBalanceCategory.Pending, amount, b, confirmedAt, $"earning:{transactionId}", earning.Id, null, transactionId)); Audit(creatorId, null, "CreatorEarningCreated", $"EarningId={earning.Id};Amount={amount}", confirmedAt); await NotifyCreator(creatorId, NotificationType.CreatorEarningConfirmed, $"earning-confirmed:{transactionId}", "Earning recorded", $"{amount} {currency} was recorded as pending. Payout occurs on the weekly schedule.", correlationId, "PurchaseTransaction", transactionId.ToString(), ct); }
    public async Task<IReadOnlyList<EarningDto>> GetEarningsAsync(Guid creatorId, string? status, CancellationToken ct) { var q = db.CreatorEarnings.AsNoTracking().Where(x => x.CreatorId == creatorId); if (Enum.TryParse<CreatorEarningStatus>(status, true, out var s)) q = q.Where(x => x.Status == s); return await q.OrderByDescending(x => x.EarnedAtUtc).Select(x => Map(x)).ToListAsync(ct); }
    public async Task<EarningDto> GetEarningAsync(Guid creatorId, Guid id, CancellationToken ct) => Map(await db.CreatorEarnings.AsNoTracking().SingleOrDefaultAsync(x => x.Id == id && x.CreatorId == creatorId, ct) ?? throw new KeyNotFoundException("Earning was not found."));
    public async Task<BalanceSummaryDto> GetSummaryAsync(Guid creatorId, DateTime now, CancellationToken ct) { var a = await db.CreatorBalanceAccounts.AsNoTracking().SingleOrDefaultAsync(x => x.CreatorId == creatorId && x.CurrencyCode == settings.CurrencyCode, ct); var schedule = await db.PayoutScheduleVersions.AsNoTracking().Where(x => x.CurrencyCode == settings.CurrencyCode && x.EffectiveFromUtc <= now).OrderByDescending(x => x.EffectiveFromUtc).ThenByDescending(x => x.VersionNumber).FirstOrDefaultAsync(ct); var fallback = await db.PlatformFinancialSettings.AsNoTracking().SingleOrDefaultAsync(x => x.CurrencyCode == settings.CurrencyCode, ct); var cutoff = PayoutSchedule.PreviousWeeklyCutoff(now, schedule?.CreatorCutoffDay ?? fallback?.CreatorCutoffDay ?? DayOfWeek.Friday, schedule?.CreatorCutoffTime ?? fallback?.CreatorCutoffTime ?? TimeSpan.Zero); var last = await db.CreatorPayouts.Where(x => x.CreatorId == creatorId && x.Status == CreatorPayoutStatus.Paid).MaxAsync(x => (DateTime?)x.PaidAtUtc, ct); var start = last.HasValue && last > cutoff ? last.Value : cutoff; var current = await db.CreatorEarnings.Where(x => x.CreatorId == creatorId && x.EarnedAtUtc >= start && x.Status != CreatorEarningStatus.Paid && x.Status != CreatorEarningStatus.Reversed && x.Status != CreatorEarningStatus.ScheduledForPayout).SumAsync(x => (decimal?)x.Amount, ct) ?? 0m; var sales = await db.PurchaseTransactions.CountAsync(x => x.CreatorId == creatorId && x.TransactionDateUtc >= start && (x.Status == TransactionStatus.Confirmed || x.Status == TransactionStatus.Settled), ct); var next = PayoutSchedule.NextWeekly(now, schedule?.CreatorPayoutDay ?? fallback?.CreatorPayoutDay ?? settings.WeeklyPayoutDay, TimeSpan.Zero); return a is null ? new(settings.CurrencyCode, 0, 0, 0, 0, 0, 0, next, current, sales, last, start) : new(a.CurrencyCode, a.PendingBalance, a.AvailableBalance, a.HeldBalance, a.ScheduledBalance, a.PaidLifetimeTotal, a.ReversedLifetimeTotal, next, current, sales, last, start); }
    public async Task<int> MatureAsync(DateTime now, Guid actor, CancellationToken ct) { await using var tx = await db.Database.BeginTransactionAsync(IsolationLevel.Serializable, ct); var earnings = await db.CreatorEarnings.Where(x => x.Status == CreatorEarningStatus.Pending && x.AvailableAtUtc <= now).ToListAsync(ct); foreach (var e in earnings) { var a = await Account(e.CreatorId, e.CurrencyCode, now, ct); e.MakeAvailable(now); var b = a.Transfer(CreatorBalanceCategory.Pending, CreatorBalanceCategory.Available, e.Amount, now); db.Add(Entry(a, CreatorBalanceEntryType.PendingToAvailable, CreatorBalanceCategory.Available, e.Amount, b, now, $"mature:{e.Id}", e.Id, null, e.PurchaseTransactionId)); Audit(e.CreatorId, actor, "EarningMatured", $"EarningId={e.Id}", now); await NotifyCreator(e.CreatorId, NotificationType.CreatorEarningAvailable, $"earning-available:{e.Id}", "Earning available", $"{e.Amount} {e.CurrencyCode} is now available for payout.", e.CorrelationId, "CreatorEarning", e.Id.ToString(), ct); } await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return earnings.Count; }
    public async Task<IReadOnlyList<PayoutDto>> GetPayoutsAsync(Guid? creatorId, CancellationToken ct) { var q = db.CreatorPayouts.AsNoTracking().AsQueryable(); if (creatorId.HasValue) q = q.Where(x => x.CreatorId == creatorId); return await q.OrderByDescending(x => x.ScheduledAtUtc).Select(x => Map(x, null)).ToListAsync(ct); }
    public async Task<PayoutDto> GetPayoutAsync(Guid? creatorId, Guid id, CancellationToken ct) { var p = await db.CreatorPayouts.AsNoTracking().Include(x => x.Items).ThenInclude(x => x.Earning).SingleOrDefaultAsync(x => x.Id == id && (!creatorId.HasValue || x.CreatorId == creatorId), ct) ?? throw new KeyNotFoundException("Payout was not found."); return Map(p, p.Items.Select(x => Map(x.Earning)).ToList()); }
    public async Task<IReadOnlyList<PayoutBatchDto>> GetBatchesAsync(CancellationToken ct) => await db.PayoutBatches.AsNoTracking().OrderByDescending(x => x.CreatedAtUtc).Select(x => Map(x, null)).ToListAsync(ct);
    public async Task<PayoutBatchDto> GetBatchAsync(Guid id, CancellationToken ct) { var b = await db.PayoutBatches.AsNoTracking().Include(x => x.Payouts).SingleOrDefaultAsync(x => x.Id == id, ct) ?? throw new KeyNotFoundException("Batch was not found."); return Map(b, b.Payouts.Select(x => Map(x, null)).ToList()); }
    public async Task<PayoutBatchDto> CreateBatchAsync(CreatePayoutBatchRequest r, Guid actor, DateTime now, CancellationToken ct) { if (r.CutoffAtUtc.Kind != DateTimeKind.Utc || r.ScheduledForUtc.Kind != DateTimeKind.Utc) throw new ArgumentException("Payout timestamps must be UTC."); var currency = r.CurrencyCode.Trim().ToUpperInvariant(); var prior = await db.PayoutBatches.AsNoTracking().SingleOrDefaultAsync(x => x.CurrencyCode == currency && x.CutoffAtUtc == r.CutoffAtUtc && x.CorrelationId == r.IdempotencyKey, ct); if (prior is not null) return await GetBatchAsync(prior.Id, ct); await MatureAsync(now, actor, ct); await using var tx = await db.Database.BeginTransactionAsync(IsolationLevel.Serializable, ct); var eligible = await db.CreatorEarnings.Where(x => x.CurrencyCode == currency && x.Status == CreatorEarningStatus.Available && x.EarnedAtUtc <= r.CutoffAtUtc && db.Creators.Any(c => c.Id == x.CreatorId && c.Status == CreatorStatus.Active)).OrderBy(x => x.EarnedAtUtc).ToListAsync(ct); var groups = eligible.GroupBy(x => x.CreatorId).Where(g => g.Sum(x => x.Amount) >= settings.MinimumCreatorPayoutAmount).ToList(); if (groups.Count == 0) throw new InvalidOperationException("No eligible Creator payouts are available for this cycle."); var batch = new PayoutBatch { Id = Guid.NewGuid(), PublicBatchId = $"PB-{Guid.NewGuid():N}", CurrencyCode = currency, Status = PayoutBatchStatus.Scheduled, CutoffAtUtc = r.CutoffAtUtc, ScheduledForUtc = r.ScheduledForUtc, CreatedAtUtc = now, CreatedByUserId = actor, CorrelationId = r.IdempotencyKey }; foreach (var g in groups) { var payout = new CreatorPayout { Id = Guid.NewGuid(), PublicPayoutId = $"PO-{Guid.NewGuid():N}", PayoutBatchId = batch.Id, CreatorId = g.Key, CurrencyCode = currency, Amount = g.Sum(x => x.Amount), Status = CreatorPayoutStatus.Scheduled, ScheduledAtUtc = r.ScheduledForUtc, IdempotencyKey = $"{r.IdempotencyKey}:{g.Key}", CorrelationId = r.IdempotencyKey, CreatedAtUtc = now }; var account = await Account(g.Key, currency, now, ct); foreach (var e in g) { e.Schedule(payout.Id, now); payout.Items.Add(new() { Id = Guid.NewGuid(), CreatorPayoutId = payout.Id, CreatorEarningId = e.Id, Amount = e.Amount, CurrencyCode = currency, CreatedAtUtc = now }); } var moved = account.Transfer(CreatorBalanceCategory.Available, CreatorBalanceCategory.Scheduled, payout.Amount, now); db.Add(Entry(account, CreatorBalanceEntryType.AvailableToScheduled, CreatorBalanceCategory.Scheduled, payout.Amount, moved, now, $"schedule:{payout.Id}", null, payout.Id, null)); batch.Payouts.Add(payout); Audit(g.Key, actor, "PayoutCreated", $"PayoutId={payout.Id};Amount={payout.Amount}", now); } batch.TotalCreatorCount = batch.Payouts.Count; batch.TotalAmount = batch.Payouts.Sum(x => x.Amount); db.Add(batch); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return await GetBatchAsync(batch.Id, ct); }
    public async Task<PayoutBatchDto> ProcessBatchAsync(Guid id, Guid actor, DateTime now, CancellationToken ct) { var b = await db.PayoutBatches.Include(x => x.Payouts).SingleOrDefaultAsync(x => x.Id == id, ct) ?? throw new KeyNotFoundException(); if (b.Status == PayoutBatchStatus.Processing) return await GetBatchAsync(id, ct); if (b.Status != PayoutBatchStatus.Scheduled) throw new InvalidOperationException("Only scheduled batches can start processing."); b.Status = PayoutBatchStatus.Processing; b.ProcessingStartedAtUtc = now; foreach (var p in b.Payouts.Where(x => x.Status == CreatorPayoutStatus.Scheduled)) p.Status = CreatorPayoutStatus.Processing; await db.SaveChangesAsync(ct); return await GetBatchAsync(id, ct); }
    public async Task<PayoutBatchDto> CancelBatchAsync(Guid id, Guid actor, DateTime now, CancellationToken ct) { var b = await db.PayoutBatches.Include(x => x.Payouts).ThenInclude(x => x.Items).ThenInclude(x => x.Earning).SingleOrDefaultAsync(x => x.Id == id, ct) ?? throw new KeyNotFoundException(); foreach (var p in b.Payouts.Where(x => x.Status is CreatorPayoutStatus.Scheduled or CreatorPayoutStatus.Draft or CreatorPayoutStatus.Processing)) await Release(p, CreatorPayoutStatus.Cancelled, "Batch cancelled", actor, now, ct); b.Status = PayoutBatchStatus.Cancelled; await db.SaveChangesAsync(ct); return await GetBatchAsync(id, ct); }
    public async Task<PayoutDto> SubmitAsync(Guid id, SubmitPayoutRequest r, Guid actor, DateTime now, CancellationToken ct) { var p = await Load(id, ct); if (p.Status == CreatorPayoutStatus.Submitted) return Map(p, null); if (p.Status is not (CreatorPayoutStatus.Scheduled or CreatorPayoutStatus.Processing)) throw new InvalidOperationException("Payout cannot be submitted in its current state."); var result = await provider.SubmitPayoutAsync(id, r.ProviderReference, ct); p.Status = CreatorPayoutStatus.Submitted; p.SubmittedAtUtc = now; p.ProviderReference = result.ProviderReference; p.Attempts.Add(Attempt(p, now, PayoutAttemptStatus.Submitted)); Audit(p.CreatorId, actor, "PayoutSubmitted", $"PayoutId={p.Id}", now); await db.SaveChangesAsync(ct); return Map(p, null); }
    public async Task<PayoutDto> MarkPaidAsync(Guid id, Guid actor, DateTime now, CancellationToken ct) { await using var tx = await db.Database.BeginTransactionAsync(IsolationLevel.Serializable, ct); var p = await Load(id, ct); if (p.Status == CreatorPayoutStatus.Paid) return Map(p, null); if (p.Status != CreatorPayoutStatus.Submitted) throw new InvalidOperationException("Only a submitted payout can be marked paid."); var account = await Account(p.CreatorId, p.CurrencyCode, now, ct); foreach (var i in p.Items) i.Earning.MarkPaid(now); var moved = account.Transfer(CreatorBalanceCategory.Scheduled, CreatorBalanceCategory.Paid, p.Amount, now); db.Add(Entry(account, CreatorBalanceEntryType.ScheduledToPaid, CreatorBalanceCategory.Paid, p.Amount, moved, now, $"paid:{p.Id}", null, p.Id, null)); p.Status = CreatorPayoutStatus.Paid; p.PaidAtUtc = now; p.Attempts.Add(Attempt(p, now, PayoutAttemptStatus.Paid)); var j = Journal(p, now); db.Add(j); Audit(p.CreatorId, actor, "PayoutMarkedPaid", $"PayoutId={p.Id}", now); await db.SaveChangesAsync(ct); var batch = await db.PayoutBatches.Include(x => x.Payouts).SingleAsync(x => x.Id == p.PayoutBatchId, ct); if (batch.Payouts.All(x => x.Status == CreatorPayoutStatus.Paid)) { batch.Status = PayoutBatchStatus.Completed; batch.CompletedAtUtc = now; } else if (batch.Payouts.Any(x => x.Status == CreatorPayoutStatus.Paid)) batch.Status = PayoutBatchStatus.PartiallyCompleted; await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return Map(p, null); }
    public async Task<PayoutDto> MarkFailedAsync(Guid id, FailPayoutRequest r, Guid actor, DateTime now, CancellationToken ct) { if (string.IsNullOrWhiteSpace(r.Reason)) throw new ArgumentException("A failure reason is required."); var p = await Load(id, ct); if (p.Status == CreatorPayoutStatus.Failed) return Map(p, null); await Release(p, CreatorPayoutStatus.Failed, r.Reason, actor, now, ct); p.FailedAtUtc = now; p.Attempts.Add(Attempt(p, now, PayoutAttemptStatus.Failed, r.Reason)); await db.SaveChangesAsync(ct); return Map(p, null); }
    public async Task<PayoutDto> RetryAsync(Guid id, Guid actor, DateTime now, CancellationToken ct) { var p = await Load(id, ct); if (p.Status != CreatorPayoutStatus.Failed) throw new InvalidOperationException("Only failed payouts can be retried."); var earnings = await db.CreatorEarnings.Where(x => p.Items.Select(i => i.CreatorEarningId).Contains(x.Id)).ToListAsync(ct); var account = await Account(p.CreatorId, p.CurrencyCode, now, ct); foreach (var e in earnings) e.Schedule(p.Id, now); var moved = account.Transfer(CreatorBalanceCategory.Available, CreatorBalanceCategory.Scheduled, p.Amount, now); db.Add(Entry(account, CreatorBalanceEntryType.AvailableToScheduled, CreatorBalanceCategory.Scheduled, p.Amount, moved, now, $"retry:{p.Id}:{p.RetryCount + 1}", null, p.Id, null)); p.Status = CreatorPayoutStatus.Scheduled; p.RetryCount++; p.FailureReason = null; Audit(p.CreatorId, actor, "PayoutRetried", $"PayoutId={p.Id};Retry={p.RetryCount}", now); await db.SaveChangesAsync(ct); return Map(p, null); }
    public async Task<PayoutDto> CancelPayoutAsync(Guid id, Guid actor, DateTime now, CancellationToken ct) { var p = await Load(id, ct); await Release(p, CreatorPayoutStatus.Cancelled, "Cancelled", actor, now, ct); await db.SaveChangesAsync(ct); return Map(p, null); }
    private async Task Release(CreatorPayout p, CreatorPayoutStatus status, string reason, Guid actor, DateTime now, CancellationToken ct) { if (p.Status is CreatorPayoutStatus.Paid or CreatorPayoutStatus.Cancelled) throw new InvalidOperationException("Payout cannot be released."); var account = await Account(p.CreatorId, p.CurrencyCode, now, ct); foreach (var i in p.Items) i.Earning.ReleaseSchedule(now); var moved = account.Transfer(CreatorBalanceCategory.Scheduled, CreatorBalanceCategory.Available, p.Amount, now); db.Add(Entry(account, CreatorBalanceEntryType.ScheduledToAvailable, CreatorBalanceCategory.Available, p.Amount, moved, now, $"release:{p.Id}:{status}", null, p.Id, null)); p.Status = status; p.FailureReason = reason; Audit(p.CreatorId, actor, status == CreatorPayoutStatus.Failed ? "PayoutFailed" : "PayoutCancelled", $"PayoutId={p.Id};Reason={reason}", now); }
    private async Task<CreatorPayout> Load(Guid id, CancellationToken ct) => await db.CreatorPayouts.Include(x => x.Items).ThenInclude(x => x.Earning).Include(x => x.Attempts).SingleOrDefaultAsync(x => x.Id == id, ct) ?? throw new KeyNotFoundException("Payout was not found.");
    private async Task<CreatorBalanceAccount> Account(Guid creator, string currency, DateTime now, CancellationToken ct) { var a = await db.CreatorBalanceAccounts.SingleOrDefaultAsync(x => x.CreatorId == creator && x.CurrencyCode == currency, ct); if (a is not null) return a; a = new() { Id = Guid.NewGuid(), CreatorId = creator, CurrencyCode = currency, CreatedAtUtc = now }; db.Add(a); return a; }
    private async Task NotifyCreator(Guid creator, NotificationType type, string key, string title, string body, string correlation, string entityType, string entityId, CancellationToken ct) { var user = await db.UserAccounts.Where(x => x.CreatorId == creator).Select(x => (Guid?)x.Id).SingleOrDefaultAsync(ct); if (user.HasValue) await notifications.CreateAsync(new(type, key, new Dictionary<string, string> { { "Title", title }, { "Body", body } }, [new(user, NotificationRecipientType.User, NotificationChannel.InApp, null, null)], NotificationPriority.High, correlation, entityType, entityId), ct); }
    private static CreatorBalanceEntry Entry(CreatorBalanceAccount a, CreatorBalanceEntryType type, CreatorBalanceCategory category, decimal amount, (decimal, decimal) b, DateTime now, string key, Guid? earning, Guid? payout, Guid? transaction) => new() { Id = Guid.NewGuid(), CreatorBalanceAccountId = a.Id, CreatorId = a.CreatorId, EntryType = type, BalanceCategory = category, Amount = amount, CurrencyCode = a.CurrencyCode, BalanceBefore = b.Item1, BalanceAfter = b.Item2, RelatedEarningId = earning, RelatedPayoutId = payout, RelatedTransactionId = transaction, IdempotencyKey = key, Description = type.ToString(), CorrelationId = key, CreatedAtUtc = now };
    private void Audit(Guid creator, Guid? actor, string type, string detail, DateTime now) => db.CreatorAuditEvents.Add(new() { Id = Guid.NewGuid(), CreatorId = creator, ActorUserAccountId = actor, EventType = type, Detail = detail, CreatedAtUtc = now });
    private static PayoutAttempt Attempt(CreatorPayout p, DateTime now, PayoutAttemptStatus status, string? failure = null) => new() { Id = Guid.NewGuid(), CreatorPayoutId = p.Id, AttemptNumber = p.Attempts.Count + 1, Status = status, ProviderReference = p.ProviderReference, FailureReason = failure, AttemptedAtUtc = now, CreatedAtUtc = now };
    private static FinancialJournal Journal(CreatorPayout p, DateTime now) { var j = new FinancialJournal { Id = Guid.NewGuid(), Reference = $"PAYOUT-{p.PublicPayoutId}", Description = "Creator payout", RelatedPayoutId = p.Id, CreatedAtUtc = now }; j.Lines.Add(new() { Id = Guid.NewGuid(), Account = JournalAccount.CreatorPayable, Type = JournalLineType.Debit, Amount = p.Amount, CurrencyCode = p.CurrencyCode, Description = "Creator payable settled", CreatedAtUtc = now }); j.Lines.Add(new() { Id = Guid.NewGuid(), Account = JournalAccount.PaymentClearing, Type = JournalLineType.Credit, Amount = p.Amount, CurrencyCode = p.CurrencyCode, Description = "Manual payout clearing", CreatedAtUtc = now }); j.Post(now); return j; }
    private DateTime Next(DateTime now) { var days = ((int)settings.WeeklyPayoutDay - (int)now.DayOfWeek + 7) % 7; var date = now.Date.AddDays(days).Add(settings.WeeklyPayoutCutoffTime); return date <= now ? date.AddDays(7) : date; }
    private static EarningDto Map(CreatorEarning x) => new(x.Id, x.PurchaseTransactionId, x.Amount, x.CurrencyCode, x.Status.ToString(), x.EarnedAtUtc, x.AvailableAtUtc, x.PaidAtUtc, x.HoldReason);
    private static PayoutDto Map(CreatorPayout x, IReadOnlyList<EarningDto>? e) => new(x.Id, x.PublicPayoutId, x.PayoutBatchId, x.Amount, x.CurrencyCode, x.Status.ToString(), x.PayoutMethodType.ToString(), x.ProviderReference, x.ScheduledAtUtc, x.SubmittedAtUtc, x.PaidAtUtc, x.FailureReason, e, x.CreatorId);
    private static PayoutBatchDto Map(PayoutBatch x, IReadOnlyList<PayoutDto>? p) => new(x.Id, x.PublicBatchId, x.CurrencyCode, x.Status.ToString(), x.CutoffAtUtc, x.ScheduledForUtc, x.TotalCreatorCount, x.TotalAmount, p);
}
