namespace CreatorPay.Application.Earnings;

public sealed class CreatorPayoutOptions { public const string SectionName = "CreatorPayouts"; public int CreatorEarningHoldingPeriodDays { get; set; } = 7; public decimal MinimumCreatorPayoutAmount { get; set; } = 100; public DayOfWeek WeeklyPayoutDay { get; set; } = DayOfWeek.Friday; public TimeSpan WeeklyPayoutCutoffTime { get; set; } = TimeSpan.Zero; public decimal MaximumAutomaticPayoutAmount { get; set; } = 10000; public decimal ManualReviewThreshold { get; set; } = 5000; public string CurrencyCode { get; set; } = "ETB"; }
public sealed record EarningDto(Guid Id, Guid PurchaseTransactionId, decimal Amount, string CurrencyCode, string Status, DateTime EarnedAtUtc, DateTime AvailableAtUtc, DateTime? PaidAtUtc, string? HoldReason);
public sealed record BalanceSummaryDto(string CurrencyCode, decimal PendingBalance, decimal AvailableBalance, decimal HeldBalance, decimal ScheduledBalance, decimal PaidLifetimeTotal, decimal ReversedLifetimeTotal, DateTime? NextEstimatedPayoutAtUtc, decimal CurrentPayoutAmount = 0, int CurrentPeriodConfirmedSales = 0, DateTime? LastPayoutAtUtc = null, DateTime? CurrentPeriodStartedAtUtc = null, decimal UpcomingPayoutAmount = 0, int ConfirmedSalesCount = 0);
public sealed record PayoutDto(Guid Id, string PublicPayoutId, Guid PayoutBatchId, decimal Amount, string CurrencyCode, string Status, string PayoutMethodType, string? ProviderReference, DateTime ScheduledAtUtc, DateTime? SubmittedAtUtc, DateTime? PaidAtUtc, string? FailureReason, IReadOnlyList<EarningDto>? Earnings = null, Guid? CreatorId = null);
public sealed record PayoutBatchDto(Guid Id, string PublicBatchId, string CurrencyCode, string Status, DateTime CutoffAtUtc, DateTime ScheduledForUtc, int TotalCreatorCount, decimal TotalAmount, IReadOnlyList<PayoutDto>? Payouts = null);
public sealed record CreatePayoutBatchRequest(DateTime CutoffAtUtc, DateTime ScheduledForUtc, string CurrencyCode, string IdempotencyKey);
public sealed record PayoutCycleLine(string PartyId, string PartyName, decimal EligibleAmount, decimal ReservedAmount, string Status, Guid? PayoutId = null, Guid? PayoutBatchId = null);
public sealed record PayoutCycleHistory(DateTime CycleStartUtc, DateTime CutoffAtUtc, DateTime PayoutDateUtc, int PartyCount, decimal TotalAmount, string Status);
public sealed record PayoutCycleReport(string CurrencyCode, DateTime CycleStartUtc, DateTime CutoffAtUtc, DateTime PayoutDateUtc, decimal ScheduledTotal, decimal ReservedTotal, decimal PaidTotal, IReadOnlyList<PayoutCycleLine> Lines, IReadOnlyList<PayoutCycleHistory> History, DateTime? LastPayoutDateUtc = null);
public sealed record PayoutHistoryRow(string PartyName, string PartyId, DateTime CycleStartUtc, DateTime CutoffAtUtc, DateTime? PayoutDateUtc, decimal EligibleAmount, decimal PaidAmount, string Status, string PayoutReference, string? BatchReference);
public sealed record PayoutHistoryPage(IReadOnlyList<PayoutHistoryRow> Items, int Page, int PageSize, int TotalCount, decimal TotalPaidAmount);
public sealed record PlatformRevenueHistory(DateTime PeriodStartUtc, DateTime PeriodEndUtc, int TransactionCount, decimal PlatformRevenue);
public sealed record PlatformRevenueReport(string CurrencyCode, DateTime CycleStartUtc, DateTime CycleEndUtc, decimal CurrentRevenue, int CurrentTransactionCount, IReadOnlyList<PlatformRevenueHistory> History);
public sealed record CreatorAdPerformanceRow(Guid PartnershipId, Guid MerchantId, string BusinessName, string Status, DateTime? ExpiresAtUtc, int ConfirmedSales, decimal CreatorEarned, string CurrencyCode);
public sealed record CreatorAdTransactionRow(Guid TransactionId, Guid PartnershipId, Guid MerchantId, string BusinessName, DateTime ConfirmedAtUtc, string Status, decimal CreatorEarned, string CurrencyCode, string EarningStatus);
public sealed record CreatorAdPerformanceReport(IReadOnlyList<CreatorAdPerformanceRow> Businesses, IReadOnlyList<CreatorAdTransactionRow> Transactions);
public sealed record SubmitPayoutRequest(string? ProviderReference); public sealed record FailPayoutRequest(string Reason);
public sealed record PayoutProviderResult(string Status, string? ProviderReference, string? FailureReason);
public interface IPayoutProvider { Task<PayoutProviderResult> SubmitPayoutAsync(Guid payoutId, string? safeReference, CancellationToken ct); Task<PayoutProviderResult> GetPayoutStatusAsync(Guid payoutId, CancellationToken ct); Task<PayoutProviderResult> CancelPayoutAsync(Guid payoutId, CancellationToken ct); }
public interface ICreatorEarningsService
{
    Task RecordConfirmedPurchaseAsync(Guid transactionId, Guid creatorId, Guid snapshotId, decimal amount, string currency, DateTime confirmedAt, string correlationId, CancellationToken ct);
    Task<IReadOnlyList<EarningDto>> GetEarningsAsync(Guid creatorId, string? status, CancellationToken ct); Task<EarningDto> GetEarningAsync(Guid creatorId, Guid id, CancellationToken ct); Task<BalanceSummaryDto> GetSummaryAsync(Guid creatorId, DateTime now, CancellationToken ct); Task<int> MatureAsync(DateTime now, Guid actor, CancellationToken ct);
    Task<IReadOnlyList<PayoutDto>> GetPayoutsAsync(Guid? creatorId, CancellationToken ct); Task<PayoutDto> GetPayoutAsync(Guid? creatorId, Guid id, CancellationToken ct); Task<IReadOnlyList<PayoutBatchDto>> GetBatchesAsync(CancellationToken ct); Task<PayoutBatchDto> GetBatchAsync(Guid id, CancellationToken ct); Task<PayoutBatchDto> CreateBatchAsync(CreatePayoutBatchRequest request, Guid actor, DateTime now, CancellationToken ct);
    Task<PayoutBatchDto> ProcessBatchAsync(Guid id, Guid actor, DateTime now, CancellationToken ct); Task<PayoutBatchDto> CancelBatchAsync(Guid id, Guid actor, DateTime now, CancellationToken ct); Task<PayoutDto> SubmitAsync(Guid id, SubmitPayoutRequest request, Guid actor, DateTime now, CancellationToken ct); Task<PayoutDto> MarkPaidAsync(Guid id, Guid actor, DateTime now, CancellationToken ct); Task<PayoutDto> MarkFailedAsync(Guid id, FailPayoutRequest request, Guid actor, DateTime now, CancellationToken ct); Task<PayoutDto> RetryAsync(Guid id, Guid actor, DateTime now, CancellationToken ct); Task<PayoutDto> CancelPayoutAsync(Guid id, Guid actor, DateTime now, CancellationToken ct);
}
