namespace CreatorPay.Application.Earnings;

public sealed class CreatorPayoutOptions { public const string SectionName = "CreatorPayouts"; public int CreatorEarningHoldingPeriodDays { get; set; } = 7; public decimal MinimumCreatorPayoutAmount { get; set; } = 100; public DayOfWeek WeeklyPayoutDay { get; set; } = DayOfWeek.Friday; public TimeSpan WeeklyPayoutCutoffTime { get; set; } = TimeSpan.Zero; public decimal MaximumAutomaticPayoutAmount { get; set; } = 10000; public decimal ManualReviewThreshold { get; set; } = 5000; public string CurrencyCode { get; set; } = "ETB"; }
public sealed record EarningDto(Guid Id, Guid PurchaseTransactionId, decimal Amount, string CurrencyCode, string Status, DateTime EarnedAtUtc, DateTime AvailableAtUtc, DateTime? PaidAtUtc, string? HoldReason);
public sealed record BalanceSummaryDto(string CurrencyCode, decimal PendingBalance, decimal AvailableBalance, decimal HeldBalance, decimal ScheduledBalance, decimal PaidLifetimeTotal, decimal ReversedLifetimeTotal, DateTime? NextEstimatedPayoutAtUtc);
public sealed record PayoutDto(Guid Id, string PublicPayoutId, Guid PayoutBatchId, decimal Amount, string CurrencyCode, string Status, string PayoutMethodType, string? ProviderReference, DateTime ScheduledAtUtc, DateTime? SubmittedAtUtc, DateTime? PaidAtUtc, string? FailureReason, IReadOnlyList<EarningDto>? Earnings = null);
public sealed record PayoutBatchDto(Guid Id, string PublicBatchId, string CurrencyCode, string Status, DateTime CutoffAtUtc, DateTime ScheduledForUtc, int TotalCreatorCount, decimal TotalAmount, IReadOnlyList<PayoutDto>? Payouts = null);
public sealed record CreatePayoutBatchRequest(DateTime CutoffAtUtc, DateTime ScheduledForUtc, string CurrencyCode, string IdempotencyKey);
public sealed record SubmitPayoutRequest(string? ProviderReference); public sealed record FailPayoutRequest(string Reason);
public sealed record PayoutProviderResult(string Status, string? ProviderReference, string? FailureReason);
public interface IPayoutProvider { Task<PayoutProviderResult> SubmitPayoutAsync(Guid payoutId, string? safeReference, CancellationToken ct); Task<PayoutProviderResult> GetPayoutStatusAsync(Guid payoutId, CancellationToken ct); Task<PayoutProviderResult> CancelPayoutAsync(Guid payoutId, CancellationToken ct); }
public interface ICreatorEarningsService
{
    Task RecordConfirmedPurchaseAsync(Guid transactionId, Guid creatorId, Guid snapshotId, decimal amount, string currency, DateTime confirmedAt, string correlationId, CancellationToken ct);
    Task<IReadOnlyList<EarningDto>> GetEarningsAsync(Guid creatorId, string? status, CancellationToken ct); Task<EarningDto> GetEarningAsync(Guid creatorId, Guid id, CancellationToken ct); Task<BalanceSummaryDto> GetSummaryAsync(Guid creatorId, DateTime now, CancellationToken ct); Task<int> MatureAsync(DateTime now, Guid actor, CancellationToken ct);
    Task<IReadOnlyList<PayoutDto>> GetPayoutsAsync(Guid? creatorId, CancellationToken ct); Task<PayoutDto> GetPayoutAsync(Guid? creatorId, Guid id, CancellationToken ct); Task<IReadOnlyList<PayoutBatchDto>> GetBatchesAsync(CancellationToken ct); Task<PayoutBatchDto> GetBatchAsync(Guid id, CancellationToken ct); Task<PayoutBatchDto> CreateBatchAsync(CreatePayoutBatchRequest request, Guid actor, DateTime now, CancellationToken ct);
    Task<PayoutBatchDto> ProcessBatchAsync(Guid id, Guid actor, DateTime now, CancellationToken ct); Task<PayoutBatchDto> CancelBatchAsync(Guid id, Guid actor, DateTime now, CancellationToken ct); Task<PayoutDto> SubmitAsync(Guid id, SubmitPayoutRequest request, Guid actor, DateTime now, CancellationToken ct); Task<PayoutDto> MarkPaidAsync(Guid id, Guid actor, DateTime now, CancellationToken ct); Task<PayoutDto> MarkFailedAsync(Guid id, FailPayoutRequest request, Guid actor, DateTime now, CancellationToken ct); Task<PayoutDto> RetryAsync(Guid id, Guid actor, DateTime now, CancellationToken ct); Task<PayoutDto> CancelPayoutAsync(Guid id, Guid actor, DateTime now, CancellationToken ct);
}
