using System.Data;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using CreatorPay.Application.Commission;
using CreatorPay.Application.Qr;
using CreatorPay.Application.Wallet;
using CreatorPay.Application.Earnings;
using CreatorPay.Domain.Entities;
using CreatorPay.Domain.Enums;
using CreatorPay.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using CreatorPay.Application.CustomerVerification;

namespace CreatorPay.Infrastructure.Wallet;

public sealed class WalletService(ApplicationDbContext db, ICreatorQrService qr, ICommissionEngine commissions, ICreatorEarningsService earnings, IOptions<WalletOptions> options, IPhoneNumberNormalizer phones, IPhoneHashService phoneHashes, IPhoneEncryptionService phoneEncryption) : IWalletService
{
    private readonly WalletOptions settings = options.Value;
    public async Task<WalletDto> GetWalletAsync(Guid merchantId, CancellationToken ct) => Map(await EnsureWallet(merchantId, ct));
    public async Task<IReadOnlyList<WalletEntryDto>> GetEntriesAsync(Guid merchantId, CancellationToken ct) => await db.MerchantWalletEntries.AsNoTracking().Where(x => x.MerchantId == merchantId).OrderByDescending(x => x.CreatedAtUtc).Select(x => new WalletEntryDto(x.Id, x.EntryType.ToString(), x.Amount, x.BalanceBefore, x.BalanceAfter, x.Description, x.CreatedAtUtc)).ToListAsync(ct);
    public async Task<IReadOnlyList<DepositDto>> GetDepositsAsync(Guid? merchantId, bool pendingOnly, CancellationToken ct) { var q = db.MerchantDeposits.AsNoTracking().AsQueryable(); if (merchantId.HasValue) q = q.Where(x => x.MerchantId == merchantId); if (pendingOnly) q = q.Where(x => x.Status == MerchantDepositStatus.PendingVerification); return await q.OrderByDescending(x => x.SubmittedAtUtc).Select(x => Map(x)).ToListAsync(ct); }
    public async Task<DepositDto> GetDepositAsync(Guid id, Guid? merchantId, CancellationToken ct) => Map(await db.MerchantDeposits.AsNoTracking().SingleOrDefaultAsync(x => x.Id == id && (!merchantId.HasValue || x.MerchantId == merchantId), ct) ?? throw new KeyNotFoundException("Deposit was not found."));
    public async Task<DepositDto> SubmitDepositAsync(Guid merchantId, Guid actor, string key, SubmitDepositRequest r, CancellationToken ct) { RequireKey(key); if (r.Amount <= 0) throw new ArgumentException("Deposit amount must be positive."); var currency = Currency(r.CurrencyCode); var hash = Hash(r); var old = await db.MerchantDeposits.AsNoTracking().SingleOrDefaultAsync(x => x.MerchantId == merchantId && x.IdempotencyKey == key, ct); if (old is not null) { if (old.RequestHash != hash) throw new IdempotencyConflictException(); return Map(old); } var wallet = await EnsureWallet(merchantId, ct); var now = DateTime.UtcNow; var d = new MerchantDeposit { Id = Guid.NewGuid(), MerchantId = merchantId, MerchantWalletId = wallet.Id, Amount = r.Amount, CurrencyCode = currency, Status = MerchantDepositStatus.PendingVerification, ExternalReference = r.ExternalReference.Trim(), ProofMetadata = r.ProofMetadata, SubmittedAtUtc = now, IdempotencyKey = key, RequestHash = hash, CreatedAtUtc = now, CreatedBy = actor.ToString() }; db.Add(d); Audit(merchantId, actor, "DepositSubmitted", $"DepositId={d.Id}"); await db.SaveChangesAsync(ct); return Map(d); }
    public async Task<DepositDto> ApproveDepositAsync(Guid id, Guid actor, string key, CancellationToken ct) { RequireKey(key); await using var tx = await db.Database.BeginTransactionAsync(IsolationLevel.Serializable, ct); var d = await db.MerchantDeposits.Include(x => x.Wallet).SingleOrDefaultAsync(x => x.Id == id, ct) ?? throw new KeyNotFoundException(); if (d.Status == MerchantDepositStatus.Completed) return Map(d); if (d.Status != MerchantDepositStatus.PendingVerification) throw new InvalidOperationException("Only a pending deposit can be approved."); var now = DateTime.UtcNow; var balance = d.Wallet.Credit(d.Amount, settings.LowBalanceThreshold, now); d.Status = MerchantDepositStatus.Completed; d.VerifiedAtUtc = now; d.VerifiedByUserId = actor; db.Add(Entry(d.Wallet, d.MerchantId, d.Amount, balance, d.Id, actor, key, MerchantWalletEntryType.Deposit)); db.Add(Journal(now, $"DEP-{d.Id}", null, d.Id, (JournalAccount.PaymentClearing, JournalLineType.Debit, d.Amount), (JournalAccount.MerchantWalletLiability, JournalLineType.Credit, d.Amount))); Audit(d.MerchantId, actor, "DepositApproved", $"DepositId={d.Id}"); Audit(d.MerchantId, actor, "WalletCredited", $"BalanceAfter={balance.After}"); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return Map(d); }
    public async Task<DepositDto> RejectDepositAsync(Guid id, Guid actor, RejectDepositRequest r, CancellationToken ct) { if (string.IsNullOrWhiteSpace(r.Reason)) throw new ArgumentException("A rejection reason is required."); var d = await db.MerchantDeposits.SingleOrDefaultAsync(x => x.Id == id, ct) ?? throw new KeyNotFoundException(); if (d.Status != MerchantDepositStatus.PendingVerification) throw new InvalidOperationException("Only a pending deposit can be rejected."); d.Status = MerchantDepositStatus.Failed; d.FailureReason = r.Reason.Trim(); d.VerifiedAtUtc = DateTime.UtcNow; d.VerifiedByUserId = actor; Audit(d.MerchantId, actor, "DepositRejected", $"DepositId={d.Id}"); await db.SaveChangesAsync(ct); return Map(d); }
    public async Task<PurchaseDto> ConfirmPurchaseAsync(Guid merchantId, Guid actor, Guid cashierId, string role, string key, ConfirmPurchaseRequest r, CancellationToken ct)
    {
        RequireKey(key); if (r.PurchaseAmount <= 0) throw new ArgumentException("Purchase amount must be positive."); var currency = Currency(r.CurrencyCode); var hash = Hash(r); var scope = $"purchase:{merchantId}";
        var old = await db.IdempotencyRecords.AsNoTracking().SingleOrDefaultAsync(x => x.Scope == scope && x.Key == key, ct); if (old is not null) { if (old.RequestHash != hash) throw new IdempotencyConflictException(); if (old.ResponseReferenceId.HasValue) return await GetPurchaseAsync(old.ResponseReferenceId.Value, merchantId, null, ct); throw new InvalidOperationException("The request is already processing."); }
        await using var tx = await db.Database.BeginTransactionAsync(IsolationLevel.Serializable, ct); var now = DateTime.UtcNow; var record = new IdempotencyRecord { Id = Guid.NewGuid(), Scope = scope, Key = key, RequestHash = hash, Status = IdempotencyStatus.Processing, CreatedAtUtc = now, ExpiresAtUtc = now.AddDays(1) }; db.Add(record); Audit(merchantId, actor, "PurchaseAttempted", $"LocationId={r.MerchantLocationId};Amount={r.PurchaseAmount}");
        var valid = await qr.ValidateAsync(r.QrPayload, r.MerchantLocationId, merchantId, actor, role, cashierId, null, ct); if (!valid.IsValid) throw new PurchaseRejectedException(valid.Code, valid.Message); var creator = await db.Creators.SingleAsync(x => x.PublicCreatorId == valid.CreatorPublicId, ct); var qrCode = await db.CreatorQrCodes.SingleAsync(x => x.CreatorId == creator.Id && x.IsActive, ct); var location = await db.MerchantLocations.SingleAsync(x => x.Id == r.MerchantLocationId, ct);
        var selected = await commissions.PreviewAsync(new(r.PurchaseAmount, merchantId, creator.Id, valid.PartnershipId, null, currency, now), false, ct); var wallet = await EnsureWallet(merchantId, ct); var total = selected.Calculation.TotalCommissionAmount; if (wallet.AvailableBalance < total) { Audit(merchantId, actor, "RestrictionTriggered", $"Available={wallet.AvailableBalance};Required={total}"); throw new PurchaseRejectedException("InsufficientWalletBalance", "The merchant wallet has insufficient available balance."); }
        var snapshot = new CommissionCalculationSnapshot { Id = Guid.NewGuid(), CommissionRuleId = selected.RuleId, CommissionRuleVersionId = selected.RuleVersionId, CurrencyCode = currency, PurchaseAmount = r.PurchaseAmount, MerchantCommissionRatePercent = selected.Calculation.MerchantCommissionRatePercent, TotalCommissionAmount = total, CreatorSharePercent = selected.Calculation.CreatorSharePercent, CreatorCommissionAmount = selected.Calculation.CreatorCommissionAmount, PlatformSharePercent = selected.Calculation.PlatformSharePercent, PlatformCommissionAmount = selected.Calculation.PlatformCommissionAmount, RoundingMode = selected.Calculation.RoundingMode, CalculatedAtUtc = now, RuleSourceType = selected.RuleSource, RuleSourceId = selected.RuleSourceId, CreatedAtUtc = now };
        var normalized = phones.Normalize(r.CustomerPhoneNumber); var phoneHash = phoneHashes.Hash(normalized); var phone = await db.CustomerPhoneReferences.SingleOrDefaultAsync(x => x.PhoneNumberHash == phoneHash, ct); if (phone is null) { phone = new() { Id = Guid.NewGuid(), PhoneNumberHash = phoneHash, EncryptedPhoneNumber = phoneEncryption.Encrypt(normalized), MaskedPhoneNumber = phones.Mask(normalized), CreatedAtUtc = now }; db.Add(phone); }
        phone.LastUsedAtUtc = now; TimeZoneInfo zone; try { zone = TimeZoneInfo.FindSystemTimeZoneById(location.TimeZoneId); } catch { throw new PurchaseRejectedException("InvalidLocationTimezone", "The merchant location timezone is invalid."); }
        var localDate = DateOnly.FromDateTime(TimeZoneInfo.ConvertTimeFromUtc(now, zone));
        var p = new PurchaseTransaction { Id = Guid.NewGuid(), PublicTransactionId = $"CP-{Guid.NewGuid():N}", CreatorId = creator.Id, MerchantId = merchantId, MerchantLocationId = location.Id, CashierId = cashierId, CreatorQrCodeId = qrCode.Id, MerchantCreatorPartnershipId = valid.PartnershipId!.Value, PurchaseAmount = r.PurchaseAmount, CurrencyCode = currency, CommissionCalculationSnapshotId = snapshot.Id, IdempotencyKey = key, ClientOperationId = r.ClientOperationId, TransactionDateUtc = now, CreatedAtUtc = now, CreatedByUserId = actor, CreatedBy = actor.ToString(), CorrelationId = key, CustomerPhoneReferenceId = phone.Id, CustomerPhoneHash = phoneHash, MerchantLocalDate = localDate, RepeatUseApprovalRequestId = r.RepeatUseApprovalRequestId, WasRepeatUseApproved = r.RepeatUseApprovalRequestId.HasValue }; var balance = wallet.Debit(total, settings.LowBalanceThreshold, now); p.Confirm(now, actor); db.Add(snapshot); db.Add(p); await earnings.RecordConfirmedPurchaseAsync(p.Id, creator.Id, snapshot.Id, snapshot.CreatorCommissionAmount, currency, now, key, ct); db.Add(Entry(wallet, merchantId, total, balance, null, actor, $"purchase:{merchantId}:{key}", MerchantWalletEntryType.CommissionDebit, p.Id)); db.Add(Journal(now, $"PUR-{p.PublicTransactionId}", p.Id, null, (JournalAccount.MerchantWalletLiability, JournalLineType.Debit, total), (JournalAccount.CreatorPayable, JournalLineType.Credit, selected.Calculation.CreatorCommissionAmount), (JournalAccount.PlatformCommissionRevenue, JournalLineType.Credit, selected.Calculation.PlatformCommissionAmount))); record.Status = IdempotencyStatus.Completed; record.ResponseReferenceId = p.Id; Audit(merchantId, actor, "CustomerPhoneNormalized", $"PhoneReferenceId={phone.Id}"); Audit(merchantId, actor, "PurchaseConfirmed", $"TransactionId={p.Id}"); Audit(merchantId, actor, "WalletDebited", $"BalanceAfter={balance.After}"); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return Map(p, snapshot, creator.DisplayName, location.Name, balance.After);
    }
    public async Task<PurchaseDto> GetPurchaseAsync(Guid id, Guid? merchantId, Guid? cashierId, CancellationToken ct) { var p = await Query().SingleOrDefaultAsync(x => x.Id == id && (!merchantId.HasValue || x.MerchantId == merchantId) && (!cashierId.HasValue || x.CashierId == cashierId), ct) ?? throw new KeyNotFoundException(); return Map(p, p.CommissionSnapshot, p.CreatorId.ToString(), p.MerchantLocationId.ToString(), null); }
    public async Task<IReadOnlyList<PurchaseDto>> GetPurchasesAsync(Guid? merchantId, Guid? cashierId, int take, CancellationToken ct) { var q = Query(); if (merchantId.HasValue) q = q.Where(x => x.MerchantId == merchantId); if (cashierId.HasValue) q = q.Where(x => x.CashierId == cashierId); return (await q.OrderByDescending(x => x.TransactionDateUtc).Take(Math.Clamp(take, 1, 100)).ToListAsync(ct)).Select(x => Map(x, x.CommissionSnapshot, x.CreatorId.ToString(), x.MerchantLocationId.ToString(), null)).ToList(); }
    private IQueryable<PurchaseTransaction> Query() => db.PurchaseTransactions.AsNoTracking().Include(x => x.CommissionSnapshot);
    private async Task<MerchantWallet> EnsureWallet(Guid merchantId, CancellationToken ct) { var w = await db.MerchantWallets.SingleOrDefaultAsync(x => x.MerchantId == merchantId && x.CurrencyCode == settings.CurrencyCode, ct); if (w is not null) return w; var m = await db.Merchants.FindAsync([merchantId], ct) ?? throw new KeyNotFoundException(); if (m.Status is MerchantStatus.Rejected or MerchantStatus.Closed) throw new InvalidOperationException("Merchant is not eligible for a wallet."); w = new() { Id = Guid.NewGuid(), MerchantId = merchantId, CurrencyCode = settings.CurrencyCode, CreatedAtUtc = DateTime.UtcNow }; db.Add(w); Audit(merchantId, null, "WalletCreated", "Currency=ETB"); await db.SaveChangesAsync(ct); return w; }
    private void Audit(Guid merchant, Guid? actor, string type, string detail) => db.MerchantAuditEvents.Add(new() { Id = Guid.NewGuid(), MerchantId = merchant, ActorUserAccountId = actor, EventType = type, Detail = detail, CreatedAtUtc = DateTime.UtcNow, CreatedBy = actor?.ToString() });
    private static MerchantWalletEntry Entry(MerchantWallet w, Guid merchant, decimal amount, (decimal Before, decimal After) b, Guid? deposit, Guid actor, string key, MerchantWalletEntryType type, Guid? transaction = null) => new() { Id = Guid.NewGuid(), MerchantWalletId = w.Id, MerchantId = merchant, EntryType = type, Amount = amount, CurrencyCode = w.CurrencyCode, BalanceBefore = b.Before, BalanceAfter = b.After, RelatedDepositId = deposit, RelatedTransactionId = transaction, IdempotencyKey = key, Description = type.ToString(), CreatedAtUtc = DateTime.UtcNow, CreatedByUserId = actor, CreatedBy = actor.ToString(), CorrelationId = key };
    private static FinancialJournal Journal(DateTime now, string reference, Guid? transaction, Guid? deposit, params (JournalAccount Account, JournalLineType Type, decimal Amount)[] lines) { var j = new FinancialJournal { Id = Guid.NewGuid(), Reference = reference, Description = reference, RelatedTransactionId = transaction, RelatedDepositId = deposit, CreatedAtUtc = now }; foreach (var x in lines) j.Lines.Add(new() { Id = Guid.NewGuid(), Account = x.Account, Type = x.Type, Amount = x.Amount, CurrencyCode = "ETB", Description = reference, CreatedAtUtc = now }); j.Post(now); return j; }
    private static string Hash<T>(T x) => Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(JsonSerializer.Serialize(x)))); private static string Currency(string x) { var c = x.Trim().ToUpperInvariant(); if (c != "ETB") throw new ArgumentException("Only ETB is supported."); return c; }
    private static void RequireKey(string x) { if (string.IsNullOrWhiteSpace(x) || x.Length > 200) throw new ArgumentException("A valid Idempotency-Key header is required."); }
    private static WalletDto Map(MerchantWallet x) => new(x.Id, x.CurrencyCode, x.AvailableBalance, x.HeldBalance, x.Status.ToString()); private static DepositDto Map(MerchantDeposit x) => new(x.Id, x.Amount, x.CurrencyCode, x.Status.ToString(), x.ExternalReference, x.ProofMetadata, x.SubmittedAtUtc, x.VerifiedAtUtc, x.FailureReason); private static PurchaseDto Map(PurchaseTransaction p, CommissionCalculationSnapshot s, string creator, string location, decimal? balance) => new(p.Id, p.PublicTransactionId, p.Status.ToString(), p.PurchaseAmount, p.CurrencyCode, s.TotalCommissionAmount, s.CreatorCommissionAmount, s.PlatformCommissionAmount, creator, location, p.ConfirmedAtUtc, balance, "Purchase confirmed.");
}
public sealed class IdempotencyConflictException : Exception { public IdempotencyConflictException() : base("The idempotency key was already used with a different request.") { } }
public sealed class PurchaseRejectedException(string code, string message) : Exception(message) { public string Code { get; } = code; }
