using CreatorPay.Application.Authentication; using CreatorPay.Application.CustomerVerification;
namespace CreatorPay.Api.CustomerVerification;
public static class CustomerVerificationEndpoints { public static IEndpointRouteBuilder MapCustomerVerificationEndpoints(this IEndpointRouteBuilder e){
 var customer=e.MapGroup("/api/v1/customer-confirmations").AllowAnonymous();customer.MapPost("/{id}/send-code",(string id,IRepeatUseApprovalService s,CancellationToken c)=>Run(()=>s.SendCodeAsync(id,c)));customer.MapPost("/{id}/verify",(string id,VerifyCodeRequest r,IRepeatUseApprovalService s,CancellationToken c)=>Run(()=>s.VerifyCodeAsync(id,r.Code,c)));
 var cashier=e.MapGroup("/api/v1/cashier/repeat-use-requests").RequireAuthorization("CashierOnly");cashier.MapGet("/{id}",(string id,ICurrentUserService u,IRepeatUseApprovalService s,CancellationToken c)=>Run(()=>s.GetAsync(id,u.MerchantId,u.CashierId,null,false,c)));
 var supervisor=e.MapGroup("/api/v1/supervisor/repeat-use-requests").RequireAuthorization("SupervisorOnly");MapReviewer(supervisor,true);
 var merchant=e.MapGroup("/api/v1/merchant/repeat-use-requests").RequireAuthorization("MerchantAdminOnly");MapReviewer(merchant,false);
 var admin=e.MapGroup("/api/v1/admin/repeat-use-requests").RequireAuthorization("PlatformAdminOnly");admin.MapGet("/",(IRepeatUseApprovalService s,CancellationToken c)=>Run(()=>s.ListAsync(null,null,true,c)));admin.MapGet("/{id}",(string id,IRepeatUseApprovalService s,CancellationToken c)=>Run(()=>s.GetAsync(id,null,null,null,true,c)));return e;}
 static void MapReviewer(RouteGroupBuilder g,bool isSupervisor){g.MapGet("/",(ICurrentUserService u,IRepeatUseApprovalService s,CancellationToken c)=>Run(()=>s.ListAsync(u.MerchantId,isSupervisor?u.SupervisorId:null,false,c)));g.MapGet("/{id}",(string id,ICurrentUserService u,IRepeatUseApprovalService s,CancellationToken c)=>Run(()=>s.GetAsync(id,u.MerchantId,null,isSupervisor?u.SupervisorId:null,false,c)));g.MapPost("/{id}/approve",(string id,ApprovalDecisionRequest r,ICurrentUserService u,IRepeatUseApprovalService s,CancellationToken c)=>Run(()=>s.DecideAsync(id,u.MerchantId!.Value,u.UserAccountId!.Value,isSupervisor?u.SupervisorId:null,true,r.Reason,c)));g.MapPost("/{id}/deny",(string id,ApprovalDecisionRequest r,ICurrentUserService u,IRepeatUseApprovalService s,CancellationToken c)=>Run(()=>s.DecideAsync(id,u.MerchantId!.Value,u.UserAccountId!.Value,isSupervisor?u.SupervisorId:null,false,r.Reason,c)));}
 static async Task<IResult> Run<T>(Func<Task<T>> f){try{return Results.Ok(await f());}catch(ArgumentException x){return Results.Problem(statusCode:400,title:"Invalid request",detail:x.Message);}catch(KeyNotFoundException){return Results.Problem(statusCode:404,title:"Not found");}catch(UnauthorizedAccessException x){return Results.Problem(statusCode:403,title:"Forbidden",detail:x.Message);}catch(InvalidOperationException x){return Results.Problem(statusCode:409,title:"Operation rejected",detail:x.Message);}}
}
