using CreatorPay.Application.Authentication;
using CreatorPay.Application.Risk;

namespace CreatorPay.Api.Risk;

public static class RiskEndpoints
{
    public static IEndpointRouteBuilder MapRiskEndpoints(this IEndpointRouteBuilder e)
    {
        MapDisputes(e.MapGroup("/api/v1/creator/disputes").RequireAuthorization("CreatorOnly")); MapDisputes(e.MapGroup("/api/v1/merchant/disputes").RequireAuthorization("MerchantAdminOnly"));
        var d = e.MapGroup("/api/v1/admin/disputes").RequireAuthorization("PlatformAdminOnly"); d.MapGet("/", (ICurrentUserService u, IRiskOperationsService s, CancellationToken c) => Run(() => s.ListDisputesAsync(u.Role!, null, null, c))); d.MapGet("/{id:guid}", (Guid id, ICurrentUserService u, IRiskOperationsService s, CancellationToken c) => Run(() => s.GetDisputeAsync(id, u.Role!, null, null, c))); d.MapPost("/{id:guid}/assign", (Guid id, AssignReviewerRequest r, ICurrentUserService u, IRiskOperationsService s, CancellationToken c) => Run(() => s.AssignDisputeAsync(id, u.UserAccountId!.Value, r, c))); d.MapPost("/{id:guid}/request-evidence", (Guid id, ReasonRequest r, ICurrentUserService u, IRiskOperationsService s, CancellationToken c) => Run(() => s.RequestEvidenceAsync(id, u.UserAccountId!.Value, r.Reason, c))); d.MapPost("/{id:guid}/approve", (Guid id, DecisionRequest r, ICurrentUserService u, IRiskOperationsService s, CancellationToken c) => Run(() => s.DecideDisputeAsync(id, u.UserAccountId!.Value, true, r, c))); d.MapPost("/{id:guid}/reject", (Guid id, DecisionRequest r, ICurrentUserService u, IRiskOperationsService s, CancellationToken c) => Run(() => s.DecideDisputeAsync(id, u.UserAccountId!.Value, false, r, c))); d.MapPost("/{id:guid}/cancel", (Guid id, ReasonRequest r, ICurrentUserService u, IRiskOperationsService s, CancellationToken c) => Run(() => s.CancelDisputeAsync(id, u.UserAccountId!.Value, r.Reason, c)));
        var f = e.MapGroup("/api/v1/admin/fraud-alerts").RequireAuthorization("PlatformAdminOnly"); f.MapGet("/", (IRiskOperationsService s, CancellationToken c) => Run(() => s.ListFraudAlertsAsync(c))); f.MapGet("/{id:guid}", (Guid id, IRiskOperationsService s, CancellationToken c) => Run(() => s.GetFraudAlertAsync(id, c))); f.MapPatch("/{id:guid}/status", (Guid id, StatusRequest r, ICurrentUserService u, IRiskOperationsService s, CancellationToken c) => Run(() => s.UpdateFraudStatusAsync(id, u.UserAccountId!.Value, r, c))); f.MapPost("/{id:guid}/assign", (Guid id, AssignReviewerRequest r, ICurrentUserService u, IRiskOperationsService s, CancellationToken c) => Run(() => s.AssignFraudAlertAsync(id, u.UserAccountId!.Value, r, c))); f.MapPost("/{id:guid}/resolve", (Guid id, ResolveFraudRequest r, ICurrentUserService u, IRiskOperationsService s, CancellationToken c) => Run(() => s.ResolveFraudAsync(id, u.UserAccountId!.Value, r, c)));
        var v = e.MapGroup("/api/v1/admin/reversals").RequireAuthorization("PlatformAdminOnly"); v.MapPost("/", (CreateReversalRequest r, HttpContext h, ICurrentUserService u, IRiskOperationsService s, CancellationToken c) => Run(() => s.CreateReversalAsync(u.UserAccountId!.Value, r, h.TraceIdentifier, c), 201)); v.MapGet("/", (IRiskOperationsService s, CancellationToken c) => Run(() => s.ListReversalsAsync(c))); v.MapGet("/{id:guid}", (Guid id, IRiskOperationsService s, CancellationToken c) => Run(() => s.GetReversalAsync(id, c))); v.MapPost("/{id:guid}/approve", (Guid id, ICurrentUserService u, IRiskOperationsService s, CancellationToken c) => Run(() => s.ApproveReversalAsync(id, u.UserAccountId!.Value, c))); v.MapPost("/{id:guid}/process", (Guid id, ICurrentUserService u, IRiskOperationsService s, CancellationToken c) => Run(() => s.ProcessReversalAsync(id, u.UserAccountId!.Value, c))); v.MapPost("/{id:guid}/cancel", (Guid id, ReasonRequest r, ICurrentUserService u, IRiskOperationsService s, CancellationToken c) => Run(() => s.CancelReversalAsync(id, u.UserAccountId!.Value, r.Reason, c))); return e;
    }
    static void MapDisputes(RouteGroupBuilder g) { g.MapPost("/", (OpenDisputeRequest r, HttpContext h, ICurrentUserService u, IRiskOperationsService s, CancellationToken c) => Run(() => s.OpenDisputeAsync(u.UserAccountId!.Value, u.Role!, u.MerchantId, u.CreatorId, r, h.TraceIdentifier, c), 201)); g.MapGet("/", (ICurrentUserService u, IRiskOperationsService s, CancellationToken c) => Run(() => s.ListDisputesAsync(u.Role!, u.MerchantId, u.CreatorId, c))); g.MapGet("/{id:guid}", (Guid id, ICurrentUserService u, IRiskOperationsService s, CancellationToken c) => Run(() => s.GetDisputeAsync(id, u.Role!, u.MerchantId, u.CreatorId, c))); }
    static async Task<IResult> Run<T>(Func<Task<T>> f, int status = 200) { try { var x = await f(); return Results.Json(x, statusCode: status); } catch (KeyNotFoundException) { return Results.NotFound(); } catch (UnauthorizedAccessException x) { return Results.Problem(statusCode: 403, title: "Forbidden", detail: x.Message); } catch (ArgumentException x) { return Results.Problem(statusCode: 400, title: "Invalid request", detail: x.Message); } catch (InvalidOperationException x) { return Results.Problem(statusCode: 409, title: "Operation rejected", detail: x.Message); } }
    public sealed record ReasonRequest(string Reason);
}
