using System.Data;
using System.Text.Json;
using CreatorPay.Application.Authentication;
using CreatorPay.Application.Risk;
using CreatorPay.Domain.Entities;
using CreatorPay.Domain.Enums;
using CreatorPay.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace CreatorPay.Infrastructure.Risk;

public sealed class RiskOperationsService(ApplicationDbContext db, IUtcClock clock) : IRiskOperationsService
{
    static object DisputeDto(Dispute x) => new { x.Id, x.PublicDisputeId, x.PurchaseTransactionId, Type = x.DisputeType.ToString(), Status = x.Status.ToString(), x.Description, x.OpenedAtUtc, x.AssignedReviewerUserId, x.ResolvedAtUtc, x.Resolution, Evidence = x.Evidence.Select(e => new { e.Id, e.EvidenceType, e.FileName, e.ContentType, e.MetadataJson, e.SubmittedAtUtc }), History = x.StatusHistory.OrderBy(h => h.ChangedAtUtc).Select(h => new { Status = h.NewStatus.ToString(), h.Reason, h.ChangedAtUtc }) };
    static object AlertDto(FraudAlert x) => new { x.Id, x.PublicFraudAlertId, x.RuleCode, Severity = x.Severity.ToString(), Status = x.Status.ToString(), x.PurchaseTransactionId, x.MerchantId, x.CreatorId, x.EvidenceJson, x.AssignedReviewerUserId, x.DetectedAtUtc, x.ResolvedAtUtc, x.Resolution };
    static object ReversalDto(TransactionReversal x) => new { x.Id, x.PublicReversalId, x.PurchaseTransactionId, x.DisputeId, Type = x.ReversalType.ToString(), x.Amount, x.CurrencyCode, x.Reason, Status = x.Status.ToString(), x.RequestedAtUtc, x.ApprovedAtUtc, x.CompletedAtUtc, Items = x.Items.Select(i => new { i.ItemType, i.OriginalAmount, i.ReversedAmount }) };
    void Audit(string type, Guid? actor, Guid? merchant, Guid? subject, string correlation = "") => db.OperationalAuditEvents.Add(new() { Id = Guid.NewGuid(), EventType = type, ActorUserId = actor, MerchantId = merchant, SubjectId = subject, CorrelationId = correlation, CreatedAtUtc = clock.UtcNow });
    public async Task<FraudEvaluationResult> EvaluateAsync(FraudEvaluationContext c, CancellationToken ct) { var rules = await db.FraudRuleVersions.Include(x => x.Rule).Where(x => x.Rule.IsActive && x.EffectiveFromUtc <= c.OccurredAtUtc && (x.EffectiveToUtc == null || x.EffectiveToUtc > c.OccurredAtUtc)).ToListAsync(ct); var alerts = new List<Guid>(); var decision = FraudEvaluationDecision.Allow; foreach (var v in rules) { var cfg = JsonSerializer.Deserialize<Dictionary<string, decimal>>(v.ConfigurationJson) ?? []; var triggered = v.Rule.Code switch { "large-purchase-amount" => c.PurchaseAmount >= cfg.GetValueOrDefault("threshold", decimal.MaxValue), "large-creator-commission" => c.CreatorCommission >= cfg.GetValueOrDefault("threshold", decimal.MaxValue), "round-number-transaction" => c.PurchaseAmount is decimal a && a >= cfg.GetValueOrDefault("minimum", 0) && a % cfg.GetValueOrDefault("multiple", 100) == 0, _ => false }; if (!triggered) continue; if (c.PurchaseTransactionId.HasValue && await db.FraudAlerts.AnyAsync(x => x.FraudRuleVersionId == v.Id && x.PurchaseTransactionId == c.PurchaseTransactionId, ct)) continue; var alert = new FraudAlert { Id = Guid.NewGuid(), PublicFraudAlertId = $"FRA-{Guid.NewGuid():N}"[..20], RuleCode = v.Rule.Code, FraudRuleVersionId = v.Id, Severity = v.Severity, PurchaseTransactionId = c.PurchaseTransactionId, MerchantId = c.MerchantId, MerchantLocationId = c.MerchantLocationId, CreatorId = c.CreatorId, CashierId = c.CashierId, CustomerPhoneHash = c.CustomerPhoneHash, EvidenceJson = JsonSerializer.Serialize(new { c.Stage, c.PurchaseAmount, c.CreatorCommission }), DetectedAtUtc = c.OccurredAtUtc, CorrelationId = c.CorrelationId, CreatedAtUtc = clock.UtcNow }; db.FraudAlerts.Add(alert); Audit("FraudAlertCreated", null, c.MerchantId, alert.Id, c.CorrelationId); alerts.Add(alert.Id); if (v.Decision > decision) decision = v.Decision; } await db.SaveChangesAsync(ct); return new(decision, alerts); }
    public async Task<object> OpenDisputeAsync(Guid actor, string role, Guid? merchantId, Guid? creatorId, OpenDisputeRequest r, string correlationId, CancellationToken ct) { var tx = await db.PurchaseTransactions.FindAsync([r.PurchaseTransactionId], ct) ?? throw new KeyNotFoundException(); if (role == nameof(UserRole.Creator) && tx.CreatorId != creatorId) throw new UnauthorizedAccessException("Transaction does not belong to this creator."); if (role == nameof(UserRole.MerchantAdmin) && tx.MerchantId != merchantId) throw new UnauthorizedAccessException("Transaction does not belong to this merchant."); if (tx.Status is not (TransactionStatus.Confirmed or TransactionStatus.Disputed or TransactionStatus.PartiallyReversed)) throw new InvalidOperationException("Only a confirmed transaction can be disputed."); var now = clock.UtcNow; var x = new Dispute { Id = Guid.NewGuid(), PublicDisputeId = $"DSP-{Guid.NewGuid():N}"[..20], PurchaseTransactionId = tx.Id, OpenedByUserId = actor, OpenedByRole = role, MerchantId = tx.MerchantId, CreatorId = tx.CreatorId, DisputeType = r.DisputeType, Description = r.Description.Trim(), OpenedAtUtc = now, CorrelationId = correlationId, CreatedAtUtc = now }; x.StatusHistory.Add(new() { Id = Guid.NewGuid(), NewStatus = DisputeStatus.Open, ChangedByUserId = actor, ChangedAtUtc = now, CreatedAtUtc = now }); foreach (var e in r.Evidence ?? []) x.Evidence.Add(new() { Id = Guid.NewGuid(), EvidenceType = e.EvidenceType, FileName = e.FileName, ContentType = e.ContentType, MetadataJson = e.MetadataJson, SubmittedByUserId = actor, SubmittedAtUtc = now, CreatedAtUtc = now }); db.Disputes.Add(x); Audit("DisputeOpened", actor, tx.MerchantId, x.Id, correlationId); await db.SaveChangesAsync(ct); return DisputeDto(x); }
    IQueryable<Dispute> Disputes() => db.Disputes.Include(x => x.Evidence).Include(x => x.StatusHistory);
    public async Task<IReadOnlyList<object>> ListDisputesAsync(string role, Guid? merchantId, Guid? creatorId, CancellationToken ct) { var q = Disputes(); if (role == nameof(UserRole.Creator)) q = q.Where(x => x.CreatorId == creatorId); else if (role == nameof(UserRole.MerchantAdmin)) q = q.Where(x => x.MerchantId == merchantId); return (await q.OrderByDescending(x => x.OpenedAtUtc).ToListAsync(ct)).Select(DisputeDto).ToList(); }
    public async Task<object> GetDisputeAsync(Guid id, string role, Guid? merchantId, Guid? creatorId, CancellationToken ct) { var x = await Disputes().SingleOrDefaultAsync(x => x.Id == id, ct) ?? throw new KeyNotFoundException(); if (role == nameof(UserRole.Creator) && x.CreatorId != creatorId || role == nameof(UserRole.MerchantAdmin) && x.MerchantId != merchantId) throw new UnauthorizedAccessException(); return DisputeDto(x); }
    void SetDisputeStatus(Dispute x, DisputeStatus status, Guid actor, string reason) { var old = x.Status; x.Status = status; var now = clock.UtcNow; if (status is DisputeStatus.Approved or DisputeStatus.Rejected or DisputeStatus.Cancelled) { x.ResolvedAtUtc = now; x.Resolution = reason; } x.StatusHistory.Add(new() { Id = Guid.NewGuid(), PreviousStatus = old, NewStatus = status, ChangedByUserId = actor, Reason = reason, ChangedAtUtc = now, CreatedAtUtc = now }); }
    public async Task<object> AssignDisputeAsync(Guid id, Guid actor, AssignReviewerRequest r, CancellationToken ct) { var x = await Disputes().SingleOrDefaultAsync(x => x.Id == id, ct) ?? throw new KeyNotFoundException(); x.AssignedReviewerUserId = r.ReviewerUserId; SetDisputeStatus(x, DisputeStatus.UnderReview, actor, "Reviewer assigned"); Audit("DisputeReviewerAssigned", actor, x.MerchantId, x.Id); await db.SaveChangesAsync(ct); return DisputeDto(x); }
    public async Task<object> RequestEvidenceAsync(Guid id, Guid actor, string reason, CancellationToken ct) { var x = await Disputes().SingleOrDefaultAsync(x => x.Id == id, ct) ?? throw new KeyNotFoundException(); SetDisputeStatus(x, DisputeStatus.AwaitingEvidence, actor, reason); Audit("DisputeEvidenceRequested", actor, x.MerchantId, x.Id); await db.SaveChangesAsync(ct); return DisputeDto(x); }
    public async Task<object> DecideDisputeAsync(Guid id, Guid actor, bool approved, DecisionRequest r, CancellationToken ct) { var x = await Disputes().SingleOrDefaultAsync(x => x.Id == id, ct) ?? throw new KeyNotFoundException(); if (x.Status is DisputeStatus.Approved or DisputeStatus.Rejected or DisputeStatus.Cancelled) throw new InvalidOperationException("Dispute is already final."); SetDisputeStatus(x, approved ? DisputeStatus.Approved : DisputeStatus.Rejected, actor, r.Reason); x.Decisions.Add(new() { Id = Guid.NewGuid(), Approved = approved, Reason = r.Reason, DecidedByUserId = actor, DecidedAtUtc = clock.UtcNow, CreatedAtUtc = clock.UtcNow }); Audit(approved ? "DisputeApproved" : "DisputeRejected", actor, x.MerchantId, x.Id); await db.SaveChangesAsync(ct); return DisputeDto(x); }
    public async Task<object> CancelDisputeAsync(Guid id, Guid actor, string reason, CancellationToken ct) { var x = await Disputes().SingleOrDefaultAsync(x => x.Id == id, ct) ?? throw new KeyNotFoundException(); SetDisputeStatus(x, DisputeStatus.Cancelled, actor, reason); Audit("DisputeCancelled", actor, x.MerchantId, x.Id); await db.SaveChangesAsync(ct); return DisputeDto(x); }
    public async Task<IReadOnlyList<object>> ListFraudAlertsAsync(CancellationToken ct) => (await db.FraudAlerts.OrderByDescending(x => x.DetectedAtUtc).ToListAsync(ct)).Select(AlertDto).ToList(); public async Task<object> GetFraudAlertAsync(Guid id, CancellationToken ct) => AlertDto(await db.FraudAlerts.FindAsync([id], ct) ?? throw new KeyNotFoundException());
    async Task<object> ChangeAlert(Guid id, Guid actor, FraudAlertStatus status, string action, string? reason, Guid? reviewer, CancellationToken ct) { var x = await db.FraudAlerts.FindAsync([id], ct) ?? throw new KeyNotFoundException(); var old = x.Status; x.Status = status; if (reviewer.HasValue) x.AssignedReviewerUserId = reviewer; x.ReviewedAtUtc = clock.UtcNow; if (status is FraudAlertStatus.Cleared or FraudAlertStatus.Closed or FraudAlertStatus.ActionTaken) { x.ResolvedAtUtc = clock.UtcNow; x.Resolution = reason; } x.ReviewHistory.Add(new() { Id = Guid.NewGuid(), PreviousStatus = old, NewStatus = status, ActorUserId = actor, Action = action, Reason = reason, OccurredAtUtc = clock.UtcNow, CreatedAtUtc = clock.UtcNow }); Audit(action, actor, x.MerchantId, x.Id); await db.SaveChangesAsync(ct); return AlertDto(x); }
    public Task<object> AssignFraudAlertAsync(Guid id, Guid actor, AssignReviewerRequest r, CancellationToken ct) => ChangeAlert(id, actor, FraudAlertStatus.UnderReview, "FraudAlertAssigned", null, r.ReviewerUserId, ct); public Task<object> UpdateFraudStatusAsync(Guid id, Guid actor, StatusRequest r, CancellationToken ct) => ChangeAlert(id, actor, r.Status, "FraudAlertStatusChanged", r.Reason, null, ct); public Task<object> ResolveFraudAsync(Guid id, Guid actor, ResolveFraudRequest r, CancellationToken ct) => ChangeAlert(id, actor, r.Status, "FraudAlertResolved", r.Resolution, null, ct);
    public async Task<object> CreateReversalAsync(Guid actor, CreateReversalRequest r, string correlationId, CancellationToken ct) { if (string.IsNullOrWhiteSpace(r.IdempotencyKey)) throw new ArgumentException("Idempotency key is required."); var existing = await db.TransactionReversals.Include(x => x.Items).SingleOrDefaultAsync(x => x.IdempotencyKey == r.IdempotencyKey, ct); if (existing != null) return ReversalDto(existing); var tx = await db.PurchaseTransactions.Include(x => x.CommissionSnapshot).SingleOrDefaultAsync(x => x.Id == r.PurchaseTransactionId, ct) ?? throw new KeyNotFoundException(); if (tx.Status is not (TransactionStatus.Confirmed or TransactionStatus.Disputed or TransactionStatus.PartiallyReversed)) throw new InvalidOperationException("Transaction is not reversible."); var previouslyCompleted = await db.TransactionReversals.Where(x => x.PurchaseTransactionId == tx.Id && x.Status == ReversalStatus.Completed).SumAsync(x => (decimal?)x.Amount, ct) ?? 0; if (r.Amount <= 0 || previouslyCompleted + r.Amount > tx.CommissionSnapshot.TotalCommissionAmount) throw new ArgumentOutOfRangeException(nameof(r.Amount), "Reversal exceeds the remaining commission amount."); if (r.ReversalType == ReversalType.Full && (previouslyCompleted != 0 || r.Amount != tx.CommissionSnapshot.TotalCommissionAmount)) throw new ArgumentException("A full reversal must equal the original total commission and cannot follow a partial reversal."); if (r.DisputeId.HasValue && !await db.Disputes.AnyAsync(x => x.Id == r.DisputeId && x.PurchaseTransactionId == tx.Id && x.Status == DisputeStatus.Approved, ct)) throw new InvalidOperationException("Reversal dispute must be approved."); var x = new TransactionReversal { Id = Guid.NewGuid(), PublicReversalId = $"REV-{Guid.NewGuid():N}"[..20], PurchaseTransactionId = tx.Id, DisputeId = r.DisputeId, ReversalType = r.ReversalType, Amount = r.Amount, CurrencyCode = tx.CurrencyCode, Reason = r.Reason, RequestedAtUtc = clock.UtcNow, RequestedByUserId = actor, IdempotencyKey = r.IdempotencyKey, CorrelationId = correlationId, CreatedAtUtc = clock.UtcNow }; x.StatusHistory.Add(new() { Id = Guid.NewGuid(), NewStatus = ReversalStatus.Pending, ChangedByUserId = actor, ChangedAtUtc = clock.UtcNow, CreatedAtUtc = clock.UtcNow }); db.TransactionReversals.Add(x); Audit("ReversalRequested", actor, tx.MerchantId, x.Id, correlationId); await db.SaveChangesAsync(ct); return ReversalDto(x); }
    IQueryable<TransactionReversal> Reversals() => db.TransactionReversals.Include(x => x.Items).Include(x => x.StatusHistory); public async Task<IReadOnlyList<object>> ListReversalsAsync(CancellationToken ct) => (await Reversals().OrderByDescending(x => x.RequestedAtUtc).ToListAsync(ct)).Select(ReversalDto).ToList(); public async Task<object> GetReversalAsync(Guid id, CancellationToken ct) => ReversalDto(await Reversals().SingleOrDefaultAsync(x => x.Id == id, ct) ?? throw new KeyNotFoundException());
    void ReversalStatusChange(TransactionReversal x, ReversalStatus status, Guid actor, string? reason = null) { var old = x.Status; x.Status = status; if (status == ReversalStatus.Approved) { x.ApprovedAtUtc = clock.UtcNow; x.ApprovedByUserId = actor; } if (status == ReversalStatus.Completed) x.CompletedAtUtc = clock.UtcNow; x.StatusHistory.Add(new() { Id = Guid.NewGuid(), PreviousStatus = old, NewStatus = status, ChangedByUserId = actor, Reason = reason, ChangedAtUtc = clock.UtcNow, CreatedAtUtc = clock.UtcNow }); }
    public async Task<object> ApproveReversalAsync(Guid id, Guid actor, CancellationToken ct) { var x = await Reversals().SingleOrDefaultAsync(x => x.Id == id, ct) ?? throw new KeyNotFoundException(); if (x.Status != ReversalStatus.Pending) throw new InvalidOperationException("Only pending reversals can be approved."); ReversalStatusChange(x, ReversalStatus.Approved, actor); Audit("ReversalApproved", actor, null, x.Id); await db.SaveChangesAsync(ct); return ReversalDto(x); }
    public async Task<object> ProcessReversalAsync(Guid id, Guid actor, CancellationToken ct)
    {
        await using var transaction = await db.Database.BeginTransactionAsync(IsolationLevel.Serializable, ct);
        var reversal = await Reversals().SingleOrDefaultAsync(x => x.Id == id, ct) ?? throw new KeyNotFoundException();
        if (reversal.Status == ReversalStatus.Completed) return ReversalDto(reversal);
        if (reversal.Status != ReversalStatus.Approved) throw new InvalidOperationException("Only approved reversals can be processed.");
        var now = clock.UtcNow;
        ReversalStatusChange(reversal, ReversalStatus.Processing, actor);
        var purchase = await db.PurchaseTransactions.Include(x => x.CommissionSnapshot).SingleAsync(x => x.Id == reversal.PurchaseTransactionId, ct);
        var earning = await db.CreatorEarnings.SingleAsync(x => x.PurchaseTransactionId == purchase.Id, ct);
        var creatorAccount = await db.CreatorBalanceAccounts.SingleAsync(x => x.CreatorId == purchase.CreatorId && x.CurrencyCode == reversal.CurrencyCode, ct);
        var originalJournal = await db.FinancialJournals.Include(x => x.Lines).SingleAsync(x => x.RelatedTransactionId == purchase.Id && x.Reference.StartsWith("FOUR-PARTY-"), ct);
        var trialFunded = originalJournal.Lines.Any(x => x.Account == JournalAccount.PlatformTrialCreditExpense && x.Type == JournalLineType.Debit);
        var ratio = reversal.Amount / purchase.CommissionSnapshot.TotalCommissionAmount;
        var creatorAmount = Math.Round(purchase.CommissionSnapshot.CreatorCommissionAmount * ratio, 2, MidpointRounding.AwayFromZero);
        var customerAmount = Math.Round(purchase.CommissionSnapshot.CustomerCashbackAmount * ratio, 2, MidpointRounding.AwayFromZero);
        var platformAmount = reversal.Amount - creatorAmount - customerAmount;

        if (trialFunded)
        {
            var trial = await db.MerchantTrialCredits.SingleAsync(x => x.MerchantId == purchase.MerchantId, ct);
            trial.Restore(reversal.Amount, reversal.ReversalType == ReversalType.Full, now);
            var merchant = await db.Merchants.SingleAsync(x => x.Id == purchase.MerchantId, ct);
            if (merchant.Status == MerchantStatus.FundingRestricted) merchant.Status = MerchantStatus.Active;
            Audit("TrialFundingRestored", actor, purchase.MerchantId, reversal.Id, reversal.CorrelationId);
        }
        else
        {
            var wallet = await db.MerchantWallets.SingleAsync(x => x.MerchantId == purchase.MerchantId && x.CurrencyCode == reversal.CurrencyCode, ct);
            var balance = wallet.Credit(reversal.Amount, 0, now);
            db.MerchantWalletEntries.Add(new MerchantWalletEntry { Id = Guid.NewGuid(), MerchantWalletId = wallet.Id, MerchantId = purchase.MerchantId, EntryType = MerchantWalletEntryType.ReversalCredit, Amount = reversal.Amount, CurrencyCode = reversal.CurrencyCode, BalanceBefore = balance.Before, BalanceAfter = balance.After, RelatedTransactionId = purchase.Id, IdempotencyKey = $"reversal:{reversal.Id}:wallet", Description = $"Reversal {reversal.PublicReversalId}", CreatedByUserId = actor, CorrelationId = reversal.CorrelationId, CreatedAtUtc = now });
            Audit("MerchantWalletCredited", actor, purchase.MerchantId, reversal.Id, reversal.CorrelationId);
        }

        var creatorPaid = earning.Status == CreatorEarningStatus.Paid;
        if (creatorPaid)
        {
            db.CreatorRecoveryBalances.Add(new CreatorRecoveryBalance { Id = Guid.NewGuid(), CreatorId = purchase.CreatorId, TransactionReversalId = reversal.Id, OriginalAmount = creatorAmount, OutstandingAmount = creatorAmount, CurrencyCode = reversal.CurrencyCode, Reason = reversal.Reason, CreatedAtUtc = now });
            Audit("CreatorRecoveryBalanceCreated", actor, purchase.MerchantId, reversal.Id, reversal.CorrelationId);
        }
        else
        {
            var category = earning.Status switch { CreatorEarningStatus.Pending => CreatorBalanceCategory.Pending, CreatorEarningStatus.Available => CreatorBalanceCategory.Available, CreatorEarningStatus.OnHold => CreatorBalanceCategory.Held, CreatorEarningStatus.ScheduledForPayout => CreatorBalanceCategory.Scheduled, _ => throw new InvalidOperationException("Unsupported earning state.") };
            var balance = creatorAccount.ReverseFrom(category, creatorAmount, now);
            db.CreatorBalanceEntries.Add(new CreatorBalanceEntry { Id = Guid.NewGuid(), CreatorBalanceAccountId = creatorAccount.Id, CreatorId = purchase.CreatorId, EntryType = CreatorBalanceEntryType.EarningReversal, Amount = creatorAmount, CurrencyCode = reversal.CurrencyCode, BalanceCategory = category, BalanceBefore = balance.Item1, BalanceAfter = balance.Item2, RelatedEarningId = earning.Id, RelatedTransactionId = purchase.Id, IdempotencyKey = $"reversal:{reversal.Id}:creator", Description = $"Reversal {reversal.PublicReversalId}", CorrelationId = reversal.CorrelationId, CreatedAtUtc = now });
            if (reversal.ReversalType == ReversalType.Full) earning.Reverse(now);
            Audit("CreatorBalanceReduced", actor, purchase.MerchantId, reversal.Id, reversal.CorrelationId);
        }

        decimal customerRecovery = 0;
        if (purchase.CustomerId.HasValue && customerAmount > 0)
        {
            var customerWallet = await db.CustomerWallets.SingleAsync(x => x.CustomerId == purchase.CustomerId && x.CurrencyCode == reversal.CurrencyCode, ct);
            if (customerWallet.ReservedCashback > 0 && customerWallet.AvailableCashback < customerAmount) throw new InvalidOperationException("Customer cashback is reserved in an active payout. Fail or cancel that payout before processing the reversal.");
            var balance = customerWallet.ReverseCashback(customerAmount, now);
            customerRecovery = balance.RecoveryCreated;
            db.CustomerCashbackEntries.Add(new CustomerCashbackEntry { Id = Guid.NewGuid(), CustomerWalletId = customerWallet.Id, CustomerId = purchase.CustomerId.Value, EntryType = CustomerCashbackEntryType.Reversal, Amount = customerAmount - customerRecovery, BalanceBefore = balance.Before, BalanceAfter = balance.After, CurrencyCode = reversal.CurrencyCode, PurchaseTransactionId = purchase.Id, IdempotencyKey = $"reversal:{reversal.Id}:customer", CorrelationId = reversal.CorrelationId, CreatedAtUtc = now });
            if (customerRecovery > 0)
            {
                db.CustomerRecoveryBalances.Add(new CustomerRecoveryBalance { Id = Guid.NewGuid(), CustomerId = purchase.CustomerId.Value, TransactionReversalId = reversal.Id, OriginalAmount = customerRecovery, OutstandingAmount = customerRecovery, CurrencyCode = reversal.CurrencyCode, Reason = reversal.Reason, CreatedAtUtc = now });
                db.CustomerCashbackEntries.Add(new CustomerCashbackEntry { Id = Guid.NewGuid(), CustomerWalletId = customerWallet.Id, CustomerId = purchase.CustomerId.Value, EntryType = CustomerCashbackEntryType.Recovery, Amount = customerRecovery, BalanceBefore = 0, BalanceAfter = customerWallet.RecoveryBalance, CurrencyCode = reversal.CurrencyCode, PurchaseTransactionId = purchase.Id, IdempotencyKey = $"reversal:{reversal.Id}:customer-recovery", CorrelationId = reversal.CorrelationId, CreatedAtUtc = now });
                Audit("CustomerRecoveryBalanceCreated", actor, purchase.MerchantId, reversal.Id, reversal.CorrelationId);
            }
        }

        var journal = new FinancialJournal { Id = Guid.NewGuid(), Reference = $"REV-{reversal.Id:N}", Description = $"Four-party reversal {reversal.PublicReversalId}", RelatedTransactionId = purchase.Id, CreatedAtUtc = now };
        journal.Lines.Add(new FinancialJournalLine { Id = Guid.NewGuid(), Account = JournalAccount.PlatformCommissionRevenue, Type = JournalLineType.Debit, Amount = platformAmount, CurrencyCode = reversal.CurrencyCode, Description = "Reverse platform revenue", CreatedAtUtc = now });
        journal.Lines.Add(new FinancialJournalLine { Id = Guid.NewGuid(), Account = creatorPaid ? JournalAccount.CreatorRecoveryReceivable : JournalAccount.CreatorPayable, Type = JournalLineType.Debit, Amount = creatorAmount, CurrencyCode = reversal.CurrencyCode, Description = "Reverse creator allocation", CreatedAtUtc = now });
        if (customerAmount - customerRecovery > 0) journal.Lines.Add(new FinancialJournalLine { Id = Guid.NewGuid(), Account = JournalAccount.CustomerCashbackPayable, Type = JournalLineType.Debit, Amount = customerAmount - customerRecovery, CurrencyCode = reversal.CurrencyCode, Description = "Reverse customer cashback", CreatedAtUtc = now });
        if (customerRecovery > 0) journal.Lines.Add(new FinancialJournalLine { Id = Guid.NewGuid(), Account = JournalAccount.CustomerRecoveryReceivable, Type = JournalLineType.Debit, Amount = customerRecovery, CurrencyCode = reversal.CurrencyCode, Description = "Record customer recovery", CreatedAtUtc = now });
        journal.Lines.Add(new FinancialJournalLine { Id = Guid.NewGuid(), Account = trialFunded ? JournalAccount.PlatformTrialCreditExpense : JournalAccount.MerchantWalletLiability, Type = JournalLineType.Credit, Amount = reversal.Amount, CurrencyCode = reversal.CurrencyCode, Description = trialFunded ? "Restore trial funding exposure" : "Credit merchant wallet", CreatedAtUtc = now });
        journal.Post(now);
        db.FinancialJournals.Add(journal);
        reversal.JournalReferences.Add(new ReversalJournalReference { Id = Guid.NewGuid(), FinancialJournalId = journal.Id, CreatedAtUtc = now });
        reversal.Items.Add(new ReversalItem { Id = Guid.NewGuid(), ItemType = "CreatorCommission", OriginalAmount = purchase.CommissionSnapshot.CreatorCommissionAmount, ReversedAmount = creatorAmount, CurrencyCode = reversal.CurrencyCode, CreatedAtUtc = now });
        reversal.Items.Add(new ReversalItem { Id = Guid.NewGuid(), ItemType = "CustomerCashback", OriginalAmount = purchase.CommissionSnapshot.CustomerCashbackAmount, ReversedAmount = customerAmount, CurrencyCode = reversal.CurrencyCode, CreatedAtUtc = now });
        reversal.Items.Add(new ReversalItem { Id = Guid.NewGuid(), ItemType = "PlatformCommission", OriginalAmount = purchase.CommissionSnapshot.PlatformCommissionAmount, ReversedAmount = platformAmount, CurrencyCode = reversal.CurrencyCode, CreatedAtUtc = now });
        purchase.ApplyReversal(reversal.ReversalType == ReversalType.Full, now, actor, reversal.CorrelationId);
        ReversalStatusChange(reversal, ReversalStatus.Completed, actor);
        Audit("FourPartyReversalProcessed", actor, purchase.MerchantId, reversal.Id, reversal.CorrelationId);
        Audit("JournalPosted", actor, purchase.MerchantId, journal.Id, reversal.CorrelationId);
        await db.SaveChangesAsync(ct);
        await transaction.CommitAsync(ct);
        return ReversalDto(reversal);
    }
    public async Task<object> CancelReversalAsync(Guid id, Guid actor, string reason, CancellationToken ct) { var x = await Reversals().SingleOrDefaultAsync(x => x.Id == id, ct) ?? throw new KeyNotFoundException(); if (x.Status is ReversalStatus.Completed or ReversalStatus.Processing) throw new InvalidOperationException("Processed reversal cannot be cancelled."); ReversalStatusChange(x, ReversalStatus.Cancelled, actor, reason); Audit("ReversalCancelled", actor, null, x.Id); await db.SaveChangesAsync(ct); return ReversalDto(x); }
}
