using CreatorPay.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CreatorPay.Infrastructure.Persistence.Configurations;

internal sealed class CommissionPlanConfiguration : IEntityTypeConfiguration<CommissionPlan> { public void Configure(EntityTypeBuilder<CommissionPlan> b) { b.ConfigureEntity(); b.Property(x=>x.Name).HasMaxLength(150).IsRequired(); b.Property(x=>x.Description).HasMaxLength(1000); b.HasIndex(x=>x.IsActive); b.HasMany(x=>x.Rules).WithOne(x=>x.Plan).HasForeignKey(x=>x.CommissionPlanId).OnDelete(DeleteBehavior.Restrict); } }
internal sealed class CommissionRuleConfiguration : IEntityTypeConfiguration<CommissionRule> { public void Configure(EntityTypeBuilder<CommissionRule> b) { b.ConfigureEntity(); b.Property(x=>x.Name).HasMaxLength(150).IsRequired(); b.Property(x=>x.CurrencyCode).HasMaxLength(3).IsRequired(); b.Property(x=>x.ScopeType).HasConversion<string>().HasMaxLength(30); b.HasIndex(x=>x.CurrencyCode); b.HasIndex(x=>x.IsActive); b.HasMany(x=>x.Versions).WithOne(x=>x.Rule).HasForeignKey(x=>x.CommissionRuleId).OnDelete(DeleteBehavior.Restrict); } }
internal sealed class CommissionRuleVersionConfiguration : IEntityTypeConfiguration<CommissionRuleVersion> { public void Configure(EntityTypeBuilder<CommissionRuleVersion> b) { b.ConfigureEntity(); b.Property(x=>x.MerchantCommissionRatePercent).HasPrecision(9,4); b.Property(x=>x.CreatorSharePercent).HasPrecision(9,4); b.Property(x=>x.PlatformSharePercent).HasPrecision(9,4); b.Property(x=>x.MinimumPurchaseAmount).HasPrecision(18,2); b.Property(x=>x.MaximumPurchaseAmount).HasPrecision(18,2); b.Property(x=>x.RoundingMode).HasConversion<string>().HasMaxLength(30); b.HasIndex(x=>new{x.CommissionRuleId,x.VersionNumber}).IsUnique(); b.HasIndex(x=>new{x.CommissionRuleId,x.EffectiveFromUtc,x.EffectiveToUtc}); b.HasIndex(x=>x.IsActive); } }
internal abstract class AssignmentConfiguration<T> : IEntityTypeConfiguration<T> where T:CommissionAssignment { public virtual void Configure(EntityTypeBuilder<T> b) { b.ConfigureEntity(); b.HasOne(x=>x.Rule).WithMany().HasForeignKey(x=>x.CommissionRuleId).OnDelete(DeleteBehavior.Restrict); b.HasIndex(x=>x.IsActive); } }
internal sealed class PlatformCommissionAssignmentConfiguration:AssignmentConfiguration<PlatformCommissionAssignment>{public override void Configure(EntityTypeBuilder<PlatformCommissionAssignment>b){base.Configure(b);b.Property(x=>x.CurrencyCode).HasMaxLength(3).IsRequired();b.HasIndex(x=>new{x.CurrencyCode,x.EffectiveFromUtc,x.EffectiveToUtc});}}
internal sealed class MerchantCommissionAssignmentConfiguration:AssignmentConfiguration<MerchantCommissionAssignment>{public override void Configure(EntityTypeBuilder<MerchantCommissionAssignment>b){base.Configure(b);b.HasIndex(x=>new{x.MerchantId,x.EffectiveFromUtc,x.EffectiveToUtc});}}
internal sealed class PartnershipCommissionAssignmentConfiguration:AssignmentConfiguration<PartnershipCommissionAssignment>{public override void Configure(EntityTypeBuilder<PartnershipCommissionAssignment>b){base.Configure(b);b.HasIndex(x=>new{x.MerchantCreatorPartnershipId,x.EffectiveFromUtc,x.EffectiveToUtc});}}
internal sealed class CampaignCommissionAssignmentConfiguration:AssignmentConfiguration<CampaignCommissionAssignment>{public override void Configure(EntityTypeBuilder<CampaignCommissionAssignment>b){base.Configure(b);b.HasIndex(x=>new{x.CampaignId,x.MerchantCreatorPartnershipId,x.EffectiveFromUtc});}}
internal sealed class CommissionCalculationSnapshotConfiguration:IEntityTypeConfiguration<CommissionCalculationSnapshot>{public void Configure(EntityTypeBuilder<CommissionCalculationSnapshot>b){b.ConfigureEntity();foreach(var p in new[]{nameof(CommissionCalculationSnapshot.PurchaseAmount),nameof(CommissionCalculationSnapshot.TotalCommissionAmount),nameof(CommissionCalculationSnapshot.CreatorCommissionAmount),nameof(CommissionCalculationSnapshot.PlatformCommissionAmount)})b.Property(p).HasPrecision(18,2);foreach(var p in new[]{nameof(CommissionCalculationSnapshot.MerchantCommissionRatePercent),nameof(CommissionCalculationSnapshot.CreatorSharePercent),nameof(CommissionCalculationSnapshot.PlatformSharePercent)})b.Property(p).HasPrecision(9,4);b.Property(x=>x.CurrencyCode).HasMaxLength(3);b.Property(x=>x.RoundingMode).HasConversion<string>();b.Property(x=>x.RuleSourceType).HasConversion<string>();b.HasOne(x=>x.RuleVersion).WithMany(x=>x.Snapshots).HasForeignKey(x=>x.CommissionRuleVersionId).OnDelete(DeleteBehavior.Restrict);}}
internal sealed class CommissionAuditEventConfiguration:IEntityTypeConfiguration<CommissionAuditEvent>{public void Configure(EntityTypeBuilder<CommissionAuditEvent>b){b.ConfigureEntity();b.Property(x=>x.EventType).HasMaxLength(100).IsRequired();b.Property(x=>x.BeforeValues).HasColumnType("jsonb");b.Property(x=>x.AfterValues).HasColumnType("jsonb");b.Property(x=>x.CorrelationId).HasMaxLength(100);b.HasIndex(x=>x.EventType);}}
