using CreatorPay.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace CreatorPay.Infrastructure.Persistence.Configurations;

internal sealed class CustomerPhoneReferenceConfiguration : IEntityTypeConfiguration<CustomerPhoneReference> { public void Configure(EntityTypeBuilder<CustomerPhoneReference> b) { b.ConfigureEntity(); b.Property(x => x.PhoneNumberHash).HasMaxLength(64); b.Property(x => x.MaskedPhoneNumber).HasMaxLength(30); b.Property(x => x.CountryCode).HasMaxLength(2); b.HasIndex(x => x.PhoneNumberHash).IsUnique(); } }
internal sealed class RepeatUseApprovalRequestConfiguration : IEntityTypeConfiguration<RepeatUseApprovalRequest> { public void Configure(EntityTypeBuilder<RepeatUseApprovalRequest> b) { b.ConfigureEntity(); b.Property(x => x.Status).HasConversion<string>(); b.Property(x => x.PurchaseAmount).HasPrecision(18, 2); b.Property(x => x.CustomerPhoneHash).HasMaxLength(64); b.Property(x => x.MaskedPhoneNumber).HasMaxLength(30); b.Property(x => x.CurrencyCode).HasMaxLength(3); b.Property(x => x.IdempotencyKey).HasMaxLength(200); b.HasIndex(x => x.PublicApprovalRequestId).IsUnique(); b.HasIndex(x => new { x.MerchantId, x.IdempotencyKey }).IsUnique(); b.HasIndex(x => new { x.MerchantId, x.CreatorId, x.CustomerPhoneHash, x.MerchantLocalDate }); } }
internal sealed class CustomerConfirmationConfiguration : IEntityTypeConfiguration<CustomerConfirmation> { public void Configure(EntityTypeBuilder<CustomerConfirmation> b) { b.ConfigureEntity(); b.Property(x => x.CodeHash).HasMaxLength(64); b.HasIndex(x => x.RepeatUseApprovalRequestId).IsUnique(); } }
internal sealed class RepeatUseApprovalHistoryConfiguration : IEntityTypeConfiguration<RepeatUseApprovalHistory> { public void Configure(EntityTypeBuilder<RepeatUseApprovalHistory> b) { b.ConfigureEntity(); b.Property(x => x.PreviousStatus).HasConversion<string>(); b.Property(x => x.NewStatus).HasConversion<string>(); b.Property(x => x.Action).HasMaxLength(80); b.HasIndex(x => new { x.RepeatUseApprovalRequestId, x.OccurredAtUtc }); } }
