using CreatorPay.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace CreatorPay.Infrastructure.Persistence.Configurations;

internal sealed class CustomerConfiguration : IEntityTypeConfiguration<Customer> { public void Configure(EntityTypeBuilder<Customer> b) { b.ConfigureEntity(); b.Property(x => x.PublicCustomerId).HasMaxLength(40); b.Property(x => x.Status).HasConversion<string>(); b.HasIndex(x => x.PublicCustomerId).IsUnique(); b.HasIndex(x => x.NormalizedPhoneNumber).IsUnique(); } }
internal sealed class CustomerWalletConfiguration : IEntityTypeConfiguration<CustomerWallet> { public void Configure(EntityTypeBuilder<CustomerWallet> b) { b.ConfigureEntity(); foreach (var p in new[] { nameof(CustomerWallet.AvailableCashback), nameof(CustomerWallet.ReservedCashback), nameof(CustomerWallet.PaidLifetime), nameof(CustomerWallet.RecoveryBalance) }) b.Property(p).HasPrecision(18, 2); b.Property(x => x.RowVersion).IsRowVersion(); b.HasIndex(x => new { x.CustomerId, x.CurrencyCode }).IsUnique(); b.HasOne<Customer>().WithMany().HasForeignKey(x => x.CustomerId).OnDelete(DeleteBehavior.Restrict); } }
internal sealed class CustomerCashbackEntryConfiguration : IEntityTypeConfiguration<CustomerCashbackEntry> { public void Configure(EntityTypeBuilder<CustomerCashbackEntry> b) { b.ConfigureEntity(); b.Property(x => x.EntryType).HasConversion<string>(); b.Property(x => x.Amount).HasPrecision(18, 2); b.Property(x => x.BalanceBefore).HasPrecision(18, 2); b.Property(x => x.BalanceAfter).HasPrecision(18, 2); b.HasIndex(x => x.IdempotencyKey).IsUnique(); b.HasIndex(x => new { x.CustomerId, x.CreatedAtUtc }); b.HasOne<CustomerWallet>().WithMany().HasForeignKey(x => x.CustomerWalletId).OnDelete(DeleteBehavior.Restrict); } }
internal sealed class CustomerRecoveryBalanceConfiguration : IEntityTypeConfiguration<CustomerRecoveryBalance> { public void Configure(EntityTypeBuilder<CustomerRecoveryBalance> b) { b.ConfigureEntity(); b.Property(x => x.OriginalAmount).HasPrecision(18, 2); b.Property(x => x.OutstandingAmount).HasPrecision(18, 2); b.Property(x => x.Status).HasConversion<string>(); b.HasIndex(x => x.TransactionReversalId).IsUnique(); b.HasIndex(x => new { x.CustomerId, x.Status }); } }
internal sealed class CustomerPayoutRequestConfiguration : IEntityTypeConfiguration<CustomerPayoutRequest> { public void Configure(EntityTypeBuilder<CustomerPayoutRequest> b) { b.ConfigureEntity(); b.Property(x => x.Amount).HasPrecision(18, 2); b.Property(x => x.Status).HasConversion<string>(); b.HasIndex(x => x.PublicPayoutId).IsUnique(); b.HasIndex(x => x.IdempotencyKey).IsUnique(); b.HasIndex(x => x.PaymentConfirmationIdempotencyKey).IsUnique().HasFilter("\"PaymentConfirmationIdempotencyKey\" IS NOT NULL"); b.HasIndex(x => new { x.Status, x.RequestedAtUtc }); } }
internal sealed class CheckoutSessionConfiguration : IEntityTypeConfiguration<CheckoutSession> { public void Configure(EntityTypeBuilder<CheckoutSession> b) { b.ConfigureEntity(); b.Property(x => x.Status).HasConversion<string>(); b.Property(x => x.PurchaseAmount).HasPrecision(18, 2); b.Property(x => x.ExpectedCreatorAmount).HasPrecision(18, 2); b.Property(x => x.ExpectedCashbackAmount).HasPrecision(18, 2); b.Property(x => x.RowVersion).IsRowVersion(); b.HasIndex(x => x.PublicCheckoutId).IsUnique(); b.HasIndex(x => x.TokenHash).IsUnique(); b.HasIndex(x => new { x.CustomerId, x.CreateIdempotencyKey }).IsUnique(); b.HasIndex(x => new { x.Status, x.ExpiresAtUtc }); b.HasOne<Customer>().WithMany().HasForeignKey(x => x.CustomerId).OnDelete(DeleteBehavior.Restrict); b.HasOne<CreatorMerchantCampaign>().WithMany().HasForeignKey(x => x.CampaignId).OnDelete(DeleteBehavior.Restrict); } }
internal sealed class SavedPromotionConfiguration : IEntityTypeConfiguration<SavedPromotion> { public void Configure(EntityTypeBuilder<SavedPromotion> b) { b.ConfigureEntity(); b.HasIndex(x => new { x.CustomerId, x.CampaignId }).IsUnique(); b.HasOne<Customer>().WithMany(x => x.SavedPromotions).HasForeignKey(x => x.CustomerId).OnDelete(DeleteBehavior.Restrict); b.HasOne<CreatorMerchantCampaign>().WithMany().HasForeignKey(x => x.CampaignId).OnDelete(DeleteBehavior.Restrict); } }
internal sealed class MerchantStoreQrConfiguration : IEntityTypeConfiguration<MerchantStoreQr> { public void Configure(EntityTypeBuilder<MerchantStoreQr> b) { b.ConfigureEntity(); b.HasIndex(x => x.MerchantId).IsUnique(); b.HasIndex(x => x.PublicQrId).IsUnique(); b.HasIndex(x => x.TokenHash).IsUnique(); } }
internal sealed class MerchantPromotionProfileConfiguration : IEntityTypeConfiguration<MerchantPromotionProfile> { public void Configure(EntityTypeBuilder<MerchantPromotionProfile> b) { b.ConfigureEntity(); b.Property(x => x.SocialLinksJson).HasColumnType("jsonb"); b.HasIndex(x => x.MerchantId).IsUnique(); } }
internal sealed class MerchantTrialCreditConfiguration : IEntityTypeConfiguration<MerchantTrialCredit> { public void Configure(EntityTypeBuilder<MerchantTrialCredit> b) { b.ConfigureEntity(); b.Property(x => x.Status).HasConversion<string>(); b.Property(x => x.TotalCommissionFunded).HasPrecision(18, 2); b.Property(x => x.MaximumCommission).HasPrecision(18, 2); b.Property(x => x.RowVersion).IsRowVersion(); b.HasIndex(x => x.MerchantId).IsUnique(); } }
internal sealed class PlatformRevenueEntryConfiguration : IEntityTypeConfiguration<PlatformRevenueEntry> { public void Configure(EntityTypeBuilder<PlatformRevenueEntry> b) { b.ConfigureEntity(); b.Property(x => x.Amount).HasPrecision(18, 2); b.HasIndex(x => x.PurchaseTransactionId).IsUnique(); b.HasIndex(x => x.IdempotencyKey).IsUnique(); } }
