using CreatorPay.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CreatorPay.Infrastructure.Persistence.Configurations;

internal sealed class CreatorEarningConfiguration : IEntityTypeConfiguration<CreatorEarning> { public void Configure(EntityTypeBuilder<CreatorEarning> b) { b.ConfigureEntity(); b.Property(x => x.Amount).HasPrecision(18, 2); b.Property(x => x.CurrencyCode).HasMaxLength(3); b.Property(x => x.Status).HasConversion<string>(); b.Property(x => x.CorrelationId).HasMaxLength(100); b.HasIndex(x => x.PurchaseTransactionId).IsUnique(); b.HasIndex(x => new { x.CreatorId, x.Status, x.AvailableAtUtc }); b.HasOne<PurchaseTransaction>().WithMany().HasForeignKey(x => x.PurchaseTransactionId).OnDelete(DeleteBehavior.Restrict); b.HasOne<CommissionCalculationSnapshot>().WithMany().HasForeignKey(x => x.CommissionCalculationSnapshotId).OnDelete(DeleteBehavior.Restrict); } }
internal sealed class CreatorBalanceAccountConfiguration : IEntityTypeConfiguration<CreatorBalanceAccount> { public void Configure(EntityTypeBuilder<CreatorBalanceAccount> b) { b.ConfigureEntity(); foreach (var p in new[] { nameof(CreatorBalanceAccount.PendingBalance), nameof(CreatorBalanceAccount.AvailableBalance), nameof(CreatorBalanceAccount.HeldBalance), nameof(CreatorBalanceAccount.ScheduledBalance), nameof(CreatorBalanceAccount.PaidLifetimeTotal), nameof(CreatorBalanceAccount.ReversedLifetimeTotal) }) b.Property(p).HasPrecision(18, 2); b.Property(x => x.CurrencyCode).HasMaxLength(3); b.Property(x => x.ConcurrencyToken).IsRowVersion(); b.HasIndex(x => new { x.CreatorId, x.CurrencyCode }).IsUnique(); b.HasOne<Creator>().WithMany().HasForeignKey(x => x.CreatorId).OnDelete(DeleteBehavior.Restrict); } }
internal sealed class CreatorBalanceEntryConfiguration : IEntityTypeConfiguration<CreatorBalanceEntry> { public void Configure(EntityTypeBuilder<CreatorBalanceEntry> b) { b.ConfigureEntity(); b.Property(x => x.Amount).HasPrecision(18, 2); b.Property(x => x.BalanceBefore).HasPrecision(18, 2); b.Property(x => x.BalanceAfter).HasPrecision(18, 2); b.Property(x => x.EntryType).HasConversion<string>(); b.Property(x => x.BalanceCategory).HasConversion<string>(); b.Property(x => x.IdempotencyKey).HasMaxLength(200); b.HasIndex(x => x.IdempotencyKey).IsUnique(); b.HasIndex(x => new { x.CreatorBalanceAccountId, x.CreatedAtUtc }); b.HasOne<CreatorBalanceAccount>().WithMany().HasForeignKey(x => x.CreatorBalanceAccountId).OnDelete(DeleteBehavior.Restrict); } }
internal sealed class PayoutBatchConfiguration : IEntityTypeConfiguration<PayoutBatch> { public void Configure(EntityTypeBuilder<PayoutBatch> b) { b.ConfigureEntity(); b.Property(x => x.TotalAmount).HasPrecision(18, 2); b.Property(x => x.Status).HasConversion<string>(); b.HasIndex(x => x.PublicBatchId).IsUnique(); b.HasIndex(x => new { x.Status, x.ScheduledForUtc }); b.HasIndex(x => new { x.CurrencyCode, x.CutoffAtUtc, x.CorrelationId }).IsUnique(); } }
internal sealed class CreatorPayoutConfiguration : IEntityTypeConfiguration<CreatorPayout> { public void Configure(EntityTypeBuilder<CreatorPayout> b) { b.ConfigureEntity(); b.Property(x => x.Amount).HasPrecision(18, 2); b.Property(x => x.Status).HasConversion<string>(); b.Property(x => x.PayoutMethodType).HasConversion<string>(); b.HasIndex(x => x.PublicPayoutId).IsUnique(); b.HasIndex(x => x.IdempotencyKey).IsUnique(); b.HasIndex(x => new { x.CreatorId, x.Status }); b.HasOne(x => x.Batch).WithMany(x => x.Payouts).HasForeignKey(x => x.PayoutBatchId).OnDelete(DeleteBehavior.Restrict); } }
internal sealed class PayoutItemConfiguration : IEntityTypeConfiguration<PayoutItem> { public void Configure(EntityTypeBuilder<PayoutItem> b) { b.ConfigureEntity(); b.Property(x => x.Amount).HasPrecision(18, 2); b.HasIndex(x => x.CreatorEarningId).IsUnique(); b.HasOne(x => x.Payout).WithMany(x => x.Items).HasForeignKey(x => x.CreatorPayoutId).OnDelete(DeleteBehavior.Restrict); b.HasOne(x => x.Earning).WithMany().HasForeignKey(x => x.CreatorEarningId).OnDelete(DeleteBehavior.Restrict); } }
internal sealed class PayoutAttemptConfiguration : IEntityTypeConfiguration<PayoutAttempt> { public void Configure(EntityTypeBuilder<PayoutAttempt> b) { b.ConfigureEntity(); b.Property(x => x.Status).HasConversion<string>(); b.HasIndex(x => new { x.CreatorPayoutId, x.AttemptNumber }).IsUnique(); b.HasOne<CreatorPayout>().WithMany(x => x.Attempts).HasForeignKey(x => x.CreatorPayoutId).OnDelete(DeleteBehavior.Restrict); } }
