using CreatorPay.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CreatorPay.Infrastructure.Persistence.Configurations;

public sealed class NotificationConfiguration : IEntityTypeConfiguration<Notification>
{
    public void Configure(EntityTypeBuilder<Notification> b) { b.ToTable("Notifications"); b.HasKey(x => x.Id); b.Property(x => x.PublicNotificationId).HasMaxLength(64).IsRequired(); b.HasIndex(x => x.PublicNotificationId).IsUnique(); b.Property(x => x.IdempotencyKey).HasMaxLength(200).IsRequired(); b.HasIndex(x => x.IdempotencyKey).IsUnique(); b.Property(x => x.Title).HasMaxLength(300).IsRequired(); b.Property(x => x.Body).HasMaxLength(4000).IsRequired(); b.Property(x => x.DataJson).HasColumnType("jsonb"); b.Property(x => x.CorrelationId).HasMaxLength(200); b.Property(x => x.RelatedEntityType).HasMaxLength(100); b.Property(x => x.RelatedEntityId).HasMaxLength(100); b.HasMany(x => x.Recipients).WithOne(x => x.Notification).HasForeignKey(x => x.NotificationId).OnDelete(DeleteBehavior.Restrict); }
}
public sealed class NotificationRecipientConfiguration : IEntityTypeConfiguration<NotificationRecipient> { public void Configure(EntityTypeBuilder<NotificationRecipient> b) { b.ToTable("NotificationRecipients"); b.HasKey(x => x.Id); b.Property(x => x.DestinationReference).HasMaxLength(500); b.Property(x => x.MaskedDestination).HasMaxLength(100); b.Property(x => x.FailureReason).HasMaxLength(500); b.Property(x => x.LanguageCode).HasMaxLength(10); b.HasIndex(x => new { x.UserAccountId, x.Status, x.CreatedAtUtc }); } }
public sealed class NotificationTemplateConfiguration : IEntityTypeConfiguration<NotificationTemplate> { public void Configure(EntityTypeBuilder<NotificationTemplate> b) { b.ToTable("NotificationTemplates"); b.HasKey(x => x.Id); b.Property(x => x.LanguageCode).HasMaxLength(10); b.Property(x => x.SubjectTemplate).HasMaxLength(300); b.Property(x => x.BodyTemplate).HasMaxLength(4000).IsRequired(); b.Property(x => x.AllowedPlaceholdersJson).HasColumnType("jsonb"); b.HasIndex(x => new { x.NotificationType, x.Channel, x.LanguageCode, x.VersionNumber }).IsUnique(); } }
public sealed class NotificationOutboxConfiguration : IEntityTypeConfiguration<NotificationOutboxMessage> { public void Configure(EntityTypeBuilder<NotificationOutboxMessage> b) { b.ToTable("NotificationOutboxMessages"); b.HasKey(x => x.Id); b.Property(x => x.LockedBy).HasMaxLength(200); b.Property(x => x.LastError).HasMaxLength(1000); b.Property(x => x.CorrelationId).HasMaxLength(200); b.Property(x => x.Version).IsRowVersion(); b.HasIndex(x => new { x.Status, x.AvailableAtUtc }); b.HasOne(x => x.Notification).WithMany().HasForeignKey(x => x.NotificationId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class NotificationDeliveryAttemptConfiguration : IEntityTypeConfiguration<NotificationDeliveryAttempt> { public void Configure(EntityTypeBuilder<NotificationDeliveryAttempt> b) { b.ToTable("NotificationDeliveryAttempts"); b.HasKey(x => x.Id); b.Property(x => x.ProviderName).HasMaxLength(100); b.Property(x => x.ProviderMessageReference).HasMaxLength(200); b.Property(x => x.ErrorCode).HasMaxLength(100); b.Property(x => x.ErrorMessage).HasMaxLength(500); b.HasIndex(x => new { x.NotificationRecipientId, x.AttemptNumber }).IsUnique(); } }
public sealed class NotificationPreferenceConfiguration : IEntityTypeConfiguration<NotificationPreference> { public void Configure(EntityTypeBuilder<NotificationPreference> b) { b.ToTable("NotificationPreferences"); b.HasKey(x => x.Id); b.Property(x => x.LanguageCode).HasMaxLength(10); b.HasIndex(x => new { x.UserAccountId, x.NotificationType }).IsUnique(); } }
public sealed class NotificationDeadLetterConfiguration : IEntityTypeConfiguration<NotificationDeadLetter> { public void Configure(EntityTypeBuilder<NotificationDeadLetter> b) { b.ToTable("NotificationDeadLetters"); b.HasKey(x => x.Id); b.Property(x => x.Reason).HasMaxLength(1000); b.HasIndex(x => x.OutboxMessageId).IsUnique(); } }
public sealed class NotificationAuditEventConfiguration : IEntityTypeConfiguration<NotificationAuditEvent> { public void Configure(EntityTypeBuilder<NotificationAuditEvent> b) { b.ToTable("NotificationAuditEvents"); b.HasKey(x => x.Id); b.Property(x => x.EventType).HasMaxLength(100); b.Property(x => x.SafeDetail).HasMaxLength(1000); b.HasIndex(x => new { x.NotificationId, x.CreatedAtUtc }); } }
