using CreatorPay.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CreatorPay.Infrastructure.Persistence.Configurations;

internal sealed class FraudRuleConfiguration:IEntityTypeConfiguration<FraudRule>{public void Configure(EntityTypeBuilder<FraudRule>b){b.ConfigureEntity();b.Property(x=>x.Code).HasMaxLength(100);b.HasIndex(x=>x.Code).IsUnique();b.HasMany(x=>x.Versions).WithOne(x=>x.Rule).HasForeignKey(x=>x.FraudRuleId).OnDelete(DeleteBehavior.Restrict);}}
internal sealed class FraudRuleVersionConfiguration:IEntityTypeConfiguration<FraudRuleVersion>{public void Configure(EntityTypeBuilder<FraudRuleVersion>b){b.ConfigureEntity();b.Property(x=>x.ConfigurationJson).HasColumnType("jsonb");b.Property(x=>x.Severity).HasConversion<string>();b.Property(x=>x.Decision).HasConversion<string>();b.HasIndex(x=>new{x.FraudRuleId,x.VersionNumber}).IsUnique();}}
internal sealed class FraudAlertConfiguration:IEntityTypeConfiguration<FraudAlert>{public void Configure(EntityTypeBuilder<FraudAlert>b){b.ConfigureEntity();b.Property(x=>x.PublicFraudAlertId).HasMaxLength(40);b.Property(x=>x.RuleCode).HasMaxLength(100);b.Property(x=>x.Severity).HasConversion<string>();b.Property(x=>x.Status).HasConversion<string>();b.Property(x=>x.EvidenceJson).HasColumnType("jsonb");b.Property(x=>x.CustomerPhoneHash).HasMaxLength(64);b.HasIndex(x=>x.PublicFraudAlertId).IsUnique();b.HasIndex(x=>new{x.Status,x.Severity,x.DetectedAtUtc});b.HasIndex(x=>new{x.FraudRuleVersionId,x.PurchaseTransactionId}).IsUnique().HasFilter("\"PurchaseTransactionId\" IS NOT NULL");b.HasMany(x=>x.Evidence).WithOne(x=>x.Alert).HasForeignKey(x=>x.FraudAlertId).OnDelete(DeleteBehavior.Restrict);b.HasMany(x=>x.ReviewHistory).WithOne(x=>x.Alert).HasForeignKey(x=>x.FraudAlertId).OnDelete(DeleteBehavior.Restrict);}}
internal sealed class FraudEvidenceConfiguration:IEntityTypeConfiguration<FraudEvidence>{public void Configure(EntityTypeBuilder<FraudEvidence>b){b.ConfigureEntity();b.Property(x=>x.MetadataJson).HasColumnType("jsonb");}}
internal sealed class FraudReviewHistoryConfiguration:IEntityTypeConfiguration<FraudReviewHistory>{public void Configure(EntityTypeBuilder<FraudReviewHistory>b){b.ConfigureEntity();b.Property(x=>x.PreviousStatus).HasConversion<string>();b.Property(x=>x.NewStatus).HasConversion<string>();}}
internal sealed class DisputeConfiguration:IEntityTypeConfiguration<Dispute>{public void Configure(EntityTypeBuilder<Dispute>b){b.ConfigureEntity();b.Property(x=>x.PublicDisputeId).HasMaxLength(40);b.Property(x=>x.DisputeType).HasConversion<string>();b.Property(x=>x.Status).HasConversion<string>();b.HasIndex(x=>x.PublicDisputeId).IsUnique();b.HasIndex(x=>new{x.Status,x.OpenedAtUtc});b.HasMany(x=>x.Evidence).WithOne(x=>x.Dispute).HasForeignKey(x=>x.DisputeId).OnDelete(DeleteBehavior.Restrict);b.HasMany(x=>x.StatusHistory).WithOne(x=>x.Dispute).HasForeignKey(x=>x.DisputeId).OnDelete(DeleteBehavior.Restrict);b.HasMany(x=>x.Decisions).WithOne(x=>x.Dispute).HasForeignKey(x=>x.DisputeId).OnDelete(DeleteBehavior.Restrict);}}
internal sealed class DisputeEvidenceConfiguration:IEntityTypeConfiguration<DisputeEvidence>{public void Configure(EntityTypeBuilder<DisputeEvidence>b){b.ConfigureEntity();b.Property(x=>x.MetadataJson).HasColumnType("jsonb");}}
internal sealed class DisputeStatusHistoryConfiguration:IEntityTypeConfiguration<DisputeStatusHistory>{public void Configure(EntityTypeBuilder<DisputeStatusHistory>b){b.ConfigureEntity();b.Property(x=>x.PreviousStatus).HasConversion<string>();b.Property(x=>x.NewStatus).HasConversion<string>();}}
internal sealed class DisputeDecisionConfiguration:IEntityTypeConfiguration<DisputeDecision>{public void Configure(EntityTypeBuilder<DisputeDecision>b)=>b.ConfigureEntity();}
internal sealed class TransactionReversalConfiguration:IEntityTypeConfiguration<TransactionReversal>{public void Configure(EntityTypeBuilder<TransactionReversal>b){b.ConfigureEntity();b.Property(x=>x.Amount).HasPrecision(18,2);b.Property(x=>x.ReversalType).HasConversion<string>();b.Property(x=>x.Status).HasConversion<string>();b.HasIndex(x=>x.PublicReversalId).IsUnique();b.HasIndex(x=>x.IdempotencyKey).IsUnique();b.HasIndex(x=>new{x.Status,x.RequestedAtUtc});b.HasIndex(x=>x.PurchaseTransactionId).IsUnique().HasFilter("\"ReversalType\" = 'Full' AND \"Status\" = 'Completed'");b.HasMany(x=>x.Items).WithOne(x=>x.Reversal).HasForeignKey(x=>x.TransactionReversalId).OnDelete(DeleteBehavior.Restrict);b.HasMany(x=>x.JournalReferences).WithOne(x=>x.Reversal).HasForeignKey(x=>x.TransactionReversalId).OnDelete(DeleteBehavior.Restrict);b.HasMany(x=>x.StatusHistory).WithOne(x=>x.Reversal).HasForeignKey(x=>x.TransactionReversalId).OnDelete(DeleteBehavior.Restrict);}}
internal sealed class ReversalItemConfiguration:IEntityTypeConfiguration<ReversalItem>{public void Configure(EntityTypeBuilder<ReversalItem>b){b.ConfigureEntity();b.Property(x=>x.OriginalAmount).HasPrecision(18,2);b.Property(x=>x.ReversedAmount).HasPrecision(18,2);}}
internal sealed class ReversalJournalReferenceConfiguration:IEntityTypeConfiguration<ReversalJournalReference>{public void Configure(EntityTypeBuilder<ReversalJournalReference>b){b.ConfigureEntity();b.HasIndex(x=>new{x.TransactionReversalId,x.FinancialJournalId}).IsUnique();}}
internal sealed class ReversalStatusHistoryConfiguration:IEntityTypeConfiguration<ReversalStatusHistory>{public void Configure(EntityTypeBuilder<ReversalStatusHistory>b){b.ConfigureEntity();b.Property(x=>x.PreviousStatus).HasConversion<string>();b.Property(x=>x.NewStatus).HasConversion<string>();}}
internal sealed class CreatorRecoveryBalanceConfiguration:IEntityTypeConfiguration<CreatorRecoveryBalance>{public void Configure(EntityTypeBuilder<CreatorRecoveryBalance>b){b.ConfigureEntity();b.Property(x=>x.OriginalAmount).HasPrecision(18,2);b.Property(x=>x.OutstandingAmount).HasPrecision(18,2);b.Property(x=>x.Status).HasConversion<string>();b.HasIndex(x=>x.TransactionReversalId).IsUnique();}}
internal sealed class OperationalAuditEventConfiguration:IEntityTypeConfiguration<OperationalAuditEvent>{public void Configure(EntityTypeBuilder<OperationalAuditEvent>b){b.ConfigureEntity();b.Property(x=>x.MetadataJson).HasColumnType("jsonb");b.HasIndex(x=>new{x.EventType,x.CreatedAtUtc});}}
