using CreatorPay.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CreatorPay.Infrastructure.Persistence.Configurations;

internal sealed class MerchantWalletConfiguration : IEntityTypeConfiguration<MerchantWallet> { public void Configure(EntityTypeBuilder<MerchantWallet> b) { b.ConfigureEntity(); b.Property(x => x.CurrencyCode).HasMaxLength(3); b.Property(x => x.AvailableBalance).HasPrecision(18, 2); b.Property(x => x.HeldBalance).HasPrecision(18, 2); b.Property(x => x.Status).HasConversion<string>().HasMaxLength(30); b.Property(x => x.ConcurrencyToken).IsRowVersion(); b.HasIndex(x => new { x.MerchantId, x.CurrencyCode }).IsUnique(); b.HasOne(x => x.Merchant).WithMany().HasForeignKey(x => x.MerchantId).OnDelete(DeleteBehavior.Restrict); } }
internal sealed class MerchantWalletEntryConfiguration : IEntityTypeConfiguration<MerchantWalletEntry> { public void Configure(EntityTypeBuilder<MerchantWalletEntry> b) { b.ConfigureEntity(); b.Property(x => x.EntryType).HasConversion<string>(); b.Property(x => x.Amount).HasPrecision(18, 2); b.Property(x => x.BalanceBefore).HasPrecision(18, 2); b.Property(x => x.BalanceAfter).HasPrecision(18, 2); b.Property(x => x.CurrencyCode).HasMaxLength(3); b.Property(x => x.IdempotencyKey).HasMaxLength(200); b.Property(x => x.CorrelationId).HasMaxLength(100); b.HasIndex(x => x.IdempotencyKey).IsUnique().HasFilter("\"IdempotencyKey\" IS NOT NULL"); b.HasIndex(x => new { x.MerchantWalletId, x.CreatedAtUtc }); b.HasOne(x => x.Wallet).WithMany(x => x.Entries).HasForeignKey(x => x.MerchantWalletId).OnDelete(DeleteBehavior.Restrict); } }
internal sealed class MerchantDepositConfiguration : IEntityTypeConfiguration<MerchantDeposit> { public void Configure(EntityTypeBuilder<MerchantDeposit> b) { b.ConfigureEntity(); b.Property(x => x.Amount).HasPrecision(18, 2); b.Property(x => x.CurrencyCode).HasMaxLength(3); b.Property(x => x.Status).HasConversion<string>(); b.Property(x => x.IdempotencyKey).HasMaxLength(200); b.Property(x => x.ExternalReference).HasMaxLength(200); b.Property(x => x.RequestHash).HasMaxLength(64); b.HasIndex(x => new { x.MerchantId, x.IdempotencyKey }).IsUnique(); b.HasIndex(x => new { x.MerchantId, x.ExternalReference }).IsUnique(); b.HasIndex(x => x.Status); b.HasOne(x => x.Wallet).WithMany().HasForeignKey(x => x.MerchantWalletId).OnDelete(DeleteBehavior.Restrict); } }
internal sealed class MerchantWalletHoldConfiguration : IEntityTypeConfiguration<MerchantWalletHold> { public void Configure(EntityTypeBuilder<MerchantWalletHold> b) { b.ConfigureEntity(); b.Property(x => x.Amount).HasPrecision(18, 2); b.Property(x => x.Status).HasConversion<string>(); } }
internal sealed class FinancialJournalConfiguration : IEntityTypeConfiguration<FinancialJournal> { public void Configure(EntityTypeBuilder<FinancialJournal> b) { b.ConfigureEntity(); b.HasMany(x => x.Lines).WithOne(x => x.Journal).HasForeignKey(x => x.FinancialJournalId).OnDelete(DeleteBehavior.Restrict); } }
internal sealed class FinancialJournalLineConfiguration : IEntityTypeConfiguration<FinancialJournalLine> { public void Configure(EntityTypeBuilder<FinancialJournalLine> b) { b.ConfigureEntity(); b.Property(x => x.Amount).HasPrecision(18, 2); b.Property(x => x.Account).HasConversion<string>(); b.Property(x => x.Type).HasConversion<string>(); } }
internal sealed class PurchaseTransactionConfiguration : IEntityTypeConfiguration<PurchaseTransaction> { public void Configure(EntityTypeBuilder<PurchaseTransaction> b) { b.ConfigureEntity(); b.Property(x => x.MerchantLocationId).IsRequired(false); b.Property(x => x.CashierId).IsRequired(false); b.Property(x => x.PurchaseAmount).HasPrecision(18, 2); b.Property(x => x.Status).HasConversion<string>(); b.Property(x => x.CurrencyCode).HasMaxLength(3); b.Property(x => x.IdempotencyKey).HasMaxLength(200); b.Property(x => x.CustomerPhoneHash).HasMaxLength(64); b.HasIndex(x => x.PublicTransactionId).IsUnique(); b.HasIndex(x => new { x.MerchantId, x.IdempotencyKey }).IsUnique(); b.HasIndex(x => new { x.MerchantId, x.CreatorId, x.CustomerPhoneHash, x.MerchantLocalDate }); b.HasIndex(x => new { x.CashierId, x.TransactionDateUtc }); b.HasOne(x => x.CommissionSnapshot).WithMany().HasForeignKey(x => x.CommissionCalculationSnapshotId).OnDelete(DeleteBehavior.Restrict); b.HasMany(x => x.StatusHistory).WithOne(x => x.PurchaseTransaction).HasForeignKey(x => x.PurchaseTransactionId).OnDelete(DeleteBehavior.Restrict); } }
internal sealed class TransactionStatusHistoryConfiguration : IEntityTypeConfiguration<TransactionStatusHistory> { public void Configure(EntityTypeBuilder<TransactionStatusHistory> b) { b.ConfigureEntity(); b.Property(x => x.PreviousStatus).HasConversion<string>(); b.Property(x => x.NewStatus).HasConversion<string>(); } }
internal sealed class IdempotencyRecordConfiguration : IEntityTypeConfiguration<IdempotencyRecord> { public void Configure(EntityTypeBuilder<IdempotencyRecord> b) { b.ConfigureEntity(); b.Property(x => x.Scope).HasMaxLength(100); b.Property(x => x.Key).HasMaxLength(200); b.Property(x => x.RequestHash).HasMaxLength(64); b.Property(x => x.Status).HasConversion<string>(); b.HasIndex(x => new { x.Scope, x.Key }).IsUnique(); } }
