using System.ComponentModel.DataAnnotations;
using CreatorPay.Application.Authentication;
using CreatorPay.Application.Creators;
using CreatorPay.Domain.Entities;
using CreatorPay.Domain.Enums;
using Microsoft.Extensions.Options;

namespace CreatorPay.Application.Merchants;

public sealed class MerchantService(IMerchantStore store, IPasswordHasher passwords, ITokenService tokens, IUtcClock clock, IMerchantVerificationProvider verifier, IMerchantDocumentStorage storage, PasswordPolicyValidator passwordPolicy, IOptions<CreatorVerificationOptions> options) : IMerchantService
{
    public Task<MerchantResult<MerchantRegistrationResponse>> RegisterAsync(RegisterMerchantRequest r, CancellationToken ct)
    {
        var error = Validate(r.LegalBusinessName, r.TradingName, r.BusinessType, r.PhoneNumber, r.Email, r.BusinessAddress, r.City, r.Region, r.Country, r.TimeZone); if (error is not null) return Task.FromResult(MerchantResult<MerchantRegistrationResponse>.Failure(error));
        if (!r.TermsAccepted) return Task.FromResult(MerchantResult<MerchantRegistrationResponse>.Failure("Terms acceptance is required."));
        if (string.IsNullOrWhiteSpace(r.PrimaryContactName) || r.PrimaryContactName.Trim().Length > 200) return Task.FromResult(MerchantResult<MerchantRegistrationResponse>.Failure("Primary contact name is required."));
        if (r.PreferredLanguage is not ("en" or "am")) return Task.FromResult(MerchantResult<MerchantRegistrationResponse>.Failure("Preferred language must be en or am."));
        var passwordErrors = passwordPolicy.Validate(r.Password); if (passwordErrors.Count > 0) return Task.FromResult(MerchantResult<MerchantRegistrationResponse>.Failure(string.Join(" ", passwordErrors)));
        var documentError = ValidateDocuments(r.Documents); if (documentError is not null) return Task.FromResult(MerchantResult<MerchantRegistrationResponse>.Failure(documentError));
        return store.InTransactionAsync(async inner =>
        {
            var email = NormalizeEmail(r.Email); var phone = NormalizePhone(r.PhoneNumber); if (await store.EmailExistsAsync(email, null, inner)) return MerchantResult<MerchantRegistrationResponse>.Failure("Email is already registered."); if (await store.PhoneExistsAsync(phone, null, inner)) return MerchantResult<MerchantRegistrationResponse>.Failure("Phone number is already registered.");
            var now = clock.UtcNow; var merchantId = Guid.NewGuid(); var userId = Guid.NewGuid(); var merchant = new Merchant { Id = merchantId, PublicMerchantId = $"ME-{Guid.NewGuid():N}"[..15].ToUpperInvariant(), LegalBusinessName = r.LegalBusinessName.Trim(), TradingName = r.TradingName.Trim(), BusinessType = r.BusinessType.Trim(), PrimaryContactName = r.PrimaryContactName!.Trim(), TaxRegistrationNumber = Clean(r.TaxRegistrationNumber), BusinessRegistrationNumber = Clean(r.BusinessRegistrationNumber), PreferredLanguage = r.PreferredLanguage, TermsAcceptedAtUtc = now, PhoneNumber = FormatPhone(phone), NormalizedPhoneNumber = phone, Email = r.Email.Trim(), BusinessAddress = r.BusinessAddress.Trim(), City = r.City.Trim(), Region = r.Region.Trim(), Country = r.Country.Trim(), TimeZone = r.TimeZone.Trim(), Status = MerchantStatus.PendingReview, CreatedAtUtc = now, CreatedBy = userId.ToString() };
            var user = new UserAccount { Id = userId, Email = r.Email.Trim(), NormalizedEmail = email, Role = UserRole.MerchantAdmin, Status = AccountStatus.PendingVerification, MerchantId = merchantId, CreatedAtUtc = now, CreatedBy = userId.ToString() }; user.PasswordHash = passwords.Hash(user, r.Password); store.Add(merchant); store.Add(user); AddDocuments(merchantId, userId, r.Documents, now); var e = Issue(userId, "Email", now); var p = Issue(userId, "Phone", now); store.Add(e.Item); store.Add(p.Item); Audit(merchantId, userId, "Registration", null, now); await store.SaveAsync(inner); await verifier.SendEmailVerificationAsync(user, e.Raw, inner); await verifier.SendPhoneVerificationAsync(merchant, p.Raw, inner); return MerchantResult<MerchantRegistrationResponse>.Success(new(merchantId, merchant.PublicMerchantId, "Registration received. Complete email and phone verification before platform review."));
        }, ct);
    }
    public Task<MerchantResult> VerifyEmailAsync(string token, CancellationToken ct) => VerifyAsync(token, "Email", ct); public Task<MerchantResult> VerifyPhoneAsync(string token, CancellationToken ct) => VerifyAsync(token, "Phone", ct);
    private Task<MerchantResult> VerifyAsync(string raw, string purpose, CancellationToken ct) => store.InTransactionAsync(async inner => { if (string.IsNullOrWhiteSpace(raw)) return MerchantResult.Failure("Invalid or expired verification token."); var hash = tokens.HashToken(raw); var token = await store.FindTokenAsync(hash, purpose, inner); var now = clock.UtcNow; if (token is null || token.UsedAtUtc is not null || token.ExpiresAtUtc <= now) return MerchantResult.Failure("Invalid or expired verification token."); var pair = await store.FindByTokenAsync(hash, purpose, inner); if (pair is null) return MerchantResult.Failure("Invalid or expired verification token."); token.UsedAtUtc = now; if (purpose == "Email") pair.Value.User.IsEmailVerified = true; else pair.Value.User.IsPhoneVerified = true; if (pair.Value.User.IsEmailVerified && pair.Value.User.IsPhoneVerified) pair.Value.User.Status = AccountStatus.PendingApproval; Audit(pair.Value.Merchant.Id, pair.Value.User.Id, $"{purpose}Verification", null, now); await store.SaveAsync(inner); return MerchantResult.Success(); }, ct);
    public async Task<MerchantResult<MerchantProfileResponse>> GetMeAsync(Guid userId, CancellationToken ct) { var p = await store.FindByUserAsync(userId, ct); return p is null ? MerchantResult<MerchantProfileResponse>.Failure("Merchant not found.") : MerchantResult<MerchantProfileResponse>.Success(ToProfile(p.Value.User, p.Value.Merchant, p.Value.Documents)); }
    public Task<MerchantResult<MerchantProfileResponse>> UpdateMeAsync(Guid userId, UpdateMerchantProfileRequest r, CancellationToken ct) => store.InTransactionAsync(async inner => { var p = await store.FindByUserAsync(userId, inner); if (p is null) return MerchantResult<MerchantProfileResponse>.Failure("Merchant not found."); var error = Validate(r.LegalBusinessName, r.TradingName, r.BusinessType, r.PhoneNumber, r.Email, r.BusinessAddress, r.City, r.Region, r.Country, r.TimeZone) ?? ValidateFile(r.Logo, true) ?? ValidateDocuments(r.Documents); if (error is not null) return MerchantResult<MerchantProfileResponse>.Failure(error); var email = NormalizeEmail(r.Email); var phone = NormalizePhone(r.PhoneNumber); if (await store.EmailExistsAsync(email, userId, inner)) return MerchantResult<MerchantProfileResponse>.Failure("Email is already registered."); if (await store.PhoneExistsAsync(phone, p.Value.Merchant.Id, inner)) return MerchantResult<MerchantProfileResponse>.Failure("Phone number is already registered."); var now = clock.UtcNow; var emailChanged = p.Value.User.NormalizedEmail != email; var phoneChanged = p.Value.Merchant.NormalizedPhoneNumber != phone; var m = p.Value.Merchant; m.LegalBusinessName = r.LegalBusinessName.Trim(); m.TradingName = r.TradingName.Trim(); m.BusinessType = r.BusinessType.Trim(); m.TaxRegistrationNumber = Clean(r.TaxRegistrationNumber); m.PhoneNumber = FormatPhone(phone); m.NormalizedPhoneNumber = phone; m.Email = r.Email.Trim(); m.BusinessAddress = r.BusinessAddress.Trim(); m.City = r.City.Trim(); m.Region = r.Region.Trim(); m.Country = r.Country.Trim(); m.TimeZone = r.TimeZone.Trim(); m.UpdatedAtUtc = now; m.UpdatedBy = userId.ToString(); p.Value.User.Email = r.Email.Trim(); p.Value.User.NormalizedEmail = email; p.Value.User.UpdatedAtUtc = now; p.Value.User.UpdatedBy = userId.ToString(); if (r.Logo is { } logo) { m.LogoFileName = logo.FileName.Trim(); m.LogoContentType = logo.ContentType; m.LogoSizeBytes = logo.SizeBytes; } AddDocuments(m.Id, userId, r.Documents, now); if (emailChanged) { p.Value.User.IsEmailVerified = false; await store.InvalidateTokensAsync(userId, "Email", now, inner); var issued = Issue(userId, "Email", now); store.Add(issued.Item); await verifier.SendEmailVerificationAsync(p.Value.User, issued.Raw, inner); } if (phoneChanged) { p.Value.User.IsPhoneVerified = false; await store.InvalidateTokensAsync(userId, "Phone", now, inner); var issued = Issue(userId, "Phone", now); store.Add(issued.Item); await verifier.SendPhoneVerificationAsync(m, issued.Raw, inner); } if (emailChanged || phoneChanged) { p.Value.User.Status = AccountStatus.PendingVerification; m.Status = MerchantStatus.PendingVerification; } Audit(m.Id, userId, "ProfileUpdate", $"EmailChanged={emailChanged};PhoneChanged={phoneChanged}", now); await store.SaveAsync(inner); var docs = await store.FindDocumentsAsync(m.Id, inner); return MerchantResult<MerchantProfileResponse>.Success(ToProfile(p.Value.User, m, docs)); }, ct);
    public async Task<IReadOnlyList<PendingMerchantResponse>> GetPendingAsync(CancellationToken ct) => (await store.FindByStatusAsync(MerchantStatus.PendingReview, ct)).Select(m => new PendingMerchantResponse(m.Id, m.PublicMerchantId, m.TradingName, m.Email, m.CreatedAtUtc)).ToArray();
    public async Task<MerchantResult<MerchantProfileResponse>> GetAsync(Guid id, CancellationToken ct) { var m = await store.FindMerchantAsync(id, ct); if (m is null) return MerchantResult<MerchantProfileResponse>.Failure("Merchant not found."); var u = await store.FindUserByMerchantAsync(id, ct); if (u is null) return MerchantResult<MerchantProfileResponse>.Failure("Merchant account not found."); return MerchantResult<MerchantProfileResponse>.Success(ToProfile(u, m, await store.FindDocumentsAsync(id, ct))); }
    public Task<MerchantResult> ApproveAsync(Guid id, Guid admin, CancellationToken ct) => Decide(id, admin, null, "Approval", MerchantStatus.PendingReview, AccountStatus.Active, (m, n, a) => m.Approve(n, a), ct); public Task<MerchantResult> RejectAsync(Guid id, Guid admin, string? reason, CancellationToken ct) => Decide(id, admin, reason, "Rejection", MerchantStatus.PendingReview, AccountStatus.Rejected, (m, n, a) => m.Reject(n, a.ToString()), ct, true); public Task<MerchantResult> RequestCorrectionAsync(Guid id, Guid admin, string? reason, CancellationToken ct) => Decide(id, admin, reason, "CorrectionRequested", MerchantStatus.PendingReview, AccountStatus.PendingApproval, (m, n, a) => { m.Status = MerchantStatus.CorrectionRequested; m.UpdatedAtUtc = n; m.UpdatedBy = a.ToString(); }, ct, true); public Task<MerchantResult> SuspendAsync(Guid id, Guid admin, string? reason, CancellationToken ct) => Decide(id, admin, reason, "Suspension", MerchantStatus.Active, AccountStatus.Suspended, (m, n, a) => m.Suspend(n, a.ToString()), ct, true); public Task<MerchantResult> ReactivateAsync(Guid id, Guid admin, string? reason, CancellationToken ct) => Decide(id, admin, reason, "Reactivation", MerchantStatus.Suspended, AccountStatus.Active, (m, n, a) => m.Reactivate(n, a.ToString()), ct);
    private Task<MerchantResult> Decide(Guid id, Guid admin, string? reason, string type, MerchantStatus required, AccountStatus target, Action<Merchant, DateTime, Guid> transition, CancellationToken ct, bool reasonRequired = false) => store.InTransactionAsync(async inner => { if (reasonRequired && string.IsNullOrWhiteSpace(reason)) return MerchantResult.Failure("A reason is required."); var m = await store.FindMerchantAsync(id, inner); if (m is null) return MerchantResult.Failure("Merchant not found."); if (m.Status != required) return MerchantResult.Failure($"Merchant must be {required} for this action."); var u = await store.FindUserByMerchantAsync(id, inner); if (u is null) return MerchantResult.Failure("Merchant account not found."); if (type == "Approval" && (!u.IsEmailVerified || !u.IsPhoneVerified)) return MerchantResult.Failure("Email and phone must be verified before approval."); var now = clock.UtcNow; transition(m, now, admin); u.Status = target; u.UpdatedAtUtc = now; u.UpdatedBy = admin.ToString(); Audit(id, admin, type, Clean(reason), now); await store.SaveAsync(inner); return MerchantResult.Success(); }, ct);
    private (MerchantVerificationToken Item, string Raw) Issue(Guid user, string purpose, DateTime now) { var raw = tokens.CreateOpaqueToken(); return (new MerchantVerificationToken { Id = Guid.NewGuid(), UserAccountId = user, Purpose = purpose, TokenHash = tokens.HashToken(raw), ExpiresAtUtc = now.AddMinutes(options.Value.TokenLifetimeMinutes), CreatedAtUtc = now }, raw); }
    private void Audit(Guid id, Guid? actor, string type, string? detail, DateTime now) => store.Add(new MerchantAuditEvent { Id = Guid.NewGuid(), MerchantId = id, ActorUserAccountId = actor, EventType = type, Detail = detail, CreatedAtUtc = now, CreatedBy = actor?.ToString() });
    private void AddDocuments(Guid id, Guid actor, IReadOnlyList<MerchantDocumentMetadata>? docs, DateTime now) { foreach (var d in docs ?? []) { var saved = storage.Register(d); store.Add(new MerchantDocument { Id = Guid.NewGuid(), MerchantId = id, DocumentType = d.DocumentType.Trim(), FileName = d.FileName.Trim(), ContentType = d.ContentType, SizeBytes = d.SizeBytes, StorageProvider = saved.Provider, StorageKey = saved.StorageKey, CreatedAtUtc = now, CreatedBy = actor.ToString() }); Audit(id, actor, "DocumentMetadataUpload", d.DocumentType.Trim(), now); } }
    private static string? Validate(string legal, string trading, string type, string phone, string email, string address, string city, string region, string country, string zone) { if (string.IsNullOrWhiteSpace(legal) || legal.Trim().Length is < 2 or > 250) return "Legal business name must be between 2 and 250 characters."; if (string.IsNullOrWhiteSpace(trading) || trading.Trim().Length is < 2 or > 250) return "Trading name must be between 2 and 250 characters."; if (string.IsNullOrWhiteSpace(type) || type.Trim().Length is < 2 or > 100) return "Business type is required."; if (string.IsNullOrWhiteSpace(email) || !new EmailAddressAttribute().IsValid(email.Trim()) || email.Trim().Length > 320) return "Email is invalid."; var digits = NormalizePhone(phone); if (digits.Length is < 8 or > 15) return "Phone number must contain 8 to 15 digits."; if (new[] { address, city, region, country, zone }.Any(string.IsNullOrWhiteSpace)) return "Business address, city, region, country, and time zone are required."; try { _ = TimeZoneInfo.FindSystemTimeZoneById(zone.Trim()); } catch (TimeZoneNotFoundException) { return "Time zone is invalid."; } catch (InvalidTimeZoneException) { return "Time zone is invalid."; } return null; }
    private static string? ValidateDocuments(IReadOnlyList<MerchantDocumentMetadata>? docs) { if (docs is null) return null; if (docs.Count > 10) return "No more than 10 document metadata records are allowed."; foreach (var d in docs) { if (d.DocumentType is not ("BusinessLicense" or "TaxDocument")) return "Document type must be BusinessLicense or TaxDocument."; var e = ValidateFile(new(d.FileName, d.ContentType, d.SizeBytes), false); if (e is not null) return e; } return null; }
    private static string? ValidateFile(MerchantFileMetadata? f, bool image) { if (f is null) return null; if (string.IsNullOrWhiteSpace(f.FileName) || f.FileName.Trim().Length > 255 || f.SizeBytes is <= 0 or > 10_000_000) return "File metadata is invalid."; var allowed = image ? new[] { "image/jpeg", "image/png", "image/webp" } : new[] { "application/pdf", "image/jpeg", "image/png" }; return allowed.Contains(f.ContentType) ? null : "File metadata is invalid."; }
    internal static string NormalizeEmail(string v) => v.Trim().ToUpperInvariant(); internal static string NormalizePhone(string v) => new(v.Where(char.IsDigit).ToArray()); private static string FormatPhone(string v) => $"+{v}"; private static string? Clean(string? v) => string.IsNullOrWhiteSpace(v) ? null : v.Trim();
    private static MerchantProfileResponse ToProfile(UserAccount u, Merchant m, IReadOnlyList<MerchantDocument> docs) { var progress = (u.IsEmailVerified ? 25 : 0) + (u.IsPhoneVerified ? 25 : 0) + (docs.Count > 0 ? 25 : 0) + (m.Status == MerchantStatus.Active ? 25 : 0); return new(m.Id, m.PublicMerchantId, m.LegalBusinessName, m.TradingName, m.BusinessType, m.TaxRegistrationNumber, m.PhoneNumber, u.Email, m.BusinessAddress, m.City, m.Region, m.Country, m.TimeZone, u.IsEmailVerified, u.IsPhoneVerified, u.Status, m.Status, m.LogoFileName is null ? null : new(m.LogoFileName, m.LogoContentType!, m.LogoSizeBytes!.Value), docs.Select(d => new MerchantDocumentMetadata(d.DocumentType, d.FileName, d.ContentType, d.SizeBytes)).ToArray(), progress, Next(u, m)); }
    private static string Next(UserAccount u, Merchant m) => !u.IsEmailVerified ? "Verify your email address." : !u.IsPhoneVerified ? "Verify your phone number." : m.Status == MerchantStatus.PendingReview ? "Your business is awaiting platform review." : m.Status == MerchantStatus.CorrectionRequested ? "Review the requested corrections and update your profile." : m.Status == MerchantStatus.Active ? "Your merchant account is active." : m.Status == MerchantStatus.Rejected ? "Your application was rejected. Contact Weymela support." : m.Status == MerchantStatus.Suspended ? "Your merchant account is suspended. Contact Weymela support." : "Complete your merchant profile and verification.";
}
