import {FormEvent,ReactNode,useEffect,useState} from 'react'
import {ReportingWorkspace} from './ReportingWorkspace'
import {clearAuthState} from './authSession'
type Row=Record<string,unknown>;type Page={items:Row[];page:number;total:number;totalPages:number};type Ops=Record<string,ReactNode>
const base=(import.meta.env.VITE_API_URL??'').replace(/\/$/,'');const token=()=>localStorage.getItem('creatorpay_access_token')??''
async function api<T>(path:string):Promise<T>{const r=await fetch(`${base}${path}`,{headers:{Authorization:`Bearer ${token()}`}});const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(r.status===401?'Authentication required.':r.status===403?'Platform Admin permission is required.':b.detail??b.error??`Request failed (${r.status}).`);return b}
const routes=[['dashboard','Dashboard'],['reports','Reports'],['support','Support'],['pilot-feedback','Pilot feedback'],['creators','Creators'],['merchants','Merchants'],['accounts','Accounts'],['partnerships','Partnerships'],['commission','Commission'],['deposits','Deposits'],['wallets','Wallets'],['purchases','Purchases'],['earnings','Earnings'],['payouts','Payouts'],['repeat-use','Repeat use'],['notifications','Notifications'],['fraud','Fraud'],['disputes','Disputes'],['reversals','Reversals'],['offline-sync','Offline sync'],['audit','Audit log'],['system','System']]
const endpoints:Record<string,string>={support:'support','pilot-feedback':'pilot-feedback',creators:'creators',merchants:'merchants',accounts:'accounts',partnerships:'partnerships',purchases:'purchases','offline-sync':'offline-sync',audit:'audit',system:'operational-alerts'}
function role(){try{const c=JSON.parse(atob(token().split('.')[1].replace(/-/g,'+').replace(/_/g,'/')));return c['http://schemas.microsoft.com/ws/2008/06/identity/claims/role']??c.role}catch{return''}}
export function AdminPortal({operations}:{operations:Ops}){if(role()!=='PlatformAdmin')return <main className="auth"><section className="panel"><h1>{role()?'Permission denied':'Authentication required'}</h1><p>This workspace requires the PlatformAdmin role.</p></section></main>;const part=location.pathname.split('/')[2]||'dashboard',page=routes.some(x=>x[0]===part)?part:'dashboard';return <div className="admin-shell"><a className="skip" href="#admin-content">Skip to content</a><aside className="admin-sidebar"><a className="admin-brand" href="/admin/dashboard">Weymela <small>Operations</small></a><nav aria-label="Admin navigation">{routes.map(([p,l])=><a key={p} aria-current={p===page?'page':undefined} href={`/admin/${p}`}>{l}</a>)}</nav></aside><div className="admin-main"><AdminHeader/><main id="admin-content" tabIndex={-1}>{page==='dashboard'?<Dashboard/>:page==='reports'?<ReportingWorkspace/>:page==='merchants'?<MerchantReview/>:endpoints[page]?<Table title={label(page)} endpoint={endpoints[page]}/>:<section><Title text={label(page)}/>{operations[page]??<Empty/>}</section>}</main></div></div>}

function MerchantReview(){const[items,setItems]=useState<Row[]>(),[selected,setSelected]=useState<Row>(),[reason,setReason]=useState(''),[message,setMessage]=useState('');const load=()=>api<Row[]>('/api/v1/admin/merchants/pending').then(setItems).catch(e=>setMessage(e.message));useEffect(()=>{void load()},[]);async function open(id:unknown){try{setSelected(await api<Row>(`/api/v1/admin/merchants/${id}`))}catch(e){setMessage((e as Error).message)}}async function decide(action:string){if(!selected)return;const needsReason=action!=='approve'&&action!=='reactivate';if(needsReason&&!reason.trim()){setMessage('A reason is required.');return}const r=await fetch(`${base}/api/v1/admin/merchants/${action}`,{method:'POST',headers:{Authorization:`Bearer ${token()}`,'Content-Type':'application/json'},body:JSON.stringify({merchantId:selected.merchantId,reason})});const b=await r.json().catch(()=>({}));setMessage(r.ok?'Decision saved and audited.':b.detail??'Decision failed.');if(r.ok){setSelected(undefined);setReason('');load()}}return <section><Title text="Merchant review"/>{message&&<aside role="status">{message}</aside>}{selected?<div className="panel"><button className="back" onClick={()=>setSelected(undefined)}>← Pending registrations</button><h2>{String(selected.tradingName)}</h2><dl>{Object.entries(selected).filter(([k])=>!['documents','logo'].includes(k)).map(([k,v])=><div key={k}><dt>{label(k)}</dt><dd>{String(v??'—')}</dd></div>)}</dl><label>Decision reason<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="actions"><button onClick={()=>decide('approve')}>Approve</button><button className="quiet" onClick={()=>decide('request-correction')}>Request correction</button><button className="danger" onClick={()=>decide('reject')}>Reject</button></div></div>:!items?<Loading/>:items.length===0?<Empty/>:<div className="cards">{items.map(x=><article key={String(x.merchantId)} onClick={()=>open(x.merchantId)}><span>PendingReview</span><strong>{String(x.tradingName)}</strong><p>{String(x.email)}<br/>{new Date(String(x.registeredAtUtc)).toLocaleString()}</p><button>Review</button></article>)}</div>}</section>}
function AdminHeader(){const[q,setQ]=useState('');function go(e:FormEvent){e.preventDefault();location.href=`/admin/purchases?q=${encodeURIComponent(q)}`}function logout(){clearAuthState();location.assign('/')}return <header className="admin-header"><form role="search" onSubmit={go}><input aria-label="Support search" minLength={3} value={q} onChange={e=>setQ(e.target.value)} placeholder="Public ID or correlation ID"/><button>Search</button></form><span>Platform Admin</span><button className="quiet" onClick={logout}>Sign out</button></header>}
function Title({text,children}:{text:string;children?:ReactNode}){return <div className="admin-title"><div><p className="eyebrow">Platform operations</p><h1>{text}</h1></div>{children}</div>}
function Dashboard(){const[data,setData]=useState<Row>(),[error,setError]=useState(''),[days,setDays]=useState('0');useEffect(()=>{const to=new Date(),from=new Date();days==='0'?from.setHours(0,0,0,0):from.setDate(to.getDate()-Number(days));api<Row>(`/api/v1/admin/dashboard/summary?from=${from.toISOString()}&to=${to.toISOString()}`).then(setData).catch(e=>setError(e.message))},[days]);return <section><Title text="Operational dashboard"><label>Time period <select value={days} onChange={e=>setDays(e.target.value)}><option value="0">Today</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option></select></label></Title>{error?<ErrorBox text={error}/>:!data?<Loading/>:<div className="summary-grid">{Object.entries(data).filter(([k,v])=>k!=='range'&&typeof v!=='object').map(([k,v])=><article className="summary-card" key={k}><span>{label(k)}</span><strong>{String(v)}</strong></article>)}</div>}</section>}
function Table({title,endpoint}:{title:string;endpoint:string}){const[data,setData]=useState<Page>(),[error,setError]=useState(''),[page,setPage]=useState(1),[input,setInput]=useState(''),[query,setQuery]=useState('');useEffect(()=>{api<Page>(`/api/v1/admin/${endpoint}?page=${page}&pageSize=25${query?`&q=${encodeURIComponent(query)}`:''}`).then(setData).catch(e=>setError(e.message))},[endpoint,page,query]);function filter(e:FormEvent){e.preventDefault();setPage(1);setQuery(input)}const cols=data?.items[0]?Object.keys(data.items[0]).filter(x=>x!=='id').slice(0,7):[];return <section><Title text={title}><form className="filter" onSubmit={filter}><input aria-label="Filter results" value={input} onChange={e=>setInput(e.target.value)} placeholder="Filter"/><button>Apply</button></form></Title>{error?<ErrorBox text={error}/>:!data?<Loading/>:!data.items.length?<Empty/>:<><div className="table-wrap"><table><thead><tr>{cols.map(c=><th scope="col" key={c}>{label(c)}</th>)}</tr></thead><tbody>{data.items.map((row,i)=><tr key={String(row.id??i)}>{cols.map(c=><td key={c} data-label={label(c)}>{cell(c,row[c])}</td>)}</tr>)}</tbody></table></div><nav className="pagination" aria-label="Pagination"><button disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page} of {Math.max(1,data.totalPages)} · {data.total} records</span><button disabled={page>=data.totalPages} onClick={()=>setPage(page+1)}>Next</button></nav></>}</section>}
function cell(k:string,v:unknown){if(v==null)return'—';if(k.toLowerCase().includes('status'))return <span className="status">{String(v)}</span>;if(k.toLowerCase().includes('correlation'))return <code>{String(v)}</code>;if(typeof v==='boolean')return v?'Yes':'No';if(typeof v==='string'&&k.endsWith('Utc'))return new Date(v).toLocaleString();return String(v)}
function Loading(){return <p aria-live="polite">Loading…</p>}function Empty(){return <div className="empty-state"><h2>Nothing here yet</h2><p>No records match the current filters.</p></div>}function ErrorBox({text}:{text:string}){return <div className="error-panel" role="alert"><h2>Unable to load</h2><p>{text}</p></div>}function label(x:string){return x.replace(/-/g,' ').replace(/([a-z])([A-Z])/g,'$1 $2').replace(/^./,c=>c.toUpperCase())}
