import {FormEvent,useState} from 'react'
import {brand,Locale} from './brand'
const base=(import.meta.env.VITE_API_URL??'').replace(/\/$/,'')
type Mode='login'|'customer'|'creator'|'merchant'; type Tokens={accessToken:string;refreshToken:string;user:{role:string}}
export function AuthWorkspace(){
 const[locale,setLocale]=useState<Locale>((localStorage.getItem('weymela_locale') as Locale)||'en'),[mode,setMode]=useState<Mode>('login'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[show,setShow]=useState(false)
 const[login,setLogin]=useState({email:'',password:''}),[customer,setCustomer]=useState({displayName:'',email:'',phoneNumber:'',password:'',confirmation:''})
 const[creator,setCreator]=useState({firstName:'',lastName:'',displayName:'',phoneNumber:'',email:'',password:'',preferredLanguage:locale,city:'Addis Ababa',zone:'',biography:'',contentCategories:'',platform:'TikTok',handle:'',profileUrl:'',followerCount:0,preferredPayoutChannel:'',preferredPayoutAccountIdentifier:'',termsAccepted:false})
 const[merchant,setMerchant]=useState({legalBusinessName:'',tradingName:'',businessType:'',primaryContactName:'',phoneNumber:'',email:'',password:'',businessAddress:'',city:'Addis Ababa',region:'',country:'Ethiopia',timeZone:'Africa/Addis_Ababa',taxRegistrationNumber:'',businessRegistrationNumber:'',preferredLanguage:locale,termsAccepted:false})
 async function post(path:string,body:unknown){setBusy(true);setMessage('');try{const r=await fetch(`${base}${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),v=await r.json().catch(()=>({}));if(!r.ok){setMessage(v.detail??'Registration failed.');return false}return true}finally{setBusy(false)}}
 async function signIn(e:FormEvent){e.preventDefault();setBusy(true);try{const r=await fetch(`${base}/api/v1/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(login)}),v=await r.json().catch(()=>({}));if(!r.ok){setMessage(v.detail??'Invalid email or password.');return}const x=v as Tokens;localStorage.setItem('creatorpay_access_token',x.accessToken);localStorage.setItem('creatorpay_refresh_token',x.refreshToken);location.assign(x.user.role==='PlatformAdmin'?'/admin':'/')}finally{setBusy(false)}}
 async function registerCreator(e:FormEvent){e.preventDefault();const{platform,handle,profileUrl,followerCount,...p}=creator;if(await post('/api/v1/creators/register',{...p,socialProfiles:[{platform,handle,profileUrl:profileUrl||null,followerCount,isPrimary:true}]}))setMessage('Registration received. Verify email and phone; your profile will then be PendingReview.')}
 const field=(state:Record<string,unknown>,set:(x:any)=>void,key:string,label:string,type='text',required=true)=><label>{label}<input type={type} required={required} value={String(state[key]??'')} onChange={e=>set({...state,[key]:type==='number'?Number(e.target.value):e.target.value})}/></label>
 const tabs:{id:Mode;label:string}[]=[{id:'login',label:'Sign In'},{id:'customer',label:'Customer Registration'},{id:'creator',label:'Creator Registration'},{id:'merchant',label:'Merchant Registration'}]
 return <main className="auth"><section className="auth-card" aria-busy={busy}><div className="auth-top"><p className="eyebrow">{brand.logoText}</p><label>Language / ቋንቋ<select value={locale} onChange={e=>{const v=e.target.value as Locale;setLocale(v);localStorage.setItem('weymela_locale',v)}}><option value="en">English</option><option value="am">አማርኛ</option></select></label></div><h1>Welcome to Weymela</h1>{mode==='login'&&<h2>Welcome back</h2>}<p>{brand.tagline}</p><div className="segmented" role="tablist">{tabs.map(x=><button type="button" role="tab" aria-selected={mode===x.id} className={mode===x.id?'active':'quiet'} onClick={()=>setMode(x.id)} key={x.id}>{x.label}</button>)}</div>
 {mode==='login'?<form className="form" onSubmit={signIn}>{field(login,setLogin,'email','Email','email')}<label>Password<span className="password-field"><input type={show?'text':'password'} required value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/><button type="button" className="quiet" onClick={()=>setShow(!show)}>{show?'Hide':'Show'}</button></span></label><button disabled={busy}>{busy?'Please wait…':'Sign In'}</button></form>
 :mode==='customer'?<form className="form" onSubmit={async e=>{e.preventDefault();if(await post('/api/v1/customers/register',customer))setMessage('Account created. Sign in to continue verification.')}}>{field(customer,setCustomer,'displayName','Display name')}{field(customer,setCustomer,'phoneNumber','Phone','tel')}{field(customer,setCustomer,'email','Email','email')}{field(customer,setCustomer,'password','Password','password')}<button disabled={busy}>Create customer account</button></form>
 :mode==='creator'?<form className="form" onSubmit={registerCreator}><p className="eyebrow full">Creator profile · required fields</p>{field(creator,setCreator,'firstName','Legal first name')}{field(creator,setCreator,'lastName','Legal last name')}{field(creator,setCreator,'displayName','Public display name')}{field(creator,setCreator,'phoneNumber','Phone','tel')}{field(creator,setCreator,'email','Email','email')}{field(creator,setCreator,'password','Password','password')} {field(creator,setCreator,'city','Primary city')}{field(creator,setCreator,'zone','Zone or neighborhood', 'text',false)}<label className="full">Short biography<textarea required value={creator.biography} onChange={e=>setCreator({...creator,biography:e.target.value})}/></label>{field(creator,setCreator,'contentCategories','Content categories') }<label>Primary social platform<select value={creator.platform} onChange={e=>setCreator({...creator,platform:e.target.value})}>{['TikTok','Instagram','Facebook','Telegram','YouTube','Other'].map(x=><option key={x}>{x}</option>)}</select></label>{field(creator,setCreator,'handle','Social handle')}{field(creator,setCreator,'profileUrl','Social profile URL','url',false)}{field(creator,setCreator,'followerCount','Estimated follower count','number')}{field(creator,setCreator,'preferredPayoutChannel','Manual payout channel','text',false)}{field(creator,setCreator,'preferredPayoutAccountIdentifier','Payout account identifier','text',false)}<label className="check full"><input type="checkbox" required checked={creator.termsAccepted} onChange={e=>setCreator({...creator,termsAccepted:e.target.checked})}/>I accept the pilot terms and privacy notice</label><button disabled={busy}>Submit for review</button></form>
 :<form className="form" onSubmit={async e=>{e.preventDefault();if(await post('/api/v1/merchants/register',{...merchant,documents:[]}))setMessage('Registration received. Verify email and phone, then follow PendingReview status.')}}>{['legalBusinessName','tradingName','businessType','primaryContactName','phoneNumber','email','businessAddress','city','region'].map(k=>field(merchant,setMerchant,k,k.replace(/([A-Z])/g,' $1')))}{field(merchant,setMerchant,'password','Password','password')}<label className="check full"><input type="checkbox" required checked={merchant.termsAccepted} onChange={e=>setMerchant({...merchant,termsAccepted:e.target.checked})}/>I accept the pilot terms and privacy notice</label><button disabled={busy}>Submit for review</button></form>}
 {message&&<aside role="status">{message}</aside>}<small>Public registration is available for customers, creators, and merchants. Platform Admin accounts are provisioned privately. Support: {brand.supportEmail}</small></section></main>
}
