import {FormEvent,useState} from 'react'
import {brand,Locale} from './brand'
const base=(import.meta.env.VITE_API_URL??'').replace(/\/$/,'')
type Tokens={accessToken:string;refreshToken:string;user:{role:string}}
const text={en:{welcome:'Welcome back',signIn:'Sign in',customer:'Customer registration',merchant:'Merchant registration',invalid:'Invalid email or password.',wait:'Please wait...',terms:'I accept the pilot terms and privacy notice'},am:{welcome:'እንኳን ደህና መጡ',signIn:'ይግቡ',customer:'የደንበኛ ምዝገባ',merchant:'የነጋዴ ምዝገባ',invalid:'ኢሜይሉ ወይም የይለፍ ቃሉ ትክክል አይደለም።',wait:'እባክዎ ይጠብቁ...',terms:'I accept the pilot terms and privacy notice'}}
export function AuthWorkspace(){
 const[locale,setLocale]=useState<Locale>((localStorage.getItem('weymela_locale') as Locale)||'en'),[mode,setMode]=useState<'login'|'customer'|'merchant'>('login'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[show,setShow]=useState(false);const c=text[locale]
 const[login,setLogin]=useState({email:'',password:''}),[customer,setCustomer]=useState({displayName:'',email:'',phoneNumber:'',password:'',confirmation:''}),[merchant,setMerchant]=useState({legalBusinessName:'',tradingName:'',businessType:'',primaryContactName:'',phoneNumber:'',email:'',password:'',businessAddress:'',city:'Addis Ababa',region:'',country:'Ethiopia',timeZone:'Africa/Addis_Ababa',taxRegistrationNumber:'',businessRegistrationNumber:'',preferredLanguage:locale,termsAccepted:false})
 async function post(path:string,body:unknown){setBusy(true);setMessage('');try{const r=await fetch(`${base}${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const value=await r.json().catch(()=>({}));if(!r.ok){setMessage(value.detail??'Registration failed.');return false}return true}finally{setBusy(false)}}
 async function signIn(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const r=await fetch(`${base}/api/v1/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(login)});const body=await r.json().catch(()=>({}));if(!r.ok){setMessage(r.status===401?c.invalid:body.detail??c.invalid);return}const x=body as Tokens;localStorage.setItem('creatorpay_access_token',x.accessToken);localStorage.setItem('creatorpay_refresh_token',x.refreshToken);location.assign(x.user.role==='PlatformAdmin'?'/admin':'/')}finally{setBusy(false)}}
 async function registerCustomer(e:FormEvent){e.preventDefault();if(await post('/api/v1/customers/register',customer)){setLogin({email:customer.email,password:customer.password});setMode('login');setMessage('Account created. Sign in to continue verification.')}}
 async function registerMerchant(e:FormEvent){e.preventDefault();if(await post('/api/v1/merchants/register',{...merchant,documents:[]}))setMessage('Registration received. Verify your email and phone, then follow your PendingReview status.')}
 function mf(key:keyof typeof merchant,label:string,type='text',required=true){return <label>{label}<input type={type} required={required} value={String(merchant[key])} onChange={e=>setMerchant({...merchant,[key]:e.target.value})}/></label>}
 return <main className="auth"><section className="auth-card" aria-busy={busy}><div className="auth-top"><p className="eyebrow">{brand.logoText}</p><label>Language / ቋንቋ<select value={locale} onChange={e=>{const v=e.target.value as Locale;setLocale(v);localStorage.setItem('weymela_locale',v)}}><option value="en">English</option><option value="am">አማርኛ</option></select></label></div><h1>{mode==='login'?c.welcome:brand.productName}</h1><p>{brand.tagline}</p><div className="segmented" role="tablist">{(['login','customer','merchant'] as const).map(x=><button type="button" role="tab" aria-selected={mode===x} className={mode===x?'active':'quiet'} onClick={()=>setMode(x)} key={x}>{x==='login'?c.signIn:x==='customer'?c.customer:c.merchant}</button>)}</div>
 {mode==='login'?<form className="form" onSubmit={signIn}><label>Email<input autoComplete="email" type="email" required value={login.email} onChange={e=>setLogin({...login,email:e.target.value})}/></label><label>Password<span className="password-field"><input autoComplete="current-password" type={show?'text':'password'} required value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/><button type="button" className="quiet" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?'Hide':'Show'}</button></span></label><button disabled={busy}>{busy?c.wait:c.signIn}</button></form>:mode==='customer'?<form className="form" onSubmit={registerCustomer}>{(['displayName','phoneNumber','email'] as const).map(k=><label key={k}>{k.replace(/([A-Z])/g,' $1')}<input type={k==='email'?'email':k==='phoneNumber'?'tel':'text'} required value={customer[k]} onChange={e=>setCustomer({...customer,[k]:e.target.value})}/></label>)}<label>Password<input type="password" minLength={12} required value={customer.password} onChange={e=>setCustomer({...customer,password:e.target.value})}/></label><label>Confirm password<input type="password" minLength={12} required value={customer.confirmation} onChange={e=>setCustomer({...customer,confirmation:e.target.value})}/></label><button disabled={busy}>{busy?c.wait:'Create account'}</button></form>:<form className="form" onSubmit={registerMerchant}>{mf('legalBusinessName','Legal business name')}{mf('tradingName','Public display name')}{mf('businessType','Business type')}{mf('primaryContactName','Primary contact name')}{mf('phoneNumber','Phone number','tel')}{mf('email','Email','email')}{mf('region','Zone or neighborhood')}{mf('city','City')}{mf('businessAddress','Address description')}{mf('taxRegistrationNumber','Tax identification number (optional)','text',false)}{mf('businessRegistrationNumber','Business registration number (optional)','text',false)}{mf('password','Password','password')}<label>Preferred language<select value={merchant.preferredLanguage} onChange={e=>setMerchant({...merchant,preferredLanguage:e.target.value as Locale})}><option value="en">English</option><option value="am">አማርኛ</option></select></label><label className="check full"><input type="checkbox" required checked={merchant.termsAccepted} onChange={e=>setMerchant({...merchant,termsAccepted:e.target.checked})}/>{c.terms}</label><button disabled={busy}>{busy?c.wait:'Submit for review'}</button></form>}{message&&<aside role="status">{message}</aside>}<small>Support: {brand.supportEmail}</small></section></main>
}
