import {FormEvent,useState} from 'react'
import {brand,Locale} from './brand'
import {workspaceRoute} from './authSession'
const base=(import.meta.env.VITE_API_URL??'').replace(/\/$/,'')
type Mode='login'|'customer'|'creator'|'merchant';type Tokens={accessToken:string;refreshToken:string;user:{role:string}}
export const businessTypes=[
 {value:'Restaurant / Café',en:'Restaurant / Café',am:'ምግብ ቤት / ካፌ'},
 {value:'Grocery / Mini-market',en:'Grocery / Mini-market',am:'ግሮሰሪ / ሚኒ ማርኬት'},
 {value:'Clothing / Boutique',en:'Clothing / Boutique',am:'ልብስ / ቡቲክ'},
 {value:'Beauty / Salon',en:'Beauty / Salon',am:'ውበት / ሳሎን'},
 {value:'Furniture',en:'Furniture',am:'የቤት ዕቃ'},
 {value:'Electronics',en:'Electronics',am:'ኤሌክትሮኒክስ'},
 {value:'Hotel / Travel',en:'Hotel / Travel',am:'ሆቴል / ጉዞ'},
 {value:'Professional Services',en:'Professional Services',am:'ሙያዊ አገልግሎቶች'},
 {value:'Other',en:'Other',am:'ሌላ'}
] as const
const en={welcome:'Welcome to Weymela',signIn:'Sign In',customer:'Shopper Registration',creator:'Content Creator Registration',merchant:'Business Owner Registration',display:'Display Name',phone:'Phone',email:'Email',password:'Password',confirm:'Confirm Password',mismatch:'Passwords do not match.',createCustomer:'Create shopper account',createCreator:'Create content creator account',createMerchant:'Create business owner account',language:'Language',show:'Show',hide:'Hide',wait:'Please wait…',failed:'Registration failed. Please try again.',invalid:'Invalid email or password.',customerSuccess:'Shopper account created. Sign in to continue verification.',creatorSuccess:'Content Creator registration received. Verify email and phone; your profile will then be PendingReview.',merchantSuccess:'Business Owner registration received. Verify email and phone, then follow PendingReview status.',first:'Legal First Name',last:"Father's Name",publicName:'Public Display Name',city:'Primary City',social:'Primary Social Platform',url:'Social Profile URL',followers:'Estimated Follower Count',terms:'I accept the pilot terms and privacy notice',notice:'Public registration is available for Shoppers, Content Creators, and Business Owners. Platform Admin accounts are provisioned privately.',support:'Support',legalBusinessName:'Legal Business Name',tradingName:'Trading Name',businessType:'Business Type',primaryContactName:'Primary Contact Name',businessAddress:'Business Address'}
const am:typeof en={welcome:'ወደ ወይሜላ እንኳን ደህና መጡ',signIn:'ይግቡ',customer:'የገበያተኛ ምዝገባ',creator:'የይዘት ፈጣሪ ምዝገባ',merchant:'የንግድ ባለቤት ምዝገባ',display:'የሚታይ ስም',phone:'ስልክ',email:'ኢሜይል',password:'የይለፍ ቃል',confirm:'የይለፍ ቃል ያረጋግጡ',mismatch:'የይለፍ ቃሎቹ አይዛመዱም።',createCustomer:'የገበያተኛ መለያ ይፍጠሩ',createCreator:'የይዘት ፈጣሪ መለያ ይፍጠሩ',createMerchant:'የንግድ ባለቤት መለያ ይፍጠሩ',language:'ቋንቋ',show:'አሳይ',hide:'ደብቅ',wait:'እባክዎ ይጠብቁ…',failed:'ምዝገባው አልተሳካም። እባክዎ እንደገና ይሞክሩ።',invalid:'ኢሜይሉ ወይም የይለፍ ቃሉ ትክክል አይደለም።',customerSuccess:'የገበያተኛ መለያው ተፈጥሯል። ማረጋገጥን ለመቀጠል ይግቡ።',creatorSuccess:'የይዘት ፈጣሪ ምዝገባዎ ደርሷል። ኢሜይልና ስልክዎን ያረጋግጡ።',merchantSuccess:'የንግድ ባለቤት ምዝገባዎ ደርሷል። ኢሜይልና ስልክዎን ያረጋግጡ።',first:'ሕጋዊ ስም',last:'የአባት ስም',publicName:'የሕዝብ ማሳያ ስም',city:'ዋና ከተማ',social:'ዋና ማህበራዊ መድረክ',url:'የማህበራዊ መገለጫ አገናኝ',followers:'የተገመተ ተከታይ ብዛት',terms:'የሙከራ ውሎችንና የግላዊነት ማስታወቂያውን እቀበላለሁ',notice:'የሕዝብ ምዝገባ ለገበያተኞች፣ የይዘት ፈጣሪዎችና የንግድ ባለቤቶች ይገኛል። የፕላትፎርም አስተዳዳሪ መለያዎች በግል ይዘጋጃሉ።',support:'ድጋፍ',legalBusinessName:'ሕጋዊ የንግድ ስም',tradingName:'የንግድ መጠሪያ',businessType:'የንግድ ዓይነት',primaryContactName:'የዋና አድራሻ ሰው ስም',businessAddress:'የንግድ አድራሻ'}
export const authText=(locale:Locale)=>locale==='am'?am:en
const passwordText={en:{requirements:'Password requirements:',length:'At least 8 characters',upper:'One uppercase letter',lower:'One lowercase letter',number:'One number',special:'One special character',match:'Passwords match',mismatch:'Passwords do not match'},am:{requirements:'የይለፍ ቃል መስፈርቶች፦',length:'ቢያንስ 8 ቁምፊዎች',upper:'አንድ የእንግሊዝኛ አቢይ ፊደል',lower:'አንድ የእንግሊዝኛ ትንሽ ፊደል',number:'አንድ ቁጥር',special:'አንድ ልዩ ምልክት',match:'የይለፍ ቃሎቹ ይዛመዳሉ',mismatch:'የይለፍ ቃሎቹ አይዛመዱም'}}
export const publicPasswordRules=[(value:string)=>value.length>=8,(value:string)=>/[A-Z]/.test(value),(value:string)=>/[a-z]/.test(value),(value:string)=>/\d/.test(value),(value:string)=>/[^A-Za-z0-9]/.test(value)]
export const ethiopianPhoneMessage='Enter a valid Ethiopian mobile number, for example 0911234567, 0712345678, or +251911234567.'
export const amharicPhoneMessage='ትክክለኛ የኢትዮጵያ ሞባይል ቁጥር ያስገቡ፣ ለምሳሌ 0911234567፣ 0712345678 ወይም +251911234567።'
export function normalizeEthiopianPhone(value:string){const compact=value.replace(/[\s-]/g,'');if(/^0[79]\d{8}$/.test(compact))return `+251${compact.slice(1)}`;if(/^\+251[79]\d{8}$/.test(compact))return compact;return null}
const amharicErrors:Record<string,string>={'Email is already registered.':'ይህ ኢሜይል አስቀድሞ ተመዝግቧል።','Phone number is already registered.':'ይህ ስልክ ቁጥር አስቀድሞ ተመዝግቧል።','Email is invalid.':'የኢሜይል ቅርጸት ትክክል አይደለም።',[ethiopianPhoneMessage]:amharicPhoneMessage,'Terms acceptance is required.':'ውሎቹን መቀበል ያስፈልጋል።'}
const freshLogin=()=>({email:'',password:''}),freshCustomer=()=>({displayName:'',email:'',phoneNumber:'',password:'',confirmation:''}),freshCreator=(locale:Locale)=>({firstName:'',lastName:'',displayName:'',phoneNumber:'',email:'',password:'',confirmation:'',preferredLanguage:locale,city:'Addis Ababa',platform:'TikTok',profileUrl:'',followerCount:0,termsAccepted:false}),freshMerchant=(locale:Locale)=>({legalBusinessName:'',tradingName:'',businessType:'',primaryContactName:'',phoneNumber:'',email:'',password:'',confirmation:'',businessAddress:'',city:'Addis Ababa',region:'Not provided',country:'Ethiopia',timeZone:'Africa/Addis_Ababa',taxRegistrationNumber:null,businessRegistrationNumber:null,preferredLanguage:locale,termsAccepted:false})
export function AuthWorkspace(){
 const[locale,setLocale]=useState<Locale>((localStorage.getItem('weymela_locale') as Locale)||'en'),[mode,setModeState]=useState<Mode>('login'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[show,setShow]=useState(false);const t=authText(locale)
 const[login,setLogin]=useState(freshLogin),[customer,setCustomer]=useState(freshCustomer),[creator,setCreator]=useState(()=>freshCreator(locale)),[merchant,setMerchant]=useState(()=>freshMerchant(locale))
 function setMode(next:Mode){setLogin(freshLogin());setCustomer(freshCustomer());setCreator(freshCreator(locale));setMerchant(freshMerchant(locale));setMessage('');setShow(false);setModeState(next)}
 async function post(path:string,body:unknown){setBusy(true);setMessage('');try{const r=await fetch(`${base}${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),v=await r.json().catch(()=>({}));if(!r.ok){const safeDetail=typeof v.detail==='string'&&v.detail.length<=500?v.detail:null;if(r.status<500){const detail=locale==='am'&&safeDetail?(amharicErrors[safeDetail]??safeDetail):safeDetail;setMessage(detail??t.failed)}else{const correlation=r.headers.get('x-correlation-id')||(typeof v.correlationId==='string'?v.correlationId:null);setMessage(`${t.failed}${correlation?` (${t.support}: ${correlation})`:''}`)}return false}return true}catch{setMessage(t.failed);return false}finally{setBusy(false)}}
 function validPhone(value:string){const normalized=normalizeEthiopianPhone(value);if(normalized)return normalized;setMessage(locale==='am'?amharicPhoneMessage:ethiopianPhoneMessage);return null}
 function matches(password:string,confirmation:string){if(!publicPasswordRules.every(rule=>rule(password))){setMessage(passwordText[locale].requirements);return false}if(password===confirmation)return true;setMessage(t.mismatch);return false}
 async function signIn(e:FormEvent){e.preventDefault();setBusy(true);try{const r=await fetch(`${base}/api/v1/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(login)}),v=await r.json().catch(()=>({}));if(!r.ok){setMessage(v.detail??t.invalid);return}const x=v as Tokens;localStorage.setItem('creatorpay_access_token',x.accessToken);localStorage.setItem('creatorpay_refresh_token',x.refreshToken);location.assign(workspaceRoute(x.user.role))}finally{setBusy(false)}}
 const field=(state:Record<string,unknown>,set:(x:any)=>void,key:string,label:string,type='text')=><label>{label}<input type={type} required value={String(state[key]??'')} onChange={e=>set({...state,[key]:type==='number'?Number(e.target.value):e.target.value})}/></label>
 const passwordFields=(state:{password:string;confirmation:string},set:(x:any)=>void)=>{const copy=passwordText[locale],results=publicPasswordRules.map(rule=>rule(state.password)),labels=[copy.length,copy.upper,copy.lower,copy.number,copy.special],hasConfirmation=state.confirmation.length>0,matchesPassword=state.password===state.confirmation;return <><label>{t.password}<input type={show?'text':'password'} required minLength={8} maxLength={128} value={state.password} onChange={e=>set({...state,password:e.target.value})}/></label><div className="password-requirements" role="status" aria-live="polite"><strong>{copy.requirements}</strong><ul>{labels.map((label,index)=><li key={label}><span aria-hidden="true">{results[index]?'✓':'○'}</span> {label}<span className="sr-only"> — {results[index]?'met':'not met'}</span></li>)}</ul></div><label>{t.confirm}<input type={show?'text':'password'} required minLength={8} maxLength={128} value={state.confirmation} onChange={e=>set({...state,confirmation:e.target.value})}/></label>{hasConfirmation&&<p role="status" aria-live="polite">{matchesPassword?`✓ ${copy.match}`:`○ ${copy.mismatch}`}</p>}<button type="button" className="quiet" onClick={()=>setShow(!show)}>{show?t.hide:t.show}</button></>}
 const tabs:[Mode,string][]=[['login',t.signIn],['customer',t.customer],['creator',t.creator],['merchant',t.merchant]]
 return <main className="auth"><section className="auth-card" aria-busy={busy}><div className="auth-top"><p className="eyebrow">{brand.logoText}</p><label>{locale==='am'?'ቋንቋ / Language':'Language / ቋንቋ'}<select aria-label="Language / ቋንቋ" value={locale} onChange={e=>{const v=e.target.value as Locale;setLocale(v);localStorage.setItem('weymela_locale',v)}}><option value="en">English</option><option value="am">አማርኛ</option></select></label></div><h1>{t.welcome}</h1><p>{brand.tagline}</p><div className="segmented" role="tablist">{tabs.map(([id,label])=><button type="button" role="tab" aria-selected={mode===id} className={mode===id?'active':'quiet'} onClick={()=>setMode(id)} key={id}>{label}</button>)}</div>
 {mode==='login'?<form className="form" onSubmit={signIn}>{field(login,setLogin,'email',t.email,'email')}<label>{t.password}<span className="password-field"><input type={show?'text':'password'} required value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/><button type="button" className="quiet" onClick={()=>setShow(!show)}>{show?t.hide:t.show}</button></span></label><button disabled={busy}>{busy?t.wait:t.signIn}</button></form>
 :mode==='customer'?<form className="form" onSubmit={async e=>{e.preventDefault();const phone=validPhone(customer.phoneNumber);if(phone&&matches(customer.password,customer.confirmation)&&await post('/api/v1/customers/register',{displayName:customer.displayName,email:customer.email,phoneNumber:phone,password:customer.password,confirmation:customer.confirmation}))setMessage(t.customerSuccess)}}>{field(customer,setCustomer,'displayName',t.display)}{field(customer,setCustomer,'phoneNumber',t.phone,'tel')}{field(customer,setCustomer,'email',t.email,'email')}{passwordFields(customer,setCustomer)}<button disabled={busy}>{t.createCustomer}</button></form>
 :mode==='creator'?<form className="form" onSubmit={async e=>{e.preventDefault();const phone=validPhone(creator.phoneNumber);if(!phone||!matches(creator.password,creator.confirmation))return;const{confirmation,platform,profileUrl,followerCount,...profile}=creator;if(await post('/api/v1/creators/register',{...profile,phoneNumber:phone,biography:'',contentCategories:'',socialProfiles:[{platform,handle:'',profileUrl,followerCount,isPrimary:true}]}))setMessage(t.creatorSuccess)}}>{field(creator,setCreator,'firstName',t.first)}{field(creator,setCreator,'lastName',t.last)}{field(creator,setCreator,'displayName',t.publicName)}{field(creator,setCreator,'phoneNumber',t.phone,'tel')}{field(creator,setCreator,'email',t.email,'email')}{passwordFields(creator,setCreator)}{field(creator,setCreator,'city',t.city)}<label>{t.social}<select value={creator.platform} onChange={e=>setCreator({...creator,platform:e.target.value})}>{['TikTok','Instagram','Facebook','Telegram','YouTube','Other'].map(x=><option key={x}>{x}</option>)}</select></label>{field(creator,setCreator,'profileUrl',t.url,'url')}{field(creator,setCreator,'followerCount',t.followers,'number')}<label className="check full"><input type="checkbox" required checked={creator.termsAccepted} onChange={e=>setCreator({...creator,termsAccepted:e.target.checked})}/>{t.terms}</label><button disabled={busy}>{t.createCreator}</button></form>
 :<form className="form" onSubmit={async e=>{e.preventDefault();const phone=validPhone(merchant.phoneNumber);if(!phone||!matches(merchant.password,merchant.confirmation))return;const{confirmation,...request}=merchant;if(await post('/api/v1/merchants/register',{...request,phoneNumber:phone,documents:[]}))setMessage(t.merchantSuccess)}}>{field(merchant,setMerchant,'legalBusinessName',t.legalBusinessName)}{field(merchant,setMerchant,'tradingName',t.tradingName)}<label>{t.businessType}<select required value={merchant.businessType} onChange={e=>setMerchant({...merchant,businessType:e.target.value})}><option value="" disabled>{locale==='am'?'የንግድ ዓይነት ይምረጡ':'Select a business type'}</option>{businessTypes.map(x=><option key={x.value} value={x.value}>{x[locale]}</option>)}</select></label>{field(merchant,setMerchant,'primaryContactName',t.primaryContactName)}{field(merchant,setMerchant,'phoneNumber',t.phone,'tel')}{field(merchant,setMerchant,'email',t.email,'email')}{field(merchant,setMerchant,'businessAddress',t.businessAddress)}{field(merchant,setMerchant,'city',t.city)}{passwordFields(merchant,setMerchant)}<label className="check full"><input type="checkbox" required checked={merchant.termsAccepted} onChange={e=>setMerchant({...merchant,termsAccepted:e.target.checked})}/>{t.terms}</label><button disabled={busy}>{t.createMerchant}</button></form>}
 {message&&<aside role="status">{message}</aside>}<small>{t.notice} {t.support}: {brand.supportEmail}</small><nav className="auth-links" aria-label="Public information"><a href="/help">Help Center</a><a href="/contact">Contact Support</a><a href="/terms">Terms</a><a href="/privacy">Privacy</a></nav></section></main>
}
