import {ReactNode,useEffect,useState} from 'react'
import {api} from './apiClient'
import {ActiveCreators,AdvertisingRequests,BusinessRelationship,FindCreators} from './BusinessAdvertising'
import {relationshipState} from './relationshipTime'
import {ConfirmedSalesWorkspace} from './ConfirmedSalesWorkspace'
import {AccountChrome} from './AccountChrome'
import {onActionableRefresh} from './actionableRefresh'
import {NavIcon} from './navIcons'
import './low-balance.css'

type Tab='home'|'find'|'active'|'requests'|'cashiers'|'confirmed-sales'|'checkout'|'wallet'|'profile'
type Metrics={confirmedSales:number;period:string}
type Profile={tradingName:string;merchantStatus:string;effectiveStatus:string;effectiveStatusReason:string}
type WalletSummary={availableBalance:number;currencyCode:string;status:string;minimumRequiredBalance?:number;advertisingEligible?:boolean}
const money=(value:number,currency='ETB')=>new Intl.NumberFormat('en-ET',{style:'currency',currency}).format(value)

export function BusinessDashboard({cashiers,checkout,wallet,profile,onSignOut}:{cashiers:ReactNode;checkout:ReactNode;wallet:ReactNode;profile:ReactNode;onSignOut:()=>void}){
 const[tab,setTab]=useState<Tab>('home'),[items,setItems]=useState<BusinessRelationship[]>([]),[business,setBusiness]=useState<Profile>(),[balance,setBalance]=useState<WalletSummary>(),[metrics,setMetrics]=useState<Metrics>(),[error,setError]=useState('')
 const load=()=>api<BusinessRelationship[]>('/api/v1/merchant/partnerships').then(value=>{setItems(value);setError('')}).catch(e=>{console.error(e);setError("We couldn't load advertising relationships right now.")})
 const loadBalance=()=>api<WalletSummary>('/api/v1/merchant/wallet').then(setBalance).catch(e=>console.error(e))
 useEffect(()=>{void load();void api<Profile>('/api/v1/merchants/me').then(setBusiness).catch(console.error);void loadBalance();void api<Metrics>('/api/v1/merchant/dashboard-metrics').then(setMetrics).catch(console.error);const refresh=()=>{if(document.visibilityState==='visible'){void load();void loadBalance();void api<Metrics>('/api/v1/merchant/dashboard-metrics').then(setMetrics).catch(console.error)}};const timer=window.setInterval(refresh,12000);document.addEventListener('visibilitychange',refresh);window.addEventListener('focus',refresh);const unsubscribe=onActionableRefresh(refresh);return()=>{window.clearInterval(timer);document.removeEventListener('visibilitychange',refresh);window.removeEventListener('focus',refresh);unsubscribe()}},[])
 const allTabs:[Tab,string][]=[['find','Find Creators'],['active','Active Ads'],['requests','Requests'],['confirmed-sales','Confirmed Sales'],['checkout','Checkout'],['wallet','Wallet']],tabs:[Tab,string][]=allTabs.filter(([id])=>balance?.advertisingEligible===true||!['find','active'].includes(id)),active=items.filter(x=>relationshipState(x).label==='Active').length,pending=items.filter(x=>x.status==='Pending').length,low=balance?.advertisingEligible===false
 const navigate=(target:string)=>setTab(target.includes('wallet')||target.includes('deposit')?'wallet':target.includes('sale')?'confirmed-sales':target.includes('checkout')?'checkout':target.includes('request')||target.includes('invitation')?'requests':'home')
 return <AccountChrome role="Business" name={business?.tradingName} status={business?.effectiveStatus} onProfile={()=>setTab('profile')} onManagement={()=>setTab('cashiers')} onHelp={()=>location.assign('/help')} onSignOut={onSignOut} onNavigate={navigate}><div className="creator-dashboard business-dashboard"><nav className="creator-tabs" aria-label="Business sections">{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} data-mobile-hidden={id==='confirmed-sales'||id==='wallet' ? 'true' : undefined} aria-current={tab===id?'page':undefined} onClick={()=>setTab(id)}><NavIcon name={id==='find'?'creators':id==='active'?'ads':id==='requests'?'requests':id==='checkout'?'checkout':'wallet'} /><span>{label}</span></button>)}</nav>{error&&tab!=='profile'&&<p className="friendly-error">{error}</p>}{low&&<div className="low-balance-warning" role="alert">Your balance is low. Add funds to continue advertising. Available: {money(balance?.availableBalance??0,balance?.currencyCode)} · Required minimum: {money(balance?.minimumRequiredBalance??0,balance?.currencyCode)}.</div>}{tab==='home'&&<div className="role-summary-list"><button onClick={()=>setTab(low?'wallet':'active')}><span>Active Ads</span><strong>{active}</strong><i>›</i></button><button onClick={()=>setTab('requests')}><span>Pending Requests</span><strong>{pending}</strong><i>›</i></button><button onClick={()=>setTab('confirmed-sales')}><span>Confirmed Sales</span><strong>{metrics?.confirmedSales??0}</strong><i>›</i></button><button onClick={()=>setTab('wallet')}><span>Wallet Balance</span><strong>{money(balance?.availableBalance??0,balance?.currencyCode)}</strong><i>›</i></button></div>}{tab==='find'&&balance?.advertisingEligible!==false&&<><FindCreators refresh={()=>void load()}/>{active>0&&<div className="secondary-section-link"><span>{active} active ad{active===1?'':'s'}</span><button className="quiet" onClick={()=>setTab('active')}>View all</button></div>}</>}{tab==='active'&&balance?.advertisingEligible!==false&&<><ActiveCreators items={items} refresh={()=>void load()}/>{error&&<p className="friendly-error">{error}</p>}</>} {tab==='requests'&&<><AdvertisingRequests items={items} refresh={()=>void load()}/>{error&&<p className="friendly-error">{error}</p>}</>} {tab==='cashiers'&&cashiers}{tab==='confirmed-sales'&&<ConfirmedSalesWorkspace/>}{tab==='checkout'&&checkout}{tab==='wallet'&&wallet}{tab==='profile'&&profile}</div></AccountChrome>
}
