import {useEffect,useState} from 'react'
import {getAccessToken} from './sessionStore'
type ReuseRule='OncePerDay'|'OncePerWeek'|'OncePerMonth'|'OncePerOffer'|'Unlimited'
type Campaign={id:string;publicCampaignId:string;status:string;durationDays:number;startsAtUtc?:string;expiresAtUtc?:string;qrStatus?:string;campaignCode?:string;reuseRule:ReuseRule;merchantName?:string;offerTitle?:string;offerLink?:string;qrPayload?:string}
type MerchantProfile={businessType:string}
const base=(import.meta.env.VITE_API_URL??'').replace(/\/$/,'');const token=getAccessToken
async function api<T>(path:string,method='GET',body?:unknown):Promise<T>{const r=await fetch(`${base}${path}`,{method,headers:{Authorization:`Bearer ${token()}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const value=await r.json().catch(()=>({}));if(!r.ok)throw Error(value.detail??`Request failed (${r.status}).`);return value}
const remaining=(v?:string)=>v?`${Math.max(0,Math.ceil((new Date(v).getTime()-Date.now())/86400000))} days remaining`:'Not started'
export const suggestedReuseRule=(businessType:string):ReuseRule|''=>businessType==='Restaurant / Café'||businessType==='Grocery / Mini-market'?'OncePerDay':businessType==='Beauty / Salon'?'OncePerWeek':['Clothing / Boutique','Furniture','Electronics','Hotel / Travel','Professional Services'].includes(businessType)?'OncePerOffer':''
export const reuseRuleOptions:[ReuseRule,string,string][]=[['OncePerDay','Once per day','The same Shopper can use this Offer again the next calendar day.'],['OncePerWeek','Once per week','The same Shopper can use this Offer again in the next configured week.'],['OncePerMonth','Once per month','The same Shopper can use this Offer again in the next calendar month.'],['OncePerOffer','Once during this Offer','The same Shopper can receive cashback only once before the Offer ends.'],['Unlimited','Unlimited','The Shopper may reuse this Offer, subject to fraud and transaction limits.']]
const displayStatus=(x:Campaign)=>x.status==='Expired'||x.qrStatus==='Expired'?'Expired':x.status==='Suspended'||x.qrStatus==='Revoked'?'Suspended':x.status==='Active'&&x.qrStatus==='Active'?'Active':'Unavailable'
export function CreatorCampaignWorkspace(){const[items,setItems]=useState<Campaign[]>(),[message,setMessage]=useState(''),[selected,setSelected]=useState<Campaign>();const load=()=>api<Campaign[]>('/api/v1/creator/campaigns').then(setItems).catch(e=>{console.error(e);setMessage('This section is temporarily unavailable.')});useEffect(()=>{void load()},[]);async function action(x:Campaign,name:'start'|'renewal-request'){try{await api(`/api/v1/creator/campaigns/${x.id}/${name}`,'POST',name==='renewal-request'?{note:''}:undefined);setMessage(name==='start'?'Offer started.':'Renewal request sent.');load()}catch(e){console.error(e);setMessage('We could not complete that request.')}}async function copy(x:Campaign){if(!x.offerLink)return;await navigator.clipboard.writeText(new URL(x.offerLink,location.origin).href);setMessage('Offer link copied.')}async function download(x:Campaign){const r=await fetch(`${base}/api/v1/creator/campaigns/${x.id}/qr-image`,{headers:{Authorization:`Bearer ${token()}`}});if(!r.ok){setMessage('This section is temporarily unavailable.');return}const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=`offer-${x.campaignCode}.png`;a.click();URL.revokeObjectURL(url)}return <section className="creator-section"><h2>My Offers</h2>{message&&<p className="friendly-error">{message}</p>}{items?.length===0?<p className="compact-empty">No active offers yet.</p>:<div className="cards">{items?.map(x=><article key={x.id}><span>{displayStatus(x)}</span><strong>{x.offerTitle??x.publicCampaignId}</strong><p>{x.merchantName??'Business'} · {x.durationDays} days</p><button className="quiet" onClick={()=>setSelected(x)}>Offer details</button>{x.offerLink&&<button onClick={()=>copy(x)}>Copy link</button>}{x.qrPayload&&<button onClick={()=>download(x)}>Download QR</button>}{x.status==='ApprovedAwaitingStart'&&<button onClick={()=>action(x,'start')}>Start Offer</button>}</article>)}</div>}{selected&&<div className="compact-panel"><h3>{selected.offerTitle}</h3><p>{selected.merchantName} · {displayStatus(selected)}</p><p>Offer code: {selected.campaignCode}</p><button onClick={()=>setSelected(undefined)}>Close</button></div>}</section>}
export function MerchantCampaignWorkspace(){const[items,setItems]=useState<Campaign[]>(),[message,setMessage]=useState(''),[businessType,setBusinessType]=useState(''),[selection,setSelection]=useState<Record<string,ReuseRule|''>>({});const load=()=>api<Campaign[]>('/api/v1/merchant/campaigns').then(setItems).catch(e=>setMessage(e.message));useEffect(()=>{void load();void api<MerchantProfile>('/api/v1/merchants/me').then(x=>setBusinessType(x.businessType)).catch(()=>{})},[]);async function approve(x:Campaign){const rule=prompt('Commission rule version ID');if(!rule)return;const reuseRule=selection[x.id]||suggestedReuseRule(businessType);if(!reuseRule){setMessage('Select a Shopper reuse rule.');return}try{await api(`/api/v1/merchant/campaigns/${x.id}/approve`,'POST',{durationDays:30,commissionRuleVersionId:rule,merchantAllowedStartAtUtc:null,conditions:null,eligibleLocationIds:null,reuseRule});setMessage('Offer approved. The Creator can access its reusable Offer QR.');load()}catch(e){setMessage((e as Error).message)}}return <section><h2>Offer operations</h2>{message&&<aside>{message}</aside>}<div className="cards">{items?.map(x=><article key={x.id}><span>{x.status}</span><strong>{x.publicCampaignId}</strong><p>{x.durationDays} days · Offer QR {x.qrStatus??'not issued'}</p>{x.status==='PendingApproval'?<><label>Shopper reuse rule<select required value={selection[x.id]??suggestedReuseRule(businessType)} onChange={e=>setSelection({...selection,[x.id]:e.target.value as ReuseRule})}><option value="" disabled>Select a rule</option>{reuseRuleOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><p>How often can the same Shopper use this Offer?</p>{suggestedReuseRule(businessType)&&<small>Suggested for your business type: {suggestedReuseRule(businessType)}</small>}<button onClick={()=>approve(x)}>Approve Offer</button></>:<p>Shopper reuse rule: {x.reuseRule}</p>}</article>)}</div></section>}
