import {useEffect,useState} from 'react'
type ReuseRule='OncePerDay'|'OncePerWeek'|'OncePerMonth'|'OncePerOffer'|'Unlimited'
type Campaign={id:string;publicCampaignId:string;status:string;durationDays:number;expiresAtUtc?:string;qrStatus?:string;campaignCode?:string;reuseRule:ReuseRule}
type MerchantProfile={businessType:string}
const base=(import.meta.env.VITE_API_URL??'').replace(/\/$/,'');const token=()=>localStorage.getItem('creatorpay_access_token')??''
async function api<T>(path:string,method='GET',body?:unknown):Promise<T>{const r=await fetch(`${base}${path}`,{method,headers:{Authorization:`Bearer ${token()}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const value=await r.json().catch(()=>({}));if(!r.ok)throw Error(value.detail??`Request failed (${r.status}).`);return value}
const remaining=(v?:string)=>v?`${Math.max(0,Math.ceil((new Date(v).getTime()-Date.now())/86400000))} days remaining`:'Not started'
export const suggestedReuseRule=(businessType:string):ReuseRule|''=>businessType==='Restaurant / Café'||businessType==='Grocery / Mini-market'?'OncePerDay':businessType==='Beauty / Salon'?'OncePerWeek':['Clothing / Boutique','Furniture','Electronics','Hotel / Travel','Professional Services'].includes(businessType)?'OncePerOffer':''
export const reuseRuleOptions:[ReuseRule,string,string][]=[['OncePerDay','Once per day','The same Shopper can use this Offer again the next calendar day.'],['OncePerWeek','Once per week','The same Shopper can use this Offer again in the next configured week.'],['OncePerMonth','Once per month','The same Shopper can use this Offer again in the next calendar month.'],['OncePerOffer','Once during this Offer','The same Shopper can receive cashback only once before the Offer ends.'],['Unlimited','Unlimited','The Shopper may reuse this Offer, subject to fraud and transaction limits.']]
export function CreatorCampaignWorkspace(){const[items,setItems]=useState<Campaign[]>(),[message,setMessage]=useState('');const load=()=>api<Campaign[]>('/api/v1/creator/campaigns').then(setItems).catch(e=>setMessage(e.message));useEffect(()=>{void load()},[]);async function action(x:Campaign,name:'start'|'renewal-request'){try{await api(`/api/v1/creator/campaigns/${x.id}/${name}`,'POST',name==='renewal-request'?{note:''}:undefined);setMessage(name==='start'?'Promotion started using server time.':'Renewal created as a new campaign.');load()}catch(e){setMessage((e as Error).message)}}return <section><h2>Merchant campaigns</h2>{message&&<aside>{message}</aside>}<div className="cards">{items?.map(x=><article key={x.id}><span>{x.status}</span><strong>{x.publicCampaignId}</strong><p>{x.durationDays} days · {remaining(x.expiresAtUtc)}</p><p>Shopper reuse rule: {x.reuseRule}</p>{x.campaignCode&&<p>Discovery code: <code>{x.campaignCode}</code></p>}{x.status==='ApprovedAwaitingStart'&&<button onClick={()=>action(x,'start')}>Start Promotion</button>}{x.status==='Expired'&&<button onClick={()=>action(x,'renewal-request')}>Request renewal</button>}</article>)}</div></section>}
export function MerchantCampaignWorkspace(){const[items,setItems]=useState<Campaign[]>(),[message,setMessage]=useState(''),[businessType,setBusinessType]=useState(''),[selection,setSelection]=useState<Record<string,ReuseRule|''>>({});const load=()=>api<Campaign[]>('/api/v1/merchant/campaigns').then(setItems).catch(e=>setMessage(e.message));useEffect(()=>{void load();void api<MerchantProfile>('/api/v1/merchants/me').then(x=>setBusinessType(x.businessType)).catch(()=>{})},[]);async function approve(x:Campaign){const rule=prompt('Commission rule version ID');if(!rule)return;const reuseRule=selection[x.id]||suggestedReuseRule(businessType);if(!reuseRule){setMessage('Select a Shopper reuse rule.');return}try{const r=await api<{qrPayload:string}>(`/api/v1/merchant/campaigns/${x.id}/approve`,'POST',{durationDays:30,commissionRuleVersionId:rule,merchantAllowedStartAtUtc:null,conditions:null,eligibleLocationIds:null,reuseRule});setMessage(`Approved. Discovery QR payload shown once: ${r.qrPayload}`);load()}catch(e){setMessage((e as Error).message)}}const hasActive=items?.some(x=>x.status==='Active'),suggested=suggestedReuseRule(businessType);return <section><h2>Campaign operations</h2>{message&&<aside>{message}</aside>}{items&&!hasActive&&<aside>No active creator promotions are available. Approve a pending campaign or ask its creator to activate an approved campaign.</aside>}<div className="cards">{items?.map(x=><article key={x.id}><span>{x.status}</span><strong>{x.publicCampaignId}</strong><p>{x.durationDays} days · discovery QR {x.qrStatus??'not issued'}</p>{x.status==='PendingApproval'?<><label>Shopper reuse rule<select required value={selection[x.id]??suggested} onChange={e=>setSelection({...selection,[x.id]:e.target.value as ReuseRule})}><option value="" disabled>Select a rule</option>{reuseRuleOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><p>How often can the same Shopper use this Offer?</p>{suggested&&<small>Suggested for your business type: {reuseRuleOptions.find(option=>option[0]===suggested)?.[1]}</small>}<small>{reuseRuleOptions.find(option=>option[0]===(selection[x.id]||suggested))?.[2]}</small><button onClick={()=>approve(x)}>Approve campaign</button></>:<p>Shopper reuse rule: {x.reuseRule}</p>}</article>)}</div></section>}
