import {FormEvent,useMemo,useState} from 'react'
const base=(import.meta.env.VITE_API_URL??'').replace(/\/$/,'')
type Result={status:string;code:string;message:string;maskedPhoneNumber?:string;checkout?:{id:string;publicCheckoutId:string;cashbackAmount?:number;creatorAmount?:number}}
const normalizePreview=(value:string)=>{const digits=value.replace(/\D/g,'');const local=digits.startsWith('251')?`0${digits.slice(3)}`:digits;return local.length===10?`${local.slice(0,2)}*****${local.slice(-3)}`:''}
export function CashierCheckoutWorkspace(){
 const[qrPayload,setQrPayload]=useState(''),[merchantLocationId,setMerchantLocationId]=useState(''),[shopperPhoneNumber,setShopperPhoneNumber]=useState(''),[purchaseAmount,setPurchaseAmount]=useState(''),[result,setResult]=useState<Result>(),[busy,setBusy]=useState(false);const masked=useMemo(()=>normalizePreview(shopperPhoneNumber),[shopperPhoneNumber]);
 async function submit(e:FormEvent){e.preventDefault();setResult(undefined);setBusy(true);try{const response=await fetch(`${base}/api/v1/cashier/checkouts/offer`,{method:'POST',headers:{Authorization:`Bearer ${localStorage.getItem('creatorpay_access_token')??''}`,'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({qrPayload,merchantLocationId,shopperPhoneNumber,purchaseAmount:Number(purchaseAmount)})});const body=await response.json().catch(()=>({}));setResult(response.ok?body:{status:'Error',code:response.status===409?'unavailable':'invalid',message:body.detail??`Request failed (${response.status}).`})}finally{setBusy(false)}}
 return <section><h2>Scan Offer QR</h2><form className="panel form" onSubmit={submit}><label>Offer QR payload<textarea required value={qrPayload} onChange={e=>setQrPayload(e.target.value)} placeholder="creatorpay:offer:…"/></label><label>Assigned location ID<input required value={merchantLocationId} onChange={e=>setMerchantLocationId(e.target.value)}/></label><label>Shopper registered phone<input required inputMode="tel" value={shopperPhoneNumber} onChange={e=>setShopperPhoneNumber(e.target.value)} placeholder="0912345678"/></label>{masked&&<p>Shopper phone: <strong>{masked}</strong></p>}<label>Purchase amount (ETB)<input required type="number" min="0.01" step="0.01" value={purchaseAmount} onChange={e=>setPurchaseAmount(e.target.value)}/></label><button disabled={busy}>{busy?'Submitting…':'Submit checkout'}</button></form>{result&&<aside className={result.status==='Success'?'success':''}><strong>{result.status}</strong><p>{result.message}</p>{result.maskedPhoneNumber&&<p>Shopper: {result.maskedPhoneNumber}</p>}{result.code==='supervisor_approval_required'&&result.checkout&&<p>Checkout {result.checkout.publicCheckoutId} is ready for supervisor approval.</p>}</aside>}</section>
}
