import {FormEvent,useEffect,useState} from 'react'
import {api} from './apiClient'

type Settings={merchantCommissionRatePercent:number;creatorSharePercent:number;shopperSharePercent:number;platformSharePercent:number;minimumBusinessWalletBalance:number;currencyCode:string;effectiveFromUtc:string;creatorCutoffDay:string;creatorCutoffTime:string;creatorPayoutDay:string;shopperCutoffDay:number;shopperCutoffTime:string;shopperPayoutDay:number;payoutScheduleEffectiveFromUtc:string}

export function CommissionWorkspace({role}:{role:string}){
  const admin=role==='PlatformAdmin',[settings,setSettings]=useState<Settings>(),[form,setForm]=useState({merchant:'',creator:'',shopper:'',platform:'',minimum:'',creatorCutoffDay:'Friday',creatorCutoffTime:'00:00',creatorPayoutDay:'Saturday',shopperCutoffDay:'0',shopperCutoffTime:'00:00',shopperPayoutDay:'1',effectiveFrom:new Date().toISOString().slice(0,16)}),[message,setMessage]=useState(''),[loading,setLoading]=useState(true)
  const apply=(x:Settings)=>{setSettings(x);setForm({merchant:String(x.merchantCommissionRatePercent),creator:String(x.creatorSharePercent),shopper:String(x.shopperSharePercent),platform:String(x.platformSharePercent),minimum:String(x.minimumBusinessWalletBalance),creatorCutoffDay:x.creatorCutoffDay,creatorCutoffTime:x.creatorCutoffTime.slice(0,5),creatorPayoutDay:x.creatorPayoutDay,shopperCutoffDay:String(x.shopperCutoffDay),shopperCutoffTime:x.shopperCutoffTime.slice(0,5),shopperPayoutDay:String(x.shopperPayoutDay),effectiveFrom:new Date(Math.max(Date.now(),new Date(x.payoutScheduleEffectiveFromUtc).getTime())).toISOString().slice(0,16)})}
  const load=()=>api<Settings>('/api/v1/admin/financial-settings').then(apply).catch(error=>{console.error(error);setMessage("We couldn't load financial settings.")}).finally(()=>setLoading(false))
  useEffect(()=>{if(admin)void load()},[admin])
  async function save(e:FormEvent){
    e.preventDefault()
    const body={merchantCommissionRatePercent:Number(form.merchant),creatorSharePercent:Number(form.creator),shopperSharePercent:Number(form.shopper),platformSharePercent:Number(form.platform),minimumBusinessWalletBalance:Number(form.minimum),creatorCutoffDay:form.creatorCutoffDay,creatorCutoffTime:`${form.creatorCutoffTime}:00`,creatorPayoutDay:form.creatorPayoutDay,shopperCutoffDay:Number(form.shopperCutoffDay),shopperCutoffTime:`${form.shopperCutoffTime}:00`,shopperPayoutDay:Number(form.shopperPayoutDay),payoutScheduleEffectiveFromUtc:`${form.effectiveFrom}:00Z`}
    if(body.creatorSharePercent+body.shopperSharePercent+body.platformSharePercent!==100){setMessage('Creator, Shopper, and Platform percentages must total 100%.');return}
    if(!confirm('Save these financial settings for new transactions? Historical transactions will not change.'))return
    try{await api('/api/v1/admin/financial-settings',{method:'PUT',body:JSON.stringify(body)});await load();setMessage('Financial settings saved. New transactions use the new effective version.')}
    catch(error){console.error(error);setMessage(error instanceof Error?error.message:'Unable to save financial settings.')}
  }
  if(!admin)return <section><h2>Commission</h2><p>Commission configuration is available to Platform Admin only.</p></section>
  const days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];return <section><div className="title"><div><p className="eyebrow">Financial configuration</p><h2>Financial Settings</h2></div></div>{message&&<aside role="status">{message}</aside>}{loading?<p>Loading…</p>:settings?<form className="panel form" onSubmit={save}><p>Changes are versioned and apply only to new transactions and future payout schedules.</p><label>Business Commission<input required type="number" min="0" max="100" step="0.01" value={form.merchant} onChange={e=>setForm({...form,merchant:e.target.value})}/><span>%</span></label><fieldset><legend>Split of that commission</legend><label>Creator<input required type="number" min="0" max="100" step="0.01" value={form.creator} onChange={e=>setForm({...form,creator:e.target.value})}/><span>%</span></label><label>Shopper<input required type="number" min="0" max="100" step="0.01" value={form.shopper} onChange={e=>setForm({...form,shopper:e.target.value})}/><span>%</span></label><label>Platform<input required type="number" min="0" max="100" step="0.01" value={form.platform} onChange={e=>setForm({...form,platform:e.target.value})}/><span>%</span></label></fieldset><label>Minimum Business Wallet Balance<input required type="number" min="0" step="0.01" value={form.minimum} onChange={e=>setForm({...form,minimum:e.target.value})}/><span>ETB</span></label><fieldset><legend>Creator Payout — Weekly</legend><label>Cutoff Day<select value={form.creatorCutoffDay} onChange={e=>setForm({...form,creatorCutoffDay:e.target.value})}>{days.map(x=><option key={x}>{x}</option>)}</select></label><label>Cutoff Time<input type="time" value={form.creatorCutoffTime} onChange={e=>setForm({...form,creatorCutoffTime:e.target.value})}/></label><label>Payout Day<select value={form.creatorPayoutDay} onChange={e=>setForm({...form,creatorPayoutDay:e.target.value})}>{days.map(x=><option key={x}>{x}</option>)}</select></label></fieldset><fieldset><legend>Shopper Payout — Monthly</legend><label>Cutoff Day (0 = last day)<input type="number" min="0" max="31" value={form.shopperCutoffDay} onChange={e=>setForm({...form,shopperCutoffDay:e.target.value})}/></label><label>Cutoff Time<input type="time" value={form.shopperCutoffTime} onChange={e=>setForm({...form,shopperCutoffTime:e.target.value})}/></label><label>Payout Day<input type="number" min="1" max="31" value={form.shopperPayoutDay} onChange={e=>setForm({...form,shopperPayoutDay:e.target.value})}/></label></fieldset><label>Schedule Effective From (UTC)<input required type="datetime-local" value={form.effectiveFrom} onChange={e=>setForm({...form,effectiveFrom:e.target.value})}/></label><button>Save Settings</button></form>:null}</section>
}
