import {FormEvent,useEffect,useState} from 'react'
import {api} from './apiClient'
import {daysLeftText,relationshipState} from './relationshipTime'
import {rankMatches,useTypeahead} from './typeahead'

type Business={id:string;publicMerchantId:string;tradingName:string;legalBusinessName:string;city:string;businessType:string}
export type AdvertisingRequest={id:string;merchantId:string;merchantName:string;status:string;relationshipState?:string;activationRequired?:boolean;requestedAtUtc:string;startDateUtc?:string;endDateUtc?:string;activatedAtUtc?:string;expiresAtUtc?:string;promotionActive:boolean;initiatedBy?:'Business'|'Creator'|'Unknown'}

export function FindBusinesses({onRequested}:{onRequested:()=>void}){
  const[query,setQuery]=useState(''),[category,setCategory]=useState(''),[items,setItems]=useState<Business[]>([]),[requests,setRequests]=useState<AdvertisingRequest[]>([]),[loading,setLoading]=useState(false),[message,setMessage]=useState('')
  const loadRequests=()=>api<AdvertisingRequest[]>('/api/v1/creator/partnerships').then(setRequests).catch(console.error)
  useEffect(()=>{void loadRequests()},[])
  async function find(term:string){setLoading(true);setMessage('');try{const found=await api<Business[]>(`/api/v1/creator/merchants/search?q=${encodeURIComponent(term)}`),filtered=category?found.filter(x=>x.businessType===category):found;return rankMatches(filtered,term,x=>[x.tradingName,x.legalBusinessName,x.city,x.publicMerchantId])}catch(error){console.error(error);setMessage("We couldn't load this information.");return[]}finally{setLoading(false)}}
  useTypeahead(query,find,setItems,[category])
  async function search(e?:FormEvent){e?.preventDefault();setItems(await find(query))}
  async function request(business:Business){setMessage('');try{await api('/api/v1/creator/partnerships/requests',{method:'POST',body:JSON.stringify({merchantId:business.id,introductoryMessage:null})});setMessage(`Advertising request sent to ${business.tradingName}.`);await loadRequests();onRequested()}catch(error){console.error(error);setMessage("We couldn't complete that advertising request.")}}
  const categories=['Restaurant / Café','Grocery / Mini-market','Clothing / Boutique','Beauty / Salon','Furniture','Electronics','Hotel / Travel','Professional Services','Other']
  function stateFor(business:Business){const relationship=requests.find(x=>x.merchantId===business.id)||requests.find(x=>x.merchantName.toLowerCase()===business.tradingName.toLowerCase());if(!relationship)return {label:'No relationship',days:'—',canRequest:true};if(relationship.status==='Pending')return {label:'Request Pending',days:'—',canRequest:false};if(relationship.status==='Approved'){const state=relationshipState(relationship);return {label:state.label==='Active'?'Active Ad':state.label,days:state.daysLeft===null?'—':daysLeftText(state.daysLeft,state.tone),canRequest:false}}if(['Revoked','Suspended'].includes(relationship.status))return {label:'Deactivated',days:'—',canRequest:false,reactivationManagedByBusiness:true};if(relationship.status==='Blocked')return {label:'Blocked',days:'—',canRequest:false};if(relationship.status==='Rejected')return {label:'Declined',days:'—',canRequest:true};return {label:'Unavailable',days:'—',canRequest:false}}
  return <section className="creator-section"><h2>Find Businesses</h2><p>Find a Business and ask for permission to advertise.</p><form className="business-search" onSubmit={search}><label>Business name<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by name, city, or public ID"/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{categories.map(x=><option key={x}>{x}</option>)}</select></label><button disabled={loading}>{loading?'Searching…':'Search'}</button></form>{message&&<p className={message.includes('sent')||message.includes('Active')?'success-note':'friendly-error'} role="status">{message}</p>}{!loading&&items.length===0?<p className="compact-empty">No eligible Businesses found.</p>:<div className="discovery-list"><div className="discovery-row discovery-headings"><span>Business</span><span>Status</span><span>Days Left</span><span>Action</span></div>{items.map(x=>{const state=stateFor(x);return <article className="discovery-row" key={x.id}><div><strong>{x.tradingName}</strong><span>{x.businessType}</span><small>{x.city}</small></div><span data-label="Status"><span className="status-badge">{state.label}</span></span><span data-label="Days Left">{state.days}</span><span data-label="Action">{state.canRequest&&<button onClick={()=>void request(x)}>{state.label==='Declined'?'Request Again':'Request to Advertise'}</button>}{state.reactivationManagedByBusiness&&<span className="hint">The Business can Reactivate this advertising relationship.</span>}</span></article>})}</div>}</section>
}

type AdBusiness={partnershipId:string;merchantId:string;businessName:string;status:'Active'|'Deactivated'|'Expired';expiresAtUtc?:string;confirmedSales:number;creatorEarned:number;currencyCode:string}
type AdTransaction={transactionId:string;partnershipId:string;merchantId:string;businessName:string;confirmedAtUtc:string;status:'Confirmed';creatorEarned:number;currencyCode:string}
type AdReport={businesses:AdBusiness[];transactions:AdTransaction[]}
const adMoney=(value:number,currency='ETB')=>new Intl.NumberFormat('en-ET',{style:'currency',currency}).format(value)

export function CreatorRequests({items,refresh}:{items:AdvertisingRequest[];refresh:()=>void}){
  const [message,setMessage]=useState('')
  async function decide(item:AdvertisingRequest,accept:boolean){try{await api(`/api/v1/creator/partnerships/${item.id}/${accept?'accept-invitation':'decline-invitation'}`,{method:'POST'});setMessage(accept?`Invitation from ${item.merchantName} accepted.`:`Invitation from ${item.merchantName} declined.`);refresh()}catch(e){setMessage((e as Error).message)}}
  async function requestAgain(item:AdvertisingRequest){try{await api('/api/v1/creator/partnerships/requests',{method:'POST',body:JSON.stringify({merchantId:item.merchantId,introductoryMessage:null})});setMessage(`Request sent to ${item.merchantName}.`);refresh()}catch(e){setMessage((e as Error).message)}}
  const active=items.filter(x=>x.status==='Pending'||x.status==='Rejected'||x.status==='Suspended'||x.status==='Revoked')
  return <section className="creator-section"><h2>Requests</h2>{message&&<p className="friendly-error" role="status">{message}</p>}{active.length===0?<p className="compact-empty">No requests or invitations.</p>:<div className="request-groups">{active.map(x=><article key={x.id}><div><strong>{x.merchantName}</strong><small>{new Date(x.requestedAtUtc).toLocaleDateString()}</small></div><span className="status-badge">{x.status==='Rejected'?'Declined':x.status}</span>{x.status==='Pending'&&x.initiatedBy==='Business'&&<div><button onClick={()=>void decide(x,true)}>Accept</button><button className="quiet" onClick={()=>void decide(x,false)}>Decline</button></div>}{x.status==='Rejected'&&<button onClick={()=>void requestAgain(x)}>Request Again</button>}</article>)}</div>}</section>
}

export function CreatorConfirmedSales(){
  const [report,setReport]=useState<AdReport>(); const [error,setError]=useState('')
  useEffect(()=>{api<AdReport>('/api/v1/creator/ads/performance').then(setReport).catch(e=>setError((e as Error).message))},[])
  const rows=report?.transactions??[]
  return <section className="creator-section"><h2>Confirmed Sales</h2>{error&&<p className="friendly-error">{error}</p>}{rows.length===0?<p className="compact-empty">No confirmed sales yet.</p>:<div className="table-wrap"><table><thead><tr><th>Date</th><th>Business</th><th>Status</th><th>Creator Earned</th></tr></thead><tbody>{rows.map(x=><tr key={x.transactionId}><td>{new Date(x.confirmedAtUtc).toLocaleDateString()}</td><td>{x.businessName}</td><td><span className="status-badge">{x.status}</span></td><td>{adMoney(x.creatorEarned,x.currencyCode)}</td></tr>)}</tbody></table></div>}</section>
}

export function ActiveAds({items,loading}:{items:AdvertisingRequest[];loading:boolean;refresh:()=>void}){
  const[report,setReport]=useState<AdReport>(),[error,setError]=useState('')
  useEffect(()=>{api<AdReport>('/api/v1/creator/ads/performance').then(setReport).catch(x=>{console.error(x);setError("We couldn't load advertising performance.")})},[])
  const businesses=(report?.businesses??[]).filter(x=>x.status==='Active'),activeRelationships=items.filter(x=>relationshipState(x).label==='Active')
  const totalSales=businesses.reduce((sum,x)=>sum+x.confirmedSales,0),totalEarned=businesses.reduce((sum,x)=>sum+x.creatorEarned,0),currency=businesses[0]?.currencyCode??'ETB'
  return <section className="creator-section"><h2>Active Ads</h2><div className="table-wrap"><table className="creator-ads-table"><thead><tr><th>Business</th><th>Status</th><th>Date Activated</th></tr></thead><tbody>{activeRelationships.map(x=><tr className="relationship-active" key={x.id}><td>{x.merchantName}</td><td><span className="status-badge">Active</span></td><td>{x.activatedAtUtc?new Date(x.activatedAtUtc).toLocaleDateString():'—'}</td></tr>)}</tbody></table></div>{error&&<p className="friendly-error">{error}</p>}{loading&&!report?<p>Loading…</p>:businesses.length===0?<p className="compact-empty">No confirmed advertising activity yet.</p>:<div className="table-wrap"><table className="creator-ads-table"><thead><tr><th>Business</th><th>Status</th><th>Days Left</th><th>Confirmed Sales</th><th>Creator Earned</th></tr></thead><tbody>{businesses.map(x=>{const days=x.status==='Active'&&x.expiresAtUtc?Math.max(0,Math.ceil((new Date(x.expiresAtUtc).getTime()-Date.now())/86_400_000)):null;return <tr className={`relationship-${x.status.toLowerCase()}`} key={x.partnershipId}><td>{x.businessName}</td><td><span className="status-badge">{x.status}</span></td><td>{days===null?'—':daysLeftText(days,days<=3?'urgent':days<=7?'soon':'active')}</td><td>{x.confirmedSales}</td><td>{adMoney(x.creatorEarned,x.currencyCode)}</td></tr>})}<tr className="creator-ads-total"><th>TOTAL</th><td></td><td></td><th>{totalSales}</th><th>{adMoney(totalEarned,currency)}</th></tr></tbody></table></div>}
  </section>
}
