import {useEffect,useState} from 'react'
import {api} from './apiClient'
import {AccountChrome,AccountStatusBadge} from './AccountChrome'
import {RoleNavigation} from './RoleNavigation'
import {creatorPhotoUrl,ProfileAvatar} from './profileMedia'
import {getExternalSession} from './externalSession'
import {CreatorDiscoverPromotions,CreatorPromotionRequests} from './PromotionWorkspace'
import {CreatorUgc} from './UgcWorkspace'
import {amount,v3Request} from './v3ProductApi'
import {onActionableRefresh} from './actionableRefresh'
import {SocialPlatformIcon} from './SocialPlatformIcon'

type Tab='home'|'discover'|'ugc'|'earnings'|'profile'|'requests'
type SocialPlatform='TikTok'|'Instagram'|'YouTube'|'Facebook'
type Profile={displayName:string;publicCreatorId:string;effectiveStatus:string;email:string;phoneNumber:string;city:string;biography?:string;contentCategories?:string;socialProfiles?:{platform:SocialPlatform;profileUrl?:string;followerCount:number;verificationStatus:string}[];profileImage?:{fileName:string}}
type SocialDraft={platform:SocialPlatform;profileUrl:string;audienceCount:string}
type Earnings={availableEarnings:number;minimumToCashOut:number;amountNeeded:number;eligibleAmount:number;viewEarnings:number;saleEarnings:number;ugcEarnings:number;history:{id:string;campaign:string;source:string;amount:number;atUtc:string}[];payoutHistory:{id:string;amount:number;status:string;eligibleAtUtc:string;paidAtUtc?:string}[]}
type Home={requests:number;activeCampaigns:number;earnings:Earnings}
const platforms:SocialPlatform[]=['TikTok','Instagram','YouTube','Facebook']

function EarningsView({value}:{value?:Earnings}){return <section className="product-workspace creator-section"><h2>Earnings</h2>{!value?<p>Loading…</p>:<><div className="summary-grid"><article><span>View Earnings</span><strong>{amount(value.viewEarnings)}</strong></article><article><span>Sale Earnings</span><strong>{amount(value.saleEarnings)}</strong></article><article><span>UGC Earnings</span><strong>{amount(value.ugcEarnings)}</strong></article><article><span>Available</span><strong>{amount(value.availableEarnings)}</strong></article></div><p>{value.eligibleAmount>0?`${amount(value.eligibleAmount)} eligible for payout.`:`${amount(value.amountNeeded)} until the next payout threshold.`}</p><h3>Recent earnings</h3>{value.history.length===0?<p className="compact-empty">No earnings yet.</p>:<div className="product-list">{value.history.map(x=><article key={x.id}><div><strong>{x.source}</strong><span>{x.campaign} · {new Date(x.atUtc).toLocaleDateString()}</span></div><strong>{amount(x.amount)}</strong></article>)}</div>}<h3>Payout status</h3>{value.payoutHistory.length===0?<p className="compact-empty">No payout history yet.</p>:<div className="product-list">{value.payoutHistory.map(x=><article key={x.id}><div><strong>{amount(x.amount)}</strong><span>{new Date(x.paidAtUtc??x.eligibleAtUtc).toLocaleDateString()}</span></div><span className="status-badge">{x.status}</span></article>)}</div>}</>}</section>}

function ProfileView({profile,refresh}:{profile?:Profile;refresh:()=>Promise<void>}){
 const[drafts,setDrafts]=useState<SocialDraft[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{setDrafts((profile?.socialProfiles??[]).map(x=>({platform:x.platform,profileUrl:x.profileUrl??'',audienceCount:String(x.followerCount)})))},[profile])
 if(!profile)return <section className="creator-section"><h2>Profile</h2><p>Loading…</p></section>
 const account=getExternalSession()
 function update(index:number,value:Partial<SocialDraft>){setDrafts(drafts.map((x,i)=>i===index?{...x,...value}:x))}
 function add(){const platform=platforms.find(x=>!drafts.some(y=>y.platform===x));if(platform)setDrafts([...drafts,{platform,profileUrl:'',audienceCount:''}])}
 async function save(){setBusy(true);setMessage('');try{if(drafts.length===0)throw new Error('Keep at least one social profile.');const socialProfiles=drafts.map(x=>{const audience=Number(x.audienceCount);if(!x.profileUrl.trim()||!Number.isSafeInteger(audience)||audience<0)throw new Error(`Complete ${x.platform} URL and audience count.`);return{platform:x.platform,profileUrl:x.profileUrl.trim(),audienceCount:audience}});await api('/api/v1/integration/v3/creator/social-profiles',{method:'PUT',body:JSON.stringify({socialProfiles})});await refresh();setMessage('Social profiles updated.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 return <section className="creator-section product-workspace"><h2>Profile</h2>{message&&<p className="product-message" role="status">{message}</p>}<div className="compact-panel creator-profile-card"><ProfileAvatar name={profile.displayName} photoUrl={creatorPhotoUrl(profile.publicCreatorId,profile.profileImage?.fileName)}/><div><strong>{profile.displayName}</strong><p>{profile.city}</p><AccountStatusBadge status={profile.effectiveStatus}/></div></div><div className="compact-panel identity-readonly"><h3>Weymela account</h3><label>Account email<input readOnly value={account?.accountEmail??profile.email??''}/></label><label>Account phone<input readOnly value={account?.accountPhone??profile.phoneNumber??''}/></label></div><div className="compact-panel creator-social-editor"><h3>Social profiles</h3><div className="social-profile-list">{drafts.map((row,index)=><div className="social-profile-row" key={row.platform}><div className="social-platform-heading"><SocialPlatformIcon platform={row.platform}/><strong>{row.platform}</strong></div><label>Platform<select value={row.platform} onChange={e=>update(index,{platform:e.target.value as SocialPlatform})}>{platforms.map(p=><option key={p} value={p} disabled={drafts.some((x,i)=>i!==index&&x.platform===p)}>{p}</option>)}</select></label><label>{row.platform==='YouTube'?'Channel URL':row.platform==='Facebook'?'Profile/Page URL':'Profile URL'}<input type="url" value={row.profileUrl} onChange={e=>update(index,{profileUrl:e.target.value})}/></label><label>{row.platform==='YouTube'?'Subscriber count':'Follower count'}<input type="number" min="0" step="1" value={row.audienceCount} onChange={e=>update(index,{audienceCount:e.target.value})}/></label><button className="quiet" disabled={drafts.length===1||busy} onClick={()=>setDrafts(drafts.filter((_,i)=>i!==index))}>Remove {row.platform}</button></div>)}</div><div className="actions"><button className="quiet" disabled={drafts.length===platforms.length||busy} onClick={add}>Add social platform</button><button disabled={busy||drafts.length===0} onClick={()=>void save()}>{busy?'Saving…':'Save social profiles'}</button></div></div></section>
}

export function CreatorDashboard({onSignOut}:{onSignOut:()=>void}){
 const[tab,setTab]=useState<Tab>('home'),[profile,setProfile]=useState<Profile>(),[home,setHome]=useState<Home>(),[earnings,setEarnings]=useState<Earnings>(),[ugcAssignments,setUgcAssignments]=useState<{status:string}[]>([]),[error,setError]=useState('')
 const loadProfile=()=>api<Profile>('/api/v1/creators/me').then(setProfile)
 const load=()=>Promise.all([loadProfile(),v3Request<Home>('/api/creator/home').then(setHome),v3Request<Earnings>('/api/creator/earnings').then(setEarnings),v3Request<{status:string}[]>('/api/creator/ugc/assignments').then(setUgcAssignments)]).then(()=>setError('')).catch(e=>setError((e as Error).message))
 useEffect(()=>{void load();const active=()=>{if(document.visibilityState==='visible')void load()};addEventListener('focus',active);return()=>removeEventListener('focus',active)},[])
 useEffect(()=>onActionableRefresh(()=>{void load()}),[])
 const navigate=(target:string)=>{if(target.includes('/ugc'))setTab('ugc');else if(target.includes('request'))setTab('requests');else if(target.includes('earning')||target.includes('payout'))setTab('earnings');else if(target.includes('profile'))setTab('profile');else if(target.includes('promotion')||target.includes('discover'))setTab('discover');else setTab('home')}
 const photo=creatorPhotoUrl(profile?.publicCreatorId,profile?.profileImage?.fileName)
 return <AccountChrome role="Creator" name={profile?.displayName} status={profile?.effectiveStatus} photoUrl={photo} onProfile={()=>setTab('profile')} onHelp={()=>location.assign('/help?category=Content%20Creators')} onSignOut={onSignOut} onNavigate={navigate}><div className="creator-dashboard"><RoleNavigation role="Creator" label="Creator sections" items={[{id:'home',label:'Home',icon:'home',active:tab==='home'||tab==='requests',onSelect:()=>setTab('home')},{id:'discover',label:'Discover',icon:'discover',active:tab==='discover',onSelect:()=>setTab('discover')},{id:'ugc',label:'UGC',icon:'video',active:tab==='ugc',onSelect:()=>setTab('ugc')},{id:'earnings',label:'Earnings',icon:'payout',active:tab==='earnings',onSelect:()=>setTab('earnings')},{id:'profile',label:'Profile',icon:'profile',active:tab==='profile',onSelect:()=>setTab('profile')}]} />{error&&<p className="friendly-error">{error}</p>}{tab==='home'&&<section className="creator-home product-workspace"><h2>Home</h2><div className="summary-grid"><button className="summary-card" onClick={()=>setTab('requests')}><span>Active Promotions</span><strong>{home?.activeCampaigns??0}</strong></button><button className="summary-card" onClick={()=>setTab('requests')}><span>Pending Requests</span><strong>{home?.requests??0}</strong></button><button className="summary-card" onClick={()=>setTab('ugc')}><span>UGC in Progress</span><strong>{ugcAssignments.filter(x=>['InProgress','Submitted','ChangesRequested'].includes(x.status)).length}</strong></button><button className="summary-card" onClick={()=>setTab('earnings')}><span>Available Earnings</span><strong>{amount(home?.earnings.availableEarnings)}</strong></button><button className="summary-card" onClick={()=>setTab('earnings')}><span>Upcoming Payout</span><strong>{amount(home?.earnings.eligibleAmount)}</strong></button></div><div className="business-quick-actions"><h3>Start earning</h3><div><button onClick={()=>setTab('discover')}>Discover Promotions</button><button onClick={()=>setTab('ugc')}>Browse UGC</button><button className="quiet" onClick={()=>setTab('requests')}>My Requests</button></div></div></section>}{tab==='discover'&&<CreatorDiscoverPromotions/>}{tab==='ugc'&&<CreatorUgc/>}{tab==='requests'&&<CreatorPromotionRequests/>}{tab==='earnings'&&<EarningsView value={earnings}/>} {tab==='profile'&&<ProfileView profile={profile} refresh={async()=>{await loadProfile()}}/>}</div></AccountChrome>
}
