import {FormEvent,useEffect,useState} from 'react'
import {getAccessToken} from './sessionStore'
import {rankMatches,useTypeahead} from './typeahead'
import {AccountChrome} from './AccountChrome'
import {onActionableRefresh} from './actionableRefresh'
import {api as request} from './apiClient'
import {ProfileAvatar} from './profileMedia'
type Wallet={availableCashback:number;reservedCashback:number;currencyCode:string;nextPayoutAtUtc?:string;lastPayoutAtUtc?:string;currentPeriodConfirmedPurchases:number}
type Checkout={id:string;publicCheckoutId:string;status:string;campaignId:string;purchaseAmount?:number;cashbackAmount?:number;expiresAtUtc:string;qrPayload?:string;merchantName?:string;creatorName?:string;createdAtUtc?:string;resolvedAtUtc?:string}
type AdvertisingRow={relationshipId:string;businessId:string;publicBusinessId:string;businessName:string;city:string;creatorId:string;publicCreatorId:string;creatorCode:string;creatorName:string;status:string;daysLeft:number;rewardsAvailable:boolean;creatorProfileImageUrl?:string}
type ShopperProfile={name:string;email:string;phone:string;accountStatus:string;isEmailVerified:boolean;isPhoneVerified:boolean}
type Offer={offerCode:string;title:string;businessName:string;description:string;expiresAtUtc:string;creatorDisplayName:string}
const token=getAccessToken
async function api<T>(path:string,method='GET',body?:unknown):Promise<T>{return request<T>(path,{method,headers:method==='GET'?undefined:{'Idempotency-Key':crypto.randomUUID()},body:body===undefined?undefined:JSON.stringify(body)})}
const money=(v?:number,c='ETB')=>`${(v??0).toFixed(2)} ${c}`
export function ShopperOfferPage({code}:{code:string}){const[offer,setOffer]=useState<Offer>(),[error,setError]=useState(''),[message,setMessage]=useState('');useEffect(()=>{api<Offer>(`/api/v1/discovery/offers/${encodeURIComponent(code)}`).then(setOffer).catch(e=>setError(e.message))},[code]);async function use(){if(!token()){sessionStorage.setItem('weymela_offer_return',location.pathname);location.assign('/');return}try{const x=await api<Checkout>('/api/v1/customer/checkouts/by-offer','POST',{offerCode:offer!.offerCode});setMessage(`Temporary checkout QR (valid for about 3 minutes): ${x.qrPayload}`)}catch(e){setMessage((e as Error).message)}}if(error)return <main className="auth"><section className="panel"><h1>Offer unavailable</h1><p>{error}</p><a href="/">Discover Businesses</a></section></main>;if(!offer)return <main className="auth"><p>Loading…</p></main>;return <main className="auth"><section className="panel offer-detail"><p className="eyebrow">Weymela</p><h1>{offer.title}</h1><h2>{offer.businessName}</h2><p>{offer.description}</p><p>With {offer.creatorDisplayName}</p><button onClick={use}>Support this Creator</button>{message&&<aside>{message}</aside>}</section></main>}
export function CustomerWorkspace({onSignOut}:{onSignOut:()=>void}){const[wallet,setWallet]=useState<Wallet>(),[walletError,setWalletError]=useState(''),[checkouts,setCheckouts]=useState<Checkout[]>([]),[checkoutsError,setCheckoutsError]=useState(''),[profile,setProfile]=useState<ShopperProfile>(),[rows,setRows]=useState<AdvertisingRow[]>([]),[query,setQuery]=useState(''),[message,setMessage]=useState(''),[processing,setProcessing]=useState<string>(),[view,setView]=useState<'discover'|'confirmations'|'cashback'|'profile'>(()=>new URLSearchParams(location.search).get('view')==='confirmations'?'confirmations':'discover');
 const loadAccount=async()=>{const[walletResult,checkoutsResult,profileResult]=await Promise.allSettled([api<Wallet>('/api/v1/customer/wallet'),api<Checkout[]>('/api/v1/customer/checkouts'),api<ShopperProfile>('/api/v1/customer/profile')]);if(walletResult.status==='fulfilled'){setWallet(walletResult.value);setWalletError('')}else{console.error(walletResult.reason);setWallet(undefined);setWalletError('Cashback information is temporarily unavailable.')}if(checkoutsResult.status==='fulfilled'){setCheckouts(checkoutsResult.value);setCheckoutsError('')}else{console.error(checkoutsResult.reason);setCheckouts([]);setCheckoutsError('Purchase confirmations are temporarily unavailable.')}if(profileResult.status==='fulfilled'){setProfile(profileResult.value)}else console.error('Shopper profile unavailable',profileResult.reason)};
 const find=async(term:string)=>{try{const p=new URLSearchParams();if(term)p.set('q',term);return rankMatches(await api<AdvertisingRow[]>(`/api/v1/customer/discovery/advertising?${p}`),term,x=>[x.businessName,x.city,x.creatorName,x.publicBusinessId,x.publicCreatorId])}catch{setMessage("We couldn't load Businesses right now.");return[]}};
 useTypeahead(query,find,setRows);
 useEffect(()=>{loadAccount();return onActionableRefresh(loadAccount)},[]);
 async function submit(e:FormEvent){e.preventDefault();setRows(await find(query.trim()))}
 async function decide(x:Checkout,approve:boolean){if(processing)return;setProcessing(x.id);try{const resolved=await api<Checkout>(`/api/v1/customer/checkouts/${x.id}/${approve?'approve':'reject'}`,'POST');setCheckouts(current=>current.map(item=>item.id===x.id?resolved:item));setMessage(approve?'Purchase confirmed.':'Purchase rejected.');loadAccount()}catch(e){console.error(e);setMessage("We couldn't update this purchase confirmation.")}finally{setProcessing(undefined)}}
 const pendingCount=checkouts.filter(x=>x.status==='AwaitingCustomerApproval').length;
 const navigate=(target:string)=>setView(target.includes('confirmation')?'confirmations':target.includes('cashback')?'cashback':'discover'),visibleRows=rows.filter(x=>x.rewardsAvailable);
 return <AccountChrome role="Customer" name={profile?.name} status={profile?.accountStatus??'Active'} onProfile={()=>setView('profile')} onHelp={()=>location.assign('/help')} onSignOut={onSignOut} onNavigate={navigate}><section className="shopper"><nav aria-label="Customer navigation">{([['discover','Discover Businesses'],['cashback','Cashback']] as const).map(x=><button key={x[0]} className={view===x[0]?'active':''} onClick={()=>setView(x[0])}>{x[1]}</button>)}</nav>{message&&<aside role="status">{message}</aside>}
 {view==='discover'&&<section><h2>Discover Businesses</h2>{pendingCount>0&&<button className="pending-confirmation-link" onClick={()=>setView('confirmations')}>Purchase confirmations <span>{pendingCount}</span></button>}<form className="search-bar shopper-relationship-search" onSubmit={submit}><label><span>Business, city, or Creator</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Businesses or Creators"/></label><button>Search</button></form>{visibleRows.length?<div className="shopper-relationship-list simplified" aria-label="Active Business and Creator advertising"><div className="shopper-relationship-row headings"><span>Business</span><span>Creator Promoting</span><span>Creator ID</span></div>{visibleRows.map(x=><article className="shopper-relationship-row" key={x.relationshipId}><strong data-label="Business">{x.businessName}</strong><span data-label="Creator Promoting"><span className="creator-heading"><ProfileAvatar name={x.creatorName} photoUrl={x.creatorProfileImageUrl} /><strong>{x.creatorName}</strong></span></span><strong className="shopper-creator-code" data-label="Creator ID">{x.creatorCode}</strong></article>)}</div>:<p className="compact-empty">No active Business advertising found.</p>}</section>}
 {view==='confirmations'&&<Confirmations items={checkouts} error={checkoutsError} processing={processing} decide={decide}/>}
 {view==='cashback'&&<Summary wallet={wallet} error={walletError}/>} {view==='profile'&&<ShopperProfileCard profile={profile}/>}</section></AccountChrome>}
function Confirmations({items,error,processing,decide}:{items:Checkout[];error:string;processing?:string;decide:(x:Checkout,approve:boolean)=>void}){const pending=items.filter(x=>x.status==='AwaitingCustomerApproval').sort((a,b)=>new Date(b.createdAtUtc??0).getTime()-new Date(a.createdAtUtc??0).getTime()),history=items.filter(x=>['Completed','Rejected'].includes(x.status)).sort((a,b)=>new Date(b.resolvedAtUtc??b.createdAtUtc??0).getTime()-new Date(a.resolvedAtUtc??a.createdAtUtc??0).getTime());return <section><h2>Action Required</h2>{error&&<p className="friendly-error" role="alert">{error}</p>}{pending.length?<div className="confirmations pending-confirmations">{pending.map(x=>{const when=new Date(x.createdAtUtc??x.expiresAtUtc);const busy=processing===x.id;return <article key={x.id}><div className="confirmation-details"><span>Business</span><strong>{x.merchantName??'Business'}</strong><span>Amount</span><strong>{money(x.purchaseAmount)}</strong><span>Date / Time</span><strong>{new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeStyle:'short'}).format(when)}</strong></div><p>Is this your purchase?</p><div className="confirmation-actions"><button disabled={busy} onClick={()=>decide(x,true)}>{busy?'PROCESSING…':"YES, IT'S ME"}</button><button disabled={busy} className="danger" onClick={()=>decide(x,false)}>NO, IT'S NOT ME</button></div></article>})}</div>:<p className="compact-empty">No confirmations need your action.</p>}<h2>History</h2>{history.length?<div className="confirmation-history"><div className="confirmation-row headings"><span>Business</span><span>Amount</span><span>Status</span><span>Date</span><span>Time</span></div>{history.map(x=>{const when=new Date(x.resolvedAtUtc??x.createdAtUtc??x.expiresAtUtc);return <article className="confirmation-row" key={x.id}><strong data-label="Business">{x.merchantName??'Business'}</strong><span data-label="Amount">{money(x.purchaseAmount)}</span><span data-label="Status">{x.status==='Completed'?'Completed':'Rejected'}</span><span data-label="Date">{new Intl.DateTimeFormat('en-GB').format(when)}</span><span data-label="Time">{when.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span></article>})}</div>:<p className="compact-empty">No completed confirmations yet.</p>}</section>}
function Summary({wallet,error}:{wallet?:Wallet;error:string}){const date=(value?:string)=>value?new Intl.DateTimeFormat('en-GB').format(new Date(value)):'—';return <div className="summary-grid">{error&&<p className="friendly-error" role="alert">{error}</p>}<article className="summary-card"><span>Available Cashback</span><strong>{money(wallet?.availableCashback,wallet?.currencyCode)}</strong></article><article className="summary-card"><span>Next Payout Date</span><strong>{date(wallet?.nextPayoutAtUtc)}</strong></article></div>}
function ShopperProfileCard({profile}:{profile?:ShopperProfile}){if(!profile)return <p className="compact-empty">Profile is temporarily unavailable.</p>;const rows=[['Name',profile.name],['Email',profile.email],['Phone',profile.phone],['Account Status',profile.accountStatus]];return <section className="shopper-profile"><h2>Profile</h2><dl>{rows.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section>}
export const shopperLabels={en:['Discover Businesses','Cashback','Search Businesses or Creators','Creator ID','No active Business advertising found.','Available Cashback','Next Payout Date']}
