import {FormEvent,useEffect,useState} from 'react'

const token=()=>localStorage.getItem('creatorpay_access_token')??''
async function api<T>(path:string,init?:RequestInit):Promise<T>{const r=await fetch(path,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()}`,...init?.headers}});if(!r.ok){const p=await r.json().catch(()=>({}));throw new Error(p.detail??`Request failed (${r.status}).`)}return r.json()}
const money=(n:number,c='ETB')=>new Intl.NumberFormat('en-ET',{style:'currency',currency:c}).format(n)
type Summary={currencyCode:string;pendingBalance:number;availableBalance:number;heldBalance:number;scheduledBalance:number;paidLifetimeTotal:number;nextEstimatedPayoutAtUtc?:string}
type Earning={id:string;amount:number;currencyCode:string;status:string;earnedAtUtc:string;availableAtUtc:string}
type Payout={id:string;publicPayoutId:string;amount:number;currencyCode:string;status:string;scheduledAtUtc:string;providerReference?:string;failureReason?:string}
type Batch={id:string;publicBatchId:string;status:string;cutoffAtUtc:string;scheduledForUtc:string;totalCreatorCount:number;totalAmount:number;payouts?:Payout[]}
const Badge=({value}:{value:string})=><span className={`badge status-${value.toLowerCase()}`}>{value.replace(/([A-Z])/g,' $1')}</span>

export function CreatorEarningsWorkspace(){const[summary,setSummary]=useState<Summary>();const[earnings,setEarnings]=useState<Earning[]>([]);const[payouts,setPayouts]=useState<Payout[]>([]);const[filter,setFilter]=useState('');const[error,setError]=useState('');const load=()=>Promise.all([api<Summary>('/api/v1/creator/earnings/summary'),api<Earning[]>(`/api/v1/creator/earnings${filter?`?status=${filter}`:''}`),api<Payout[]>('/api/v1/creator/payouts')]).then(([s,e,p])=>{setSummary(s);setEarnings(e);setPayouts(p)}).catch(x=>setError(x.message));useEffect(()=>{void load()},[filter]);return <section><div className="title"><div><p className="eyebrow">Creator earnings</p><h2>Balances and payouts</h2></div></div>{error&&<p className="error">{error}</p>}{!summary?<p>Loading…</p>:<><div className="metric-grid">{[['Pending',summary.pendingBalance],['Available',summary.availableBalance],['Held',summary.heldBalance],['Scheduled',summary.scheduledBalance],['Paid lifetime',summary.paidLifetimeTotal]].map(([k,v])=><article key={String(k)}><span>{k}</span><strong>{money(Number(v),summary.currencyCode)}</strong></article>)}</div><p>Next estimated payout: {summary.nextEstimatedPayoutAtUtc?new Date(summary.nextEstimatedPayoutAtUtc).toLocaleString():'Not scheduled'}</p></>}<div className="title"><h3>Earnings history</h3><select aria-label="Earning status" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All statuses</option>{['Pending','Available','OnHold','ScheduledForPayout','Paid','Reversed'].map(x=><option key={x}>{x}</option>)}</select></div>{earnings.length===0?<p className="empty">No earnings in this category.</p>:<div className="table-wrap"><table><thead><tr><th>Earned</th><th>Status</th><th>Amount</th><th>Available</th></tr></thead><tbody>{earnings.map(x=><tr key={x.id}><td>{new Date(x.earnedAtUtc).toLocaleDateString()}</td><td><Badge value={x.status}/></td><td>{money(x.amount,x.currencyCode)}</td><td>{new Date(x.availableAtUtc).toLocaleDateString()}</td></tr>)}</tbody></table></div>}<h3>Payout history</h3>{payouts.length===0?<p className="empty">No payouts yet.</p>:payouts.map(x=><article className="panel" key={x.id}><Badge value={x.status}/><strong>{x.publicPayoutId} · {money(x.amount,x.currencyCode)}</strong><p>Scheduled {new Date(x.scheduledAtUtc).toLocaleString()}</p>{x.failureReason&&<p className="error">{x.failureReason}</p>}</article>)}</section>}

export function AdminPayoutWorkspace(){const[batches,setBatches]=useState<Batch[]>([]);const[payouts,setPayouts]=useState<Payout[]>([]);const[selected,setSelected]=useState<Batch>();const[error,setError]=useState('');const load=()=>Promise.all([api<Batch[]>('/api/v1/admin/payout-batches'),api<Payout[]>('/api/v1/admin/payouts')]).then(([b,p])=>{setBatches(b);setPayouts(p)}).catch(x=>setError(x.message));useEffect(()=>{void load()},[]);async function action(path:string,body?:unknown){if(!confirm('Confirm this financial action?'))return;try{await api(path,{method:'POST',body:body===undefined?undefined:JSON.stringify(body)});setSelected(undefined);load()}catch(x){setError((x as Error).message)}}if(selected)return <section><button className="back" onClick={()=>setSelected(undefined)}>← Back</button><h2>{selected.publicBatchId}</h2><Badge value={selected.status}/><p>{selected.totalCreatorCount} creators · {money(selected.totalAmount)}</p><div className="actions"><button onClick={()=>action(`/api/v1/admin/payout-batches/${selected.id}/process`)}>Start processing</button><button className="danger" onClick={()=>action(`/api/v1/admin/payout-batches/${selected.id}/cancel`)}>Cancel batch</button></div></section>;return <section><div className="title"><h2>Weekly payout batches</h2><CreateBatch done={load}/></div>{error&&<p className="error">{error}</p>}{batches.length===0?<p className="empty">No payout batches.</p>:<div className="cards">{batches.map(x=><article key={x.id} onClick={()=>api<Batch>(`/api/v1/admin/payout-batches/${x.id}`).then(setSelected)}><Badge value={x.status}/><strong>{x.publicBatchId}</strong><p>{x.totalCreatorCount} creators · {money(x.totalAmount)}</p></article>)}</div>}<h2>Creator payout queue</h2>{payouts.length===0?<p className="empty">The queue is empty.</p>:payouts.map(x=><article className="panel" key={x.id}><Badge value={x.status}/><strong>{x.publicPayoutId} · {money(x.amount)}</strong><div className="actions">{['Scheduled','Processing'].includes(x.status)&&<button onClick={()=>action(`/api/v1/admin/payouts/${x.id}/submit`,{providerReference:prompt('Safe external reference (optional)')})}>Submit</button>}{x.status==='Submitted'&&<><button onClick={()=>action(`/api/v1/admin/payouts/${x.id}/mark-paid`)}>Mark paid</button><button className="danger" onClick={()=>action(`/api/v1/admin/payouts/${x.id}/mark-failed`,{reason:prompt('Failure reason')})}>Mark failed</button></>}{x.status==='Failed'&&<button onClick={()=>action(`/api/v1/admin/payouts/${x.id}/retry`)}>Retry</button>}{['Scheduled','Processing'].includes(x.status)&&<button className="quiet" onClick={()=>action(`/api/v1/admin/payouts/${x.id}/cancel`)}>Cancel</button>}</div></article>)}</section>}
function CreateBatch({done}:{done:()=>void}){const[open,setOpen]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),cutoff=new Date(String(f.get('cutoff'))),scheduled=new Date(String(f.get('scheduled')));await api('/api/v1/admin/payout-batches',{method:'POST',body:JSON.stringify({cutoffAtUtc:cutoff.toISOString(),scheduledForUtc:scheduled.toISOString(),currencyCode:'ETB',idempotencyKey:crypto.randomUUID()})});setOpen(false);done()}return open?<form className="inline-form" onSubmit={submit}><input name="cutoff" type="datetime-local" required/><input name="scheduled" type="datetime-local" required/><button>Create</button></form>:<button onClick={()=>setOpen(true)}>Create batch</button>}
