import {StrictMode,FormEvent,useEffect,useState,Component,ReactNode} from 'react'
import {createRoot} from 'react-dom/client'
import './styles.css'
import {PartnershipWorkspace} from './PartnershipWorkspace'
import {CreatorQrWorkspace,MerchantQrWorkspace} from './QrWorkspace'
import {CommissionWorkspace} from './CommissionWorkspace'
import {AdminDepositWorkspace,MerchantWalletWorkspace} from './WalletWorkspace'
import {AdminPayoutWorkspace,CreatorEarningsWorkspace} from './EarningsWorkspace'
import {NotificationCenter,NotificationOperations} from './NotificationWorkspace'
import {AdminRiskWorkspace,DisputeWorkspace} from './RiskWorkspace'
import {CashierCheckoutWorkspace} from './CashierCheckoutWorkspace'
import {AdminPortal} from './AdminPortal'
import {ReportingWorkspace} from './ReportingWorkspace'
import {CreatorCampaignWorkspace,MerchantCampaignWorkspace} from './CampaignWorkspace'
import {CustomerWorkspace,ShopperOfferPage} from './CustomerWorkspace'
import {AuthWorkspace} from './AuthWorkspace'
import {brand} from './brand'
import {MerchantWorkspace} from './MerchantWorkspace'
import {clearAuthState,isWorkspacePathAllowed,workspaceRoute} from './authSession'
import {OnboardingStatus} from './OnboardingStatus'

type Location={id:string;name:string;addressLine1:string;addressLine2?:string;city:string;region?:string;countryCode:string;timeZoneId:string;isActive:boolean}
type StaffLocation={id:string;name:string;isActive:boolean;isPrimary:boolean}
type Staff={id:string;firstName:string;lastName:string;email:string;phoneNumber:string;isActive:boolean;locations:StaffLocation[]}
type User={role:string;status?:string;merchantId?:string}
const strings={en:{locations:'Locations',supervisors:'Supervisors',cashiers:'Cashiers',profile:'My profile',assigned:'Assigned locations',empty:'Nothing here yet.',loading:'Loading…',save:'Save',invite:'Send invitation'}}
const t=strings.en
const token=()=>localStorage.getItem('creatorpay_access_token')??''
const apiBase=(import.meta.env.VITE_API_URL??'').replace(/\/$/,'')
function claims():User{try{const value=JSON.parse(atob(token().split('.')[1].replace(/-/g,'+').replace(/_/g,'/')));return{role:value['http://schemas.microsoft.com/ws/2008/06/identity/claims/role']??value.role,status:value.account_status,merchantId:value.merchant_id}}catch{return{role:''}}}
async function refreshAccess(){const refreshToken=localStorage.getItem('creatorpay_refresh_token');if(!refreshToken)return false;const response=await fetch(`${apiBase}/api/v1/auth/refresh`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refreshToken})});if(!response.ok)return false;const value=await response.json();localStorage.setItem('creatorpay_access_token',value.accessToken);localStorage.setItem('creatorpay_refresh_token',value.refreshToken);return true}
async function api<T>(path:string,init?:RequestInit,retry=true):Promise<T>{const response=await fetch(`${apiBase}${path}`,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()}`,...init?.headers}});if(response.status===401&&retry&&await refreshAccess())return api<T>(path,init,false);if(response.status===401){clearAuthState();location.assign('/')}if(!response.ok){const p=await response.json().catch(()=>({}));const correlation=p.correlationId??response.headers.get('X-Correlation-ID');throw new Error(`${p.detail??`Request failed (${response.status}).`}${response.status>=500&&correlation?` Support ID: ${correlation}`:''}`)}return response.status===204?undefined as T:response.json()}
async function signOut(){const refreshToken=localStorage.getItem('creatorpay_refresh_token');try{if(refreshToken)await fetch(`${apiBase}/api/v1/auth/logout`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refreshToken})})}finally{clearAuthState();location.assign('/')}}
const SignOutButton=()=> <button className="quiet" onClick={()=>void signOut()}>Sign out</button>

class ErrorBoundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true}}render(){return this.state.failed?<main className="auth"><section className="panel"><h1>Something went wrong</h1><p>Reload the page. If the issue continues, contact support.</p></section></main>:this.props.children}}

function LocationForm({value,onDone}:{value?:Location;onDone:()=>void}){const[f,setF]=useState({name:value?.name??'',addressLine1:value?.addressLine1??'',addressLine2:value?.addressLine2??'',city:value?.city??'',region:value?.region??'',countryCode:value?.countryCode??'ET',timeZoneId:value?.timeZoneId??Intl.DateTimeFormat().resolvedOptions().timeZone});const[error,setError]=useState('');async function submit(e:FormEvent){e.preventDefault();setError('');try{await api(value?`/api/v1/merchant/locations/${value.id}`:'/api/v1/merchant/locations',{method:value?'PUT':'POST',body:JSON.stringify(f)});onDone()}catch(x){setError((x as Error).message)}}return <form onSubmit={submit} className="panel form"><h2>{value?'Edit':'Create'} location</h2>{Object.entries(f).map(([key,val])=><label key={key}>{key.replace(/([A-Z])/g,' $1')}<input required={!['addressLine2','region'].includes(key)} value={val} onChange={e=>setF({...f,[key]:e.target.value})}/></label>)}{error&&<p className="error">{error}</p>}<button>{t.save}</button></form>}
function Locations(){const[items,setItems]=useState<Location[]|null>(null);const[editing,setEditing]=useState<Location|undefined>();const[creating,setCreating]=useState(false);const[error,setError]=useState('');const load=()=>api<Location[]>('/api/v1/merchant/locations').then(setItems).catch(e=>setError(e.message));useEffect(()=>{void load()},[]);async function status(x:Location){await api(`/api/v1/merchant/locations/${x.id}/status`,{method:'PATCH',body:JSON.stringify({isActive:!x.isActive})});load()}if(creating||editing)return <LocationForm value={editing} onDone={()=>{setCreating(false);setEditing(undefined);load()}}/>;return <section><div className="title"><h2>{t.locations}</h2><button onClick={()=>setCreating(true)}>New location</button></div>{error&&<p className="error">{error}</p>}{!items?<p>{t.loading}</p>:items.length===0?<p className="empty">{t.empty}</p>:<div className="cards">{items.map(x=><article key={x.id}><span>{x.isActive?'Active':'Inactive'}</span><strong>{x.name}</strong><p>{x.addressLine1}, {x.city}</p><div><button onClick={()=>setEditing(x)}>Edit</button><button className="quiet" onClick={()=>status(x)}>{x.isActive?'Deactivate':'Activate'}</button></div></article>)}</div>}</section>}
function StaffArea({kind}:{kind:'supervisors'|'cashiers'}){const[items,setItems]=useState<Staff[]|null>(null);const[locations,setLocations]=useState<Location[]>([]);const[selected,setSelected]=useState<Staff>();const[invite,setInvite]=useState(false);const[message,setMessage]=useState('');const load=()=>api<Staff[]>(`/api/v1/merchant/${kind}`).then(setItems).catch(e=>setMessage(e.message));useEffect(()=>{load();api<Location[]>('/api/v1/merchant/locations').then(setLocations)},[kind]);if(invite)return <Invite kind={kind} locations={locations} done={(m)=>{setInvite(false);setMessage(m);load()}}/>;if(selected)return <StaffDetail kind={kind} staff={selected} locations={locations} done={()=>{setSelected(undefined);load()}}/>;return <section><div className="title"><h2>{kind==='cashiers'?t.cashiers:t.supervisors}</h2><button onClick={()=>setInvite(true)}>Invite {kind.slice(0,-1)}</button></div>{message&&<aside>{message}</aside>}{!items?<p>{t.loading}</p>:items.length===0?<p className="empty">{t.empty}</p>:<div className="cards">{items.map(x=><article key={x.id} onClick={()=>setSelected(x)}><span>{x.isActive?'Active':'Invited / inactive'}</span><strong>{x.firstName} {x.lastName}</strong><p>{x.email}<br/>{x.locations.length} location(s)</p></article>)}</div>}</section>}
function Invite({kind,locations,done}:{kind:string;locations:Location[];done:(m:string)=>void}){const[f,setF]=useState({firstName:'',lastName:'',email:'',phoneNumber:'',locationIds:[] as string[]});const[error,setError]=useState('');async function submit(e:FormEvent){e.preventDefault();try{const result=await api<{developmentToken?:string}>(`/api/v1/merchant/${kind}/invitations`,{method:'POST',body:JSON.stringify(f)});done(result.developmentToken?`Development invitation token (shown once): ${result.developmentToken}`:'Invitation created.') }catch(x){setError((x as Error).message)}}return <form className="panel form" onSubmit={submit}><h2>Invite {kind.slice(0,-1)}</h2>{['firstName','lastName','email','phoneNumber'].map(k=><label key={k}>{k.replace(/([A-Z])/g,' $1')}<input type={k==='email'?'email':'text'} required value={f[k as keyof typeof f] as string} onChange={e=>setF({...f,[k]:e.target.value})}/></label>)}<fieldset><legend>Initial locations</legend>{locations.filter(x=>x.isActive).map(x=><label className="check" key={x.id}><input type="checkbox" checked={f.locationIds.includes(x.id)} onChange={e=>setF({...f,locationIds:e.target.checked?[...f.locationIds,x.id]:f.locationIds.filter(id=>id!==x.id)})}/>{x.name}</label>)}</fieldset>{error&&<p className="error">{error}</p>}<button>{t.invite}</button></form>}
function StaffDetail({kind,staff,locations,done}:{kind:string;staff:Staff;locations:Location[];done:()=>void}){const[ids,setIds]=useState(staff.locations.map(x=>x.id));const[primary,setPrimary]=useState(staff.locations.find(x=>x.isPrimary)?.id??'');const[error,setError]=useState('');async function save(){try{await api(`/api/v1/merchant/${kind}/${staff.id}/locations`,{method:'PUT',body:JSON.stringify(kind==='cashiers'?{locationIds:ids,primaryLocationId:primary||null}:{locationIds:ids})});done()}catch(x){setError((x as Error).message)}}async function status(){await api(`/api/v1/merchant/${kind}/${staff.id}/status`,{method:'PATCH',body:JSON.stringify({isActive:!staff.isActive})});done()}return <section className="panel"><button className="back" onClick={done}>← Back</button><h2>{staff.firstName} {staff.lastName}</h2><p>{staff.email} · {staff.phoneNumber}</p><h3>Location assignments</h3>{locations.filter(x=>x.isActive).map(x=><div className="assignment" key={x.id}><label className="check"><input type="checkbox" checked={ids.includes(x.id)} onChange={e=>setIds(e.target.checked?[...ids,x.id]:ids.filter(id=>id!==x.id))}/>{x.name}</label>{kind==='cashiers'&&ids.includes(x.id)&&<label className="check"><input type="radio" name="primary" checked={primary===x.id} onChange={()=>setPrimary(x.id)}/>Primary</label>}</div>)}{error&&<p className="error">{error}</p>}<div className="actions"><button onClick={save}>{t.save}</button><button className="danger" onClick={status}>{staff.isActive?'Deactivate':'Activate'}</button></div></section>}
function AcceptInvitation(){const[f,setF]=useState({token:new URLSearchParams(location.search).get('token')??'',password:'',confirmation:''});const[message,setMessage]=useState('');async function submit(e:FormEvent){e.preventDefault();try{await api('/api/v1/staff-invitations/accept',{method:'POST',body:JSON.stringify(f),headers:{Authorization:''}});setMessage('Invitation accepted. You can now sign in.')}catch(x){setMessage((x as Error).message)}}return <main className="auth"><form className="panel form" onSubmit={submit}><p className="eyebrow">Weymela staff</p><h1>Accept invitation</h1><label>Invitation token<input required value={f.token} onChange={e=>setF({...f,token:e.target.value})}/></label><label>Password<input type="password" required value={f.password} onChange={e=>setF({...f,password:e.target.value})}/></label><label>Confirm password<input type="password" required value={f.confirmation} onChange={e=>setF({...f,confirmation:e.target.value})}/></label><button>Activate account</button>{message&&<aside>{message}</aside>}</form></main>}
function StaffHome({role}:{role:'supervisor'|'cashier'}){const[data,setData]=useState<Staff>();const[error,setError]=useState('');useEffect(()=>{api<Staff>(`/api/v1/${role}/me`).then(setData).catch(e=>setError(e.message))},[role]);return <section><h2>{t.profile}</h2>{error&&<p className="error">{error}</p>}{!data?<p>{t.loading}</p>:<div className="panel"><h3>{data.firstName} {data.lastName}</h3><p>{data.email}<br/>{data.phoneNumber}</p><h3>{t.assigned}</h3>{data.locations.length?data.locations.map(x=><p key={x.id}>{x.name}{x.isPrimary?' · Primary':''}</p>):<p>{t.empty}</p>}</div>}</section>}
function App(){const user=claims();if(user.role==='Supervisor'||user.role==='Cashier')return <main className="app"><header><div><p className="eyebrow">{brand.productName}</p><h1>{user.role==='Cashier'?'Cashier checkout workspace':'Supervisor workspace'}</h1></div><SignOutButton/></header><NotificationCenter/><StaffHome role={user.role.toLowerCase() as 'supervisor'|'cashier'}/><MerchantQrWorkspace role={user.role}/>{user.role==='Cashier'&&<CashierCheckoutWorkspace/>}</main>;const creator=user.role==='Creator',active=user.status==='Active';return <main className="app"><a className="skip" href="#workspace-content">Skip to content</a><header><div><p className="eyebrow">{brand.productName}</p><h1>{creator?'Creator workspace':'Business Owner workspace'}</h1></div><SignOutButton/></header><div id="workspace-content" tabIndex={-1}>{!active?<OnboardingStatus role={creator?'Creator':'MerchantAdmin'}/>:creator?<><OnboardingStatus role="Creator"/><ReportingWorkspace/><NotificationCenter/><DisputeWorkspace scope="creator"/><CreatorCampaignWorkspace/><CreatorEarningsWorkspace/><CreatorQrWorkspace/><PartnershipWorkspace merchant={false}/></>:<><MerchantWorkspace/><ReportingWorkspace/><NotificationCenter/><DisputeWorkspace scope="merchant"/><MerchantCampaignWorkspace/><MerchantWalletWorkspace/><MerchantQrWorkspace role="MerchantAdmin"/><PartnershipWorkspace merchant/><CommissionWorkspace role={user.role}/></>}</div></main>}
function Root(){if(location.pathname.includes('/staff-invitations/accept'))return <AcceptInvitation/>;const offerCode=location.pathname.match(/^\/(?:offers|o)\/([^/]+)/)?.[1];if(offerCode)return <ShopperOfferPage code={decodeURIComponent(offerCode)}/>;const user=claims();if(!user.role)return <AuthWorkspace/>;if(!isWorkspacePathAllowed(user.role,location.pathname)){location.replace(workspaceRoute(user.role));return null}if(user.role==='Customer')return <main className="app"><header><div><p className="eyebrow">{brand.productName}</p><h1>Shopper workspace</h1></div><SignOutButton/></header>{user.status==='Active'?<><NotificationCenter/><CustomerWorkspace/></>:<OnboardingStatus role="Customer"/>}</main>;return user.role==='PlatformAdmin'?<AdminPortal operations={{commission:<CommissionWorkspace role={user.role}/>,deposits:<AdminDepositWorkspace/>,payouts:<AdminPayoutWorkspace/>,notifications:<NotificationOperations/>,fraud:<AdminRiskWorkspace/>,disputes:<AdminRiskWorkspace/>,reversals:<AdminRiskWorkspace/>}}/>:<App/>}
createRoot(document.getElementById('root')!).render(<StrictMode><ErrorBoundary><Root/></ErrorBoundary></StrictMode>)
if('serviceWorker'in navigator)window.addEventListener('load',()=>{if(import.meta.env.DEV){void Promise.all([navigator.serviceWorker.getRegistrations().then(registrations=>Promise.all(registrations.map(registration=>registration.unregister()))),'caches'in window?caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith('creatorpay-shell-')).map(key=>caches.delete(key)))):Promise.resolve([])]);return}void navigator.serviceWorker.register('/sw.js').then(reg=>{reg.addEventListener('updatefound',()=>{const worker=reg.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)dispatchEvent(new CustomEvent('creatorpay-update-ready'))})})}).catch(()=>{})})
