import{FormEvent,useEffect,useState}from'react'
import{api}from'./apiClient'
import{AccountStatusBadge}from'./AccountChrome'

type FileMetadata={fileName:string;contentType:string;sizeBytes:number}
type DocumentMetadata=FileMetadata&{documentType:string}
type Profile={legalBusinessName:string;tradingName:string;businessType:string;primaryContactName:string;taxRegistrationNumber?:string;phoneNumber:string;email:string;businessAddress:string;city:string;region:string;country:string;timeZone:string;effectiveStatus:string;logo?:FileMetadata;documents:DocumentMetadata[]}

export function MerchantWorkspace(){
 const[profile,setProfile]=useState<Profile>(),[error,setError]=useState(''),[message,setMessage]=useState(''),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false)
 const load=()=>api<Profile>('/api/v1/merchants/me').then(value=>{setProfile(value);setError('')}).catch(error=>{console.error(error);setError('This section is temporarily unavailable.')})
 useEffect(()=>{void load()},[])
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!profile||busy)return;const form=new FormData(event.currentTarget);setBusy(true);setMessage('');try{await api('/api/v1/merchants/me',{method:'PUT',body:JSON.stringify({legalBusinessName:form.get('legalBusinessName'),tradingName:form.get('tradingName'),businessType:profile.businessType,taxRegistrationNumber:profile.taxRegistrationNumber??null,phoneNumber:profile.phoneNumber,email:profile.email,businessAddress:form.get('businessAddress'),city:form.get('city'),region:form.get('region'),country:profile.country,timeZone:profile.timeZone,logo:profile.logo??null,documents:profile.documents})});await load();setEditing(false);setMessage('Business profile updated.')}catch(error){setMessage((error as Error).message)}finally{setBusy(false)}}
 if(!profile)return error?<section className="creator-section" role="alert"><h2>Profile</h2><p className="friendly-error">{error}</p></section>:<p>Loading profile…</p>
 return <section className="creator-section business-profile product-workspace" aria-labelledby="business-profile"><div className="product-title"><h2 id="business-profile">Profile</h2><button className="quiet" onClick={()=>setEditing(!editing)}>{editing?'Cancel':'Edit Profile'}</button></div>{error&&<p className="friendly-error" role="alert">{error}</p>}{message&&<p className="product-message" role="status">{message}</p>}{editing?<form className="compact-panel product-form" onSubmit={save}><label>Legal business name<input name="legalBusinessName" required defaultValue={profile.legalBusinessName}/></label><label>Business name<input name="tradingName" required defaultValue={profile.tradingName}/></label><label>Address<input name="businessAddress" required defaultValue={profile.businessAddress}/></label><label>City<input name="city" required defaultValue={profile.city}/></label><label>Region<input name="region" required defaultValue={profile.region}/></label><div className="actions"><button disabled={busy}>{busy?'Saving…':'Save Profile'}</button><button type="button" className="quiet" onClick={()=>setEditing(false)}>Cancel</button></div></form>:<div className="compact-panel profile-details"><dl><div><dt>Business Name</dt><dd><strong>{profile.tradingName}</strong></dd></div><div><dt>Business Type</dt><dd>{profile.businessType}</dd></div><div><dt>Primary Contact</dt><dd>{profile.primaryContactName}</dd></div><div><dt>Account phone</dt><dd>{profile.phoneNumber}</dd></div><div><dt>Account email</dt><dd>{profile.email||'No email provided'}</dd></div><div><dt>Address</dt><dd>{profile.businessAddress}</dd></div><div><dt>Primary City</dt><dd>{profile.city}</dd></div><div><dt>Status</dt><dd><AccountStatusBadge status={profile.effectiveStatus}/></dd></div></dl><small>Account email and phone are managed through Weymela account security.</small></div>}</section>
}
