import {useEffect,useState} from 'react'
import {businessTypes} from './AuthWorkspace'
import {api,statusLabel} from './apiClient'

type FileMetadata={fileName:string;contentType:string;sizeBytes:number}
type DocumentMetadata=FileMetadata&{documentType:string}
type Profile={publicMerchantId:string;legalBusinessName:string;tradingName:string;businessType:string;primaryContactName:string;taxRegistrationNumber?:string;phoneNumber:string;email:string;businessAddress:string;city:string;region:string;country:string;timeZone:string;merchantStatus:string;accountStatus:string;registrationProgress:number;nextStep:string;isEmailVerified:boolean;isPhoneVerified:boolean;logo?:FileMetadata;documents:DocumentMetadata[]}
export function MerchantWorkspace(){
 const[profile,setProfile]=useState<Profile>(),[error,setError]=useState(''),[businessType,setBusinessType]=useState(''),[saving,setSaving]=useState(false)
 useEffect(()=>{void api<Profile>('/api/v1/merchants/me').then(p=>{setProfile(p);setBusinessType(p.businessType)}).catch(e=>{console.error(e);setError('This section is temporarily unavailable.')})},[])
 if(!profile)return error?<section className="creator-section" role="alert"><h2>Profile</h2><p className="friendly-error">{error}</p></section>:<p>Loading profile…</p>
 const saveBusinessType=async()=>{setSaving(true);setError('');try{const updated=await api<Profile>('/api/v1/merchants/me',{method:'PUT',body:JSON.stringify({legalBusinessName:profile.legalBusinessName,tradingName:profile.tradingName,businessType,taxRegistrationNumber:profile.taxRegistrationNumber??null,phoneNumber:profile.phoneNumber,email:profile.email,businessAddress:profile.businessAddress,city:profile.city,region:profile.region,country:profile.country,timeZone:profile.timeZone,logo:profile.logo??null,documents:profile.documents??[]})});setProfile(updated);setBusinessType(updated.businessType)}catch(e){console.error(e);setError('This section is temporarily unavailable.')}finally{setSaving(false)}}
 return <section className="creator-section" aria-labelledby="business-profile"><h2 id="business-profile">Profile</h2>{error&&<p className="friendly-error" role="alert">{error}</p>}<div className="compact-panel profile-details"><strong>{profile.tradingName}</strong><dl><div><dt>Business Type</dt><dd>{profile.businessType}</dd></div><div><dt>Primary Contact</dt><dd>{profile.primaryContactName}</dd></div><div><dt>Phone</dt><dd>{profile.phoneNumber}</dd></div><div><dt>Email</dt><dd>{profile.email||'No email provided'}</dd></div><div><dt>Address</dt><dd>{profile.businessAddress}</dd></div><div><dt>Primary City</dt><dd>{profile.city}</dd></div><div><dt>Business ID</dt><dd>{profile.publicMerchantId}</dd></div><div><dt>Status</dt><dd><span className="status-badge">{statusLabel(profile.merchantStatus)}</span></dd></div></dl><label>Business Type<select required value={businessType} onChange={e=>setBusinessType(e.target.value)}>{!businessTypes.some(x=>x.value===businessType)&&businessType&&<option value={businessType}>{businessType} (legacy value)</option>}{businessTypes.map(x=><option key={x.value} value={x.value}>{x.en}</option>)}</select></label><button type="button" disabled={saving||!businessType||businessType===profile.businessType} onClick={saveBusinessType}>{saving?'Saving…':'Save Business Type'}</button></div></section>
}
