import {useEffect,useState} from 'react'
import {brand} from './brand'
type Profile={tradingName:string;merchantStatus:string;accountStatus:string;registrationProgress:number;nextStep:string;isEmailVerified:boolean;isPhoneVerified:boolean;logo?:{fileName:string}}
type Wallet={availableBalance:number;status:string;currencyCode:string}
type Trial={maximumTransactions:number;confirmedTransactionCount:number;maximumCommissionAmount:number;commissionConsumed:number;status:string}
type Location={id:string;isActive:boolean}
type Cashier={id:string;isActive:boolean}
const root=(import.meta.env.VITE_API_URL??'').replace(/\/$/,'');const token=()=>localStorage.getItem('creatorpay_access_token')??''
async function get<T>(path:string):Promise<T>{const r=await fetch(`${root}${path}`,{headers:{Authorization:`Bearer ${token()}`}});const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b.detail??`Request failed (${r.status}).`);return b}
export function MerchantWorkspace(){const[profile,setProfile]=useState<Profile>(),[wallet,setWallet]=useState<Wallet>(),[trial,setTrial]=useState<Trial>(),[locations,setLocations]=useState<Location[]>([]),[cashiers,setCashiers]=useState<Cashier[]>([]),[error,setError]=useState('');useEffect(()=>{Promise.all([get<Profile>('/api/v1/merchants/me'),get<Location[]>('/api/v1/merchant/locations'),get<Cashier[]>('/api/v1/merchant/cashiers')]).then(([p,l,c])=>{setProfile(p);setLocations(l);setCashiers(c)}).catch(e=>setError(e.message));get<Wallet>('/api/v1/merchant/wallet').then(setWallet).catch(()=>{});get<Trial>('/api/v1/merchant/trial-credit').then(setTrial).catch(()=>{})},[])
 if(error)return <section className="panel" role="alert"><h2>Merchant status</h2><p className="error">{error}</p></section>;if(!profile)return <p>Loading merchant dashboard...</p>
 const funding=wallet?.status??(profile.merchantStatus==='Active'?'Funding status unavailable':'Not available until approval');return <section aria-labelledby="merchant-dashboard"><div className="title"><div><p className="eyebrow">{brand.productName} merchant</p><h2 id="merchant-dashboard">{profile.tradingName}</h2></div><span className="status">{profile.merchantStatus}</span></div>{profile.merchantStatus!=='Active'&&<aside role="status"><strong>Next step:</strong> {profile.nextStep}</aside>}{wallet?.status==='LowBalance'&&<p className="offline-warning">Low balance. Add pilot funding before the wallet becomes restricted.</p>}{wallet?.status==='FundingRequired'&&<p className="offline-warning">Funding Required. Financial checkout remains unavailable.</p>}<div className="summary-grid"><article className="summary-card"><span>Trial status</span><strong>{trial?.status??'Not started'}</strong><small>{trial?`${trial.confirmedTransactionCount}/${trial.maximumTransactions} transactions · ${trial.commissionConsumed}/${trial.maximumCommissionAmount} ${brand.currency}`:'Available after approval'}</small></article><article className="summary-card"><span>Funding status</span><strong>{funding}</strong><small>Wallet projection: {wallet?.availableBalance??0} {wallet?.currencyCode??brand.currency}</small></article><article className="summary-card"><span>Locations</span><strong>{locations.filter(x=>x.isActive).length}</strong><small>{locations.length} total</small></article><article className="summary-card"><span>Cashiers</span><strong>{cashiers.filter(x=>x.isActive).length}</strong><small>{cashiers.length} invited or created</small></article></div><div className="panel"><h3>Registration status</h3><progress value={profile.registrationProgress} max="100" aria-label="Registration progress"/><p>{profile.registrationProgress}% complete · Email {profile.isEmailVerified?'verified':'not verified'} · Phone {profile.isPhoneVerified?'verified':'not verified'}</p><p>Campaigns, creator requests, featured creator, and recent transactions appear in their workspaces below when available.</p></div></section>}
