import {useEffect,useState} from 'react'

const token=()=>localStorage.getItem('creatorpay_access_token')??''
async function api<T>(path:string,init?:RequestInit):Promise<T>{const r=await fetch(path,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()}`,...init?.headers}});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).detail??`Request failed (${r.status}).`);return r.status===204?undefined as T:r.json()}
type Notice={notificationId:string;type:string;title:string;body:string;priority:string;status:string;createdAtUtc:string;readAtUtc?:string}
type Preference={notificationType:string;inAppEnabled:boolean;emailEnabled:boolean;smsEnabled:boolean;pushEnabled:boolean;languageCode:string;isMandatory:boolean}
export function NotificationCenter(){const[items,setItems]=useState<Notice[]|null>(null),[count,setCount]=useState(0),[error,setError]=useState(''),[filter,setFilter]=useState('');const load=()=>{api<{items:Notice[]}>(`/api/v1/notifications?page=1&pageSize=50${filter?`&notificationType=${filter}`:''}`).then(x=>setItems(x.items)).catch(e=>setError(e.message));api<{count:number}>('/api/v1/notifications/unread-count').then(x=>setCount(x.count))};useEffect(load,[filter]);async function read(id:string){await api(`/api/v1/notifications/${id}/read`,{method:'POST'});load()}return <section><div className="title"><h2>Notifications <span className="badge">{count} unread</span></h2><button className="quiet" onClick={async()=>{await api('/api/v1/notifications/read-all',{method:'POST'});load()}}>Mark all read</button></div><label>Filter by type<input value={filter} placeholder="e.g. PayoutPaid" onChange={e=>setFilter(e.target.value)}/></label>{error&&<p className="error">{error}</p>}{!items?<p>Loading…</p>:items.length===0?<p className="empty">No notifications match this filter.</p>:<div className="cards">{items.map(x=><article key={x.notificationId} className={x.readAtUtc?'':'unread'}><span>{x.type} · {x.status} · {x.priority}</span><strong>{x.title}</strong><p>{x.body}</p><small>{new Date(x.createdAtUtc).toLocaleString()}</small>{!x.readAtUtc&&<button onClick={()=>read(x.notificationId)}>Mark read</button>}</article>)}</div>}<NotificationPreferences/></section>}
function NotificationPreferences(){const[items,setItems]=useState<Preference[]|null>(null),[message,setMessage]=useState('');useEffect(()=>{api<Preference[]>('/api/v1/notification-preferences').then(setItems)},[]);if(!items)return <p>Loading preferences…</p>;async function save(){await api('/api/v1/notification-preferences',{method:'PUT',body:JSON.stringify(items)});setMessage('Preferences saved.')}return <div className="panel"><h3>Notification preferences</h3>{items.map((x,i)=><div className="assignment" key={x.notificationType}><strong>{x.notificationType}</strong>{(['inAppEnabled','emailEnabled','smsEnabled','pushEnabled'] as const).map(k=><label className="check" key={k}><input type="checkbox" disabled={x.isMandatory&&k==='inAppEnabled'} checked={x[k]} onChange={e=>setItems(items.map((p,j)=>j===i?{...p,[k]:e.target.checked}:p))}/>{k.replace('Enabled','')}</label>)}</div>)}<button onClick={save}>Save preferences</button>{message&&<aside>{message}</aside>}</div>}
type Outbox={id:string;status:string;attemptCount:number;availableAtUtc:string;lastError?:string}
type Dead={id:string;outboxMessageId:string;status:string;reason:string;deadLetteredAtUtc:string}
type Template={id:string;notificationType:string;channel:string;languageCode:string;versionNumber:number;isActive:boolean}
export function NotificationOperations(){const[outbox,setOutbox]=useState<Outbox[]>([]),[dead,setDead]=useState<Dead[]>([]),[templates,setTemplates]=useState<Template[]>([]),[error,setError]=useState('');const load=()=>Promise.all([api<Outbox[]>('/api/v1/admin/notification-outbox').then(setOutbox),api<Dead[]>('/api/v1/admin/notification-dead-letters').then(setDead),api<Template[]>('/api/v1/admin/notification-templates').then(setTemplates)]).catch(e=>setError(e.message));useEffect(()=>{void load()},[]);async function action(path:string){await api(path,{method:'POST'});load()}return <section><h2>Notification operations</h2>{error&&<p className="error">{error}</p>}<div className="panel"><h3>Outbox</h3>{outbox.length===0?<p className="empty">Outbox is empty.</p>:outbox.map(x=><div className="assignment" key={x.id}><span>{x.status} · attempt {x.attemptCount}</span><small>{x.lastError}</small><button onClick={()=>action(`/api/v1/admin/notification-outbox/${x.id}/retry`)}>Retry</button><button className="danger" onClick={()=>action(`/api/v1/admin/notification-outbox/${x.id}/cancel`)}>Cancel</button></div>)}</div><div className="panel"><h3>Dead letters</h3>{dead.length===0?<p className="empty">No dead letters.</p>:dead.map(x=><div className="assignment" key={x.id}><span>{x.status} · {x.reason}</span><button onClick={()=>action(`/api/v1/admin/notification-dead-letters/${x.id}/retry`)}>Retry</button><button onClick={()=>action(`/api/v1/admin/notification-dead-letters/${x.id}/resolve`)}>Resolve</button></div>)}</div><div className="panel"><h3>Templates</h3>{templates.length===0?<p className="empty">No templates configured; safe notification content is used.</p>:templates.map(x=><div className="assignment" key={x.id}><span>{x.notificationType} · {x.channel} · {x.languageCode} · v{x.versionNumber}</span><span>{x.isActive?'Active':'Inactive'}</span></div>)}</div></section>}
