export type OfflineOperationStatus='Draft'|'Queued'|'Synchronizing'|'Confirmed'|'ApprovalRequired'|'Rejected'|'Conflict'|'Expired'|'Cancelled'|'FailedRetryable'|'FailedPermanent'
export type OfflinePurchaseOperation={localOperationId:string;idempotencyKey:string;clientOperationId:string;createdAtLocal:string;createdAtUtc:string;cashierUserId:string;merchantId:string;merchantLocationId:string;qrPayloadEncrypted:string;customerPhoneEncrypted:string;maskedPhone:string;purchaseAmount:number;currencyCode:string;status:OfflineOperationStatus;retryCount:number;lastAttemptAtUtc?:string;lastErrorCode?:string;lastErrorMessage?:string;serverTransactionId?:string;publicTransactionId?:string;serverApprovalRequestId?:string;correlationId?:string;appVersion:string;schemaVersion:number;completedAtUtc?:string}
const DB='creatorpay-offline-v1',STORE='purchase-operations',KEYS='crypto-keys',VERSION=1
function request<T>(r:IDBRequest<T>){return new Promise<T>((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function db(){return new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE)){const s=d.createObjectStore(STORE,{keyPath:'localOperationId'});s.createIndex('idempotencyKey','idempotencyKey',{unique:true});s.createIndex('statusCreated',['status','createdAtUtc'])}if(!d.objectStoreNames.contains(KEYS))d.createObjectStore(KEYS)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function key(){const d=await db(),tx=d.transaction(KEYS,'readwrite'),s=tx.objectStore(KEYS);let k=await request(s.get('payload-key')) as CryptoKey|undefined;if(!k){k=await crypto.subtle.generateKey({name:'AES-GCM',length:256},false,['encrypt','decrypt']);s.put(k,'payload-key')}return k}
const encode=(x:ArrayBuffer)=>btoa(String.fromCharCode(...new Uint8Array(x))),decode=(x:string)=>Uint8Array.from(atob(x),c=>c.charCodeAt(0))
export async function protect(value:string){const iv=crypto.getRandomValues(new Uint8Array(12)),body=await crypto.subtle.encrypt({name:'AES-GCM',iv},await key(),new TextEncoder().encode(value));return `${encode(iv.buffer)}.${encode(body)}`}
export async function reveal(value:string){const[iv,body]=value.split('.');return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:decode(iv)},await key(),decode(body)))}
export const maskPhone=(x:string)=>{const d=x.replace(/\D/g,'');return d.length<4?'••••':`••• ••• ${d.slice(-4)}`}
export class IndexedDbOfflineOperationStore{
 async put(x:OfflinePurchaseOperation){const d=await db();await request(d.transaction(STORE,'readwrite').objectStore(STORE).put(x))}
 async get(id:string){const d=await db();return request(d.transaction(STORE).objectStore(STORE).get(id)) as Promise<OfflinePurchaseOperation|undefined>}
 async list(){const d=await db();return (await request(d.transaction(STORE).objectStore(STORE).getAll()) as OfflinePurchaseOperation[]).sort((a,b)=>b.createdAtUtc.localeCompare(a.createdAtUtc))}
 async remove(id:string){const d=await db();await request(d.transaction(STORE,'readwrite').objectStore(STORE).delete(id))}
 async cleanup(days=7){const cutoff=Date.now()-days*86400000;for(const x of await this.list())if(x.completedAtUtc&&Date.parse(x.completedAtUtc)<cutoff)await this.remove(x.localOperationId)}
}
export const offlineStore=new IndexedDbOfflineOperationStore()
export function tokenClaims(){try{const token=sessionStorage.getItem('creatorpay_access_token')??localStorage.getItem('creatorpay_access_token')??'',p=JSON.parse(atob(token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/')));return{token,expires:Number(p.exp)*1000,userId:p['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier']??p.sub,merchantId:p.merchant_id,role:p['http://schemas.microsoft.com/ws/2008/06/identity/claims/role']??p.role}}catch{return{token:'',expires:0,userId:'',merchantId:'',role:''}}}
type ItemResult={clientOperationId:string;resultStatus:string;transactionId?:string;publicTransactionId?:string;approvalRequestId?:string;errorCode?:string;safeMessage:string;retryable:boolean;correlationId:string}
export async function syncQueue(onChange?:()=>void){if(!navigator.onLine)return;const auth=tokenClaims();if(auth.expires<=Date.now())throw new Error('Reauthentication is required before synchronization.');const queued=(await offlineStore.list()).filter(x=>['Queued','FailedRetryable'].includes(x.status)&&x.retryCount<8);for(let i=0;i<queued.length;i+=25){const group=queued.slice(i,i+25);for(const x of group){x.status='Synchronizing';x.lastAttemptAtUtc=new Date().toISOString();await offlineStore.put(x)}onChange?.();try{const operations=await Promise.all(group.map(async x=>({clientOperationId:x.clientOperationId,idempotencyKey:x.idempotencyKey,merchantLocationId:x.merchantLocationId,qrPayload:await reveal(x.qrPayloadEncrypted),customerPhoneNumber:await reveal(x.customerPhoneEncrypted),purchaseAmount:x.purchaseAmount,currencyCode:x.currencyCode,clientCreatedAtUtc:x.createdAtUtc})));const response=await fetch('/api/v1/cashier/offline-sync',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${auth.token}`},body:JSON.stringify({batchId:crypto.randomUUID(),appVersion:'17.0',schemaVersion:1,operations})});if(response.status===401)throw new Error('Reauthentication is required before synchronization.');if(response.status===429)throw new Error(`Rate limited. Retry later${response.headers.get('Retry-After')?` (${response.headers.get('Retry-After')} seconds)`:''}.`);if(!response.ok)throw new Error('Synchronization is temporarily unavailable.');const data=await response.json() as {results:ItemResult[]};for(const result of data.results){const x=group.find(v=>v.clientOperationId===result.clientOperationId)!;x.status=result.resultStatus==='DuplicateConfirmed'?'Confirmed':result.resultStatus==='RetryLater'?'FailedRetryable':result.resultStatus as OfflineOperationStatus;x.retryCount++;x.lastErrorCode=result.errorCode;x.lastErrorMessage=result.safeMessage;x.serverTransactionId=result.transactionId;x.publicTransactionId=result.publicTransactionId;x.serverApprovalRequestId=result.approvalRequestId;x.correlationId=result.correlationId;if(x.status==='Confirmed'){x.qrPayloadEncrypted='';x.customerPhoneEncrypted='';x.completedAtUtc=new Date().toISOString()}await offlineStore.put(x)}}catch(e){for(const x of group){x.status=(e as Error).message.startsWith('Reauthentication')?'Queued':'FailedRetryable';x.retryCount++;x.lastErrorMessage=(e as Error).message;await offlineStore.put(x)}throw e}finally{onChange?.()}}
}

export async function refreshApprovalRequired(){if(!navigator.onLine)return;for(const x of (await offlineStore.list()).filter(x=>x.status==='ApprovalRequired')){x.status='FailedRetryable';await offlineStore.put(x)}await syncQueue()}
