import {FormEvent,useEffect,useRef,useState} from 'react'

export type PilotRole='Shopper'|'Creator'|'Business Owner'|'Cashier'|'Supervisor'
type Locale='en'|'am'
type TourStep={title:string;body:string;help:string}
const base=(import.meta.env.VITE_API_URL??'').replace(/\/$/,'')
const token=()=>localStorage.getItem('creatorpay_access_token')??''

const copy={
 en:{online:'Back online. You can continue.',offline:'You are offline. Browsing may use saved information, but checkout and financial actions require a connection.',session:'Your session will expire soon.',stay:'Stay signed in',signout:'Sign out',welcome:'Welcome to Weymela',intro:'A quick tour will show you the safest way to use your workspace.',start:'Start tour',later:'Not now',next:'Next',back:'Back',done:'Finish',help:'Help',feedback:'Send pilot feedback',close:'Close',skip:'Skip tour',question:'What do you need help with?',helpCenter:'Open Help Center',feedbackTitle:'Pilot feedback',feedbackHint:'Do not include phone numbers, email addresses, payment details, or other personal information.',category:'Category',message:'What happened or what could be better?',send:'Send feedback',sent:'Thank you. Your feedback was sent to the pilot team.',required:'Enter at least 10 characters (maximum 2,000).',failed:'Feedback could not be sent. Try again when you are online.',survey:'How was this checkout?',surveyHelp:'Your rating helps improve the pilot. Do not include personal information.',submitRating:'Submit rating',surveyThanks:'Thanks for rating your checkout.'},
 am:{online:'እንደገና መስመር ላይ ነዎት። መቀጠል ይችላሉ።',offline:'ከመስመር ውጭ ነዎት። የተቀመጠ መረጃ ሊታይ ይችላል፤ ክፍያና የገንዘብ ተግባር ግን ኢንተርኔት ይፈልጋል።',session:'የመግቢያ ጊዜዎ በቅርቡ ያበቃል።',stay:'እንደገቡ ይቆዩ',signout:'ውጣ',welcome:'ወደ ወይመላ እንኳን ደህና መጡ',intro:'አጭር መመሪያ የስራ ቦታዎን በደህንነት እንዲጠቀሙ ያሳያል።',start:'መመሪያውን ጀምር',later:'በኋላ',next:'ቀጣይ',back:'ተመለስ',done:'ጨርስ',help:'እገዛ',feedback:'የሙከራ አስተያየት',close:'ዝጋ',skip:'መመሪያውን ዝለል',question:'በምን ልንረዳዎ?',helpCenter:'የእገዛ ማዕከል',feedbackTitle:'የሙከራ አስተያየት',feedbackHint:'ስልክ፣ ኢሜይል፣ የክፍያ መረጃ ወይም ሌላ የግል መረጃ አያስገቡ።',category:'ምድብ',message:'ምን ተከሰተ ወይም ምን ሊሻሻል ይችላል?',send:'አስተያየት ላክ',sent:'እናመሰግናለን። አስተያየትዎ ለሙከራ ቡድኑ ተልኳል።',required:'ቢያንስ 10 ፊደላት ያስገቡ (ከ2,000 አይበልጥ)።',failed:'አስተያየት አልተላከም። መስመር ላይ ሲሆኑ ይሞክሩ።',survey:'ይህ ግዢ እንዴት ነበር?',surveyHelp:'ደረጃዎ ሙከራውን ለማሻሻል ይረዳል። የግል መረጃ አያስገቡ።',submitRating:'ደረጃ ላክ',surveyThanks:'ግዢዎን ስለመዘኑ እናመሰግናለን።'}
}
const tours:Record<PilotRole,Record<Locale,TourStep[]>>={
 Shopper:{en:[{title:'Discover Offers',body:'Find a Creator, then choose an active Offer from a participating Business.',help:'Search works without location access.'},{title:'Use at checkout',body:'Show the temporary Offer QR to the Cashier before it expires.',help:'A QR is single-use and normally lasts about three minutes.'},{title:'Confirm and earn',body:'Review the Business and amount before approving. Cashback appears only after a completed checkout.',help:'Never approve an amount you do not recognize.'}],am:[{title:'ቅናሾችን ያግኙ',body:'ፈጣሪን ይፈልጉና ከተሳታፊ ንግድ ንቁ ቅናሽ ይምረጡ።',help:'ያለ አካባቢ ፈቃድ መፈለግ ይችላሉ።'},{title:'በክፍያ ጊዜ ይጠቀሙ',body:'ጊዜው ሳያበቃ ጊዜያዊ QR ለገንዘብ ተቀባዩ ያሳዩ።',help:'QR አንድ ጊዜ ብቻ ይሰራል።'},{title:'ያረጋግጡና ያግኙ',body:'ከማጽደቅዎ በፊት ንግዱንና መጠኑን ይመልከቱ።',help:'የማያውቁትን መጠን አያጽድቁ።'}]},
 Creator:{en:[{title:'Complete your profile',body:'Finish verification so Businesses can review your profile.',help:'Onboarding status shows the exact next step.'},{title:'Build partnerships',body:'Review partnership invitations and the Offer terms before accepting.',help:'Use Help for campaign and commission guidance.'},{title:'Share your QR',body:'Use an active Offer QR and monitor earnings and notifications.',help:'Never edit or reuse an expired QR payload.'}],am:[{title:'መገለጫዎን ያጠናቅቁ',body:'ንግዶች መገለጫዎን እንዲመለከቱ ማረጋገጫውን ያጠናቅቁ።',help:'የመመዝገብ ሁኔታ ቀጣዩን እርምጃ ያሳያል።'},{title:'አጋርነት ይገንቡ',body:'ከመቀበልዎ በፊት ግብዣና የቅናሽ ውሎችን ይመልከቱ።',help:'ስለ ዘመቻና ኮሚሽን እገዛን ይጠቀሙ።'},{title:'QR ያጋሩ',body:'ንቁ የቅናሽ QR ይጠቀሙና ገቢና ማሳወቂያዎችን ይከታተሉ።',help:'ጊዜው ያለፈ QR አይጠቀሙ።'}]},
 'Business Owner':{en:[{title:'Set up your Business',body:'Complete approval, locations, and staff assignments first.',help:'Only active assigned locations can process checkout.'},{title:'Create Offers',body:'Approve Creator partnerships and configure clear Offer terms.',help:'Review the Shopper reuse rule before publishing.'},{title:'Stay funded',body:'Monitor wallet, checkout, notifications, and reports from this dashboard.',help:'Low balance can restrict new checkouts.'}],am:[{title:'ንግድዎን ያዘጋጁ',body:'ማጽደቅ፣ ቦታዎችና የሰራተኛ ምደባን ያጠናቅቁ።',help:'ንቁና የተመደቡ ቦታዎች ብቻ ክፍያ ይቀበላሉ።'},{title:'ቅናሾችን ይፍጠሩ',body:'የፈጣሪ አጋርነትን ያጽድቁና ግልጽ ውሎችን ያዘጋጁ።',help:'ከማተምዎ በፊት የደንበኛ ዳግም አጠቃቀምን ይመልከቱ።'},{title:'በቂ ቀሪ ሂሳብ ይኑርዎት',body:'ቦርሳ፣ ክፍያ፣ ማሳወቂያና ሪፖርቶችን ይከታተሉ።',help:'ዝቅተኛ ቀሪ ሂሳብ አዲስ ክፍያን ሊገድብ ይችላል።'}]},
 Cashier:{en:[{title:'Check your location',body:'Confirm the assigned location before starting a checkout.',help:'Ask a Supervisor if the correct location is missing.'},{title:'Scan and verify',body:'Accept only a valid temporary Offer QR, then confirm the masked Shopper and amount.',help:'Financial actions require a live connection.'},{title:'Explain the result',body:'Wait for the final result and give the Shopper clear next steps.',help:'Do not repeatedly submit while a request is loading.'}],am:[{title:'ቦታዎን ያረጋግጡ',body:'ክፍያ ከመጀመርዎ በፊት የተመደበውን ቦታ ያረጋግጡ።',help:'ቦታው ከሌለ ሱፐርቫይዘርን ይጠይቁ።'},{title:'ይቃኙና ያረጋግጡ',body:'ትክክለኛ ጊዜያዊ QR ብቻ ይቀበሉ፤ የደንበኛና መጠን መረጃ ያረጋግጡ።',help:'የገንዘብ ተግባር ኢንተርኔት ይፈልጋል።'},{title:'ውጤቱን ያብራሩ',body:'የመጨረሻ ውጤት ይጠብቁና ለደንበኛው ቀጣዩን እርምጃ ይንገሩ።',help:'ጥያቄው ሲጫን ደጋግመው አይላኩ።'}]},
 Supervisor:{en:[{title:'Review assignments',body:'Confirm your active locations and support Cashiers on shift.',help:'A Business Owner manages location assignments.'},{title:'Handle exceptions',body:'Review the Shopper, Offer, amount, and reuse reason before approving an exception.',help:'Never bypass a financial validation.'},{title:'Escalate safely',body:'Use notifications, Help, and pilot feedback when an issue cannot be resolved.',help:'Include public references, never personal or payment data.'}],am:[{title:'ምደባዎችን ይመልከቱ',body:'ንቁ ቦታዎችን ያረጋግጡና ገንዘብ ተቀባዮችን ይርዱ።',help:'የንግድ ባለቤት የቦታ ምደባን ያስተዳድራል።'},{title:'ልዩ ሁኔታ ይመልከቱ',body:'ልዩ ፈቃድ ከመስጠትዎ በፊት ደንበኛ፣ ቅናሽ፣ መጠንና ምክንያት ይመልከቱ።',help:'የገንዘብ ማረጋገጫን አይዝለሉ።'},{title:'በደህንነት ያሳውቁ',body:'ችግሩ ካልተፈታ ማሳወቂያ፣ እገዛና የሙከራ አስተያየት ይጠቀሙ።',help:'የህዝብ ማጣቀሻ ብቻ ያስገቡ።'}]}
}

export function trackUx(event:string,context:Record<string,string|number|boolean>={}){window.dispatchEvent(new CustomEvent('weymela:ux',{detail:{event,context,timestamp:new Date().toISOString()}}))}
export function showToast(message:string,tone:'success'|'error'|'info'='info'){window.dispatchEvent(new CustomEvent('weymela:toast',{detail:{message,tone}}))}

export function PilotExperience({role}:{role:PilotRole}){
 const locale:Locale=localStorage.getItem('weymela_locale')==='am'?'am':'en',t=copy[locale],steps=tours[role][locale],dialog=useRef<HTMLDivElement>(null)
 const key=`weymela_tour_v32_${role.replace(/\s/g,'_')}`, [tour,setTour]=useState(()=>localStorage.getItem(key)?-1:0),[help,setHelp]=useState(false),[feedback,setFeedback]=useState(false),[online,setOnline]=useState(navigator.onLine),[toast,setToast]=useState<{message:string;tone:string}>(),[expiring,setExpiring]=useState(false),[survey,setSurvey]=useState<string>()
 useEffect(()=>{const status=()=>{setOnline(navigator.onLine);showToast(navigator.onLine?t.online:t.offline,navigator.onLine?'success':'error')};const toastHandler=(e:Event)=>{const d=(e as CustomEvent).detail;setToast(d);window.setTimeout(()=>setToast(undefined),5000)};const timer=window.setInterval(()=>{try{const payload=JSON.parse(atob(token().split('.')[1].replace(/-/g,'+').replace(/_/g,'/')));setExpiring(Boolean(payload.exp&&payload.exp*1000-Date.now()<120000))}catch{setExpiring(false)}},15000);addEventListener('online',status);addEventListener('offline',status);addEventListener('weymela:toast',toastHandler);return()=>{clearInterval(timer);removeEventListener('online',status);removeEventListener('offline',status);removeEventListener('weymela:toast',toastHandler)}},[t.offline,t.online])
 useEffect(()=>{if(tour>=0||help||feedback){const first=dialog.current?.querySelector<HTMLElement>('button,input,textarea,select');first?.focus()}},[tour,help,feedback])
 useEffect(()=>{if(role!=='Shopper'||!online)return;fetch(`${base}/api/v1/customer/checkouts`,{headers:{Authorization:`Bearer ${token()}`}}).then(r=>r.ok?r.json():[]).then((items:{publicCheckoutId:string;status:string}[])=>{const item=items.find(x=>x.status==='Completed'&&!localStorage.getItem(`weymela_survey_${x.publicCheckoutId}`));if(item)setSurvey(item.publicCheckoutId)}).catch(()=>{})},[role,online])
 function finish(){localStorage.setItem(key,'complete');setTour(-1);trackUx('tour_completed',{role})}
 function signOut(){localStorage.removeItem('creatorpay_access_token');localStorage.removeItem('creatorpay_refresh_token');location.assign('/')}
 async function refresh(){try{const refreshToken=localStorage.getItem('creatorpay_refresh_token');const r=await fetch(`${base}/api/v1/auth/refresh`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refreshToken})});if(!r.ok)throw Error();const v=await r.json();localStorage.setItem('creatorpay_access_token',v.accessToken);localStorage.setItem('creatorpay_refresh_token',v.refreshToken);setExpiring(false);showToast(t.online,'success')}catch{showToast(t.failed,'error')}}
 return <>
  {!online&&<div className="offline-banner" role="alert">{t.offline}</div>}
  {expiring&&<div className="session-banner" role="alert"><span>{t.session}</span><button onClick={()=>void refresh()}>{t.stay}</button><button className="quiet" onClick={signOut}>{t.signout}</button></div>}
  <nav className="pilot-tools" aria-label="Pilot assistance"><button className="quiet" aria-haspopup="dialog" onClick={()=>{setHelp(true);trackUx('context_help_opened',{role,path:location.pathname})}}>{t.help}</button><button className="quiet" aria-haspopup="dialog" onClick={()=>setFeedback(true)}>{t.feedback}</button></nav>
  {toast&&<div className={`toast ${toast.tone}`} role={toast.tone==='error'?'alert':'status'} aria-live="polite"><span>{toast.message}</span><button aria-label={t.close} onClick={()=>setToast(undefined)}>×</button></div>}
  {survey&&tour<0&&!help&&!feedback&&<CheckoutSurvey checkoutId={survey} onDone={()=>setSurvey(undefined)}/>} 
  {tour>=0&&<div className="modal-backdrop"><div className="tour-dialog" role="dialog" aria-modal="true" aria-labelledby="tour-title" ref={dialog} onKeyDown={e=>{if(e.key==='Escape'){localStorage.setItem(key,'skipped');setTour(-1)}}}><p className="eyebrow">{role} · {tour+1}/{steps.length}</p><h2 id="tour-title">{tour===0?t.welcome:steps[tour].title}</h2><p>{tour===0?t.intro:steps[tour].body}</p>{tour>0&&<aside className="context-tip"><strong>{t.help}:</strong> {steps[tour].help}</aside>}<div className="actions">{tour>0&&<button className="quiet" onClick={()=>setTour(tour-1)}>{t.back}</button>}<button onClick={()=>tour===steps.length-1?finish():setTour(tour+1)}>{tour===0?t.start:tour===steps.length-1?t.done:t.next}</button><button className="quiet" onClick={()=>{localStorage.setItem(key,'skipped');setTour(-1);trackUx('tour_skipped',{role,step:tour})}}>{tour===0?t.later:t.skip}</button></div></div></div>}
  {(help||feedback)&&<div className="modal-backdrop"><div className="help-dialog" role="dialog" aria-modal="true" aria-labelledby="help-title" ref={dialog} onKeyDown={e=>{if(e.key==='Escape'){setHelp(false);setFeedback(false)}}}><button className="dialog-close" aria-label={t.close} onClick={()=>{setHelp(false);setFeedback(false)}}>×</button>{feedback?<FeedbackForm role={role} locale={locale} onSent={()=>setFeedback(false)}/>:<><h2 id="help-title">{t.question}</h2><p>{steps[Math.max(0,tour)].help}</p><div className="actions"><button onClick={()=>{setHelp(false);setTour(1)}}>{t.start}</button><a className="button-link quiet" href={`/help?category=${encodeURIComponent(role)}`}>{t.helpCenter}</a></div></>}</div></div>}
 </>
}

function FeedbackForm({role,locale,onSent}:{role:PilotRole;locale:Locale;onSent:()=>void}){const t=copy[locale],[category,setCategory]=useState('Usability'),[message,setMessage]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();if(message.trim().length<10||message.length>2000){setStatus(t.required);return}setBusy(true);try{const r=await fetch(`${base}/api/v1/pilot/feedback`,{method:'POST',headers:{Authorization:`Bearer ${token()}`,'Content-Type':'application/json'},body:JSON.stringify({category,message:message.trim(),preferredLanguage:locale,context:location.pathname})});if(!r.ok)throw Error();showToast(t.sent,'success');trackUx('pilot_feedback_submitted',{role,category});onSent()}catch{setStatus(t.failed)}finally{setBusy(false)}}return <form onSubmit={submit} className="form" aria-busy={busy}><h2 id="help-title">{t.feedbackTitle}</h2><p>{t.feedbackHint}</p><label>{t.category}<select value={category} onChange={e=>setCategory(e.target.value)}><option>Usability</option><option>Accessibility</option><option>Translation</option><option>Checkout</option><option>Other</option></select></label><label>{t.message}<textarea required minLength={10} maxLength={2000} value={message} onChange={e=>setMessage(e.target.value)} aria-describedby="feedback-hint"/></label><small id="feedback-hint">{message.length}/2000 · {t.feedbackHint}</small>{status&&<p className="error" role="alert">{status}</p>}<button disabled={busy||!navigator.onLine}>{busy?'…':t.send}</button></form>}

export function CheckoutSurvey({checkoutId,onDone}:{checkoutId:string;onDone:()=>void}){const locale:Locale=localStorage.getItem('weymela_locale')==='am'?'am':'en',t=copy[locale],[rating,setRating]=useState(0),[busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();if(!rating)return;setBusy(true);try{const r=await fetch(`${base}/api/v1/pilot/checkout-survey`,{method:'POST',headers:{Authorization:`Bearer ${token()}`,'Content-Type':'application/json'},body:JSON.stringify({checkoutId,rating,preferredLanguage:locale})});if(!r.ok)throw Error();localStorage.setItem(`weymela_survey_${checkoutId}`,'complete');showToast(t.surveyThanks,'success');trackUx('checkout_survey_submitted',{rating});onDone()}catch{showToast(t.failed,'error')}finally{setBusy(false)}}return <div className="survey-card" role="region" aria-labelledby="survey-title"><form onSubmit={submit}><h3 id="survey-title">{t.survey}</h3><p>{t.surveyHelp}</p><fieldset><legend className="sr-only">{t.survey}</legend><div className="rating">{[1,2,3,4,5].map(x=><button type="button" key={x} aria-label={`${x} of 5`} aria-pressed={rating===x} className={rating===x?'active':'quiet'} onClick={()=>setRating(x)}>{x}★</button>)}</div></fieldset><button disabled={!rating||busy}>{t.submitRating}</button><button type="button" className="quiet" onClick={onDone}>{t.later}</button></form></div>}
