import {FormEvent, useEffect, useState} from 'react'
import {amount, friendlyStatus, v3Post, v3Request} from './v3ProductApi'
import {NavIcon} from './navIcons'
import {SocialPlatformIcon,type SocialPlatform} from './SocialPlatformIcon'

type PlatformSlot={platform:string;approved:number;capacity:number;available:number}
type Social={id:string;platform:string;profileUrl:string;selfReportedAudience:number;verificationStatus:string;verifiedAudience?:number}
type Promotion={id:string;businessId:string;business:string;title:string;type:string;campaignBudget:number;assignedToCreators:number;availableCampaignBudget:number;used:number;remaining:number;creatorCount:number;startUtc:string;endUtc:string;status:string;version:number;slogan?:string;location?:string;platforms?:PlatformSlot[]}
type Opportunity={id:string;business:{displayName:string};title:string;description:string;type:string;requirements?:string;startUtc:string;endUtc:string;requestStatus?:string;slogan?:string;location?:string;platforms?:PlatformSlot[];eligibleSocialProfiles?:Social[];budget:number;approvedCreators:number;creatorCapacity:number}
type CreatorRequest={id:string;campaign:string;business:string;type:string;status:string;appliedAtUtc:string}
type Applicant={id:string;creator:{displayName:string};message?:string;contentConcept?:string;status:string;appliedAtUtc:string;platform?:string}
type PromotionDetail={campaign:Promotion;description:string;requirements?:string;applicants:Applicant[];creators:{id:string;creator:{displayName:string};creatorBudget:number;used:number;budgetRemaining:number;status:string}[]}
type AdminPromotionDetail={campaign:Promotion;creators:{creator:{displayName:string};creatorBudget:number;used:number;budgetRemaining:number;verifiedViews:number;verifiedSales:number;viewEarnings:number;saleCommission:number;customerCashback:number;platformRevenue:number;status:string}[];creatorEarnings:number;customerCashback:number;platformRevenue:number;history:{id:string;title:string;atUtc:string}[];financialConfigurationVersion:number}
type Wallet={available:number;reserved:number;version:number}
const platforms=['TikTok','Instagram','YouTube','Facebook'] as const
const date=(value:string)=>new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(new Date(value))

function PlatformCapacity({items=[]}:{items?:PlatformSlot[]}){
  return <div className="product-platforms">{items.map(x=><span key={x.platform} aria-label={`${x.platform}: ${x.approved} of ${x.capacity} Creators approved`}><SocialPlatformIcon platform={x.platform as SocialPlatform}/><b className="sr-only">{x.platform}</b> {x.approved}/{x.capacity}</span>)}</div>
}

export function CreatorDiscoverPromotions(){
  const[items,setItems]=useState<Opportunity[]>(),[selected,setSelected]=useState<Opportunity>(),[social,setSocial]=useState(''),[message,setMessage]=useState('')
  const load=()=>v3Request<Opportunity[]>('/api/creator/promotions/discover').then(setItems).catch(e=>setMessage((e as Error).message))
  useEffect(()=>{void load()},[])
  async function join(event:FormEvent){event.preventDefault();if(!selected||!social)return;const profile=selected.eligibleSocialProfiles?.find(x=>x.id===social);if(!profile)return
    try{await v3Post(`/api/creator/promotions/${selected.id}/request`,{platform:profile.platform,creatorSocialProfileId:profile.id,message:null,contentConcept:null});setMessage('Request submitted. Waiting for approval.');setSelected(undefined);setSocial('');await load()}catch(e){setMessage((e as Error).message)}}
  return <section className="product-workspace creator-section"><div className="product-title"><div><p className="eyebrow">Creator</p><h2>Discover Promotions</h2></div></div>{message&&<p role="status" className="product-message">{message}</p>}
    {!items?<p>Loading…</p>:items.length===0?<p className="compact-empty">No Promotions available right now.</p>:<div className="product-card-grid">{items.map(x=><article className="product-card" key={x.id}>
      <strong className="product-business">{x.business.displayName}</strong><h3>{x.title}</h3>{x.slogan&&<p className="product-slogan">{x.slogan}</p>}<PlatformCapacity items={x.platforms}/>
      <div className="product-meta"><span>{friendlyStatus(x.type)}</span><span>{amount(x.budget)} · creators {x.approvedCreators}/{x.creatorCapacity}</span>{x.location&&<span>{x.location}</span>}</div>
      {x.requestStatus?<span className="status-badge">{friendlyStatus(x.requestStatus)}</span>:<button type="button" onClick={()=>{setSelected(x);setSocial(x.eligibleSocialProfiles?.[0]?.id??'')}}>Request to Join</button>}
    </article>)}</div>}
    {selected&&<div className="modal-backdrop"><form className="help-dialog product-dialog" role="dialog" aria-modal="true" aria-labelledby="promotion-platform-dialog-title" onSubmit={e=>void join(e)}><h2 id="promotion-platform-dialog-title">Choose platform</h2><p><strong>{selected.title}</strong></p>
      <div className="platform-choice-list">{(selected.eligibleSocialProfiles??[]).map(x=>{const slot=selected.platforms?.find(p=>p.platform===x.platform);return <label key={x.id}><input type="radio" name="platform" value={x.id} checked={social===x.id} onChange={()=>setSocial(x.id)}/><SocialPlatformIcon platform={x.platform as SocialPlatform}/><span><strong>{x.platform}</strong><small>{slot?.available??0} spot{slot?.available===1?'':'s'} available · self-reported {amount(x.selfReportedAudience)}</small></span></label>})}</div>
      <div className="actions"><button disabled={!social}>Submit request</button><button type="button" className="quiet" onClick={()=>setSelected(undefined)}>Cancel</button></div></form></div>}
  </section>
}

export function CreatorPromotionRequests(){
  const[requests,setRequests]=useState<CreatorRequest[]>(),[active,setActive]=useState<any[]>(),[message,setMessage]=useState('')
  useEffect(()=>{void Promise.all([v3Request<CreatorRequest[]>('/api/creator/requests').then(setRequests),v3Request<any[]>('/api/creator/campaigns').then(setActive)]).catch(e=>setMessage((e as Error).message))},[])
  return <section className="product-workspace creator-section"><h2>My Requests</h2>{message&&<p className="friendly-error">{message}</p>}
    {!requests?<p>Loading…</p>:requests.length===0?<p className="compact-empty">No Promotion requests yet.</p>:<div className="product-list">{requests.map(x=><article key={x.id}><div><strong>{x.campaign}</strong><span>{x.business} · {friendlyStatus(x.type)}</span></div><span className="status-badge">{friendlyStatus(x.status)}</span></article>)}</div>}
    <h2>Active Promotions</h2>{!active?<p>Loading…</p>:active.length===0?<p className="compact-empty">No approved Promotions yet.</p>:<div className="product-card-grid">{active.map(x=><article className="product-card" key={x.budgetId}><strong>{x.business.displayName}</strong><h3>{x.title}</h3><div className="product-meta"><span>{friendlyStatus(x.type)}</span><span>Budget {amount(x.yourBudget)}</span><span>Remaining {amount(x.budgetRemaining)}</span></div><span className="status-badge">{friendlyStatus(x.status)}</span></article>)}</div>}
  </section>
}

const emptyCap=Object.fromEntries(platforms.map(x=>[x,1])) as Record<string,number>
export function BusinessPromotions(){
  const[items,setItems]=useState<Promotion[]>(),[detail,setDetail]=useState<PromotionDetail>(),[creating,setCreating]=useState(false),[editing,setEditing]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[caps,setCaps]=useState({...emptyCap}),[chosen,setChosen]=useState<string[]>(['TikTok']),[promotionType,setPromotionType]=useState<'View Only'|'View & Sale'>('View Only')
  const load=()=>v3Request<Promotion[]>('/api/business/promotions').then(setItems).catch(e=>setMessage((e as Error).message))
  useEffect(()=>{void load()},[])
  async function open(id:string){try{setDetail(await v3Request<PromotionDetail>(`/api/business/promotions/${id}`))}catch(e){setMessage((e as Error).message)}}
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;setBusy(true);setMessage('');const form=new FormData(event.currentTarget);const end=new Date(String(form.get('end')));const start=new Date();const publish=((event.nativeEvent as SubmitEvent).submitter as HTMLButtonElement|null)?.value==='publish'
    try{const created=await v3Post<{id:string}>('/api/business/promotions',{title:form.get('title'),slogan:form.get('slogan')||null,description:form.get('instructions'),requirements:form.get('instructions'),location:form.get('location')||null,type:form.get('type'),campaignBudget:Number(form.get('budget')),category:null,region:null,minimumVerifiedFollowers:null,startUtc:start.toISOString(),endUtc:end.toISOString(),resources:[],platforms:chosen.map(platform=>({platform,capacity:caps[platform]}))});
      if(publish)await fundAndPublish(created.id);setMessage(publish?'Promotion published.':'Promotion draft saved.');setCreating(false);await load();await open(created.id)}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
  async function fundAndPublish(id:string){let saved=await v3Request<PromotionDetail>(`/api/business/promotions/${id}`);if(saved.campaign.status==='Draft'){const wallet=await v3Request<Wallet>('/api/business/wallet');await v3Post(`/api/business/promotions/${id}/fund`,{campaignVersion:saved.campaign.version,walletVersion:wallet.version});saved=await v3Request<PromotionDetail>(`/api/business/promotions/${id}`)}if(saved.campaign.status==='Funded')await v3Post(`/api/business/promotions/${id}/publish`,{version:saved.campaign.version})}
  async function publish(id:string){try{await fundAndPublish(id);setMessage('Promotion published and funded.');await open(id);await load()}catch(e){setMessage((e as Error).message)}}
  async function review(applicant:Applicant,approve:boolean){if(!detail)return;try{if(approve){const raw=prompt('Creator budget allocation');const value=Number(raw);if(!raw||!Number.isFinite(value)||value<=0)return;await v3Post(`/api/business/promotion-requests/${applicant.id}/approve`,{amount:value,version:detail.campaign.version})}else await v3Post(`/api/business/promotion-requests/${applicant.id}/reject`);setMessage(approve?'Creator approved.':'Request rejected.');await open(detail.campaign.id);await load()}catch(e){setMessage((e as Error).message)}}
  async function update(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!detail)return;const form=new FormData(event.currentTarget);try{await v3Post(`/api/business/promotions/${detail.campaign.id}/update`,{description:form.get('description'),slogan:form.get('slogan')||null,location:form.get('location')||null,resources:String(form.get('resources')??'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean),version:detail.campaign.version});setMessage('Promotion details updated without changing its financial terms.');setEditing(false);await open(detail.campaign.id);await load()}catch(e){setMessage((e as Error).message)}}
  async function cancel(){if(!detail||!confirm('Cancel this Promotion?'))return;try{await v3Post(`/api/business/promotions/${detail.campaign.id}/cancel`,{version:detail.campaign.version});setMessage('Promotion cancelled. Reserved funds were released where safe.');setEditing(false);await open(detail.campaign.id);await load()}catch(e){setMessage((e as Error).message)}}
  if(detail)return <section className="product-workspace"><button className="back" onClick={()=>{setDetail(undefined);setEditing(false)}}>← Promotions</button><div className="product-title"><div><h2>{detail.campaign.title}</h2>{detail.campaign.slogan&&<p>{detail.campaign.slogan}</p>}</div><span className="status-badge">{friendlyStatus(detail.campaign.status)}</span></div>{message&&<p className="product-message" role="status">{message}</p>}<div className="actions">{(detail.campaign.status==='Draft'||detail.campaign.status==='Funded')&&<button onClick={()=>void publish(detail.campaign.id)}>Fund and publish</button>}{['Draft','Funded','Open','Active'].includes(friendlyStatus(detail.campaign.status))&&<button className="quiet" onClick={()=>setEditing(!editing)}>{editing?'Close edit':'Edit details'}</button>}{['Draft','Funded','Open'].includes(friendlyStatus(detail.campaign.status))&&detail.creators.length===0&&<button className="danger" onClick={()=>void cancel()}>Cancel Promotion</button>}</div>{editing&&<form className="panel product-form" onSubmit={e=>void update(e)}><label>Promotion slogan <small>Optional</small><input name="slogan" maxLength={160} defaultValue={detail.campaign.slogan}/></label><label>Creator note/instructions <small>Optional</small><textarea name="description" maxLength={3000} defaultValue={detail.description}/></label><label>Location/city <small>Optional</small><input name="location" defaultValue={detail.campaign.location}/></label><label>Reference URLs <small>Optional, one secure URL per line</small><textarea name="resources"/></label><div className="actions"><button>Save details</button><button type="button" className="quiet" onClick={()=>setEditing(false)}>Cancel edit</button></div></form>}<PlatformCapacity items={detail.campaign.platforms}/><div className="summary-grid"><article><span>Budget</span><strong>{amount(detail.campaign.campaignBudget)}</strong></article><article><span>Reserved</span><strong>{amount(detail.campaign.remaining)}</strong></article><article><span>Spent</span><strong>{amount(detail.campaign.used)}</strong></article></div><h3>Requests</h3>{detail.applicants.filter(x=>x.status==='Pending').length===0?<p className="compact-empty">No pending Creator requests.</p>:detail.applicants.filter(x=>x.status==='Pending').map(x=><article className="request-review-card" key={x.id}><div><strong>{x.creator.displayName}</strong>{x.platform&&<span>{x.platform}</span>}</div><div className="actions"><button onClick={()=>void review(x,true)}>Approve</button><button className="danger" onClick={()=>void review(x,false)}>Reject</button></div></article>)}</section>
  return <section className="product-workspace"><div className="product-title"><div><p className="eyebrow">Business</p><h2>Promotions</h2></div><button onClick={()=>setCreating(!creating)}>Create Promotion</button></div>{message&&<p className="product-message" role="status">{message}</p>}
    {creating&&<form className="panel product-form" onSubmit={e=>void create(e)}><label>Promotion name<input name="title" required maxLength={120}/></label><label>Promotion slogan <small>Optional</small><input name="slogan" maxLength={160}/></label><fieldset className="promotion-type-cards"><legend>Promotion type</legend><input type="hidden" name="type" value={promotionType}/><button type="button" className={promotionType==='View Only'?'selected':''} onClick={()=>setPromotionType('View Only')}><NavIcon name="discover" size={28}/><strong>View Only</strong><span>Grow awareness through verified Creator views.</span></button><button type="button" className={promotionType==='View & Sale'?'selected':''} onClick={()=>setPromotionType('View & Sale')}><NavIcon name="checkout" size={28}/><strong>View &amp; Sale</strong><span>Verified views plus Customer Sale tracking.</span></button></fieldset><label>Creator note/instructions <small>Optional</small><textarea name="instructions" maxLength={2000}/></label><label>Location/city <small>Optional</small><input name="location"/></label><label>Budget<input name="budget" type="number" min="0.01" step="0.01" required/></label><label>End date<input name="end" type="date" required min={new Date(Date.now()+86400000).toISOString().slice(0,10)}/></label><fieldset><legend>Platforms and Creator capacity</legend>{platforms.map(p=><div className="platform-capacity-input" key={p}><label><input type="checkbox" checked={chosen.includes(p)} onChange={e=>setChosen(e.target.checked?[...chosen,p]:chosen.filter(x=>x!==p))}/><SocialPlatformIcon platform={p}/> <span className="sr-only">{p}</span></label>{chosen.includes(p)&&<label>Creators<input aria-label={`${p} Creator capacity`} type="number" min="1" max="100" value={caps[p]} onChange={e=>setCaps({...caps,[p]:Number(e.target.value)})}/></label>}</div>)}</fieldset><div className="actions"><button value="publish" disabled={busy||chosen.length===0}>{busy?'Saving…':'Publish Promotion'}</button><button value="draft" className="quiet" disabled={busy||chosen.length===0}>Save Draft</button><button type="button" className="quiet" onClick={()=>setCreating(false)}>Cancel</button></div></form>}
    {!items?<p>Loading…</p>:items.length===0?<div className="empty-state"><h3>No Promotions yet.</h3><p>Create your first Promotion.</p></div>:<div className="product-card-grid">{items.map(x=><article className="product-card" key={x.id}><h3>{x.title}</h3>{x.slogan&&<p className="product-slogan">{x.slogan}</p>}<span className="status-badge">{friendlyStatus(x.status)}</span><PlatformCapacity items={x.platforms}/><div className="product-meta"><span>{friendlyStatus(x.type)}</span><span>Budget {amount(x.campaignBudget)}</span><span>{x.creatorCount}/{x.platforms?.reduce((sum,p)=>sum+p.capacity,0)??0} Creators</span><span>Ends {date(x.endUtc)}</span></div><button onClick={()=>void open(x.id)}>Manage</button></article>)}</div>}
  </section>
}

export function AdminPromotions(){
  const[items,setItems]=useState<Promotion[]>(),[detail,setDetail]=useState<AdminPromotionDetail>(),[message,setMessage]=useState('')
  useEffect(()=>{v3Request<Promotion[]>('/api/admin/promotions').then(setItems).catch(e=>setMessage((e as Error).message))},[])
  async function open(id:string){try{setDetail(await v3Request<AdminPromotionDetail>(`/api/admin/campaigns/${id}`))}catch(e){setMessage((e as Error).message)}}
  if(detail)return <section className="product-workspace"><button className="back" onClick={()=>setDetail(undefined)}>← Promotions</button><div className="product-title"><div><strong>{detail.campaign.business}</strong><h1>{detail.campaign.title}</h1></div><span className="status-badge">{friendlyStatus(detail.campaign.status)}</span></div><p>{friendlyStatus(detail.campaign.type)} · Financial Settings version {detail.financialConfigurationVersion}</p><PlatformCapacity items={detail.campaign.platforms}/><div className="summary-grid"><article><span>Budget</span><strong>{amount(detail.campaign.campaignBudget)}</strong></article><article><span>Reserved / remaining</span><strong>{amount(detail.campaign.remaining)}</strong></article><article><span>Spent</span><strong>{amount(detail.campaign.used)}</strong></article><article><span>Creator earnings</span><strong>{amount(detail.creatorEarnings)}</strong></article><article><span>Customer cashback</span><strong>{amount(detail.customerCashback)}</strong></article><article><span>Platform revenue</span><strong>{amount(detail.platformRevenue)}</strong></article></div><p>{date(detail.campaign.startUtc)} – {date(detail.campaign.endUtc)}</p><h2>Approved Creators</h2>{detail.creators.length===0?<p className="compact-empty">No approved Creators.</p>:<div className="product-list">{detail.creators.map((x,index)=><article key={index}><div><strong>{x.creator.displayName}</strong><span>{friendlyStatus(x.status)} · {amount(x.verifiedViews)} verified views · {x.verifiedSales} Sales</span></div><span>{amount(x.budgetRemaining)} remaining</span></article>)}</div>}<h2>Audit history</h2>{detail.history.length===0?<p className="compact-empty">No Promotion history.</p>:<div className="product-list">{detail.history.map(x=><article key={x.id}><div><strong>{x.title}</strong><time dateTime={x.atUtc}>{new Date(x.atUtc).toLocaleString()}</time></div></article>)}</div>}</section>
  return <section className="product-workspace"><h1>Promotions</h1>{message&&<p className="friendly-error">{message}</p>}{!items?<p>Loading…</p>:items.length===0?<p className="compact-empty">No Promotions found.</p>:<div className="product-card-grid">{items.map(x=><article className="product-card" key={x.id}><strong>{x.business}</strong><h3>{x.title}</h3><span className="status-badge">{friendlyStatus(x.status)}</span><PlatformCapacity items={x.platforms}/><div className="product-meta"><span>{friendlyStatus(x.type)}</span><span>Budget {amount(x.campaignBudget)}</span><span>Reserved {amount(x.remaining)}</span><span>Spent {amount(x.used)}</span></div><button onClick={()=>void open(x.id)}>Inspect</button></article>)}</div>}</section>
}
