import {FormEvent,useEffect,useState} from 'react'
type Qr={id:string;publicQrId:string;issuedAtUtc:string;isActive:boolean}
type Location={id:string;name:string;isActive:boolean}
type Result={isValid:boolean;code:string;message:string;creatorPublicId?:string;creatorDisplayName?:string}
const token=()=>localStorage.getItem('creatorpay_access_token')??''
async function api<T>(path:string,init?:RequestInit):Promise<T>{const r=await fetch(path,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()}`,...init?.headers}});if(!r.ok){const p=await r.json().catch(()=>({}));throw new Error(p.detail??`Request failed (${r.status}).`)}return r.status===204?undefined as T:r.json()}
function QrImage(){const[src,setSrc]=useState('');useEffect(()=>{let url='';fetch('/api/v1/creator/qr/image',{headers:{Authorization:`Bearer ${token()}`}}).then(r=>{if(!r.ok)throw new Error('QR image unavailable.');return r.blob()}).then(b=>{url=URL.createObjectURL(b);setSrc(url)});return()=>{if(url)URL.revokeObjectURL(url)}},[]);async function download(){const r=await fetch('/api/v1/creator/qr/image',{headers:{Authorization:`Bearer ${token()}`}}),url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download='creatorpay-qr.png';a.click();URL.revokeObjectURL(url)}return <>{src&&<img className="qr-image" src={src} alt="Creator QR code"/>}<button onClick={download}>Download PNG</button></>}
export function CreatorQrWorkspace(){const[q,setQ]=useState<Qr>(),[history,setHistory]=useState<Qr[]>([]);const load=()=>Promise.all([api<Qr>('/api/v1/creator/qr'),api<Qr[]>('/api/v1/creator/qr/history')]).then(([a,b])=>{setQ(a);setHistory(b)});useEffect(()=>{void load()},[]);async function regenerate(){if(confirm('Regenerate this QR? The current QR will stop working immediately.')){await api('/api/v1/creator/qr/regenerate',{method:'POST',body:JSON.stringify({confirmed:true})});void load()}}async function revoke(){if(confirm('Revoke this QR?')){await api('/api/v1/creator/qr/revoke',{method:'POST',body:JSON.stringify({reason:'Revoked by creator'})});void load()}}return <section><div className="title"><h2>My QR</h2><span>{q?.isActive?'Active':'Unavailable'}</span></div>{q&&<div className="panel"><QrImage/><p>Issued {new Date(q.issuedAtUtc).toLocaleString()}</p><div className="actions"><button onClick={regenerate}>Regenerate</button><button className="danger" onClick={revoke}>Revoke</button></div></div>}<h3>QR history</h3><div className="cards">{history.map(x=><article key={x.id}><span>{x.isActive?'Active':'Revoked'}</span><strong>{x.publicQrId}</strong><p>{new Date(x.issuedAtUtc).toLocaleDateString()}</p></article>)}</div></section>}
export function MerchantQrWorkspace({role}:{role:string}){const[locations,setLocations]=useState<Location[]>([]),[locationId,setLocationId]=useState(''),[payload,setPayload]=useState(''),[result,setResult]=useState<Result>();useEffect(()=>{const prefix=role==='MerchantAdmin'?'merchant':role.toLowerCase();api<Location[]>(`/api/v1/${prefix}/locations`).then(x=>{const a=x.filter(y=>y.isActive);setLocations(a);setLocationId(a[0]?.id??'')})},[role]);async function submit(e:FormEvent){e.preventDefault();setResult(await api('/api/v1/merchant/qr/validate',{method:'POST',body:JSON.stringify({payload,locationId})}))}return <section><h2>Validate creator QR</h2><p>Paste a scanned QR payload. Live camera capture is a future enhancement.</p><form className="panel form" onSubmit={submit}><label>Location<select required value={locationId} onChange={e=>setLocationId(e.target.value)}>{locations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>QR payload<textarea required rows={4} value={payload} onChange={e=>setPayload(e.target.value)}/></label><button>Validate QR</button></form>{result&&<aside><strong>{result.isValid?'Valid creator QR':result.code}</strong><p>{result.message}</p>{result.isValid&&<p>{result.creatorDisplayName} · {result.creatorPublicId}</p>}</aside>}</section>}
