namespace CreatorPay.Application.CustomerVerification;

public sealed class CustomerVerificationOptions { public const string SectionName = "CustomerVerification"; public string HmacSecret { get; set; } = ""; public string EncryptionKey { get; set; } = ""; public int RepeatUseApprovalExpirationMinutes { get; set; } = 15; public bool RequireCustomerOtpForRepeatUse { get; set; } = true; public bool RequireSupervisorApprovalForRepeatUse { get; set; } = true; public int MaximumRepeatUseApprovalsPerDay { get; set; } = 3; public int CustomerVerificationCodeLifetimeMinutes { get; set; } = 5; public int CustomerVerificationMaxAttempts { get; set; } = 5; public bool ReturnDevelopmentCode { get; set; } }
public interface IPhoneNumberNormalizer { string Normalize(string value); string Mask(string normalized); }
public interface IPhoneHashService { string Hash(string normalized); }
public interface IPhoneEncryptionService { byte[] Encrypt(string normalized); string Decrypt(byte[] protectedValue); }
public interface ICustomerVerificationProvider { (string Code, string Hash) CreateCode(); bool Verify(string code, string hash); }
public sealed record RepeatUseDto(string ApprovalRequestId, string Status, string MaskedPhoneNumber, string[] RequiredActions, DateTime ExpiresAtUtc, string Message, decimal PurchaseAmount, string CurrencyCode, Guid MerchantLocationId, Guid CreatorId, Guid CashierId, string? CreatorDisplayName = null, string? LocationName = null, string? DevelopmentCode = null);
public sealed record PurchasePrecheckRequest(string QrPayload, Guid MerchantLocationId, decimal PurchaseAmount, string CurrencyCode, string CustomerPhoneNumber);
public sealed record VerificationCodeRequest(); public sealed record VerifyCodeRequest(string Code); public sealed record ApprovalDecisionRequest(string? Reason);
public interface IRepeatUseApprovalService { Task<object> PrecheckAsync(Guid merchantId, Guid actor, Guid cashierId, string role, PurchasePrecheckRequest request, CancellationToken ct); Task<RepeatUseDto?> GateAsync(Guid merchantId, Guid actor, Guid cashierId, string role, string key, CreatorPay.Application.Wallet.ConfirmPurchaseRequest request, CancellationToken ct); Task<RepeatUseDto> GetAsync(string id, Guid? merchantId, Guid? cashierId, Guid? supervisorId, bool admin, CancellationToken ct); Task<IReadOnlyList<RepeatUseDto>> ListAsync(Guid? merchantId, Guid? supervisorId, bool admin, CancellationToken ct); Task<RepeatUseDto> SendCodeAsync(string id, CancellationToken ct); Task<RepeatUseDto> VerifyCodeAsync(string id, string code, CancellationToken ct); Task<RepeatUseDto> DecideAsync(string id, Guid merchantId, Guid actor, Guid? supervisorId, bool approve, string? reason, CancellationToken ct); }
