using System.Text.Json;
using CreatorPay.Api.Authentication;
using CreatorPay.Application.Authentication;
using CreatorPay.Application.Commission;
using CreatorPay.Domain.Entities;
using CreatorPay.Domain.Enums;
using CreatorPay.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace CreatorPay.Api.Commission;

public sealed record PlanRequest(string Name, string? Description, bool IsActive = true);
public sealed record RuleRequest(Guid CommissionPlanId, string Name, CommissionScopeType ScopeType, string CurrencyCode, bool IsActive = true);
public sealed record VersionRequest(decimal MerchantCommissionRatePercent, decimal CreatorSharePercent, decimal PlatformSharePercent, decimal MinimumPurchaseAmount, decimal? MaximumPurchaseAmount, DateTime EffectiveFromUtc, DateTime? EffectiveToUtc, CommissionRoundingMode RoundingMode, bool IsActive = true);
public sealed record StatusRequest(bool IsActive);
public sealed record PlatformAssignmentRequest(Guid CommissionRuleId, string CurrencyCode, DateTime EffectiveFromUtc, DateTime? EffectiveToUtc);
public sealed record MerchantAssignmentRequest(Guid MerchantId, Guid CommissionRuleId, DateTime EffectiveFromUtc, DateTime? EffectiveToUtc);
public sealed record PartnershipAssignmentRequest(Guid PartnershipId, Guid CommissionRuleId, DateTime EffectiveFromUtc, DateTime? EffectiveToUtc);
public sealed record PreviewRequest(decimal PurchaseAmount, Guid PartnershipId, Guid? CampaignId, string CurrencyCode, DateTime CalculationAtUtc);

public static class CommissionEndpoints
{
    public static IEndpointRouteBuilder MapCommissionEndpoints(this IEndpointRouteBuilder e)
    {
        var a = e.MapGroup("/api/v1/admin").WithTags("Commission").RequireAuthorization("PlatformAdminOnly");
        a.MapGet("/commission-plans", async (ApplicationDbContext db, CancellationToken ct) => Results.Ok(await db.CommissionPlans.AsNoTracking().OrderBy(x => x.Name).ToListAsync(ct))); a.MapPost("/commission-plans", CreatePlan); a.MapGet("/commission-plans/{id:guid}", async (Guid id, ApplicationDbContext db, CancellationToken ct) => await db.CommissionPlans.AsNoTracking().Where(x => x.Id == id).Select(x => new { x.Id, x.Name, x.Description, x.IsActive, x.CreatedAtUtc, x.UpdatedAtUtc }).FirstOrDefaultAsync(ct) is { } x ? Results.Ok(x) : Missing()); a.MapPut("/commission-plans/{id:guid}", UpdatePlan);
        a.MapGet("/commission-rules", async (ApplicationDbContext db, CancellationToken ct) => Results.Ok(await db.CommissionRules.AsNoTracking().Select(x => new { x.Id, x.CommissionPlanId, x.Name, x.ScopeType, x.CurrencyCode, x.IsActive }).ToListAsync(ct))); a.MapPost("/commission-rules", CreateRule); a.MapGet("/commission-rules/{id:guid}", async (Guid id, ApplicationDbContext db, CancellationToken ct) => await db.CommissionRules.AsNoTracking().Where(x => x.Id == id).Select(x => new { x.Id, x.CommissionPlanId, x.Name, x.ScopeType, x.CurrencyCode, x.IsActive }).FirstOrDefaultAsync(ct) is { } x ? Results.Ok(x) : Missing()); a.MapPost("/commission-rules/{id:guid}/versions", CreateVersion); a.MapGet("/commission-rules/{id:guid}/versions", async (Guid id, ApplicationDbContext db, CancellationToken ct) => Results.Ok(await db.CommissionRuleVersions.AsNoTracking().Where(x => x.CommissionRuleId == id).OrderByDescending(x => x.VersionNumber).ToListAsync(ct))); a.MapGet("/commission-rules/{id:guid}/versions/{versionId:guid}", async (Guid id, Guid versionId, ApplicationDbContext db, CancellationToken ct) => await db.CommissionRuleVersions.AsNoTracking().FirstOrDefaultAsync(x => x.Id == versionId && x.CommissionRuleId == id, ct) is { } x ? Results.Ok(x) : Missing()); a.MapPatch("/commission-rules/{id:guid}/status", SetStatus);
        a.MapPost("/commission-assignments/platform-default", AssignPlatform); a.MapPost("/commission-assignments/merchant", AssignMerchant); a.MapPost("/commission-assignments/partnership", AssignPartnership); a.MapGet("/commission-assignments/merchant/{id:guid}", async (Guid id, ApplicationDbContext db, CancellationToken ct) => Results.Ok(await db.MerchantCommissionAssignments.AsNoTracking().Where(x => x.MerchantId == id).ToListAsync(ct))); a.MapGet("/commission-assignments/partnership/{id:guid}", async (Guid id, ApplicationDbContext db, CancellationToken ct) => Results.Ok(await db.PartnershipCommissionAssignments.AsNoTracking().Where(x => x.MerchantCreatorPartnershipId == id).ToListAsync(ct))); a.MapPost("/commission-preview", AdminPreview);
        var m = e.MapGroup("/api/v1/merchant").WithTags("Commission").RequireAuthorization("MerchantAdminOnly"); m.MapGet("/commission-rules/effective", MerchantEffective); m.MapGet("/partnerships/{id:guid}/commission-rule", MerchantPartnership); m.MapPost("/commission-preview", MerchantPreview);
        e.MapGet("/api/v1/creator/partnerships/{id:guid}/commission-rule", CreatorPartnership).WithTags("Commission").RequireAuthorization("CreatorOnly"); return e;
    }
    static async Task<IResult> CreatePlan(PlanRequest r, ICurrentUserService u, ApplicationDbContext db, HttpContext h, CancellationToken ct) { if (string.IsNullOrWhiteSpace(r.Name)) return Bad("Name is required."); var now = DateTime.UtcNow; var x = new CommissionPlan { Id = Guid.NewGuid(), Name = r.Name.Trim(), Description = r.Description?.Trim(), IsActive = r.IsActive, CreatedAtUtc = now, CreatedBy = u.UserAccountId.ToString() }; db.Add(x); Audit(db, u, h, "CommissionPlanCreated", null, x); await db.SaveChangesAsync(ct); return Results.Created($"/api/v1/admin/commission-plans/{x.Id}", x); }
    static async Task<IResult> UpdatePlan(Guid id, PlanRequest r, ICurrentUserService u, ApplicationDbContext db, HttpContext h, CancellationToken ct) { var x = await db.CommissionPlans.FindAsync([id], ct); if (x is null) return Missing(); var before = new { x.Name, x.Description, x.IsActive }; x.Name = r.Name.Trim(); x.Description = r.Description?.Trim(); x.IsActive = r.IsActive; x.UpdatedAtUtc = DateTime.UtcNow; Audit(db, u, h, "CommissionPlanChanged", before, new { x.Name, x.Description, x.IsActive }); await db.SaveChangesAsync(ct); return Results.Ok(x); }
    static async Task<IResult> CreateRule(RuleRequest r, ICurrentUserService u, ApplicationDbContext db, HttpContext h, CancellationToken ct) { if (!await db.CommissionPlans.AnyAsync(x => x.Id == r.CommissionPlanId, ct) || string.IsNullOrWhiteSpace(r.Name) || r.CurrencyCode.Trim().Length != 3) return Bad("A valid plan, name, and ISO currency code are required."); var x = new CommissionRule { Id = Guid.NewGuid(), CommissionPlanId = r.CommissionPlanId, Name = r.Name.Trim(), ScopeType = r.ScopeType, CurrencyCode = r.CurrencyCode.Trim().ToUpperInvariant(), IsActive = r.IsActive, CreatedAtUtc = DateTime.UtcNow, CreatedBy = u.UserAccountId.ToString() }; db.Add(x); Audit(db, u, h, "CommissionRuleCreated", null, x); await db.SaveChangesAsync(ct); return Results.Created($"/api/v1/admin/commission-rules/{x.Id}", x); }
    static async Task<IResult> CreateVersion(Guid id, VersionRequest r, ICurrentUserService u, ApplicationDbContext db, HttpContext h, CancellationToken ct) { var rule = await db.CommissionRules.FindAsync([id], ct); if (rule is null) return Missing(); var x = new CommissionRuleVersion { Id = Guid.NewGuid(), CommissionRuleId = id, VersionNumber = (await db.CommissionRuleVersions.Where(v => v.CommissionRuleId == id).MaxAsync(v => (int?)v.VersionNumber, ct) ?? 0) + 1, MerchantCommissionRatePercent = r.MerchantCommissionRatePercent, CreatorSharePercent = r.CreatorSharePercent, PlatformSharePercent = r.PlatformSharePercent, MinimumPurchaseAmount = r.MinimumPurchaseAmount, MaximumPurchaseAmount = r.MaximumPurchaseAmount, EffectiveFromUtc = r.EffectiveFromUtc, EffectiveToUtc = r.EffectiveToUtc, RoundingMode = r.RoundingMode, IsActive = r.IsActive, CreatedAtUtc = DateTime.UtcNow, CreatedByUserId = u.UserAccountId!.Value, CreatedBy = u.UserAccountId.ToString() }; try { x.Validate(); if (await db.CommissionRuleVersions.AnyAsync(v => v.CommissionRuleId == id && v.IsActive && x.IsActive && v.EffectiveFromUtc < (x.EffectiveToUtc ?? DateTime.MaxValue) && x.EffectiveFromUtc < (v.EffectiveToUtc ?? DateTime.MaxValue), ct)) throw new ArgumentException("Active version effective periods cannot overlap."); } catch (Exception ex) when (ex is ArgumentException or ArgumentOutOfRangeException) { Audit(db, u, h, "InvalidCommissionConfigurationAttempt", null, new { ex.Message }); await db.SaveChangesAsync(ct); return Bad(ex.Message); } db.Add(x); Audit(db, u, h, "CommissionRuleVersionCreated", null, x); await db.SaveChangesAsync(ct); return Results.Created($"/api/v1/admin/commission-rules/{id}/versions/{x.Id}", x); }
    static async Task<IResult> SetStatus(Guid id, StatusRequest r, ICurrentUserService u, ApplicationDbContext db, HttpContext h, CancellationToken ct) { var x = await db.CommissionRules.FindAsync([id], ct); if (x is null) return Missing(); var before = x.IsActive; x.IsActive = r.IsActive; x.UpdatedAtUtc = DateTime.UtcNow; Audit(db, u, h, r.IsActive ? "CommissionRuleActivated" : "CommissionRuleDeactivated", new { IsActive = before }, new { x.IsActive }); await db.SaveChangesAsync(ct); return Results.Ok(new { x.Id, x.IsActive }); }
    static Task<IResult> AssignPlatform(PlatformAssignmentRequest r, ICurrentUserService u, ApplicationDbContext db, HttpContext h, CancellationToken ct) => Assign(new PlatformCommissionAssignment { CurrencyCode = r.CurrencyCode.Trim().ToUpperInvariant(), CommissionRuleId = r.CommissionRuleId, EffectiveFromUtc = r.EffectiveFromUtc, EffectiveToUtc = r.EffectiveToUtc }, "PlatformDefaultAssigned", u, db, h, ct);
    static Task<IResult> AssignMerchant(MerchantAssignmentRequest r, ICurrentUserService u, ApplicationDbContext db, HttpContext h, CancellationToken ct) => Assign(new MerchantCommissionAssignment { MerchantId = r.MerchantId, CommissionRuleId = r.CommissionRuleId, EffectiveFromUtc = r.EffectiveFromUtc, EffectiveToUtc = r.EffectiveToUtc }, "MerchantRuleAssigned", u, db, h, ct);
    static Task<IResult> AssignPartnership(PartnershipAssignmentRequest r, ICurrentUserService u, ApplicationDbContext db, HttpContext h, CancellationToken ct) => Assign(new PartnershipCommissionAssignment { MerchantCreatorPartnershipId = r.PartnershipId, CommissionRuleId = r.CommissionRuleId, EffectiveFromUtc = r.EffectiveFromUtc, EffectiveToUtc = r.EffectiveToUtc }, "PartnershipRuleAssigned", u, db, h, ct);
    static async Task<IResult> Assign(CommissionAssignment x, string type, ICurrentUserService u, ApplicationDbContext db, HttpContext h, CancellationToken ct) { if (x.EffectiveFromUtc.Kind != DateTimeKind.Utc || x.EffectiveToUtc <= x.EffectiveFromUtc || !await db.CommissionRules.AnyAsync(r => r.Id == x.CommissionRuleId, ct)) return Bad("A valid rule and UTC effective period are required."); x.Id = Guid.NewGuid(); x.IsActive = true; x.CreatedAtUtc = DateTime.UtcNow; x.CreatedBy = u.UserAccountId.ToString(); db.Add(x); Audit(db, u, h, type, null, x); await db.SaveChangesAsync(ct); return Results.Created("/api/v1/admin/commission-assignments", x); }
    static async Task<IResult> AdminPreview(PreviewRequest r, ICommissionEngine engine, ApplicationDbContext db, ICurrentUserService u, HttpContext h, CancellationToken ct) { var p = await db.MerchantCreatorPartnerships.AsNoTracking().FirstOrDefaultAsync(x => x.Id == r.PartnershipId, ct); if (p is null) return Missing(); return await Preview(r, p, engine, db, u, h, ct); }
    static async Task<IResult> MerchantPreview(PreviewRequest r, ICommissionEngine engine, ApplicationDbContext db, ICurrentUserService u, HttpContext h, CancellationToken ct) { var p = await db.MerchantCreatorPartnerships.AsNoTracking().FirstOrDefaultAsync(x => x.Id == r.PartnershipId && x.MerchantId == u.MerchantId, ct); if (p is null) { Audit(db, u, h, "UnauthorizedCommissionAccessAttempt", null, new { r.PartnershipId }); await db.SaveChangesAsync(ct); return Missing(); } return await Preview(r, p, engine, db, u, h, ct); }
    static async Task<IResult> Preview(PreviewRequest r, MerchantCreatorPartnership p, ICommissionEngine engine, ApplicationDbContext db, ICurrentUserService u, HttpContext h, CancellationToken ct) { try { var value = await engine.PreviewAsync(new(r.PurchaseAmount, p.MerchantId, p.CreatorId, p.Id, r.CampaignId, r.CurrencyCode, r.CalculationAtUtc), false, ct); Audit(db, u, h, "CommissionPreviewExecuted", null, new { value.RuleId, value.RuleVersionId, value.RuleSource, r.PurchaseAmount }); await db.SaveChangesAsync(ct); return Results.Ok(value); } catch (Exception ex) when (ex is CommissionConfigurationException or ArgumentException) { return Bad(ex.Message); } }
    static async Task<IResult> MerchantEffective(string? currencyCode, ICurrentUserService u, ICommissionEngine engine, CancellationToken ct) { try { return Results.Ok(await engine.SelectAsync(new(0, u.MerchantId!.Value, null, null, null, currencyCode ?? "ETB", DateTime.UtcNow), ct)); } catch (CommissionConfigurationException ex) { return Bad(ex.Message); } }
    static async Task<IResult> MerchantPartnership(Guid id, ICurrentUserService u, ICommissionEngine engine, ApplicationDbContext db, CancellationToken ct) { var p = await db.MerchantCreatorPartnerships.AsNoTracking().FirstOrDefaultAsync(x => x.Id == id && x.MerchantId == u.MerchantId, ct); return p is null ? Missing() : await ViewRule(p, engine, ct); }
    static async Task<IResult> CreatorPartnership(Guid id, ICurrentUserService u, ICommissionEngine engine, ApplicationDbContext db, CancellationToken ct) { var p = await db.MerchantCreatorPartnerships.AsNoTracking().FirstOrDefaultAsync(x => x.Id == id && x.CreatorId == u.CreatorId && x.Status == PartnershipStatus.Approved, ct); return p is null ? Missing() : await ViewRule(p, engine, ct); }
    static async Task<IResult> ViewRule(MerchantCreatorPartnership p, ICommissionEngine engine, CancellationToken ct) { try { var s = await engine.SelectAsync(new(0, p.MerchantId, p.CreatorId, p.Id, null, "ETB", DateTime.UtcNow), ct); return Results.Ok(new { s.Rule.Id, s.Rule.Name, s.Rule.CurrencyCode, s.SourceType, s.Version.CreatorSharePercent, s.Version.PlatformSharePercent, s.Version.MerchantCommissionRatePercent, s.Version.EffectiveFromUtc, s.Version.EffectiveToUtc, s.Version.RoundingMode }); } catch (CommissionConfigurationException ex) { return Bad(ex.Message); } }
    static void Audit(ApplicationDbContext db, ICurrentUserService u, HttpContext h, string type, object? before, object? after) => db.CommissionAuditEvents.Add(new() { Id = Guid.NewGuid(), ActorUserAccountId = u.UserAccountId, MerchantId = u.MerchantId, EventType = type, BeforeValues = before is null ? null : JsonSerializer.Serialize(before), AfterValues = after is null ? null : JsonSerializer.Serialize(after), CorrelationId = h.TraceIdentifier, CreatedAtUtc = DateTime.UtcNow, CreatedBy = u.UserAccountId.ToString() });
    static IResult Bad(string detail) => Results.Problem(statusCode: 400, title: "Commission configuration error", detail: detail); static IResult Missing() => Results.Problem(statusCode: 404, title: "Not found", detail: "Commission resource was not found in your scope.");
}
