using CreatorPay.Application.Authentication;
using CreatorPay.Application.Wallet;
using CreatorPay.Infrastructure.Wallet;
using CreatorPay.Application.CustomerVerification;

namespace CreatorPay.Api.Wallet;

public static class WalletEndpoints
{
    public static IEndpointRouteBuilder MapWalletEndpoints(this IEndpointRouteBuilder e)
    {
        var m = e.MapGroup("/api/v1/merchant").RequireAuthorization("MerchantAdminOnly"); m.MapGet("/wallet", async (ICurrentUserService u, IWalletService s, CancellationToken c) => Results.Ok(await s.GetWalletAsync(u.MerchantId!.Value, c))); m.MapGet("/wallet/entries", async (ICurrentUserService u, IWalletService s, CancellationToken c) => Results.Ok(await s.GetEntriesAsync(u.MerchantId!.Value, c))); m.MapGet("/deposits", async (ICurrentUserService u, IWalletService s, CancellationToken c) => Results.Ok(await s.GetDepositsAsync(u.MerchantId, false, c))); m.MapPost("/deposits", (SubmitDepositRequest x, HttpRequest r, ICurrentUserService u, IWalletService s, CancellationToken c) => Run(() => s.SubmitDepositAsync(u.MerchantId!.Value, u.UserAccountId!.Value, Key(r), x, c), 201)); m.MapGet("/deposits/{id:guid}", (Guid id, ICurrentUserService u, IWalletService s, CancellationToken c) => Run(() => s.GetDepositAsync(id, u.MerchantId, c))); m.MapGet("/purchases", (ICurrentUserService u, IWalletService s, CancellationToken c) => Run(() => s.GetPurchasesAsync(u.MerchantId, null, 100, c))); m.MapGet("/purchases/{id:guid}", (Guid id, ICurrentUserService u, IWalletService s, CancellationToken c) => Run(() => s.GetPurchaseAsync(id, u.MerchantId, null, c)));
        var a = e.MapGroup("/api/v1/admin").RequireAuthorization("PlatformAdminOnly"); a.MapGet("/deposits/pending", (IWalletService s, CancellationToken c) => Run(() => s.GetDepositsAsync(null, true, c))); a.MapGet("/deposits/{id:guid}", (Guid id, IWalletService s, CancellationToken c) => Run(() => s.GetDepositAsync(id, null, c))); a.MapPost("/deposits/{id:guid}/approve", (Guid id, HttpRequest r, ICurrentUserService u, IWalletService s, CancellationToken c) => Run(() => s.ApproveDepositAsync(id, u.UserAccountId!.Value, Key(r), c))); a.MapPost("/deposits/{id:guid}/reject", (Guid id, RejectDepositRequest x, ICurrentUserService u, IWalletService s, CancellationToken c) => Run(() => s.RejectDepositAsync(id, u.UserAccountId!.Value, x, c))); a.MapGet("/purchases", (IWalletService s, CancellationToken c) => Run(() => s.GetPurchasesAsync(null, null, 100, c))); a.MapGet("/purchases/{id:guid}", (Guid id, IWalletService s, CancellationToken c) => Run(() => s.GetPurchaseAsync(id, null, null, c)));
        var p = e.MapGroup("/api/v1/cashier/purchases").RequireAuthorization("CashierOnly"); p.MapPost("/precheck", (PurchasePrecheckRequest x, ICurrentUserService u, IRepeatUseApprovalService a, CancellationToken c) => Run(() => a.PrecheckAsync(u.MerchantId!.Value, u.UserAccountId!.Value, u.CashierId!.Value, u.Role!, x, c))); p.MapPost("/", async (ConfirmPurchaseRequest x, HttpRequest r, ICurrentUserService u, IRepeatUseApprovalService a, IWalletService s, CancellationToken c) => { try { var gate = await a.GateAsync(u.MerchantId!.Value, u.UserAccountId!.Value, u.CashierId!.Value, u.Role!, Key(r), x, c); return gate is not null ? Results.Json(gate, statusCode: 202) : Results.Json(await s.ConfirmPurchaseAsync(u.MerchantId.Value, u.UserAccountId.Value, u.CashierId.Value, u.Role!, Key(r), x, c), statusCode: 201); } catch (Exception ex) { return Error(ex); } }); p.MapGet("/recent", (ICurrentUserService u, IWalletService s, CancellationToken c) => Run(() => s.GetPurchasesAsync(u.MerchantId, u.CashierId, 25, c))); p.MapGet("/{id:guid}", (Guid id, ICurrentUserService u, IWalletService s, CancellationToken c) => Run(() => s.GetPurchaseAsync(id, u.MerchantId, u.CashierId, c))); return e;
    }
    static string Key(HttpRequest r) => r.Headers["Idempotency-Key"].ToString();
    static async Task<IResult> Run<T>(Func<Task<T>> f, int status = 200) { try { var value = await f(); return status == 201 ? Results.Json(value, statusCode: 201) : Results.Ok(value); } catch (Exception x) { return Error(x); } }
    static IResult Error(Exception x) => x switch { IdempotencyConflictException => Results.Problem(statusCode: 409, title: "Idempotency conflict", detail: x.Message), PurchaseRejectedException p => Results.Problem(statusCode: 422, title: p.Code, detail: p.Message), ArgumentException => Results.Problem(statusCode: 400, title: "Invalid request", detail: x.Message), KeyNotFoundException => Results.Problem(statusCode: 404, title: "Not found", detail: x.Message), UnauthorizedAccessException => Results.Problem(statusCode: 403, title: "Forbidden", detail: x.Message), _ => Results.Problem(statusCode: 409, title: "Operation rejected", detail: x.Message) };
}
