namespace CreatorPay.Application.Checkout;

public sealed class CheckoutOptions { public const string SectionName = "Checkout"; public int LifetimeMinutes { get; set; } = 3; public int RepeatUseApprovalLifetimeMinutes { get; set; } = 15; public decimal CashbackPayoutThreshold { get; set; } = 1000m; public string CurrencyCode { get; set; } = "ETB"; }
public sealed record RegisterCustomerRequest(string DisplayName, string Email, string PhoneNumber, string Password, string Confirmation);
public sealed record CreateCheckoutRequest(Guid CampaignId);
public sealed record CreateOfferCheckoutRequest(string OfferCode);
public sealed record PresentCheckoutRequest(string QrPayload, Guid MerchantLocationId, decimal PurchaseAmount);
public sealed record CreateRepeatUseApprovalRequest(Guid CheckoutId, string Reason);
public sealed record DecideRepeatUseApprovalRequest(string Reason);
public sealed record RepeatUseApprovalDto(Guid Id, string PublicApprovalRequestId, Guid CheckoutId, string Status, string MaskedPhoneNumber, string Reason, DateTime RequestedAtUtc, DateTime ExpiresAtUtc, Guid? DecidedByUserId, DateTime? DecidedAtUtc);
public sealed record CheckoutDto(Guid Id, string PublicCheckoutId, string Status, Guid CustomerId, Guid CampaignId, Guid MerchantId, Guid CreatorId, decimal? PurchaseAmount, decimal? CreatorAmount, decimal? CashbackAmount, DateTime ExpiresAtUtc, Guid? PurchaseTransactionId, string? QrPayload = null);
public sealed record CustomerWalletDto(decimal AvailableCashback, decimal ReservedCashback, decimal PaidLifetime, decimal RecoveryBalance, string CurrencyCode);
public sealed record CustomerPayoutDto(Guid Id, string PublicPayoutId, decimal Amount, string CurrencyCode, string Status, DateTime RequestedAtUtc, DateTime? PaidAtUtc, string? ExternalReference);
public sealed record MarkCustomerPayoutPaidRequest(string ExternalMethod, string ExternalReference, DateTime PaidAtUtc, string? SafeNote);
public interface ICheckoutService { Task<Guid> RegisterCustomerAsync(RegisterCustomerRequest request, CancellationToken ct); Task<CheckoutDto> CreateAsync(Guid customerId, string idempotencyKey, CreateCheckoutRequest request, CancellationToken ct); Task<CheckoutDto> CreateFromOfferAsync(Guid customerId, string idempotencyKey, CreateOfferCheckoutRequest request, CancellationToken ct); Task<CheckoutDto> PresentAsync(Guid merchantId, Guid cashierId, string idempotencyKey, PresentCheckoutRequest request, CancellationToken ct); Task<CheckoutDto> ApproveAsync(Guid customerId, Guid id, string idempotencyKey, CancellationToken ct); Task<CheckoutDto> RejectAsync(Guid customerId, Guid id, CancellationToken ct); Task<IReadOnlyList<CheckoutDto>> GetCustomerCheckoutsAsync(Guid customerId, CancellationToken ct); Task<CustomerWalletDto> GetWalletAsync(Guid customerId, CancellationToken ct); Task<CustomerPayoutDto> RequestPayoutAsync(Guid customerId, string idempotencyKey, CancellationToken ct); Task<IReadOnlyList<CustomerPayoutDto>> GetPayoutsAsync(Guid? customerId, CancellationToken ct); Task<CustomerPayoutDto> MarkPayoutProcessingAsync(Guid id, Guid actor, CancellationToken ct); Task<CustomerPayoutDto> MarkPayoutPaidAsync(Guid id, Guid actor, string idempotencyKey, MarkCustomerPayoutPaidRequest request, CancellationToken ct); Task<CustomerPayoutDto> MarkPayoutFailedAsync(Guid id, Guid actor, string reason, CancellationToken ct); Task<int> ExpireAsync(CancellationToken ct); }
