import test from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
const read=name=>readFileSync(new URL(`../src/${name}`,import.meta.url),'utf8')
const chrome=read('AccountChrome.tsx'),creator=read('CreatorDashboard.tsx'),business=read('BusinessDashboard.tsx'),confirmedSales=read('ConfirmedSalesWorkspace.tsx'),shopper=read('CustomerWorkspace.tsx'),roleNav=read('RoleNavigation.tsx'),auth=read('AuthWorkspace.tsx'),pin=read('PinExperience.tsx'),api=read('apiClient.ts'),lifecycle=read('mobileLifecycle.ts'),styles=read('styles.css'),actionable=read('actionableRefresh.ts'),adminPortal=read('AdminPortal.tsx')

test('all customer roles use compact accessible account chrome',()=>{for(const source of [creator,business,shopper])assert.match(source,/AccountChrome/);for(const label of ['aria-label="Notifications"','aria-label="Settings"','Help','Sign out'])assert.match(chrome,new RegExp(label));assert.doesNotMatch(chrome,/role="menuitem"[^>]*>\s*<span>Profile<\/span>/);assert.match(chrome,/unread\s*>\s*0\s*&&\s*<span className="notification-count"/);assert.match(chrome,/className="signout-action"/);assert.match(styles,/min-width:2\.85rem/)})
test('settings menu closes from every shared authenticated account shell path',()=>{assert.match(chrome,/settingsRef/);assert.match(chrome,/pointerdown/);assert.doesNotMatch(chrome,/setSettingsOpen\(false\);onProfile\(\)/);assert.match(chrome,/setSettingsOpen\(false\);\s*void enablePushNotifications\(/);assert.match(chrome,/setSettingsOpen\(false\);\s*onHelp\(\)/);assert.match(chrome,/setSettingsOpen\(false\);\s*onSignOut\(\)/);assert.match(chrome,/setSettingsOpen\(!settingsOpen\)\s*setNotificationsOpen\(false\)/)})
test('notification read state and background refresh use the persisted API',()=>{for(const route of ['/api/v1/notifications?page=1&pageSize=30','/api/v1/notifications/unread-count','/read-all'])assert.ok(chrome.includes(route));assert.match(chrome,/setInterval\(\(\)=>\{[^}]+\},12_000\)/);for(const event of ['online','visibilitychange','weymela:app-resume'])assert.ok(chrome.includes(event)||lifecycle.includes(event));assert.match(chrome,/Mark all as read/)})
test('shared notification controls reject legacy green touch-hover while preserving role focus and red badges',()=>{for(const className of ['notification-trigger','notification-close','notification-item','notification-action','settings-notification-row'])assert.match(chrome,new RegExp(className));assert.match(styles,/Shared notification controls never inherit legacy green touch-hover states/);assert.match(styles,/\.account-shell \.notification-trigger[\s\S]*-webkit-user-select: none;[\s\S]*-webkit-touch-callout: none;[\s\S]*-webkit-tap-highlight-color: transparent;/);assert.match(styles,/\.account-shell \.notification-count \{[\s\S]*background: #d8322b !important;[\s\S]*color: #fff !important;/);assert.match(styles,/\.account-shell \.notification-trigger:focus-visible,[\s\S]*outline: 3px solid var\(--role-accent\)/);assert.match(styles,/@media \(hover: hover\) and \(pointer: fine\) \{[\s\S]*\.account-shell \.notification-item:hover/);assert.doesNotMatch(styles,/\.account-shell \.notification-item[^}]*background:\s*#205d39/)})
test('subsequent actionable notifications invalidate every mounted role workspace',()=>{assert.match(actionable,/weymela:actionable-refresh/);for(const source of [shopper,creator,business])assert.match(source,/onActionableRefresh/);assert.match(chrome,/requestActionableRefresh\(\)/);assert.match(chrome,/requestActionableRefresh\(\);const target/);assert.match(chrome,/requestActionableRefresh\(\)\s*if\s*\(!notificationsOpen\)/)})
test('role navigation and customer financial summaries are intentionally minimal',()=>{assert.match(creator,/label: 'Home'/);assert.match(creator,/Find Businesses/);assert.match(creator,/Active Ads/);assert.match(creator,/Requests/);assert.match(creator,/Payout/);assert.match(creator,/Profile/);assert.match(creator,/Confirmed Sales/);assert.doesNotMatch(creator,/\['overview'|\['creator-id'/);assert.match(creator,/Creator ID/);assert.doesNotMatch(creator,/Reserved Payout|Last Payout Date/);assert.match(business,/Creators/);assert.match(business,/Active Ads/);assert.match(business,/Requests/);assert.match(business,/Checkout/);assert.match(business,/Profile/);assert.match(business,/Confirmed Sales/);assert.match(business,/Wallet/);assert.doesNotMatch(business,/\['overview'/);assert.match(confirmedSales,/Cashier/);assert.doesNotMatch(confirmedSales,/Processed By|Actor Name|<th>Actor<\/th>/);assert.match(chrome,/Cashier Management/);assert.match(business,/onManagement=\{\(\)=>setTab\('cashiers'\)\}/);assert.match(shopper,/Discover Promotions/);assert.match(shopper,/Cashback/);assert.match(shopper,/Profile/);const discovery=shopper.slice(shopper.indexOf("view==='discover'"),shopper.indexOf("view==='confirmations'")),summary=shopper.slice(shopper.indexOf('function Summary'),shopper.indexOf('function ShopperProfileCard'));assert.doesNotMatch(discovery,/data-label="Status"|data-label="Days Left"/);assert.doesNotMatch(summary,/Reserved Payout|Last Payout Date|Confirmed Purchases/)})
test('primary navigation uses the shared role nav and polished explicit icon sizing',()=>{for(const source of [creator,business,shopper])assert.match(source,/RoleNavigation/);assert.match(roleNav,/const activeItemId = items\.find/);assert.match(roleNav,/aria-current=\{isActive \? 'page' : undefined\}/);assert.match(roleNav,/NavIcon name=\{item\.icon\} size=\{24\}/);assert.match(roleNav,/workspace-nav-icon/);assert.match(roleNav,/workspace-nav/);assert.match(styles,/\.workspace-nav-icon svg\{width:24px;height:24px;flex-shrink:0;stroke:currentColor;fill:none\}/);assert.match(styles,/\.account-shell \.workspace-nav button\.is-active \{/);assert.match(styles,/background: transparent;/);assert.match(styles,/button\.is-active::after/);assert.doesNotMatch(styles,/\.nav-icon svg\{width:100%;height:100%/);assert.match(styles,/\.account-shell \.workspace-nav button:focus-visible/)})
test('registration presentation no longer collects birth date or legal business name',()=>{const registration=auth.slice(auth.indexOf("mode==='customer'"));assert.doesNotMatch(registration,/birthFields\(shopper|birthFields\(creator|birthFields\(business|Legal Business Name/);assert.match(auth,/Sign Up to Weymela/);assert.match(pin,/Create 5-digit PIN/);assert.doesNotMatch(pin,/Create your 5-digit PIN/)})
test('shared API client refreshes once before ending an expired session',()=>{assert.match(api,/response\.status===401&&retry&&await refreshAccessToken\(\)/);assert.match(shopper,/api as request/);assert.doesNotMatch(shopper,/handleUnauthorized/)})
test('admin account deletion keeps the delete action and success copy wired in the frontend',()=>{
  assert.match(adminPortal,/action\(x\.id, "delete"\)/)
  assert.match(adminPortal,/Account deleted and anonymized\./)
  assert.match(adminPortal,/Unable to change this account\./)
  assert.match(adminPortal,/delete/);
})

test('admin cleanup keeps password reset tools and business type correction wired in the frontend',()=>{
  assert.match(adminPortal,/password-reset-requests/)
  assert.match(adminPortal,/Delete Request/)
  assert.match(adminPortal,/Edit Business Type/)
  assert.match(adminPortal,/allowBusinessTypeEdit=\{role === "PlatformAdmin"\}/)
  assert.doesNotMatch(adminPortal,/showPasswordResets/)
  assert.doesNotMatch(adminPortal,/showPasswordResets=\{true\}/)
  assert.match(adminPortal,/columns=\{\["name", "email", "phone", "role", "status", "isLocked", "lastLoginAtUtc"\]\}/)
  assert.match(adminPortal,/columns=\{\["name", "email", "phone", "businessName", "publicBusinessId", "merchantBusinessType", "isLocked", "lastLoginAtUtc"\]\}/)
  assert.doesNotMatch(adminPortal,/columns=\{\["name", "email", "phone", "businessName", "publicBusinessId", "merchantBusinessType", "status", "isLocked", "lastLoginAtUtc"\]\}/)
  assert.match(adminPortal,/columns=\{\["name", "publicCreatorId", "email", "phone", "status", "isLocked", "lastLoginAtUtc"\]\}/)
  assert.match(adminPortal,/columns=\{\["name", "publicCustomerId", "email", "phone", "status", "isLocked", "lastLoginAtUtc"\]\}/)
  assert.doesNotMatch(adminPortal,/walletBalance/)
  assert.doesNotMatch(adminPortal,/fundingStatus/)
  assert.doesNotMatch(adminPortal,/isEmailVerified/)
  assert.doesNotMatch(adminPortal,/isPhoneVerified/)
})
