import test from 'node:test'
import assert from 'node:assert/strict'
import {readFile} from 'node:fs/promises'
import {repoPath} from './repoPath.mjs'

test('admin operations exposes the simplified secure pilot navigation',async()=>{
  const source=await readFile(new URL('../src/AdminPortal.tsx',import.meta.url),'utf8')
  const auth=await readFile(new URL('../src/AuthWorkspace.tsx',import.meta.url),'utf8')
  for(const item of ['Dashboard','Reports','Creator Review','Business Review','Admin Accounts','Password Reset Requests','Business Accounts','Creator Accounts','Customer Accounts','Cashier Accounts','Commission','Deposits','Wallets','Payouts','Fraud','System']) assert.match(source,new RegExp(item))
  for(const route of ['creator-review','business-review','admin-accounts','password-reset-requests','business-accounts','creator-accounts','customer-accounts','cashier-accounts','notifications','disputes','reversals']) assert.match(source,new RegExp(route))
  for(const role of ['PlatformAdmin','OperationsAdmin']) assert.match(source,new RegExp(role))
  assert.match(source,/const operationsBlockedPages: PageId\[] = \["dashboard", "reports", "admin-accounts", "commission", "system"\]/)
  assert.match(source,/id: "commission", label: "Commission", roles: \["PlatformAdmin"\]/)
  assert.match(source,/id: "system", label: "System", roles: \["PlatformAdmin"\]/)
  assert.match(source,/const visibleNav = platformNav\.filter\(\(item\) => role === "PlatformAdmin" \|\| item\.roles\.includes\(role\)\)/)
  assert.match(source,/showSearch=\{role === "PlatformAdmin"\}/)
  for(const create of ['createRoles=\\{\\[\\s*"PlatformAdmin"\\s*\\]\\}','createRoles=\\{\\[\\s*"MerchantAdmin"\\s*\\]\\}','createRoles=\\{\\[\\s*"Creator"\\s*\\]\\}','createRoles=\\{\\[\\s*"Customer"\\s*\\]\\}','createRoles=\\{\\[\\s*"Cashier"\\s*\\]\\}']) assert.match(source,new RegExp(create))
  assert.doesNotMatch(source,/\['transactions','Transactions'\]/)
  for(const removed of ["'Support'","'Pilot feedback'","'Partnerships'","'Repeat use'","'Offline sync'","'Audit log'"]) assert.doesNotMatch(source,new RegExp(removed))
  const reports=await readFile(new URL('../src/ReportingWorkspace.tsx',import.meta.url),'utf8')
  assert.match(reports,/financial-summary/)
  assert.match(source,/Deactivate/)
  const commission=await readFile(new URL('../src/CommissionWorkspace.tsx',import.meta.url),'utf8')
  assert.match(commission,/const admin = role === "PlatformAdmin"/)
  assert.match(commission,/Minimum Business Wallet Balance by Business Type/)
  assert.match(commission,/Minimum Wallet Balance \(ETB\)/)
  assert.match(commission,/Minimum TikTok Followers/)
  assert.match(commission,/Split of that commission/)
  assert.match(commission,/Save Settings/)
  assert.match(commission,/percentages must total 100%/)
  for(const scheduleControl of ['Creator Payout — Weekly','Shopper Payout — Monthly','Cutoff Day','Cutoff Time','Payout Day','Effective','Now','Schedule for later','Schedule Effective From']) assert.match(commission,new RegExp(scheduleControl))
  assert.doesNotMatch(commission,/Minimum Business Wallet Balance = 1200 ETB/)
  const api=await readFile(repoPath(import.meta.url,'src/CreatorPay.Api/Admin/AdminEndpoints.cs'),'utf8')
  for(const signal of ['failedCheckouts','pendingPayouts','openFraudAlerts','systemHealth','FinancialSummary','fundingStatus']) assert.match(api,new RegExp(signal))
  for(const cashierField of ['cashierName','businessName','publicBusinessId','assignedLocation']) assert.match(source,new RegExp(cashierField))
  assert.match(source,/cashierName/)
  assert.match(source,/label\(value\)/)
  assert.match(source,/Disable Cashier/)
  assert.match(api,/MerchantCashiers/)
  for(const accountFilter of ['General Search','All statuses','Business name or public ID','Clear Filters']) assert.match(source,new RegExp(accountFilter))
  for(const wrapper of ['AdminAccountsPage','AccountPage','PasswordResetRequests']) assert.match(source,new RegExp(wrapper))
  assert.match(source,/allowRemove=\{role === "PlatformAdmin"\}/)
  assert.match(source,/allowBusinessTypeEdit=\{role === "PlatformAdmin"\}/)
  assert.match(source,/allowBusinessTypeEdit && Boolean\(x\.merchantId\)/)
  assert.doesNotMatch(source,/allowBusinessTypeEdit && x\.role === "MerchantAdmin" && Boolean\(x\.merchantId\)/)
  const styles=await readFile(new URL('../src/styles.css',import.meta.url),'utf8')
  assert.match(styles,/\.admin-main td\[data-label="Action"\] \.actions\{display:flex;flex-wrap:nowrap;align-items:center;justify-content:flex-start;gap:\.45rem;margin-top:0;max-width:100%;overflow-x:auto;white-space:nowrap\}/)
  assert.match(styles,/\.admin-main td\[data-label="Action"\] \.actions button\{min-width:0;white-space:nowrap\}/)
  assert.match(source,/columns=\{\["name", "email", "phone", "businessName", "publicBusinessId", "merchantBusinessType", "isLocked", "lastLoginAtUtc"\]\}/)
  assert.doesNotMatch(source,/columns=\{\["name", "email", "phone", "businessName", "publicBusinessId", "merchantBusinessType", "status", "isLocked", "lastLoginAtUtc"\]\}/)
  assert.match(source,/columns=\{\["name", "publicCreatorId", "email", "phone", "status", "isLocked", "lastLoginAtUtc"\]\}/)
  assert.match(source,/columns=\{\["name", "publicCustomerId", "email", "phone", "status", "isLocked", "lastLoginAtUtc"\]\}/)
  assert.match(source,/columns=\{\["name", "email", "phone", "businessName", "publicBusinessId", "assignedLocation", "status", "isLocked", "lastLoginAtUtc"\]\}/)
  assert.match(source,/roles=\{\[\s*"PlatformAdmin"\s*\]\}/)
  assert.match(source,/roles=\{\[\s*"MerchantAdmin"\s*,\s*"Supervisor"\s*\]\}/)
  assert.match(source,/roles=\{\[\s*"Creator"\s*\]\}/)
  assert.match(source,/roles=\{\[\s*"Customer"\s*\]\}/)
  assert.match(source,/roles=\{\[\s*"Cashier"\s*\]\}/)
  assert.match(source,/password-reset-requests", label: "Password Reset Requests", roles: adminRoles, countKey: "openSupportRequests"/)
  assert.doesNotMatch(source,/admin-accounts", label: "Admin Accounts", roles: \["PlatformAdmin"\], countKey: "openSupportRequests"/)
  assert.match(source,/openSupportRequests/)
  assert.match(source,/allowCreate=\{role === "PlatformAdmin"\}/)
  assert.doesNotMatch(source,/showPasswordResets/)
  assert.doesNotMatch(source,/<PasswordResetRequests \/>\s*<\/AccountPage>/)
  assert.match(source,/className="help-dialog admin-business-type-editor"/)
  assert.match(source,/role="dialog"/)
  assert.match(source,/aria-labelledby="business-type-editor-title"/)
  assert.match(source,/Current Business Type:/)
  assert.match(source,/New Business Type/)
  assert.match(source,/setEditing\(\{[\s\S]*merchantId: String\(x\.merchantId\)/)
  assert.match(source,/setEditingBusinessType\(String\(x\.merchantBusinessType \?\? "Other"\)\)/)
  assert.match(source,/setMessage\("Business Type updated\."\)/)
  assert.match(source,/sr-only">Action<\/span>/)
  assert.match(source,/sr-only">Status<\/span>/)
  assert.match(source,/blockedByRole/)
  assert.doesNotMatch(source,/walletBalance/)
  assert.doesNotMatch(source,/fundingStatus/)
  assert.doesNotMatch(source,/isEmailVerified/)
  assert.doesNotMatch(source,/isPhoneVerified/)
  assert.match(source,/Delete Request/)
  assert.match(source,/Edit Business Type/)
  const create=await readFile(new URL('../src/AdminAccountCreate.tsx',import.meta.url),'utf8')
  for(const businessType of ['Restaurant / Café','Grocery / Mini-market','Clothing / Boutique','Beauty / Salon','Furniture','Electronics','Hotel / Travel','Professional Services','Other']) assert.match(auth,new RegExp(businessType))
  assert.match(create,/businessTypes\.map/)
  assert.match(create,/Business type[\s\S]*<select/)
  const payouts=await readFile(new URL('../src/EarningsWorkspace.tsx',import.meta.url),'utf8')
  for(const label of ['Cycle Start','Cutoff','Payout Date','Eligible/Scheduled Total','Reserved/In Batch','Paid This Cycle','Creator Name','Creator ID','Eligible Amount','Customer Name','Eligible Cashback','Payout Status','UNPAID','Search Creator Name or Creator ID','Search Customer Name','Clear','Period Start','Period End','Transactions','Platform Revenue','Platform Revenue History'])assert.match(payouts,new RegExp(label))
  assert.match(payouts,/payout-batches\/\$\{line\.payoutBatchId\}\/process/)
  assert.match(payouts,/customer-payouts\/\$\{line\.payoutId\}\/processing/)
  assert.match(payouts,/Confirm this payout has been sent\?/)
  assert.match(payouts,/!x\.payoutId \|\|\s*x\.reservedAmount <= 0/)
  assert.match(payouts,/tab === "revenue"[\s\S]*platform-revenue/)
  assert.doesNotMatch(payouts,/payout-cycles\/\$\{tab\}[\s\S]*platform-revenue.*Promise\.all/)
  assert.match(source,/lastDeposit/)
  assert.match(source,/day:\s*"2-digit",\s*month:\s*"2-digit",\s*year:\s*"numeric"/)
  assert.match(source,/hiddenPages/)
  assert.match(source,/operations\[page\]/)
})
