import test from 'node:test'
import assert from 'node:assert/strict'
import {readFile} from 'node:fs/promises'
import {repoPath} from './repoPath.mjs'

test('admin operations exposes the simplified secure pilot navigation',async()=>{
  const source=await readFile(new URL('../src/AdminPortal.tsx',import.meta.url),'utf8')
  for(const item of ['Dashboard','Reports','Creator Review','Business Review','Admin Accounts','Business Accounts','Creator Accounts','Customer Accounts','Cashier Accounts','Commission','Deposits','Wallets','Payouts','Fraud','System']) assert.match(source,new RegExp(item))
  for(const route of ['creator-review','business-review','admin-accounts','business-accounts','creator-accounts','customer-accounts','cashier-accounts','notifications','disputes','reversals']) assert.match(source,new RegExp(route))
  for(const role of ['PlatformAdmin','OperationsAdmin']) assert.match(source,new RegExp(role))
  assert.match(source,/const operationsBlockedPages: PageId\[] = \["dashboard", "reports", "admin-accounts"\]/)
  assert.match(source,/const visibleNav = platformNav\.filter\(\(item\) => role === "PlatformAdmin" \|\| item\.roles\.includes\(role\)\)/)
  assert.match(source,/showSearch=\{role === "PlatformAdmin"\}/)
  for(const create of ['createRoles=\\{\\[\\s*"PlatformAdmin"\\s*,\\s*"OperationsAdmin"\\s*\\]\\}','createRoles=\\{\\[\\s*"MerchantAdmin"\\s*\\]\\}','createRoles=\\{\\[\\s*"Creator"\\s*\\]\\}','createRoles=\\{\\[\\s*"Customer"\\s*\\]\\}','createRoles=\\{\\[\\s*"Cashier"\\s*\\]\\}']) assert.match(source,new RegExp(create))
  assert.doesNotMatch(source,/\['transactions','Transactions'\]/)
  for(const removed of ["'Support'","'Pilot feedback'","'Partnerships'","'Repeat use'","'Offline sync'","'Audit log'"]) assert.doesNotMatch(source,new RegExp(removed))
  const reports=await readFile(new URL('../src/ReportingWorkspace.tsx',import.meta.url),'utf8')
  assert.match(reports,/financial-summary/)
  assert.match(source,/Deactivate/)
  const commission=await readFile(new URL('../src/CommissionWorkspace.tsx',import.meta.url),'utf8')
  assert.match(commission,/Minimum Business Wallet Balance/)
  assert.match(commission,/Minimum TikTok Followers/)
  assert.match(commission,/Split of that commission/)
  assert.match(commission,/Save Settings/)
  assert.match(commission,/percentages must total 100%/)
  for(const scheduleControl of ['Creator Payout — Weekly','Shopper Payout — Monthly','Cutoff Day','Cutoff Time','Payout Day','Schedule Effective From']) assert.match(commission,new RegExp(scheduleControl))
  const api=await readFile(repoPath(import.meta.url,'src/CreatorPay.Api/Admin/AdminEndpoints.cs'),'utf8')
  for(const signal of ['failedCheckouts','pendingPayouts','openFraudAlerts','systemHealth','FinancialSummary','fundingStatus']) assert.match(api,new RegExp(signal))
  for(const cashierField of ['cashierName','businessName','publicBusinessId','assignedLocation']) assert.match(source,new RegExp(cashierField))
  assert.match(source,/cashierName/)
  assert.match(source,/label\(value\)/)
  assert.match(source,/Disable Cashier/)
  assert.match(api,/MerchantCashiers/)
  for(const accountFilter of ['General Search','All statuses','Business name or public ID','Clear Filters']) assert.match(source,new RegExp(accountFilter))
  for(const wrapper of ['AdminAccountsPage','AccountPage','PasswordResetRequests']) assert.match(source,new RegExp(wrapper))
  assert.match(source,/roles=\{\[\s*"PlatformAdmin"\s*,\s*"OperationsAdmin"\s*\]\}/)
  assert.match(source,/roles=\{\[\s*"MerchantAdmin"\s*,\s*"Supervisor"\s*\]\}/)
  assert.match(source,/roles=\{\[\s*"Creator"\s*\]\}/)
  assert.match(source,/roles=\{\[\s*"Customer"\s*\]\}/)
  assert.match(source,/roles=\{\[\s*"Cashier"\s*\]\}/)
  assert.match(source,/openSupportRequests/)
  assert.match(source,/allowCreate=\{role === "PlatformAdmin"\}/)
  assert.match(source,/showPasswordResets/)
  assert.match(source,/sr-only">Action<\/span>/)
  assert.match(source,/sr-only">Status<\/span>/)
  assert.match(source,/blockedByRole/)
  assert.doesNotMatch(source,/isEmailVerified/)
  assert.doesNotMatch(source,/isPhoneVerified/)
  const payouts=await readFile(new URL('../src/EarningsWorkspace.tsx',import.meta.url),'utf8')
  for(const label of ['Cycle Start','Cutoff','Payout Date','Eligible/Scheduled Total','Reserved/In Batch','Paid This Cycle','Creator Name','Creator ID','Eligible Amount','Customer Name','Eligible Cashback','Payout Status','UNPAID','Search Creator Name or Creator ID','Search Customer Name','Clear','Period Start','Period End','Transactions','Platform Revenue','Platform Revenue History'])assert.match(payouts,new RegExp(label))
  assert.match(payouts,/payout-batches\/\$\{line\.payoutBatchId\}\/process/)
  assert.match(payouts,/customer-payouts\/\$\{line\.payoutId\}\/processing/)
  assert.match(payouts,/Confirm this payout has been sent\?/)
  assert.match(payouts,/!x\.payoutId \|\|\s*x\.reservedAmount <= 0/)
  assert.match(payouts,/tab === "revenue"[\s\S]*platform-revenue/)
  assert.doesNotMatch(payouts,/payout-cycles\/\$\{tab\}[\s\S]*platform-revenue.*Promise\.all/)
  assert.match(source,/lastDeposit/)
  assert.match(source,/day:\s*"2-digit",\s*month:\s*"2-digit",\s*year:\s*"numeric"/)
  assert.match(source,/hiddenPages/)
  assert.match(source,/operations\[page\]/)
})
