import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
const experience=fs.readFileSync(new URL('../src/PilotExperience.tsx',import.meta.url),'utf8')
const styles=fs.readFileSync(new URL('../src/styles.css',import.meta.url),'utf8')
const wallet=fs.readFileSync(new URL('../src/WalletWorkspace.tsx',import.meta.url),'utf8')
const main=fs.readFileSync(new URL('../src/main.tsx',import.meta.url),'utf8')
const creatorAds=fs.readFileSync(new URL('../src/CreatorAdvertising.tsx',import.meta.url),'utf8')
const creatorDashboard=fs.readFileSync(new URL('../src/CreatorDashboard.tsx',import.meta.url),'utf8')
const businessAds=fs.readFileSync(new URL('../src/BusinessAdvertising.tsx',import.meta.url),'utf8')
const relationshipTime=fs.readFileSync(new URL('../src/relationshipTime.ts',import.meta.url),'utf8')
const cashier=fs.readFileSync(new URL('../src/CashierCheckoutWorkspace.tsx',import.meta.url),'utf8')
const auth=fs.readFileSync(new URL('../src/AuthWorkspace.tsx',import.meta.url),'utf8')
const qr=fs.readFileSync(new URL('../src/QrWorkspace.tsx',import.meta.url),'utf8')
const qrDecoder=fs.readFileSync(new URL('../src/qrImageDecoder.ts',import.meta.url),'utf8')
const onboarding=fs.readFileSync(new URL('../src/OnboardingStatus.tsx',import.meta.url),'utf8')
const compact=value=>value.replace(/\s+/g,'')
const experienceCompact=compact(experience),mainCompact=compact(main),walletCompact=compact(wallet),stylesCompact=compact(styles),qrDecoderCompact=compact(qrDecoder)

test('pilot experience supports every operational role in English',()=>{
  for(const role of ['Shopper','Creator','Business Owner','Cashier','Supervisor'])assert.ok(experience.includes(`'${role}'`))
  assert.doesNotMatch(experience,/[\u1200-\u137f]|Locale='en'\|'am'/)
})
test('offline, feedback, toast, and anonymous UX support remain available',()=>{
  for(const item of ['navigator.onLine','creatorpay_access_token','weymela:toast','weymela:ux','/api/v1/pilot/feedback'])assert.ok(experience.includes(item))
  assert.doesNotMatch(experience,/analytics.*(?:email|phone|displayName)/i)
})
test('Creator and Business dashboards have one header Help link and no feedback tools',()=>{
  assert.match(experienceCompact,/role===["']Creator["']\|\|role===["']BusinessOwner["']/)
  assert.match(experienceCompact,/!dashboardRole/)
  assert.match(mainCompact,/HelpLinkcategory=\{creator\?["']ContentCreators["']:["']Businesses["']\}/)
})
test('Business Wallet uses the shared API client and friendly errors',()=>{
  assert.match(wallet,/import \{api,apiBlob\} from '\.\/apiClient'/)
  assert.doesNotMatch(wallet,/fetch\(/)
  assert.match(wallet,/This section is temporarily unavailable\./)
})
test('pilot deposits use image proof and Business controls advertising state',()=>{
  assert.match(wallet,/Upload Proof of Payment/)
  assert.match(wallet,/accept="image\/jpeg,image\/png,image\/webp"/)
  assert.doesNotMatch(wallet,/Bank \/ reference number|Proof metadata/)
  assert.match(wallet,/Pending Review/)
  assert.match(wallet,/\/api\/v1\/admin\/deposits'/)
  for(const label of ['Business','Amount','Submitted','Status','Proof','Action','View Proof','Approve','Reject'])assert.match(wallet,new RegExp(label))
  assert.match(businessAds,/Deactivate Ad/)
  assert.match(businessAds,/Reactivate Ad/)
  assert.match(businessAds,/Activate Ad/)
  assert.doesNotMatch(creatorAds,/Deactivate Ad/)
})
test('Creator Ads preserves historical performance without exposing Shopper or purchase details',()=>{
  for(const label of ['Ads','Business','Status','Days Left','Confirmed Sales','Creator Earned','TOTAL','Confirmed Transactions','Search Business'])assert.match(creatorAds,new RegExp(label))
  for(const status of ['Active','Deactivated','Expired'])assert.match(creatorAds,new RegExp(status))
  assert.match(creatorAds,/\/api\/v1\/creator\/ads\/performance/)
  assert.doesNotMatch(creatorAds,/purchaseAmount|shopper|phone|customer/i)
  assert.doesNotMatch(creatorDashboard,/\['ads','Active Ads'\]|Confirmed Sales — Current Period/)
  assert.match(creatorDashboard,/\['ads','Ads'\]/)
  for(const label of ['Payout Amount','Pending Requests','Reserved Payout'])assert.match(creatorDashboard,new RegExp(label))
})
test('Business creates phone-first Cashier credentials without email invitation delivery',()=>{
  for(const label of ['Create Cashier','Cashier Name','Phone Number','Temporary Password','Confirm Temporary Password','Location / Branch (Optional)','Cashier account created.','Disable','Reactivate'])assert.ok(main.includes(label))
  assert.doesNotMatch(main,/Username<input/)
  assert.match(main,/\/api\/v1\/merchant\/cashiers/)
  assert.match(mainCompact,/locationName:locationName\.trim\(\)\|\|null/)
  assert.doesNotMatch(main,/Business Location<select required|Send Invitation|Copy invitation link/)
  for(const label of ['New Purchase','Recent Transactions','Profile','Creator ID','Customer Phone Number','Status:</strong> Eligible','Purchase Amount (ETB)','Submit Purchase'])assert.ok(cashier.includes(label))
  for(const label of ['placeholder="Creator ID"','placeholder="Customer Phone Number"','placeholder="Purchase Amount"','cashier-transaction-row','Amount','Status','Date','Time'])assert.ok(cashier.includes(label))
  assert.doesNotMatch(cashier,/placeholder="4827"|placeholder="0912345678"|publicTransactionId\}<\/small>/)
  assert.doesNotMatch(businessAds,/data-label="Confirmed Sales"|data-label="Commission Generated"/)
  assert.doesNotMatch(cashier,/merchantLocationId|Take Photo of QR|type="file"|decodeQrImage/)
  assert.match(cashier,/\/api\/v1\/cashier\/checkouts\/validate-creator/)
  assert.match(cashier,/\/api\/v1\/cashier\/checkouts\/by-creator/)
  assert.match(cashier,/Shopper account not found\./)
  assert.doesNotMatch(auth,/type Mode=.*cashier/)
})
test('Business Cashier creation uses POST, friendly errors, and shared responsive table columns',()=>{
  assert.match(mainCompact,/\/api\/v1\/merchant\/cashiers["'],\{method:["']POST["']/)
  for(const message of ['Unable to create Cashier.','Please check the information and try again.','Legacy account'])assert.ok(main.includes(message))
  for(const className of ['business-table-row cashier-grid','business-table-row business-active-grid'])assert.ok(main.includes(className)||businessAds.includes(className))
  assert.match(stylesCompact,/\.business-table-row\{[^}]*grid-template-columns:var\(--business-table-columns\)/)
  assert.match(stylesCompact,/\.cashier-grid\{--business-table-columns:[^}]+\}/)
  assert.match(stylesCompact,/\.business-active-grid\{--business-table-columns:[^}]+\}/)
  assert.match(stylesCompact,/@media\(max-width:650px\)\{\.business-table-row\.headings[^}]*display:none/)
  assert.match(stylesCompact,/\.business-table-row,\.cashier-list\.business-table-row\{grid-template-columns:1fr/)
})
test('checkout survey remains authenticated and English-only',()=>{
  assert.match(experience,/\/api\/v1\/pilot\/checkout-survey/)
  assert.match(experience,/Authorization:`Bearer/)
  assert.match(experience,/languageCode:'en'/)
})
test('accessibility and mobile safeguards remain present',()=>{
  for(const item of ['role="alert"','aria-pressed'])assert.ok(experience.includes(item))
  assert.match(styles,/prefers-reduced-motion:reduce/)
  assert.match(styles,/forced-colors:active/)
  assert.match(styles,/@media\s*\(max-width:600px\)/)
  assert.match(styles,/\.creator-tabs button\.active[^}]*color:#fff/)
  assert.match(styles,/\.shopper nav button\.active[^}]*color:#fff/)
  assert.match(styles,/\.admin-sidebar nav a\[aria-current=page\][^}]*color:#fff/)
  assert.match(styles,/\.admin-sidebar nav a:focus-visible/)
})
test('Business onboarding uses concise verification wording',()=>{
  assert.match(onboarding,/role==='MerchantAdmin'\?[^:]+Verified/)
  assert.doesNotMatch(onboarding,/role==='MerchantAdmin'[^}]+Email \{data\.isEmailVerified/s)
})
test('Welcome mode changes reset every controlled authentication flow',()=>{
  for(const reset of ['setLogin(loginBlank())','setShopper(shopperBlank())','setCreator(creatorBlank())','setBusiness(businessBlank())','setMessage("")','setForgot(false)','setResetStage("request")','setResetReference("")'])assert.ok(auth.includes(reset))
  assert.match(auth,/onClick=\{\(\)=>changeMode\("login"\)\}/)
  for(const value of ['current-password','new-password','email','tel','name'])assert.ok(auth.includes(`"${value}"`))
})
test('public authentication uses support-approved recovery without verification UX',()=>{
  assert.match(auth,/Welcome back\. Keep shopping, promoting, and earning with Weymela\./)
  assert.match(auth,/Welcome to Weymela — where shoppers save, creators earn, and businesses grow\./)
  for(const value of ['Request Password Reset','Check Approval Status','Contact Weymela Support','mailto:support@weymela.com?subject=Weymela%20Support%20Request','password-reset-requests'])assert.ok(auth.includes(value))
  assert.ok(!auth.includes('admin@weymela.com'))
  assert.doesNotMatch(auth,/Send verification code|Verify your phone|6-digit verification code|code sent to your phone/)
})
test('Creator and Business discovery show relationship status without duplicate actions',()=>{
  for(const label of ['Request Pending','Active Ad','Deactivated','Days Left'])assert.match(creatorAds,new RegExp(label))
  for(const label of ['Invitation Pending','Currently Advertising','Deactivated','Days Left'])assert.match(businessAds,new RegExp(label))
  assert.match(relationshipTime,/Activation Required/)
  assert.match(creatorAds,/canRequest\s*&&/)
  assert.match(businessAds,/canInvite\s*&&/)
  assert.match(styles,/\.discovery-row/)
})
test('Creator dashboard presents the permanent four-digit Creator ID',()=>{
  assert.match(qr,/\/api\/v1\/creators\/me/)
  assert.match(qr,/profile\.creatorCode/)
  assert.match(qr,/Give this Creator ID to the cashier/)
  assert.match(qr,/creator-id-number/)
  assert.doesNotMatch(qr,/apiBlob|Download PNG|Creator QR code/)
  assert.match(styles,/\.creator-id-number\{[^}]*font-size:clamp\(3\.5rem,\s*16vw,\s*7rem\)/)
})
