import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
const experience=fs.readFileSync(new URL('../src/PilotExperience.tsx',import.meta.url),'utf8')
const styles=fs.readFileSync(new URL('../src/styles.css',import.meta.url),'utf8')
const wallet=fs.readFileSync(new URL('../src/WalletWorkspace.tsx',import.meta.url),'utf8')
const main=fs.readFileSync(new URL('../src/main.tsx',import.meta.url),'utf8')
const creatorAds=fs.readFileSync(new URL('../src/CreatorAdvertising.tsx',import.meta.url),'utf8')
const creatorDashboard=fs.readFileSync(new URL('../src/CreatorDashboard.tsx',import.meta.url),'utf8')
const businessAds=fs.readFileSync(new URL('../src/BusinessAdvertising.tsx',import.meta.url),'utf8')
const relationshipTime=fs.readFileSync(new URL('../src/relationshipTime.ts',import.meta.url),'utf8')
const cashier=fs.readFileSync(new URL('../src/CashierCheckoutWorkspace.tsx',import.meta.url),'utf8')
const auth=fs.readFileSync(new URL('../src/AuthWorkspace.tsx',import.meta.url),'utf8')
const qr=fs.readFileSync(new URL('../src/QrWorkspace.tsx',import.meta.url),'utf8')
const onboarding=fs.readFileSync(new URL('../src/OnboardingStatus.tsx',import.meta.url),'utf8')
const compact=value=>value.replace(/\s+/g,'')
const experienceCompact=compact(experience),mainCompact=compact(main),walletCompact=compact(wallet),stylesCompact=compact(styles)

test('pilot experience supports every operational role in English',()=>{
  for(const role of ['Shopper','Creator','Business Owner','Cashier','Supervisor'])assert.ok(experience.includes(`'${role}'`))
  assert.doesNotMatch(experience,/[\u1200-\u137f]|Locale='en'\|'am'/)
})
test('offline, feedback, toast, and anonymous UX support remain available',()=>{
  for(const item of ['navigator.onLine','getAccessToken','weymela:toast','weymela:ux','/api/v1/pilot/feedback'])assert.ok(experience.includes(item))
  assert.doesNotMatch(experience,/analytics.*(?:email|phone|displayName)/i)
})
test('Creator and Business use unified account chrome without duplicate header tools',()=>{
  assert.match(experienceCompact,/role===["']Creator["']\|\|role===["']BusinessOwner["']/)
  assert.match(experienceCompact,/!dashboardRole/)
  assert.doesNotMatch(mainCompact,/HelpLinkcategory=\{creator\?["']ContentCreators["']:["']Businesses["']\}/)
  assert.match(creatorDashboard,/AccountChrome/)
  assert.match(creatorDashboard,/identityMedia=/)
})
test('Business Wallet uses the shared API client and friendly errors',()=>{
  assert.match(wallet,/import \{api,apiBlob\} from '\.\/apiClient'/)
  assert.doesNotMatch(wallet,/fetch\(/)
  assert.match(wallet,/This section is temporarily unavailable\./)
})
test('pilot deposits use image proof and Business controls advertising state',()=>{
  assert.match(wallet,/Upload Proof of Payment/)
  assert.match(wallet,/accept="image\/jpeg,image\/png,image\/webp"/)
  assert.doesNotMatch(wallet,/capture=/)
  assert.match(wallet,/maximumProofBytes=5\*1024\*1024/)
  assert.match(wallet,/proofTypes\.includes\(file\.type\)/)
  assert.match(wallet,/Selected payment proof preview/)
  assert.match(wallet,/proof\.name/)
  assert.doesNotMatch(wallet,/Bank \/ reference number|Proof metadata/)
  assert.match(wallet,/Pending Review/)
  assert.match(wallet,/\/api\/v1\/admin\/deposits'/)
  for(const label of ['Business','Amount','Submitted','Status','Proof','Action','View Proof','Approve','Reject'])assert.match(wallet,new RegExp(label))
  assert.match(businessAds,/Deactivate Ad/)
  assert.match(businessAds,/Active Ads/)
  assert.match(businessAds,/creatorPhoneNumber/)
  assert.match(businessAds,/phoneNumber/)
  assert.match(businessAds,/📍/)
  assert.doesNotMatch(creatorAds,/Deactivate Ad/)
})
test('Creator Ads preserves historical performance without exposing Shopper or purchase details',()=>{
  const activeAds=creatorAds.slice(creatorAds.indexOf('export function ActiveAds'))
  for(const label of ['Ads','Business','Status','Date Activated','Days Left'])assert.match(activeAds,new RegExp(label))
  assert.match(creatorAds,/export function CreatorConfirmedSales/)
  assert.doesNotMatch(creatorAds,/Confirmed Transactions|Search Business/)
  for(const status of ['Active','Deactivated','Expired'])assert.match(creatorAds,new RegExp(status))
  assert.match(creatorAds,/\/api\/v1\/creator\/ads\/performance/)
  assert.doesNotMatch(creatorAds,/purchaseAmount|shopper|phone|customer/i)
  assert.doesNotMatch(activeAds,/Confirmed Sales|Creator Earned|creator-ads-total|No confirmed advertising activity yet/)
  assert.match(activeAds,/No active advertising relationships yet\./)
  assert.doesNotMatch(activeAds,/data-label="Action"/)
  assert.match(creatorDashboard,/Active Ads/)
  for(const label of ['Payout Amount','Pending Requests','Next Payout Date'])assert.match(creatorDashboard,new RegExp(label))
  assert.doesNotMatch(creatorDashboard,/Reserved Payout/)
})
test('Business advertising surfaces creator social media links without changing eligibility behavior',()=>{
  const findCreators=businessAds.slice(businessAds.indexOf('export function FindCreators'),businessAds.indexOf('export function ActiveCreators'))
  const activeAds=businessAds.slice(businessAds.indexOf('export function ActiveCreators'),businessAds.indexOf('export function AdvertisingRequests'))
  const requests=businessAds.slice(businessAds.indexOf('export function AdvertisingRequests'))
  assert.match(findCreators,/business-discovery-card/)
  assert.match(findCreators,/business-card-meta/)
  assert.match(activeAds,/table-action/)
  assert.doesNotMatch(findCreators,/Action|Social Media|data-label="Status"/)
  assert.doesNotMatch(activeAds,/Action|Social Media|data-label="Status"/)
  assert.match(findCreators,/business-find-creators/)
  assert.match(findCreators,/state\.daysText !== null/)
  assert.match(findCreators,/daysLeftText\(state\.daysLeft, state\.tone\)/)
  assert.match(findCreators,/No Relationship/)
  assert.match(findCreators,/Invitation Pending/)
  assert.match(findCreators,/Invite to Advertise/)
  assert.doesNotMatch(activeAds,/Social profile available/)
  assert.doesNotMatch(activeAds,/↗/)
  assert.match(requests,/Social Media/)
  assert.match(businessAds,/target="_blank"/)
  assert.match(businessAds,/rel="noopener noreferrer"/)
  assert.match(businessAds,/Not provided/)
  assert.match(businessAds,/social-media-link/)
  assert.doesNotMatch(businessAds,/↗/)
  assert.doesNotMatch(businessAds,/\bfollowers\b/i)
  assert.match(businessAds,/url\.protocol !== "http:" && url\.protocol !== "https:"/)
  assert.doesNotMatch(businessAds,/javascript:|data:/)
})
test('Creator Find Businesses cards stay compact and hide redundant labels',()=>{
  const findBusinesses=creatorAds.slice(creatorAds.indexOf('export function FindBusinesses'),creatorAds.indexOf('type AdBusiness'))
  assert.match(findBusinesses,/business-discovery-card/)
  assert.match(findBusinesses,/business-card-top/)
  assert.match(findBusinesses,/business-card-meta/)
  assert.match(findBusinesses,/business-card-actions/)
  assert.match(findBusinesses,/Days left:/)
  assert.match(findBusinesses,/Request to Advertise/)
  assert.doesNotMatch(findBusinesses,/STATUS:|ACTION:|data-label="Status"|data-label="Action"/)
})
test('Business creates phone-first Cashier credentials without a location field',()=>{
  for(const label of ['Create Cashier','Cashier Name','Phone Number','Temporary Password','Confirm Temporary Password','Cashier account created.','Disable','Reactivate'])assert.ok(main.includes(label))
  assert.doesNotMatch(main,/Username<input/)
  assert.match(main,/\/api\/v1\/merchant\/cashiers/)
  assert.doesNotMatch(main,/Location \(Optional\)|No location assigned\. You can assign this Cashier later\./)
  assert.doesNotMatch(mainCompact,/placeholder="Main Location"/)
  assert.doesNotMatch(main,/Business Location<select required|Send Invitation|Copy invitation link/)
  for(const label of ['New Purchase','Recent Transactions','Profile','Creator ID','Customer Phone Number','Status:</strong> Eligible','Purchase Amount (ETB)','Submit Purchase'])assert.ok(cashier.includes(label))
  for(const label of ['placeholder="Creator ID"','placeholder="Customer Phone Number"','placeholder="Purchase Amount"','cashier-transaction-row','Amount','Status','Date','Time'])assert.ok(cashier.includes(label))
  assert.doesNotMatch(cashier,/placeholder="4827"|placeholder="0912345678"|publicTransactionId\}<\/small>/)
  assert.doesNotMatch(businessAds,/data-label="Confirmed Sales"|data-label="Commission Generated"/)
  assert.doesNotMatch(cashier,/merchantLocationId|Take Photo of QR|type="file"|decodeQrImage/)
  assert.match(cashier,/\/api\/v1\/cashier\/checkouts\/validate-creator/)
  assert.match(cashier,/\/api\/v1\/cashier\/checkouts\/by-creator/)
  assert.match(cashier,/Customer account not found\./)
  assert.doesNotMatch(auth,/type Mode=.*cashier/)
})
test('Business Cashier creation uses POST, friendly errors, and shared responsive table columns',()=>{
  assert.match(mainCompact,/\/api\/v1\/merchant\/cashiers["'],\{method:["']POST["']/)
  for(const message of ['Unable to create Cashier.','Please check the information and try again.','Legacy account'])assert.ok(main.includes(message))
  for(const className of ['business-table-row cashier-grid','business-table-row business-active-grid'])assert.ok(main.includes(className)||businessAds.includes(className))
  assert.match(stylesCompact,/\.business-table-row\{[^}]*grid-template-columns:var\(--business-table-columns\)/)
  assert.match(stylesCompact,/\.cashier-grid\{--business-table-columns:[^}]+\}/)
  assert.match(stylesCompact,/\.business-active-grid\{--business-table-columns:[^}]+\}/)
  assert.match(stylesCompact,/@media\(max-width:650px\)\{\.business-table-row\.headings[^}]*display:none/)
  assert.match(stylesCompact,/\.business-table-row,\.cashier-list\.business-table-row\{grid-template-columns:1fr/)
})
test('deactivated Business advertising rows provide the merchant Reactivate action',()=>{
  assert.match(businessAds,/partnerships\/\$\{relationship\.id\}\/reactivate/)
  assert.match(businessAds,/Reactivate/)
  assert.match(businessAds,/relationship\.status === "Blocked"/)
})
test('checkout survey remains authenticated and English-only',()=>{
  assert.match(experience,/\/api\/v1\/pilot\/checkout-survey/)
  assert.match(experience,/Authorization:`Bearer/)
  assert.match(experience,/languageCode:'en'/)
})
test('accessibility and mobile safeguards remain present',()=>{
  for(const item of ['role="alert"','aria-pressed'])assert.ok(experience.includes(item))
  assert.match(styles,/prefers-reduced-motion:reduce/)
  assert.match(styles,/forced-colors:active/)
  assert.match(styles,/@media\s*\(max-width:600px\)/)
  assert.match(styles,/\.creator-tabs button\.active[^}]*color:#fff/)
  assert.match(styles,/\.shopper nav button\.active[^}]*color:#fff/)
  assert.match(styles,/\.admin-sidebar nav a\[aria-current=page\][^}]*color:#fff/)
  assert.match(styles,/\.admin-sidebar nav a:focus-visible/)
})
test('Business onboarding uses concise verification wording',()=>{
  assert.ok(onboarding.includes("role === 'MerchantAdmin'"))
  assert.ok(onboarding.includes('Your account is under review. You will be notified after the Platform Admin approves your account.'))
  assert.doesNotMatch(onboarding,/Email \{data\.isEmailVerified|Phone \{data\.isPhoneVerified/i)
})
test('Creator onboarding stays generic and does not expose verification steps',()=>{
  assert.ok(onboarding.includes("role === 'Creator'"))
  assert.ok(onboarding.includes('Your creator account is under review. You will be able to access the approved creator tools after activation.'))
  assert.doesNotMatch(onboarding,/email verified|phone verified|Verify your email|Verify your phone|isEmailVerified|isPhoneVerified/i)
})
test('Welcome mode changes reset every controlled authentication flow',()=>{
  for(const reset of ['setLogin(loginBlank())','setShopper(shopperBlank())','setCreator(creatorBlank())','setBusiness(businessBlank())','setMessage("")','setForgot(false)','setResetReference("")','setResetStatus("Pending")'])assert.ok(auth.includes(reset))
  assert.match(auth,/onClick=\{\(\)=>changeMode\("login"\)\}/)
  for(const value of ['current-password','new-password','email','tel','name'])assert.ok(auth.includes(`"${value}"`))
})
test('public authentication uses support-approved recovery without verification UX',()=>{
  assert.match(auth,/Welcome back\. Keep shopping, promoting, and earning with Weymela\./)
  assert.match(auth,/Welcome to Weymela — where customers save, creators earn, and businesses grow\./)
  for(const value of ['Request Password Reset','Check Approval Status','Request New Password Reset','waiting for admin approval','Your password reset request was rejected.','Contact Weymela Support','mailto:support@weymela.com?subject=Weymela%20Support%20Request','password-reset-requests'])assert.ok(auth.includes(value))
  assert.match(auth,/Status:\s*\{resetStatus\}/)
  assert.match(auth,/resetStatusMessage\s*\|\|\s*passwordResetStatusText\(resetStatus\)/)
  assert.match(auth,/normalizePasswordResetStatus/)
  assert.match(auth,/refreshPasswordResetStatus/)
  assert.match(auth,/resetStatus\s*===\s*["']Approved["']/)
  assert.match(auth,/resetStatus\s*===\s*["']Rejected["']/)
  assert.ok(!auth.includes('admin@weymela.com'))
  assert.doesNotMatch(auth,/Send verification code|Verify your phone|6-digit verification code|code sent to your phone/)
})
test('Creator and Business discovery show relationship status without duplicate actions',()=>{
  for(const label of ['Request Pending','Active','Deactivated'])assert.match(creatorAds,new RegExp(label))
  for(const label of ['Invitation Pending','Active','Deactivated'])assert.match(businessAds,new RegExp(label))
  assert.doesNotMatch(creatorAds,/Currently Advertising/)
  assert.doesNotMatch(businessAds,/Currently Advertising/)
  assert.match(relationshipTime,/Activation Required/)
  assert.match(creatorAds,/canRequest\s*&&/)
  assert.match(businessAds,/canInvite\s*&&/)
  assert.match(styles,/\.discovery-row/)
})
test('current partnership history collapses to the newest Creator-business pair before action rendering',()=>{
  const currentPartnerships=(items,keyOf)=>{const current=new Map();for(const item of items){const key=keyOf(item);if(!key)continue;const requestedAt=Date.parse(item.requestedAtUtc);const existing=current.get(key);if(!existing||requestedAt>existing.requestedAt)current.set(key,{item,requestedAt})}return [...current.values()].sort((a,b)=>b.requestedAt-a.requestedAt).map(x=>x.item)}
  const history=[
    {id:'declined',merchantId:'m1',creatorId:'c1',requestedAtUtc:'2026-01-01T00:00:00Z',status:'Rejected'},
    {id:'active',merchantId:'m1',creatorId:'c1',requestedAtUtc:'2026-02-01T00:00:00Z',status:'Approved'},
    {id:'pending',merchantId:'m2',creatorId:'c2',requestedAtUtc:'2026-03-01T00:00:00Z',status:'Pending'},
    {id:'declined-only',merchantId:'m3',creatorId:'c3',requestedAtUtc:'2026-04-01T00:00:00Z',status:'Rejected'}
  ]
  assert.deepEqual(currentPartnerships(history,x=>x.merchantId).map(x=>x.id),['declined-only','pending','active'])
  const creatorVisible=currentPartnerships(history,x=>x.merchantId).filter(x=>x.status==='Pending'||x.status==='Rejected')
  assert.deepEqual(creatorVisible.map(x=>x.id),['declined-only','pending'])
  const businessVisible=currentPartnerships(history,x=>x.creatorId).filter(x=>x.status!=='Approved'&&x.status!=='Suspended'&&x.status!=='Revoked')
  assert.deepEqual(businessVisible.map(x=>x.id),['declined-only','pending'])
  assert.match(creatorAds,/currentPartnerships\(requests,x=>x.merchantId\)/)
  assert.match(creatorAds,/currentPartnerships\(items,x=>x.merchantId\)/)
  assert.match(businessAds,/currentPartnerships\(relationships, \(x\) => x.creatorId\)/)
  assert.match(businessAds,/currentPartnerships\(items, \(x\) => x.creatorId\)/)
  assert.doesNotMatch(creatorAds,/Request Again.*A pending or active relationship/)
})
test('Creator dashboard presents the permanent four-digit Creator ID',()=>{
  assert.match(creatorDashboard,/\/api\/v1\/creators\/me/)
  assert.match(creatorDashboard,/profile\.creatorCode/)
  assert.match(creatorDashboard,/Copy Creator ID/)
  assert.match(creatorDashboard,/creator-id-profile/)
  assert.match(creatorDashboard,/copy-creator-id/)
  assert.doesNotMatch(creatorDashboard,/apiBlob|Download PNG|Creator QR code/)
  assert.match(styles,/\.creator-id-profile/)
})
