import test from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'

const ui=readFileSync(new URL('../src/CustomerWorkspace.tsx',import.meta.url),'utf8')
const styles=readFileSync(new URL('../src/styles.css',import.meta.url),'utf8')
const notifications=readFileSync(new URL('../src/NotificationWorkspace.tsx',import.meta.url),'utf8')
const typeahead=readFileSync(new URL('../src/typeahead.ts',import.meta.url),'utf8')
const main=readFileSync(new URL('../src/main.tsx',import.meta.url),'utf8')
const displayFormat=readFileSync(new URL('../src/displayFormat.ts',import.meta.url),'utf8')
test('shopper money uses the shared two-decimal formatter without a visible currency code',()=>{assert.match(ui,/formatAmount/);assert.match(displayFormat,/minimumFractionDigits: 2/);assert.doesNotMatch(ui,/ETB/)})
test('Customer discovery uses only authoritative eligible offers and one-time QR without Creator IDs',()=>{assert.doesNotMatch(ui,/\/api\/v1\/customer\/discovery\/advertising/);assert.match(ui,/\/api\/customer\/offers/);assert.doesNotMatch(ui,/Creator ID/);assert.match(ui,/offer-qr-dialog|Offer QR/);assert.match(ui,/QRCode\.toDataURL/);assert.match(ui,/setActiveQr\(\{offer,image,expiresAtUtc:result\.expiresAtUtc\}\)/)})
test('customer navigation has explicit Home, Discover, Cashback, and Profile destinations',()=>{for(const label of ['Home','Discover Promotions','Cashback','Profile'])assert.match(ui,new RegExp(label));assert.match(ui,/role="Customer"/);assert.match(ui,/Customer navigation/);assert.doesNotMatch(ui,/\['confirmations','My Confirmations'\]|[\u1200-\u137f]/)})
test('Shopper confirmation actions remain accessible without a permanent tab',()=>{assert.match(ui,/Is this your purchase\?/);assert.match(ui,/YES, IT'S ME/);assert.match(ui,/NO, IT'S NOT ME/);assert.match(ui,/x\.status\s*===\s*['"]AwaitingCustomerApproval['"]/);assert.match(ui,/pendingCount/);assert.match(ui,/pending-confirmation-link/);assert.match(ui,/\['Completed',\s*'Rejected'\]/);assert.match(ui,/confirmation-history/);assert.match(ui,/pending\.map/)})
test('private Business funding details are not rendered',()=>{assert.doesNotMatch(ui,/wallet balance|minimum business wallet/i);assert.match(ui,/visibleRows\s*=\s*rows\.filter\(\(x\)\s*=>\s*x\.rewardsAvailable\)/)})
test('Shopper discovery renders compact customer-only offer cards',()=>{const discovery=ui.slice(ui.indexOf("view === 'discover'"),ui.indexOf("view === 'confirmations'"));assert.match(discovery,/Available Customer Offers/);assert.match(discovery,/v3Offers\.map/);assert.match(discovery,/AuthoritativeOfferCard/);assert.match(ui,/Use Offer/);assert.match(ui,/Watch Promotion/);assert.match(ui,/Get Directions/);assert.match(ui,/target="_blank"[\s\S]*?rel="noopener noreferrer"/);for(const internal of ['Creator payment','Creators needed','follower requirements','content instructions','UGC submission'])assert.doesNotMatch(discovery,new RegExp(internal,'i'))})
test('Shopper advertising results are compact responsive cards',()=>{assert.match(ui,/customer-promotion-card/);assert.match(ui,/customer-promotion-feed/);assert.match(styles,/\.role-customer \.customer-promotion-card/);assert.match(styles,/\.role-customer \.customer-promotion-feed \{/);assert.match(styles,/grid-template-columns: repeat\(2,minmax\(0,1fr\)\)/);assert.match(styles,/\.role-customer \.customer-promotion-feed \{\s*grid-template-columns: 1fr/s)})
test('Customer Creator identity, address, and distance use names without exposing Creator ID',()=>{assert.match(ui,/Promoted by/);assert.match(ui,/\{row\.creatorName\}/);assert.doesNotMatch(ui,/customer-creator-id|Creator ID/);assert.match(ui,/businessAddress\(row\)/);assert.match(ui,/missingDisplayValues/);assert.match(ui,/toLocaleLowerCase/);assert.match(ui,/km away/);assert.doesNotMatch(ui,/>Not provided</)})
test('Customer Home uses authoritative offers and wallet data without demo content',()=>{assert.match(ui,/Available Offers/);assert.match(ui,/v3Offers\.slice\(0,3\)/);assert.match(ui,/availableCashback/);assert.match(ui,/nextPayoutAtUtc/);assert.doesNotMatch(ui,/fake|demo promotion/i)})
test('offer failures are friendly and raw errors are never rendered',()=>{assert.match(ui,/We couldn't load current offers\./);assert.match(ui,/Only eligible Customer-facing offers appear here\./);assert.doesNotMatch(ui,/error\.message/)})
test('customer profile is account information only while role-scoped Help and sign out stay in Settings',()=>{assert.match(ui,/AccountChrome/);assert.match(ui,/onProfile=\{\(\)\s*=>\s*setView\('profile'\)\}/);assert.match(ui,/onHelp=\{\(\)\s*=>\s*location\.assign\('\/help\?category=Customers'\)\}/);for(const label of ['Name','Email','Phone','Status'])assert.match(ui,new RegExp(label));for(const removed of ['Email Verified','Phone Verified','profile-actions'])assert.doesNotMatch(ui,new RegExp(removed));assert.match(ui,/\/api\/v1\/customer\/profile/)})
test('type-ahead uses two characters, 300ms debounce, stale suppression, and ranked matching',()=>{assert.match(typeahead,/TYPEAHEAD_DELAY_MS=300/);assert.match(typeahead,/TYPEAHEAD_MIN_LENGTH=2/);assert.match(typeahead,/request===sequence\.current/);assert.match(typeahead,/x===term/);assert.match(typeahead,/x\.startsWith\(term\)/);assert.match(typeahead,/x\.includes\(term\)/)})
test('shopper notification preference table and raw event labels are absent',()=>{assert.doesNotMatch(notifications,/NotificationPreferences/);assert.doesNotMatch(notifications,/x\.type\s*}.*x\.status/s)})
