import test from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'

const ui=readFileSync(new URL('../src/CustomerWorkspace.tsx',import.meta.url),'utf8')
const styles=readFileSync(new URL('../src/styles.css',import.meta.url),'utf8')
const notifications=readFileSync(new URL('../src/NotificationWorkspace.tsx',import.meta.url),'utf8')
const typeahead=readFileSync(new URL('../src/typeahead.ts',import.meta.url),'utf8')
const main=readFileSync(new URL('../src/main.tsx',import.meta.url),'utf8')
test('shopper money is formatted with two decimals',()=>assert.match(ui,/toFixed\(2\)/))
test('Shopper discovery uses authenticated active promotions and Creator IDs without QR controls',()=>{assert.match(ui,/\/api\/v1\/customer\/discovery\/advertising/);assert.match(ui,/relationshipId/);assert.match(ui,/creatorCode/);assert.match(ui,/Creator ID/);assert.doesNotMatch(ui,/qr-image|View QR|Selected Creator QR/)})
test('customer navigation is simplified and English-only',()=>{for(const label of ['Discover Businesses','Cashback'])assert.match(ui,new RegExp(label));assert.match(ui,/role="Customer"/);assert.match(ui,/Customer navigation/);assert.doesNotMatch(ui,/\['confirmations','My Confirmations'\]|\['profile','Profile'\]|[\u1200-\u137f]/)})
test('Shopper confirmation actions remain accessible without a permanent tab',()=>{assert.match(ui,/Is this your purchase\?/);assert.match(ui,/YES, IT'S ME/);assert.match(ui,/NO, IT'S NOT ME/);assert.match(ui,/x\.status==='AwaitingCustomerApproval'/);assert.match(ui,/pendingCount/);assert.match(ui,/pending-confirmation-link/);assert.match(ui,/\['Completed','Rejected'\]/);assert.match(ui,/confirmation-history/);assert.match(ui,/pending\.map/)})
test('private Business funding details are not rendered',()=>{assert.doesNotMatch(ui,/wallet balance|minimum business wallet/i);assert.match(ui,/visibleRows=rows\.filter\(x=>x\.rewardsAvailable\)/)})
test('Shopper discovery removes categories and internal relationship status',()=>{const discovery=ui.slice(ui.indexOf("view==='discover'"),ui.indexOf("view==='confirmations'"));assert.doesNotMatch(discovery,/<select value=\{category\}|All categories|businessTypes/);assert.match(discovery,/visibleRows\.map/);assert.match(discovery,/key=\{x\.relationshipId\}/);for(const label of ['Business','Creator Promoting','Creator ID'])assert.match(discovery,new RegExp(label));assert.doesNotMatch(discovery,/data-label="(?:Action|Status|Days Left)"/)})
test('Shopper advertising rows become compact mobile cards',()=>{assert.match(ui,/className="shopper-relationship-list simplified"/);assert.match(ui,/className="shopper-relationship-row"/);assert.match(styles,/\.shopper-relationship-list\.simplified \.shopper-relationship-row\{[^}]*grid-template-columns/);assert.match(styles,/@media \(max-width:650px\).*\.shopper-relationship-list\.simplified \.shopper-relationship-row\{grid-template-columns:1fr/s)})
test('Shopper Creator ID is visually distinct',()=>{assert.match(ui,/shopper-creator-code/);assert.match(ui,/\{x\.creatorCode\}/)})
test('customer profile and Help move into unified account chrome',()=>{assert.match(ui,/AccountChrome/);assert.match(ui,/onProfile=\{\(\)=>setView\('profile'\)\}/);assert.match(ui,/onHelp=\{\(\)=>location\.assign\('\/help'\)\}/);for(const label of ['Name','Email','Phone','Account Status'])assert.match(ui,new RegExp(label));for(const removed of ['Email Verified','Phone Verified'])assert.doesNotMatch(ui,new RegExp(removed));assert.match(ui,/\/api\/v1\/customer\/profile/)})
test('type-ahead uses two characters, 300ms debounce, stale suppression, and ranked matching',()=>{assert.match(typeahead,/TYPEAHEAD_DELAY_MS=300/);assert.match(typeahead,/TYPEAHEAD_MIN_LENGTH=2/);assert.match(typeahead,/request===sequence\.current/);assert.match(typeahead,/x===term/);assert.match(typeahead,/x\.startsWith\(term\)/);assert.match(typeahead,/x\.includes\(term\)/)})
test('shopper notification preference table and raw event labels are absent',()=>{assert.doesNotMatch(notifications,/NotificationPreferences/);assert.doesNotMatch(notifications,/x\.type\s*}.*x\.status/s)})
