using CreatorPay.Domain.Entities;
using CreatorPay.Domain.Enums;
using CreatorPay.Domain.Services;
namespace CreatorPay.Domain.Tests;

public sealed class FourPartyFinanceTests
{
    [Fact] public void Ten_percent_rule_splits_four_three_three() { var v = new CommissionRuleVersion { MerchantCommissionRatePercent = 10, CreatorSharePercent = 40, CustomerCashbackSharePercent = 30, PlatformSharePercent = 30, MinimumPurchaseAmount = 0, EffectiveFromUtc = DateTime.UtcNow, RoundingMode = CommissionRoundingMode.AwayFromZero }; var x = CommissionCalculator.Calculate(2000, v); Assert.Equal(200, x.TotalCommissionAmount); Assert.Equal(80, x.CreatorCommissionAmount); Assert.Equal(60, x.CustomerCashbackAmount); Assert.Equal(60, x.PlatformCommissionAmount); }
    [Fact] public void Customer_payout_reserves_full_balance_only_after_threshold() { var w = new CustomerWallet { Id = Guid.NewGuid(), CustomerId = Guid.NewGuid(), CreatedAtUtc = DateTime.UtcNow }; w.Credit(999, DateTime.UtcNow); Assert.Throws<InvalidOperationException>(() => w.ReserveFull(1000, DateTime.UtcNow)); w.Credit(1, DateTime.UtcNow); var moved = w.ReserveFull(1000, DateTime.UtcNow); Assert.Equal(1000, moved.Before); Assert.Equal(0, w.AvailableCashback); Assert.Equal(1000, w.ReservedCashback); }
    [Fact] public void Trial_stops_at_three_sales_or_commission_limit() { var t = new MerchantTrialCredit { Id = Guid.NewGuid(), MerchantId = Guid.NewGuid(), CreatedAtUtc = DateTime.UtcNow }; t.Use(100, DateTime.UtcNow); t.Use(100, DateTime.UtcNow); t.Use(100, DateTime.UtcNow); Assert.Equal(TrialCreditStatus.Exhausted, t.Status); var capped = new MerchantTrialCredit { Id = Guid.NewGuid(), MerchantId = Guid.NewGuid(), CreatedAtUtc = DateTime.UtcNow }; capped.Use(1000, DateTime.UtcNow); Assert.Equal(TrialCreditStatus.Exhausted, capped.Status); }
    [Fact] public void Unpaid_cashback_is_removed_without_negative_balance() { var w = new CustomerWallet { Id = Guid.NewGuid(), CustomerId = Guid.NewGuid(), CreatedAtUtc = DateTime.UtcNow }; w.Credit(60, DateTime.UtcNow); var reversed = w.ReverseCashback(60, DateTime.UtcNow); Assert.Equal(0, reversed.After); Assert.Equal(0, reversed.RecoveryCreated); Assert.Equal(0, w.RecoveryBalance); }
    [Fact] public void Paid_cashback_creates_recovery_and_future_cashback_offsets_it() { var w = new CustomerWallet { Id = Guid.NewGuid(), CustomerId = Guid.NewGuid(), CreatedAtUtc = DateTime.UtcNow }; var reversed = w.ReverseCashback(60, DateTime.UtcNow); Assert.Equal(60, reversed.RecoveryCreated); Assert.Equal(60, w.RecoveryBalance); var earned = w.Credit(40, DateTime.UtcNow); Assert.Equal(40, earned.Recovered); Assert.Equal(20, w.RecoveryBalance); Assert.Equal(0, w.AvailableCashback); }
    [Fact] public void Trial_funded_reversal_restores_usage() { var t = new MerchantTrialCredit { Id = Guid.NewGuid(), MerchantId = Guid.NewGuid(), CreatedAtUtc = DateTime.UtcNow }; t.Use(100, DateTime.UtcNow); t.Use(100, DateTime.UtcNow); t.Use(100, DateTime.UtcNow); t.Restore(100, true, DateTime.UtcNow); Assert.Equal(TrialCreditStatus.Active, t.Status); Assert.Equal(2, t.ConfirmedTransactionCount); Assert.Equal(200, t.TotalCommissionFunded); }
}
