using CreatorPay.Domain.Common;
using CreatorPay.Domain.Enums;
namespace CreatorPay.Domain.Entities;

public sealed class Customer : Entity { public string PublicCustomerId { get; set; } = ""; public string DisplayName { get; set; } = ""; public string PhoneNumber { get; set; } = ""; public string NormalizedPhoneNumber { get; set; } = ""; public CustomerStatus Status { get; set; } = CustomerStatus.Active; public ICollection<SavedPromotion> SavedPromotions { get; } = []; }
public sealed class CustomerWallet : Entity { public Guid CustomerId { get; set; } public string CurrencyCode { get; set; } = "ETB"; public decimal AvailableCashback { get; private set; } public decimal ReservedCashback { get; private set; } public decimal PaidLifetime { get; private set; } public decimal RecoveryBalance { get; private set; } public uint RowVersion { get; set; } public (decimal Before, decimal After, decimal Recovered) Credit(decimal amount, DateTime now) { Positive(amount); var before = AvailableCashback; var recovered = Math.Min(RecoveryBalance, amount); RecoveryBalance -= recovered; AvailableCashback += amount - recovered; UpdatedAtUtc = now; return (before, AvailableCashback, recovered); } public (decimal Before, decimal After, decimal RecoveryCreated) ReverseCashback(decimal amount, DateTime now) { Positive(amount); var before = AvailableCashback; var applied = Math.Min(AvailableCashback, amount); AvailableCashback -= applied; var recovery = amount - applied; RecoveryBalance += recovery; UpdatedAtUtc = now; return (before, AvailableCashback, recovery); } public (decimal Before, decimal After) ReserveFull(decimal threshold, DateTime now) { if (AvailableCashback < threshold) throw new InvalidOperationException("Cashback payout threshold has not been reached."); var amount = AvailableCashback; AvailableCashback = 0; ReservedCashback += amount; UpdatedAtUtc = now; return (amount, 0); } public void MarkPaid(decimal amount, DateTime now) { Positive(amount); if (ReservedCashback < amount) throw new InvalidOperationException("Reserved cashback is insufficient."); ReservedCashback -= amount; PaidLifetime += amount; UpdatedAtUtc = now; } public void Release(decimal amount, DateTime now) { Positive(amount); if (ReservedCashback < amount) throw new InvalidOperationException("Reserved cashback is insufficient."); ReservedCashback -= amount; AvailableCashback += amount; UpdatedAtUtc = now; } static void Positive(decimal x) { if (x <= 0) throw new ArgumentOutOfRangeException(nameof(x)); } }
public sealed class CustomerCashbackEntry : Entity { public Guid CustomerWalletId { get; set; } public Guid CustomerId { get; set; } public CustomerCashbackEntryType EntryType { get; set; } public decimal Amount { get; set; } public decimal BalanceBefore { get; set; } public decimal BalanceAfter { get; set; } public string CurrencyCode { get; set; } = "ETB"; public Guid? PurchaseTransactionId { get; set; } public Guid? CustomerPayoutRequestId { get; set; } public string IdempotencyKey { get; set; } = ""; public string CorrelationId { get; set; } = ""; }
public sealed class CustomerPayoutRequest : Entity { public string PublicPayoutId { get; set; } = ""; public Guid CustomerId { get; set; } public Guid CustomerWalletId { get; set; } public decimal Amount { get; set; } public string CurrencyCode { get; set; } = "ETB"; public CustomerPayoutStatus Status { get; set; } public DateTime RequestedAtUtc { get; set; } public DateTime? ProcessingAtUtc { get; set; } public DateTime? PaidAtUtc { get; set; } public DateTime? FailedAtUtc { get; set; } public string? ExternalMethod { get; set; } public string? ExternalReference { get; set; } public string? FailureReason { get; set; } public string IdempotencyKey { get; set; } = ""; public string? PaymentConfirmationIdempotencyKey { get; set; } }
public sealed class CheckoutSession : Entity { public string PublicCheckoutId { get; set; } = ""; public Guid CustomerId { get; set; } public Guid CampaignId { get; set; } public Guid MerchantId { get; set; } public Guid CreatorId { get; set; } public string TokenHash { get; set; } = ""; public CheckoutSessionStatus Status { get; set; } = CheckoutSessionStatus.Created; public DateTime ExpiresAtUtc { get; set; } public DateTime? PresentedAtUtc { get; set; } public Guid? CashierId { get; set; } public Guid? MerchantLocationId { get; set; } public decimal? PurchaseAmount { get; set; } public decimal? ExpectedCreatorAmount { get; set; } public decimal? ExpectedCashbackAmount { get; set; } public DateTime? CustomerApprovedAtUtc { get; set; } public DateTime? CompletedAtUtc { get; set; } public Guid? PurchaseTransactionId { get; set; } public string CreateIdempotencyKey { get; set; } = ""; public string? PresentIdempotencyKey { get; set; } public string? ApprovalIdempotencyKey { get; set; } public uint RowVersion { get; set; } }
public sealed class SavedPromotion : Entity { public Guid CustomerId { get; set; } public Guid CampaignId { get; set; } }
public sealed class MerchantStoreQr : Entity { public Guid MerchantId { get; set; } public string PublicQrId { get; set; } = ""; public string TokenHash { get; set; } = ""; public bool IsActive { get; set; } = true; }
public sealed class MerchantPromotionProfile : Entity { public Guid MerchantId { get; set; } public Guid? FeaturedCreatorId { get; set; } public string? ZoneCode { get; set; } public string? SocialLinksJson { get; set; } }
public sealed class MerchantTrialCredit : Entity { public Guid MerchantId { get; set; } public TrialCreditStatus Status { get; set; } = TrialCreditStatus.Active; public int ConfirmedTransactionCount { get; set; } public decimal TotalCommissionFunded { get; set; } public int MaximumTransactions { get; set; } = 3; public decimal MaximumCommission { get; set; } = 1000m; public uint RowVersion { get; set; } public bool CanFund(decimal commission) => Status == TrialCreditStatus.Active && ConfirmedTransactionCount < MaximumTransactions && TotalCommissionFunded + commission <= MaximumCommission; public void Use(decimal commission, DateTime now) { if (!CanFund(commission)) throw new InvalidOperationException("Trial credit is exhausted."); ConfirmedTransactionCount++; TotalCommissionFunded += commission; if (ConfirmedTransactionCount >= MaximumTransactions || TotalCommissionFunded >= MaximumCommission) Status = TrialCreditStatus.Exhausted; UpdatedAtUtc = now; } public void Restore(decimal commission, bool fullTransaction, DateTime now) { if (commission <= 0 || commission > TotalCommissionFunded) throw new InvalidOperationException("Trial reversal exceeds funded exposure."); TotalCommissionFunded -= commission; if (fullTransaction && ConfirmedTransactionCount > 0) ConfirmedTransactionCount--; Status = TrialCreditStatus.Active; UpdatedAtUtc = now; } }
public sealed class CustomerRecoveryBalance : Entity { public Guid CustomerId { get; set; } public Guid TransactionReversalId { get; set; } public decimal OriginalAmount { get; set; } public decimal OutstandingAmount { get; set; } public string CurrencyCode { get; set; } = "ETB"; public CreatorRecoveryStatus Status { get; set; } = CreatorRecoveryStatus.Open; public string Reason { get; set; } = ""; }
public sealed class PlatformRevenueEntry : Entity { public Guid PurchaseTransactionId { get; set; } public decimal Amount { get; set; } public string CurrencyCode { get; set; } = "ETB"; public string IdempotencyKey { get; set; } = ""; }
