using CreatorPay.Domain.Common;
using CreatorPay.Domain.Enums;
namespace CreatorPay.Domain.Entities;
public sealed class CustomerPhoneReference : Entity { public byte[] EncryptedPhoneNumber { get; set; }=[]; public string PhoneNumberHash { get; set; }=""; public string MaskedPhoneNumber { get; set; }=""; public string CountryCode { get; set; }="ET"; public DateTime? LastUsedAtUtc { get; set; } }
public sealed class RepeatUseApprovalRequest : Entity {
 public string PublicApprovalRequestId { get; set; }=""; public Guid MerchantId { get; set; } public Guid MerchantLocationId { get; set; } public Guid CreatorId { get; set; } public Guid MerchantCreatorPartnershipId { get; set; } public Guid CashierId { get; set; } public Guid CreatedByUserId { get; set; } public Guid CustomerPhoneReferenceId { get; set; } public string CustomerPhoneHash { get; set; }=""; public string MaskedPhoneNumber { get; set; }=""; public DateOnly MerchantLocalDate { get; set; } public decimal PurchaseAmount { get; set; } public string CurrencyCode { get; set; }="ETB"; public string QrReference { get; set; }=""; public RepeatUseApprovalStatus Status { get; set; } public string Reason { get; set; }="Repeated customer phone use"; public DateTime RequestedAtUtc { get; set; } public DateTime ExpiresAtUtc { get; set; } public DateTime? SupervisorDecisionAtUtc { get; set; } public Guid? SupervisorUserId { get; set; } public DateTime? CustomerConfirmedAtUtc { get; set; } public DateTime? FinalizedAtUtc { get; set; } public Guid? RelatedPurchaseTransactionId { get; set; } public string IdempotencyKey { get; set; }=""; public string CorrelationId { get; set; }=""; public bool RequiresCustomerConfirmation { get; set; } public bool RequiresSupervisorApproval { get; set; } public bool SupervisorApproved { get; set; } public Guid? CustomerConfirmationId { get; set; }
}
public sealed class CustomerConfirmation : Entity { public Guid RepeatUseApprovalRequestId { get; set; } public string CodeHash { get; set; }=""; public DateTime ExpiresAtUtc { get; set; } public int AttemptCount { get; set; } public int MaximumAttempts { get; set; } public DateTime? ConfirmedAtUtc { get; set; } public DateTime? FailedAtUtc { get; set; } }
public sealed class RepeatUseApprovalHistory : Entity { public Guid RepeatUseApprovalRequestId { get; set; } public RepeatUseApprovalStatus? PreviousStatus { get; set; } public RepeatUseApprovalStatus NewStatus { get; set; } public Guid? ActorUserId { get; set; } public string Action { get; set; }=""; public string? Reason { get; set; } public DateTime OccurredAtUtc { get; set; } }
