using CreatorPay.Domain.Common;
using CreatorPay.Domain.Enums;

namespace CreatorPay.Domain.Entities;

public sealed class FraudRule : Entity { public string Code { get; set; } = ""; public string Name { get; set; } = ""; public bool IsActive { get; set; } = true; public ICollection<FraudRuleVersion> Versions { get; } = []; }
public sealed class FraudRuleVersion : Entity { public Guid FraudRuleId { get; set; } public int VersionNumber { get; set; } public string ConfigurationJson { get; set; } = "{}"; public FraudAlertSeverity Severity { get; set; } public FraudEvaluationDecision Decision { get; set; } public DateTime EffectiveFromUtc { get; set; } public DateTime? EffectiveToUtc { get; set; } public Guid CreatedByUserId { get; set; } public FraudRule Rule { get; set; } = null!; }
public sealed class FraudAlert : Entity { public string PublicFraudAlertId { get; set; } = ""; public string RuleCode { get; set; } = ""; public Guid FraudRuleVersionId { get; set; } public FraudAlertSeverity Severity { get; set; } public FraudAlertStatus Status { get; set; } = FraudAlertStatus.Open; public Guid? PurchaseTransactionId { get; set; } public Guid? MerchantId { get; set; } public Guid? MerchantLocationId { get; set; } public Guid? CreatorId { get; set; } public Guid? CashierId { get; set; } public Guid? CustomerPhoneReferenceId { get; set; } public string? CustomerPhoneHash { get; set; } public string EvidenceJson { get; set; } = "{}"; public Guid? AssignedReviewerUserId { get; set; } public DateTime DetectedAtUtc { get; set; } public DateTime? ReviewedAtUtc { get; set; } public DateTime? ResolvedAtUtc { get; set; } public string? Resolution { get; set; } public string CorrelationId { get; set; } = ""; public ICollection<FraudEvidence> Evidence { get; } = []; public ICollection<FraudReviewHistory> ReviewHistory { get; } = []; }
public sealed class FraudEvidence : Entity { public Guid FraudAlertId { get; set; } public string EvidenceType { get; set; } = ""; public string MetadataJson { get; set; } = "{}"; public Guid AddedByUserId { get; set; } public FraudAlert Alert { get; set; } = null!; }
public sealed class FraudReviewHistory : Entity { public Guid FraudAlertId { get; set; } public FraudAlertStatus? PreviousStatus { get; set; } public FraudAlertStatus NewStatus { get; set; } public Guid ActorUserId { get; set; } public string Action { get; set; } = ""; public string? Reason { get; set; } public DateTime OccurredAtUtc { get; set; } public FraudAlert Alert { get; set; } = null!; }

public sealed class Dispute : Entity { public string PublicDisputeId { get; set; } = ""; public Guid PurchaseTransactionId { get; set; } public Guid OpenedByUserId { get; set; } public string OpenedByRole { get; set; } = ""; public Guid MerchantId { get; set; } public Guid CreatorId { get; set; } public DisputeType DisputeType { get; set; } public DisputeStatus Status { get; set; } = DisputeStatus.Open; public string Description { get; set; } = ""; public DateTime OpenedAtUtc { get; set; } public Guid? AssignedReviewerUserId { get; set; } public DateTime? ResolvedAtUtc { get; set; } public string? Resolution { get; set; } public string CorrelationId { get; set; } = ""; public ICollection<DisputeEvidence> Evidence { get; } = []; public ICollection<DisputeStatusHistory> StatusHistory { get; } = []; public ICollection<DisputeDecision> Decisions { get; } = []; }
public sealed class DisputeEvidence : Entity { public Guid DisputeId { get; set; } public string EvidenceType { get; set; } = ""; public string FileName { get; set; } = ""; public string? ContentType { get; set; } public string MetadataJson { get; set; } = "{}"; public Guid SubmittedByUserId { get; set; } public DateTime SubmittedAtUtc { get; set; } public Dispute Dispute { get; set; } = null!; }
public sealed class DisputeStatusHistory : Entity { public Guid DisputeId { get; set; } public DisputeStatus? PreviousStatus { get; set; } public DisputeStatus NewStatus { get; set; } public Guid ChangedByUserId { get; set; } public string? Reason { get; set; } public DateTime ChangedAtUtc { get; set; } public Dispute Dispute { get; set; } = null!; }
public sealed class DisputeDecision : Entity { public Guid DisputeId { get; set; } public bool Approved { get; set; } public string Reason { get; set; } = ""; public Guid DecidedByUserId { get; set; } public DateTime DecidedAtUtc { get; set; } public Dispute Dispute { get; set; } = null!; }

public sealed class TransactionReversal : Entity { public string PublicReversalId { get; set; } = ""; public Guid PurchaseTransactionId { get; set; } public Guid? DisputeId { get; set; } public ReversalType ReversalType { get; set; } public decimal Amount { get; set; } public string CurrencyCode { get; set; } = "ETB"; public string Reason { get; set; } = ""; public ReversalStatus Status { get; set; } = ReversalStatus.Pending; public DateTime RequestedAtUtc { get; set; } public DateTime? ApprovedAtUtc { get; set; } public DateTime? CompletedAtUtc { get; set; } public Guid RequestedByUserId { get; set; } public Guid? ApprovedByUserId { get; set; } public string IdempotencyKey { get; set; } = ""; public string CorrelationId { get; set; } = ""; public ICollection<ReversalItem> Items { get; } = []; public ICollection<ReversalJournalReference> JournalReferences { get; } = []; public ICollection<ReversalStatusHistory> StatusHistory { get; } = []; }
public sealed class ReversalItem : Entity { public Guid TransactionReversalId { get; set; } public string ItemType { get; set; } = ""; public decimal OriginalAmount { get; set; } public decimal ReversedAmount { get; set; } public string CurrencyCode { get; set; } = "ETB"; public TransactionReversal Reversal { get; set; } = null!; }
public sealed class ReversalJournalReference : Entity { public Guid TransactionReversalId { get; set; } public Guid FinancialJournalId { get; set; } public TransactionReversal Reversal { get; set; } = null!; }
public sealed class ReversalStatusHistory : Entity { public Guid TransactionReversalId { get; set; } public ReversalStatus? PreviousStatus { get; set; } public ReversalStatus NewStatus { get; set; } public Guid ChangedByUserId { get; set; } public string? Reason { get; set; } public DateTime ChangedAtUtc { get; set; } public TransactionReversal Reversal { get; set; } = null!; }
public sealed class CreatorRecoveryBalance : Entity { public Guid CreatorId { get; set; } public Guid TransactionReversalId { get; set; } public decimal OriginalAmount { get; set; } public decimal OutstandingAmount { get; set; } public string CurrencyCode { get; set; } = "ETB"; public CreatorRecoveryStatus Status { get; set; } = CreatorRecoveryStatus.Open; public string Reason { get; set; } = ""; }
public sealed class OperationalAuditEvent : Entity { public string EventType { get; set; } = ""; public Guid? ActorUserId { get; set; } public Guid? MerchantId { get; set; } public Guid? SubjectId { get; set; } public string MetadataJson { get; set; } = "{}"; public string CorrelationId { get; set; } = ""; }
