import {expect,test} from './fixtures'
import type {Page} from '@playwright/test'

const password=process.env.E2E_SHOPPER_PASSWORD!
async function login(page:Page,phone:string){await page.goto('/');const welcome=page.getByRole('button',{name:'Already have an account? Sign In'});if(await welcome.isVisible())await welcome.click();await page.getByLabel('Phone Number').fill(phone);await page.getByLabel('Password').fill(password);await page.locator('form').getByRole('button',{name:'Sign In',exact:true}).click();const setup=page.getByRole('heading',{name:/^(Complete your secure setup|Create 5-digit PIN)$/});try{await setup.waitFor({state:'visible',timeout:2500})}catch{return}if(await page.getByLabel('Day').isVisible()){await page.getByLabel('Day').fill('2');await page.getByLabel('Month').fill('1');await page.getByLabel('Year').fill('1990')}await page.getByLabel('Create 5-digit PIN').fill('12345');await page.getByLabel('Confirm PIN').fill('12345');await page.getByRole('button',{name:'Create PIN'}).click()}
async function noOverflow(page:Page){expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1)}

test('Shopper uses simplified mobile-safe navigation and account controls',async({page})=>{await login(page,process.env.E2E_SHOPPER_PHONE!);await expect(page.getByRole('heading',{name:'Shopper'})).toBeVisible();await expect(page.getByRole('navigation',{name:'Shopper navigation'}).getByRole('button')).toHaveText(['Discover Businesses','Cashback']);await page.getByRole('button',{name:'Cashback'}).click();await expect(page.getByText('Available Cashback',{exact:true})).toBeVisible();await expect(page.getByText('Next Payout Date',{exact:true})).toBeVisible();for(const hidden of ['Reserved Payout','Last Payout Date','Confirmed Purchases'])await expect(page.getByText(hidden,{exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Notifications'}).click();await expect(page.getByRole('complementary',{name:'Notifications'})).toBeVisible();await page.getByRole('button',{name:'Close notifications'}).last().click();await page.getByRole('button',{name:'Settings'}).click();await expect(page.getByRole('menuitem',{name:'Profile'})).toBeVisible();await noOverflow(page)})

test('Creator keeps daily actions and moves Creator ID into Profile',async({page})=>{await login(page,process.env.E2E_CREATOR_PHONE!);await expect(page.getByRole('heading',{name:'Creator'})).toBeVisible();await expect(page.getByRole('navigation',{name:'Creator sections'}).getByRole('button')).toHaveText(['Find Businesses','Ads','Payout']);await page.getByRole('button',{name:'Payout'}).click();await expect(page.getByText('Payout Amount',{exact:true})).toBeVisible();await expect(page.getByText('Next Payout Date',{exact:true})).toBeVisible();await expect(page.getByText('Reserved Payout',{exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Settings'}).click();await page.getByRole('menuitem',{name:'Profile'}).click();await expect(page.getByText('Creator ID',{exact:true})).toBeVisible();await noOverflow(page)})

test('Business uses simplified actions while Cashier Management remains reachable',async({page})=>{await login(page,process.env.E2E_OWNER_PHONE!);await expect(page.getByRole('heading',{name:'Business'})).toBeVisible();await expect(page.getByRole('navigation',{name:'Business sections'}).getByRole('button')).toHaveText(['Find Creators','Requests','Confirmed Sales','Wallet']);await page.getByRole('button',{name:'Settings'}).click();await expect(page.getByRole('menuitem',{name:'Cashier Management'})).toBeVisible();await page.getByRole('menuitem',{name:'Cashier Management'}).click();await expect(page.getByRole('heading',{name:/Cashier/i}).first()).toBeVisible();await noOverflow(page)})
