import {expect,test} from './fixtures'
import type {Page} from '@playwright/test'

const password=process.env.E2E_SHOPPER_PASSWORD!
async function login(page:Page,phone:string){await page.goto('/');const welcome=page.getByRole('button',{name:'Already have an account? Sign In'});if(await welcome.isVisible())await welcome.click();await page.getByLabel('Phone Number').fill(phone);await page.getByRole('textbox',{name:'Password'}).fill(password);await page.locator('form').getByRole('button',{name:'Sign In',exact:true}).click();const setup=page.getByRole('heading',{name:/^(Complete your secure setup|Create 5-digit PIN)$/});const app=page.locator('main.app');await expect(setup.or(app)).toBeVisible({timeout:30000});if(await app.isVisible())return;await page.getByLabel('Create 5-digit PIN').fill('12345');await page.getByLabel('Confirm PIN').fill('12345');await page.getByRole('button',{name:'Create PIN'}).click()}
async function noOverflow(page:Page){expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1)}

test('Customer uses simplified mobile-safe navigation and account controls',async({page})=>{await login(page,'shopper@e2e.invalid');await expect(page.getByRole('heading',{name:'Customer'})).toBeVisible();const nav=page.getByRole('navigation',{name:'Customer navigation'});await expect(nav.getByRole('button')).toHaveText(['Discover','Cashback','Profile']);await nav.getByRole('button',{name:'Cashback',exact:true}).click();await expect(page.getByText('Available Cashback',{exact:true})).toBeVisible();await expect(page.getByText('Next Payout Date',{exact:true})).toBeVisible();for(const hidden of ['Reserved Payout','Last Payout Date','Confirmed Purchases'])await expect(page.getByText(hidden,{exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Notifications'}).click();await expect(page.getByRole('complementary',{name:'Notifications'})).toBeVisible();await page.getByRole('button',{name:'Close notifications'}).last().click();await nav.getByRole('button',{name:'Profile',exact:true}).click();await expect(page.getByRole('heading',{name:'Profile'})).toBeVisible();await noOverflow(page)})

test('Creator keeps Confirmed Sales separate from Payout and Profile',async({page})=>{await login(page,'creator@e2e.invalid');await expect(page.getByRole('heading',{name:'Creator'})).toBeVisible();const nav=page.getByRole('navigation',{name:'Creator sections'});await expect(nav.getByRole('button')).toHaveText(['Find Businesses','Active Ads','Requests','Confirmed Sales','Payout','Profile']);await nav.getByRole('button',{name:'Confirmed Sales',exact:true}).click();await expect(page.getByRole('heading',{name:'Confirmed Sales'})).toBeVisible();await nav.getByRole('button',{name:'Payout',exact:true}).click();await expect(page.getByText('Payout Amount',{exact:true})).toBeVisible();await expect(page.getByText('Next Payout Date',{exact:true})).toBeVisible();await expect(page.getByText('Reserved Payout',{exact:true})).toHaveCount(0);await nav.getByRole('button',{name:'Profile',exact:true}).click();await expect(page.getByText('Creator ID',{exact:true})).toBeVisible();await noOverflow(page)})

test('Business keeps Confirmed Sales and Cashier Management reachable',async({page})=>{await login(page,'business-1@e2e.invalid');await expect(page.getByRole('heading',{name:'Business'})).toBeVisible();const nav=page.getByRole('navigation',{name:'Business sections'});await expect(nav.getByRole('button')).toHaveText(['Creators','Active Ads','Requests','Confirmed Sales','Checkout','Profile']);await nav.getByRole('button',{name:'Confirmed Sales',exact:true}).click();await expect(page.getByRole('heading',{name:'Confirmed Sales'})).toBeVisible();await page.getByRole('button',{name:'Settings'}).click();await expect(page.getByRole('menuitem',{name:'Cashier Management'})).toBeVisible();await page.getByRole('menuitem',{name:'Cashier Management'}).click();await expect(page.getByRole('heading',{name:/Cashier/i}).first()).toBeVisible();await noOverflow(page)})
