import { expect, test } from './fixtures'
import type { Page } from '@playwright/test'
import { login } from './auth-helpers'

const widths = [375, 390, 393, 430]
const screenshotDir = process.env.E2E_SCREENSHOT_DIR

async function assertNoOverflow(page: Page) {
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)
  expect(overflow).toBeLessThanOrEqual(1)
}

async function assertNavIconSize(page: Page, selector: string) {
  const sizes = await page.locator(selector).evaluateAll((nodes) =>
    nodes.map((node) => {
      const style = getComputedStyle(node)
      return { width: Number.parseFloat(style.width), height: Number.parseFloat(style.height) }
    }),
  )
  expect(sizes.length).toBeGreaterThan(0)
  for (const size of sizes) {
    expect(size.width).toBeGreaterThanOrEqual(18)
    expect(size.width).toBeLessThanOrEqual(26)
    expect(size.height).toBeGreaterThanOrEqual(18)
    expect(size.height).toBeLessThanOrEqual(26)
  }
}

async function assertNavGeometry(page: Page, selector: string, expectedCount: number, minWidth: number) {
  const nav = page.locator(selector)
  await expect(nav).toBeVisible()
  await expect(nav.locator('button')).toHaveCount(expectedCount)
  await expect(nav).toHaveCSS('position', 'fixed')
  await expect(nav.locator('[aria-current="page"]')).toHaveCount(1)
  const navBox = await nav.boundingBox()
  expect(navBox).not.toBeNull()
  expect(navBox!.height).toBeGreaterThanOrEqual(64)
  expect(navBox!.height).toBeLessThanOrEqual(82)
  const boxes = await nav.locator('button').evaluateAll((nodes) =>
    nodes.map((node) => {
      const box = node.getBoundingClientRect()
      return { width: box.width, height: box.height }
    }),
  )
  expect(boxes.length).toBe(expectedCount)
  for (const box of boxes) {
    expect(box.width).toBeGreaterThanOrEqual(minWidth)
    expect(box.height).toBeGreaterThanOrEqual(44)
    expect(box.height).toBeLessThanOrEqual(84)
  }
  await expect(page.locator('main, .account-shell').first()).toBeVisible()
}

for (const width of widths) {
  test(`mobile customer, creator, and business layouts stay within ${width}px`, async ({ page }) => {
    test.setTimeout(90_000)
    await page.setViewportSize({ width, height: 900 })

    await login(page, 'shopper@e2e.invalid')
    await expect(page.getByRole('heading', { name: 'Discover Promotions' })).toBeVisible()
    await expect(page.getByPlaceholder('Search business or creator')).toBeVisible()
    const customerNav = page.getByRole('navigation', { name: 'Customer navigation' })
    await expect(customerNav.getByRole('button')).toHaveText(['Discover', 'Cashback', 'Profile'])
    await expect(customerNav.getByRole('button', { name: 'Discover', exact: true })).toHaveAttribute('aria-current', 'page')
    await assertNavGeometry(page, 'nav[aria-label="Customer navigation"]', 3, 86)
    await assertNavIconSize(page, 'nav[aria-label="Customer navigation"] .workspace-nav-icon svg')
    await expect(page.getByLabel('Open filters')).toBeVisible()
    await page.getByLabel('Open filters').click()
    await expect(page.getByRole('dialog', { name: 'Filters' })).toBeVisible()
    await expect(page.getByText('Business Type', { exact: true })).toBeVisible()
    await expect(page.getByRole('combobox', { name: 'Business Type' })).toHaveValue('')
    await expect(page.getByText('Nearest', { exact: true })).toBeVisible()
    await expect(page.getByText('Recommended', { exact: true })).toBeVisible()
    await expect(page.getByText('📍 Near Me')).toBeVisible()
    await page.getByRole('button', { name: 'Done', exact: true }).click()
    await expect(page.getByRole('dialog', { name: 'Filters' })).toBeHidden()
    await page.getByRole('button', { name: 'Profile', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Profile' })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Help', exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Sign out', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Cashback', exact: true }).click()
    await expect(page.getByText('Available Cashback', { exact: true })).toBeVisible()
    await assertNoOverflow(page)

    await login(page, 'creator@e2e.invalid')
    const creatorNav = page.getByRole('navigation', { name: 'Creator sections' })
    await expect(creatorNav.getByRole('button')).toHaveText(['Home', 'Find Businesses', 'Active Ads', 'Requests', 'Payout', 'Profile'])
    await expect(creatorNav.getByRole('button', { name: 'Home', exact: true })).toHaveAttribute('aria-current', 'page')
    await assertNavGeometry(page, 'nav[aria-label="Creator sections"]', 6, 48)
    await assertNavIconSize(page, 'nav[aria-label="Creator sections"] .workspace-nav-icon svg')
    const creatorStroke = await creatorNav.locator('svg').first().getAttribute('stroke-width')
    expect(Number(creatorStroke)).toBeGreaterThanOrEqual(2.2)
    await expect(page.getByRole('heading', { name: 'Dashboard' })).toBeVisible()
    await expect(page.locator('.creator-home-stat')).toHaveCount(3)
    await expect(page.locator('.creator-home-stat').filter({ hasText: 'Confirmed Sales' }).locator('strong')).toHaveText('2')
    await expect(page.locator('.creator-home-stat').filter({ hasText: 'Pending Requests' }).locator('strong')).toHaveText('1')
    await expect(page.locator('.creator-recent-ad').first()).toBeVisible()
    const creatorStatus = page.locator('.account-identity--creator .account-status')
    await expect(creatorStatus).toHaveCSS('color', 'rgb(23, 107, 70)')
    const headerBox = await page.locator('.role-creator .account-header').boundingBox()
    const avatarBox = await page.locator('.role-creator .account-header-avatar').boundingBox()
    const identityBox = await page.locator('.role-creator .account-header-creator-copy').boundingBox()
    const actionsBox = await page.locator('.role-creator .account-actions').boundingBox()
    expect(headerBox).not.toBeNull()
    expect(avatarBox).not.toBeNull()
    expect(identityBox).not.toBeNull()
    expect(actionsBox).not.toBeNull()
    expect(headerBox!.height).toBeLessThanOrEqual(104)
    expect(avatarBox!.x).toBeLessThan(identityBox!.x)
    expect(avatarBox!.x + avatarBox!.width).toBeLessThanOrEqual(actionsBox!.x)
    expect(avatarBox!.y).toBeGreaterThanOrEqual(headerBox!.y)
    expect(avatarBox!.y + avatarBox!.height).toBeLessThanOrEqual(headerBox!.y + headerBox!.height)
    const settings = page.getByRole('button', { name: 'Settings', exact: true })
    await settings.click()
    const settingsMenu = page.getByRole('menu')
    await expect(settingsMenu).toBeVisible()
    const settingsBox = await settingsMenu.boundingBox()
    expect(settingsBox).not.toBeNull()
    expect(settingsBox!.x).toBeGreaterThanOrEqual(0)
    expect(settingsBox!.x + settingsBox!.width).toBeLessThanOrEqual(width)
    const notificationRow = settingsMenu.locator('.settings-notification-row')
    await expect(notificationRow).toContainText('Enable device')
    await expect(notificationRow).toContainText('notifications')
    const notificationRowBox = await notificationRow.boundingBox()
    const notificationControlBox = await notificationRow.locator('.settings-row-control').boundingBox()
    expect(notificationRowBox).not.toBeNull()
    expect(notificationControlBox).not.toBeNull()
    expect(notificationControlBox!.x).toBeGreaterThan(notificationRowBox!.x + notificationRowBox!.width / 2)
    if (screenshotDir) await page.screenshot({ path: `${screenshotDir}/creator-settings-${width}.png`, animations: 'disabled' })
    await settings.click()
    await page.waitForTimeout(250)
    if (screenshotDir) await page.screenshot({ path: `${screenshotDir}/creator-home-${width}.png`, animations: 'disabled' })
    await creatorNav.getByRole('button', { name: 'Find Businesses', exact: true }).click()
    await expect(page.locator('.business-discovery-card .business-card-days')).toHaveCount(0)
    await page.getByRole('button', { name: 'Active Ads', exact: true }).click()
    await expect(creatorNav.getByRole('button', { name: 'Active Ads', exact: true })).toHaveAttribute('aria-current', 'page')
    await expect.poll(() => page.evaluate(() => window.scrollY)).toBeLessThanOrEqual(1)
    await expect(creatorNav.getByRole('button', { name: 'Find Businesses', exact: true })).not.toHaveAttribute('aria-current', 'page')
    await page.getByRole('button', { name: 'Requests', exact: true }).click()
    await expect(creatorNav.getByRole('button', { name: 'Requests', exact: true })).toHaveAttribute('aria-current', 'page')
    await page.getByRole('button', { name: 'Payout', exact: true }).click()
    await expect(creatorNav.getByRole('button', { name: 'Payout', exact: true })).toHaveAttribute('aria-current', 'page')
    await expect(page.getByText('Upcoming Payout', { exact: true })).toBeVisible()
    await expect(page.getByText('40.00', { exact: true })).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Payout History' })).toBeVisible()
    const paidPayout = page.locator('.creator-payout-history-item').filter({ hasText: 'Paid' })
    await expect(paidPayout).toContainText('60.00')
    await expect(paidPayout).toContainText('Paid')
    await expect(page.locator('main.creator-app')).not.toContainText('ETB')
    if (screenshotDir) await page.screenshot({ path: `${screenshotDir}/creator-payout-${width}.png`, animations: 'disabled' })
    await creatorNav.getByRole('button', { name: 'Home', exact: true }).click()
    await page.locator('.creator-home-stat').filter({ hasText: 'Confirmed Sales' }).click()
    await expect(creatorNav.getByRole('button', { name: 'Home', exact: true })).toHaveAttribute('aria-current', 'page')
    await expect(page.getByRole('heading', { name: 'Confirmed Sales' })).toBeVisible()
    await page.getByRole('button', { name: 'Active Ads', exact: true }).click()
    await expect(creatorNav.getByRole('button', { name: 'Active Ads', exact: true })).toHaveAttribute('aria-current', 'page')
    await expect(page.getByRole('heading', { name: 'Creator' })).toBeVisible()
    const activeRow = page.locator('.creator-ads-row.relationship-active').filter({ hasText: 'Active E2E Business' }).first()
    await expect(activeRow).toBeVisible()
    await expect(activeRow.getByRole('link', { name: 'View TikTok Video' })).toHaveAttribute('href', 'https://www.tiktok.com/@weymela-e2e/video/1234567890123456789')
    const activeBadge = activeRow.locator('.creator-ad-status--live')
    await expect(activeBadge).toHaveText('Active')
    const badgeBox = await activeBadge.boundingBox()
    expect(badgeBox).not.toBeNull()
    expect(badgeBox!.width).toBeLessThanOrEqual(90)
    await expect(activeRow.locator('.creator-ads-activated')).not.toBeEmpty()
    await expect(activeRow.locator('.creator-ads-days')).toContainText('days left')
    const awaitingRow = page.locator('.creator-ads-row').filter({ hasText: 'Approved Metric Business' })
    const addVideo = awaitingRow.getByRole('button', { name: 'Add Promo Video', exact: true })
    await expect(awaitingRow.getByText('Awaiting Video', { exact: true })).toBeVisible()
    const addVideoBox = await addVideo.boundingBox()
    expect(addVideoBox).not.toBeNull()
    expect(addVideoBox!.height).toBeGreaterThanOrEqual(30)
    expect(addVideoBox!.height).toBeLessThanOrEqual(34)
    expect(addVideoBox!.width).toBeLessThanOrEqual(140)
    await expect(awaitingRow.locator('.creator-ads-activated')).toBeEmpty()
    await expect(awaitingRow.locator('.creator-ads-days')).toBeEmpty()
    await page.waitForTimeout(250)
    if (screenshotDir) await page.screenshot({ path: `${screenshotDir}/creator-active-ads-${width}.png`, animations: 'disabled' })
    await page.getByRole('button', { name: 'Profile', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Profile' })).toBeVisible()
    await expect.poll(() => page.evaluate(() => window.scrollY)).toBeLessThanOrEqual(1)
    await expect(page.getByText('Creator ID', { exact: true })).toBeVisible()
    await page.waitForTimeout(250)
    if (screenshotDir) await page.screenshot({ path: `${screenshotDir}/creator-profile-${width}.png`, animations: 'disabled' })
    await assertNoOverflow(page)

    await login(page, 'business-1@e2e.invalid')
    const businessNav = page.getByRole('navigation', { name: 'Business sections' })
    await expect(page.getByRole('heading', { name: 'Business' })).toBeVisible()
    await expect(businessNav.getByRole('button')).toHaveText(['Creators', 'Active Ads', 'Requests', 'Confirmed Sales', 'Checkout', 'Profile'])
    await expect(businessNav.getByRole('button', { name: 'Creators', exact: true })).toHaveAttribute('aria-current', 'page')
    await assertNavGeometry(page, 'nav[aria-label="Business sections"]', 6, 48)
    await assertNavIconSize(page, 'nav[aria-label="Business sections"] .workspace-nav-icon svg')
    await page.getByRole('button', { name: 'Active Ads', exact: true }).click()
    await expect(businessNav.getByRole('button', { name: 'Active Ads', exact: true })).toHaveAttribute('aria-current', 'page')
    await expect(businessNav.getByRole('button', { name: 'Creators', exact: true })).not.toHaveAttribute('aria-current', 'page')
    await expect(page.getByRole('button', { name: 'Requests', exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Checkout', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Requests', exact: true }).click()
    await expect(businessNav.getByRole('button', { name: 'Requests', exact: true })).toHaveAttribute('aria-current', 'page')
    await page.getByRole('button', { name: 'Confirmed Sales', exact: true }).click()
    await expect(businessNav.getByRole('button', { name: 'Confirmed Sales', exact: true })).toHaveAttribute('aria-current', 'page')
    await expect(page.getByRole('heading', { name: 'Confirmed Sales' })).toBeVisible()
    await page.getByRole('button', { name: 'Checkout', exact: true }).click()
    await expect(businessNav.getByRole('button', { name: 'Checkout', exact: true })).toHaveAttribute('aria-current', 'page')
    await page.getByRole('button', { name: 'Profile', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Profile' })).toBeVisible()
    await expect(page.getByText('Business Type')).toBeVisible()
    await assertNoOverflow(page)
  })
}

test('desktop role navigation stays in the top chrome and remains compact', async ({ page }) => {
  test.setTimeout(90_000)
  await page.setViewportSize({ width: 1280, height: 900 })

  await login(page, 'shopper@e2e.invalid')
  const customerNav = page.getByRole('navigation', { name: 'Customer navigation' })
  await expect(customerNav).not.toHaveCSS('position', 'fixed')
  await expect(customerNav.getByRole('button')).toHaveText(['Discover', 'Cashback', 'Profile'])
  await assertNavIconSize(page, 'nav[aria-label="Customer navigation"] .workspace-nav-icon svg')
  expect((await customerNav.boundingBox())!.height).toBeLessThanOrEqual(64)

  await login(page, 'creator@e2e.invalid')
  const creatorNav = page.getByRole('navigation', { name: 'Creator sections' })
  await expect(creatorNav).not.toHaveCSS('position', 'fixed')
  await expect(creatorNav.getByRole('button')).toHaveText(['Home', 'Find Businesses', 'Active Ads', 'Requests', 'Payout', 'Profile'])
  await assertNavIconSize(page, 'nav[aria-label="Creator sections"] .workspace-nav-icon svg')
  expect((await creatorNav.boundingBox())!.height).toBeLessThanOrEqual(64)
  if (screenshotDir) await page.screenshot({ path: `${screenshotDir}/creator-home-desktop.png`, fullPage: true, animations: 'disabled' })

  await login(page, 'business-1@e2e.invalid')
  const businessNav = page.getByRole('navigation', { name: 'Business sections' })
  await expect(businessNav).not.toHaveCSS('position', 'fixed')
  await expect(businessNav.getByRole('button')).toHaveText(['Creators', 'Active Ads', 'Requests', 'Confirmed Sales', 'Checkout', 'Profile'])
  await assertNavIconSize(page, 'nav[aria-label="Business sections"] .workspace-nav-icon svg')
  expect((await businessNav.boundingBox())!.height).toBeLessThanOrEqual(64)
  await assertNoOverflow(page)
})
