import {expect,test} from './fixtures'
import type {Page} from '@playwright/test'
import {randomUUID} from 'node:crypto'
const api=process.env.E2E_API_URL!,phone=process.env.E2E_SHOPPER_PHONE!,password=process.env.E2E_SHOPPER_PASSWORD!,creator=process.env.E2E_CREATOR_NAME!,offer=process.env.E2E_ACTIVE_OFFER!,expired=process.env.E2E_EXPIRED_OFFER!
function diagnostics(page:Page){const errors:string[]=[];page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('pageerror',e=>errors.push(e.message));return errors}
async function openSignIn(page:Page){await page.goto('/help');await page.evaluate(()=>localStorage.clear());await page.goto('/');const welcome=page.getByRole('button',{name:'Already have an account? Sign In'});if(await welcome.isVisible())await welcome.click();await expect(page.getByLabel('Phone Number')).toBeVisible()}
async function signIn(page:Page){await openSignIn(page);await page.getByLabel('Phone Number').fill(phone);await page.getByRole('textbox',{name:'Password'}).fill(password);await page.locator('form').getByRole('button',{name:'Sign In'}).click();const enroll=page.getByRole('heading',{name:'Create 5-digit PIN'});let needsEnrollment=false;try{await enroll.waitFor({state:'visible',timeout:5000});needsEnrollment=true}catch{}if(needsEnrollment){const pinInputs=page.locator('label.pin-entry input');await expect(pinInputs).toHaveCount(2);await pinInputs.nth(0).fill('12345');await pinInputs.nth(1).fill('12345');await expect(pinInputs.nth(0)).toHaveValue('12345');await expect(pinInputs.nth(1)).toHaveValue('12345');await page.getByRole('button',{name:'Create PIN'}).click();await expect(enroll).toHaveCount(0,{timeout:10000})}await expect(page.getByRole('navigation',{name:'Customer navigation'})).toBeVisible();await expect(page.getByRole('button',{name:'Home',exact:true})).toBeVisible()}

test('production-style service probes are reachable',async({page,request})=>{const live=await request.get(`${api}/health/live`);expect(live.ok()).toBeTruthy();expect(await live.json()).toMatchObject({status:'Healthy',service:'CreatorPay API'});const ready=await request.get(`${api}/health/ready`);expect(ready.ok()).toBeTruthy();await page.goto('/healthz');await expect(page.locator('body')).toContainText('healthy')})

test('Shopper remains English-only with unified tools and a useful Profile',async({page})=>{await signIn(page);await expect(page.locator('body')).not.toContainText(/[\u1200-\u137f]/);await page.getByRole('button',{name:'Settings'}).click();const menu=page.getByRole('menu');await expect(menu.getByRole('menuitem',{name:'Help',exact:true})).toBeVisible();await page.getByRole('button',{name:'Settings'}).click();await page.getByRole('navigation',{name:'Customer navigation'}).getByRole('button',{name:'Profile',exact:true}).click();for(const label of ['Name','Email','Phone','Status'])await expect(page.getByText(label,{exact:true})).toBeVisible();for(const label of ['Email Verified','Phone Verified'])await expect(page.getByText(label,{exact:true})).toHaveCount(0);await expect(page.locator('.shopper-profile').getByRole('button')).toHaveCount(0)})

test('authentication failures are safe and Shopper session logs out',async({page})=>{await openSignIn(page);for(const [number,secret] of [[phone,'Wrong1!Password'],['0911000999',password]]){await page.getByLabel('Phone Number').fill(number);await page.getByRole('textbox',{name:'Password'}).fill(secret);await page.locator('form').getByRole('button',{name:'Sign In'}).click();await expect(page.getByRole('status')).toContainText('Invalid phone number or password.');if(number!== '0911000999')await openSignIn(page)}await signIn(page);await page.getByRole('button',{name:'Settings'}).click();await page.getByRole('menu').getByRole('menuitem',{name:'Sign out',exact:true}).click();await expect(page.locator('form').getByRole('button',{name:'Sign In'})).toBeVisible();expect(await page.evaluate(()=>[localStorage.getItem('creatorpay_access_token'),localStorage.getItem('creatorpay_refresh_token')])).toEqual([null,null]);await page.goto('/creator');await expect(page.locator('form').getByRole('button',{name:'Sign In'})).toBeVisible()})

test('shopper summary and simplified notifications render cleanly',async({page})=>{const errors=diagnostics(page);await signIn(page);const notifications=page.getByRole('button',{name:'Notifications'});await expect(notifications.locator('.notification-count')).toHaveCount(0);await notifications.click();await expect(page.getByRole('complementary',{name:'Notifications'})).toBeVisible();await expect(page.getByText('No notifications yet.')).toBeVisible();await page.getByRole('button',{name:'Close notifications'}).last().click();await page.getByRole('button',{name:'Cashback'}).click();await expect(page.getByText('Available cashback')).toBeVisible();await expect(page.getByText('0.00',{exact:true})).toHaveCount(1);await expect(page.getByText('Next Payout Date')).toBeVisible();await expect(page.getByRole('button',{name:'Mark all read'})).toHaveCount(0);await expect(page.getByText('Notification preferences')).toHaveCount(0);await expect(page.locator('body')).not.toContainText('Unexpected token <');expect(errors).toEqual([]);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);expect(overflow).toBeLessThanOrEqual(1)})

test('Shopper sees one compact card per active Creator promotion with Creator ID',async({page})=>{await signIn(page);await page.getByRole('navigation',{name:'Customer navigation'}).getByRole('button',{name:'Discover',exact:true}).click();const rows=page.locator('.customer-promotion-card');expect(await rows.count()).toBeGreaterThanOrEqual(2);await expect(rows.filter({hasText:creator})).toContainText('Creator ID 4827');const mimi=rows.filter({hasText:'Mimi Active'});await expect(mimi).toContainText('Creator ID 4830');await expect(mimi).toContainText('Watch Promotion');await expect(page.getByLabel('Category')).toHaveCount(0);await expect(page.locator('input[type=file]')).toHaveCount(0);await expect(mimi).not.toContainText(/wallet|minimum|@e2e\.invalid|\+251/i);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);expect(overflow).toBeLessThanOrEqual(1)})

test('Shopper Business and Creator type-ahead waits for two characters and ignores stale results',async({page})=>{let calls=0;await page.route('**/api/v1/customer/discovery/advertising**',async route=>{calls++;if(new URL(route.request().url()).searchParams.get('q')?.toLowerCase()==='zz')await new Promise(r=>setTimeout(r,700));await route.continue()});await signIn(page);await page.getByRole('navigation',{name:'Customer navigation'}).getByRole('button',{name:'Discover',exact:true}).click();const result=page.locator('article').filter({hasText:'Active E2E Business'}).first();await expect(result).toBeVisible();const input=page.getByPlaceholder('Search business or creator'),initial=calls;await input.fill('Z');await page.waitForTimeout(400);expect(calls).toBe(initial);await input.fill('Zz');await page.waitForTimeout(350);await input.fill('Mi');await expect(page.locator('article').filter({hasText:'Mimi Active'})).toBeVisible();await page.waitForTimeout(800);await expect(page.locator('article').filter({hasText:'Mimi Active'})).toBeVisible();expect(calls).toBeGreaterThan(initial)})


test('authenticated Shopper logs out after inactivity and activity resets the timer',async({page})=>{await page.clock.install();await signIn(page);await page.clock.fastForward(90_000);await page.getByRole('button',{name:'Cashback'}).click();await page.clock.fastForward(90_000);await expect(page.getByRole('heading',{name:'Shopper'})).toBeVisible();await page.clock.fastForward(31_000);await expect(page.locator('form').getByRole('button',{name:'Sign In'})).toBeVisible()})

test('a 401 response clears the session and returns to Sign In',async({page})=>{await signIn(page);await page.route('**/api/v1/customer/discovery/advertising**',route=>route.fulfill({status:401,contentType:'application/json',body:'{"detail":"Authentication required."}'}));await page.reload();const pin=page.getByLabel('5-digit PIN');if(await pin.isVisible({timeout:5000}).catch(()=>false)){await pin.fill('12345');await page.getByRole('button',{name:'Sign In',exact:true}).click()}const welcome=page.getByRole('button',{name:'Already have an account? Sign In',exact:true});if(await welcome.isVisible({timeout:10000}).catch(()=>false))await welcome.click();await expect(page.locator('form').getByRole('button',{name:'Sign In'})).toBeVisible();expect(await page.evaluate(()=>localStorage.getItem('creatorpay_access_token'))).toBeNull()})

test('expired Offer is unavailable and checkout creation requires the Shopper role',async({page,request})=>{await page.goto(`/offers/${expired}`);await expect(page.getByRole('heading',{name:'Offer unavailable'})).toBeVisible();const unauth=await request.post(`${api}/api/v1/customer/checkouts/by-offer`,{data:{offerCode:offer},headers:{'Idempotency-Key':randomUUID()}});expect(unauth.status()).toBe(401);await signIn(page);await page.goto(`/offers/${offer}`);const purchasesBefore=await request.get(`${api}/api/v1/customer/checkouts`);expect(purchasesBefore.status()).toBe(401);await page.getByRole('button',{name:'Support this Creator'}).click();await expect(page.getByText('Temporary checkout QR',{exact:false})).toBeVisible()})

test('primary actions are keyboard reachable in the English-only UI',async({page})=>{await openSignIn(page);await expect(page.getByLabel(/Language/)).toHaveCount(0);await expect(page.locator('form').getByRole('button',{name:'Sign In'})).toBeVisible();await page.keyboard.press('Tab');expect(await page.evaluate(()=>document.activeElement?.tagName)).not.toBe('BODY')})
