import {expect,test} from './fixtures'
import type {Page} from '@playwright/test'
import {randomUUID} from 'node:crypto'
const api=process.env.E2E_API_URL!,email=process.env.E2E_SHOPPER_EMAIL!,password=process.env.E2E_SHOPPER_PASSWORD!,creator=process.env.E2E_CREATOR_NAME!,offer=process.env.E2E_ACTIVE_OFFER!,expired=process.env.E2E_EXPIRED_OFFER!,qr=process.env.E2E_OFFER_QR!
function diagnostics(page:Page){const errors:string[]=[];page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('pageerror',e=>errors.push(e.message));return errors}
const shopperTourKey='weymela_tour_v32_Shopper'
async function dismissShopperTour(page:Page){const tour=page.getByRole('dialog',{name:'Welcome to Weymela'});if(await tour.isVisible()){await tour.getByRole('button',{name:'Not now'}).click();await expect(tour).toBeHidden();expect(await page.evaluate(key=>localStorage.getItem(key),shopperTourKey)).toBe('skipped')}}
async function signIn(page:Page,dismissTour=true){await page.goto('/');await page.getByLabel('Email').fill(email);await page.getByLabel('Password').fill(password);await page.getByRole('button',{name:'Sign In'}).click();await expect(page.getByRole('heading',{name:'Shopper workspace'})).toBeVisible();if(dismissTour)await dismissShopperTour(page)}

test('production-style service probes are reachable',async({page,request})=>{const live=await request.get(`${api}/health/live`);expect(live.ok()).toBeTruthy();expect(await live.json()).toMatchObject({status:'Healthy',service:'CreatorPay API'});const ready=await request.get(`${api}/health/ready`);expect(ready.ok()).toBeTruthy();await page.goto('/healthz');await expect(page.locator('body')).toContainText('healthy')})

test('first-run Shopper tour dismisses through real UI and stays dismissed',async({page})=>{await signIn(page,false);const tour=page.getByRole('dialog',{name:'Welcome to Weymela'});await expect(tour).toBeVisible();expect(await page.evaluate(key=>localStorage.getItem(key),shopperTourKey)).toBeNull();await tour.getByRole('button',{name:'Not now'}).click();await expect(tour).toBeHidden();expect(await page.evaluate(key=>localStorage.getItem(key),shopperTourKey)).toBe('skipped');await page.reload();await expect(page.getByRole('heading',{name:'Shopper workspace'})).toBeVisible();await expect(page.getByRole('dialog',{name:'Welcome to Weymela'})).toHaveCount(0);const confirmations=page.getByRole('button',{name:'Purchase Confirmations'});await confirmations.click();await expect(confirmations).toHaveClass(/active/)})

test('authentication failures are safe and shopper session logs out',async({page})=>{await page.goto('/');for(const [address,secret] of [[email,'Wrong1!Password'],['unknown@e2e.invalid',password]]){await page.getByLabel('Email').fill(address);await page.getByLabel('Password').fill(secret);await page.getByRole('button',{name:'Sign In'}).click();await expect(page.getByRole('status')).toContainText('Invalid email or password.')}await signIn(page);await page.getByRole('button',{name:'Sign out'}).click();await expect(page.getByRole('button',{name:'Sign In'})).toBeVisible();expect(await page.evaluate(()=>[localStorage.getItem('creatorpay_access_token'),localStorage.getItem('creatorpay_refresh_token')])).toEqual([null,null]);await page.goto('/creator');await expect(page.getByRole('button',{name:'Sign In'})).toBeVisible()})

test('shopper summary and simplified notifications render cleanly',async({page})=>{const errors=diagnostics(page);await signIn(page);await expect(page.getByText('0 unread')).toBeVisible();await expect(page.getByText('Available cashback')).toBeVisible();await expect(page.getByText('0.00 ETB')).toHaveCount(2);await expect(page.getByText('Reserved payout')).toBeVisible();await expect(page.getByText('No notifications yet.')).toBeVisible();await page.getByRole('button',{name:'Mark all read'}).click();await expect(page.getByText('Notification preferences')).toHaveCount(0);await expect(page.locator('body')).not.toContainText('Unexpected token <');expect(errors).toEqual([]);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);expect(overflow).toBeLessThanOrEqual(1)})

test('creator discovery exposes only safe public fields and canonical Offer routes',async({page,request})=>{await signIn(page);await page.getByRole('button',{name:'Discover Creators'}).click();await page.getByPlaceholder('Search creator name').fill(`  ${creator.toUpperCase()}  `);await page.getByRole('button',{name:'Search'}).click();const card=page.locator('article').filter({hasText:creator});await expect(card).toBeVisible();await expect(card).not.toContainText('@e2e.invalid');await expect(card).not.toContainText('+251');await card.getByRole('button',{name:'View Creator'}).click();await expect(page.getByRole('link',{name:'TikTok'})).toHaveAttribute('rel','noopener noreferrer');await expect(page.getByRole('link',{name:'YouTube'})).toBeVisible();await expect(page.getByRole('link',{name:'Other'})).toHaveCount(0);const response=await request.get(`${api}/api/v1/discovery/creators?q=${encodeURIComponent('  SELAM ACTIVE  ')}`);expect(response.ok()).toBeTruthy();const body=await response.text();expect(body).not.toMatch(/email|phone|payout|tax|follower|risk/i);for(const path of [`/offers/${offer}`,`/o/${offer}`]){await page.goto(path);await expect(page.getByText('E2E Active Offer',{exact:false})).toBeVisible()}const resolved=await request.get(`${api}/api/v1/discovery/offer-qr/${qr}`);expect((await resolved.json()).offerCode).toBe(offer)})

test('expired Offer is unavailable and checkout creation requires the Shopper role',async({page,request})=>{await page.goto(`/offers/${expired}`);await expect(page.getByRole('heading',{name:'Offer unavailable'})).toBeVisible();const unauth=await request.post(`${api}/api/v1/customer/checkouts/by-offer`,{data:{offerCode:offer},headers:{'Idempotency-Key':randomUUID()}});expect(unauth.status()).toBe(401);await signIn(page);await page.goto(`/offers/${offer}`);const purchasesBefore=await request.get(`${api}/api/v1/customer/checkouts`);expect(purchasesBefore.status()).toBe(401);await page.getByRole('button',{name:'Shop with this Creator'}).click();await expect(page.getByText('Temporary checkout QR',{exact:false})).toBeVisible()})

test('primary actions are keyboard reachable and language switch preserves route',async({page})=>{await page.goto('/');await page.getByLabel(/Language/).selectOption('am');await expect(page).toHaveURL('/');await expect(page.getByRole('button',{name:/ይግቡ|Sign In/})).toBeVisible();await page.keyboard.press('Tab');expect(await page.evaluate(()=>document.activeElement?.tagName)).not.toBe('BODY')})
