import {expect,test} from './fixtures'

const tab=(page:any,name:string)=>page.getByLabel('Welcome options').getByRole('button',{name,exact:true})

test('Welcome modes clear fields, messages, OTP reset state, and fit the viewport',async({page})=>{
  await page.goto('/')

  await page.getByLabel('Phone Number').fill('0911234567')
  await page.getByLabel('Password').fill('OldPassword1!')
  await tab(page,'Shopper Registration').click()
  await expect(page.getByLabel('Display Name')).toHaveValue('')
  await expect(page.getByLabel('Phone',{exact:true})).toHaveValue('')
  await expect(page.getByLabel('Email',{exact:true})).toHaveValue('')

  await page.getByLabel('Display Name').fill('Test Shopper')
  await page.getByLabel('Phone',{exact:true}).fill('0911234567')
  await page.getByLabel('Email',{exact:true}).fill('shopper@example.test')
  await tab(page,'Sign In').click()
  await expect(page.getByLabel('Phone Number')).toHaveValue('')
  await expect(page.getByLabel('Password')).toHaveValue('')

  await tab(page,'Content Creator Registration').click()
  await page.getByLabel('Legal First Name').fill('Ayele')
  await page.getByLabel("Father's Name").fill('Kebede')
  await page.getByLabel('Public Display Name').fill('Ayele K')
  await page.getByLabel('Phone',{exact:true}).fill('0911234567')
  await page.getByLabel('Primary Social Platform').fill('TikTok')
  await page.getByLabel('Estimated Follower Count').fill('1200')
  await page.getByLabel(/accept the pilot terms/i).check()
  await tab(page,'Business Owner Registration').click()
  await expect(page.getByLabel('Legal Business Name')).toHaveValue('')
  await expect(page.getByLabel('Trading Name')).toHaveValue('')
  await expect(page.getByLabel('Business Type')).toHaveValue('')
  await expect(page.getByLabel(/accept the pilot terms/i)).not.toBeChecked()

  await page.getByLabel('Legal Business Name').fill('Test Business PLC')
  await page.getByLabel('Trading Name').fill('Test Business')
  await page.getByLabel('Business Type').selectOption('Restaurant / Café')
  await page.getByLabel('Primary Contact Name').fill('Owner')
  await page.getByLabel('Business Address').fill('Main Street')
  await page.getByLabel(/accept the pilot terms/i).check()
  await tab(page,'Content Creator Registration').click()
  await expect(page.getByLabel('Legal First Name')).toHaveValue('')
  await expect(page.getByLabel("Father's Name")).toHaveValue('')
  await expect(page.getByLabel('Public Display Name')).toHaveValue('')
  await expect(page.getByLabel(/accept the pilot terms/i)).not.toBeChecked()

  await tab(page,'Sign In').click()
  await page.getByLabel('Phone Number').fill('0911000999')
  await page.getByLabel('Password').fill('WrongPassword1!')
  await page.getByRole('button',{name:'Sign In',exact:true}).last().click()
  await expect(page.getByRole('status')).toContainText('Invalid phone number or password.')
  await tab(page,'Shopper Registration').click()
  await expect(page.getByRole('status')).toHaveCount(0)

  await tab(page,'Sign In').click()
  await page.getByRole('button',{name:'Forgot Password'}).click()
  await page.getByLabel('Phone Number').fill('0911234567')
  await tab(page,'Shopper Registration').click()
  await tab(page,'Sign In').click()
  await expect(page.getByRole('button',{name:'Forgot Password'})).toBeVisible()
  await expect(page.getByLabel('Phone Number')).toHaveValue('')
  await expect(page.getByText('6-digit verification code')).toHaveCount(0)

  for(const name of ['Sign In','Shopper Registration','Content Creator Registration','Business Owner Registration'])
    await expect(tab(page,name)).toBeVisible()
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)
  expect(overflow).toBeLessThanOrEqual(1)
})
