using CreatorPay.Application.CustomerVerification;
using CreatorPay.Application.Qr;
using CreatorPay.Application.Wallet;
using CreatorPay.Application.Notifications;
using CreatorPay.Domain.Entities;
using CreatorPay.Domain.Enums;
using CreatorPay.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
namespace CreatorPay.Infrastructure.CustomerVerification;

public sealed class RepeatUseApprovalService(ApplicationDbContext db, IPhoneNumberNormalizer normalizer, IPhoneHashService hashes, IPhoneEncryptionService encryption, ICustomerVerificationProvider codes, ICreatorQrService qr, IWalletService wallet, INotificationService notifications, IOptions<CustomerVerificationOptions> options, IOptions<NotificationOptions> notificationOptions) : IRepeatUseApprovalService
{
    readonly CustomerVerificationOptions policy = options.Value;
    public async Task<object> PrecheckAsync(Guid merchantId, Guid actor, Guid cashierId, string role, PurchasePrecheckRequest r, CancellationToken ct) { var n = normalizer.Normalize(r.CustomerPhoneNumber); var h = hashes.Hash(n); var context = await Resolve(merchantId, actor, cashierId, role, r.QrPayload, r.MerchantLocationId, ct); var repeat = await Used(merchantId, context.Creator.Id, h, context.Date, ct); return new { status = repeat ? "ApprovalRequired" : "Eligible", maskedPhoneNumber = normalizer.Mask(n), merchantLocalDate = context.Date, requiresApproval = repeat, message = repeat ? "This phone was already used today for this merchant and creator." : "Phone is eligible for this purchase." }; }
    public async Task<RepeatUseDto?> GateAsync(Guid merchantId, Guid actor, Guid cashierId, string role, string key, ConfirmPurchaseRequest r, CancellationToken ct) { var n = normalizer.Normalize(r.CustomerPhoneNumber); var h = hashes.Hash(n); var c = await Resolve(merchantId, actor, cashierId, role, r.QrPayload, r.MerchantLocationId, ct); if (r.RepeatUseApprovalRequestId.HasValue) { var approved = await db.RepeatUseApprovalRequests.SingleOrDefaultAsync(x => x.Id == r.RepeatUseApprovalRequestId && x.MerchantId == merchantId, ct) ?? throw new KeyNotFoundException("Approval request was not found."); if (approved.Status != RepeatUseApprovalStatus.Approved || approved.FinalizedAtUtc.HasValue || approved.ExpiresAtUtc <= DateTime.UtcNow || approved.CustomerPhoneHash != h) throw new InvalidOperationException("The repeat-use approval is not valid for this purchase."); return null; } if (!await Used(merchantId, c.Creator.Id, h, c.Date, ct)) return null; var old = await db.RepeatUseApprovalRequests.AsNoTracking().SingleOrDefaultAsync(x => x.MerchantId == merchantId && x.IdempotencyKey == key, ct); if (old is not null) return Map(old); var count = await db.RepeatUseApprovalRequests.CountAsync(x => x.MerchantId == merchantId && x.CustomerPhoneHash == h && x.MerchantLocalDate == c.Date, ct); if (count >= policy.MaximumRepeatUseApprovalsPerDay) throw new InvalidOperationException("Maximum repeat-use approval requests reached for today."); var phone = await db.CustomerPhoneReferences.SingleOrDefaultAsync(x => x.PhoneNumberHash == h, ct); if (phone is null) { phone = new() { Id = Guid.NewGuid(), PhoneNumberHash = h, EncryptedPhoneNumber = encryption.Encrypt(n), MaskedPhoneNumber = normalizer.Mask(n), CreatedAtUtc = DateTime.UtcNow }; db.Add(phone); } var now = DateTime.UtcNow; var x = new RepeatUseApprovalRequest { Id = Guid.NewGuid(), PublicApprovalRequestId = $"RUA-{Guid.NewGuid():N}", MerchantId = merchantId, MerchantLocationId = r.MerchantLocationId, CreatorId = c.Creator.Id, MerchantCreatorPartnershipId = c.PartnershipId, CashierId = cashierId, CreatedByUserId = actor, CustomerPhoneReferenceId = phone.Id, CustomerPhoneHash = h, MaskedPhoneNumber = phone.MaskedPhoneNumber, MerchantLocalDate = c.Date, PurchaseAmount = r.PurchaseAmount, CurrencyCode = r.CurrencyCode.Trim().ToUpperInvariant(), QrReference = r.QrPayload, Status = Initial(), RequestedAtUtc = now, ExpiresAtUtc = now.AddMinutes(policy.RepeatUseApprovalExpirationMinutes), IdempotencyKey = key, CorrelationId = key, RequiresCustomerConfirmation = policy.RequireCustomerOtpForRepeatUse, RequiresSupervisorApproval = policy.RequireSupervisorApprovalForRepeatUse, CreatedAtUtc = now }; db.Add(x); History(x, null, x.Status, actor, "ApprovalRequestCreated", null); Audit(x, "RepeatUseDetected", actor); await db.SaveChangesAsync(ct); return Map(x); }
    public async Task<RepeatUseDto> GetAsync(string id, Guid? merchantId, Guid? cashierId, Guid? supervisorId, bool admin, CancellationToken ct) { var x = await Scoped(id, merchantId, cashierId, supervisorId, admin, ct); return Map(x); }
    public async Task<IReadOnlyList<RepeatUseDto>> ListAsync(Guid? merchantId, Guid? supervisorId, bool admin, CancellationToken ct) { var q = db.RepeatUseApprovalRequests.AsNoTracking().AsQueryable(); if (!admin) q = q.Where(x => x.MerchantId == merchantId); if (supervisorId.HasValue) { var ids = db.SupervisorLocationAssignments.Where(a => a.SupervisorId == supervisorId && a.IsActive).Select(a => a.MerchantLocationId); q = q.Where(x => ids.Contains(x.MerchantLocationId)); } return (await q.OrderByDescending(x => x.RequestedAtUtc).Take(100).ToListAsync(ct)).Select(x => Map(x)).ToList(); }
    public async Task<RepeatUseDto> SendCodeAsync(string id, CancellationToken ct) { var x = await Find(id, ct); EnsureLive(x); if (!x.RequiresCustomerConfirmation) throw new InvalidOperationException("Customer confirmation is not required."); var generated = codes.CreateCode(); var now = DateTime.UtcNow; var prior = await db.CustomerConfirmations.SingleOrDefaultAsync(c => c.RepeatUseApprovalRequestId == x.Id, ct); if (prior is not null) db.Remove(prior); var confirmation = new CustomerConfirmation { Id = Guid.NewGuid(), RepeatUseApprovalRequestId = x.Id, CodeHash = generated.Hash, ExpiresAtUtc = now.AddMinutes(policy.CustomerVerificationCodeLifetimeMinutes), MaximumAttempts = policy.CustomerVerificationMaxAttempts, CreatedAtUtc = now }; db.Add(confirmation); x.CustomerConfirmationId = confirmation.Id; Audit(x, "VerificationCodeRequested", null); await notifications.CreateAsync(new(NotificationType.CustomerVerificationCode, $"otp:{x.Id}:{confirmation.Id}", new Dictionary<string, string> { { "Title", "Verification code requested" }, { "Body", $"A verification code was requested and expires in {policy.CustomerVerificationCodeLifetimeMinutes} minutes." }, { "ExpirationMinutes", policy.CustomerVerificationCodeLifetimeMinutes.ToString() } }, [new(null, NotificationRecipientType.Customer, NotificationChannel.Sms, x.CustomerPhoneReferenceId.ToString(), x.MaskedPhoneNumber)], NotificationPriority.Critical, x.CorrelationId, "RepeatUseApprovalRequest", x.PublicApprovalRequestId, confirmation.ExpiresAtUtc), ct); await db.SaveChangesAsync(ct); var reveal = policy.ReturnDevelopmentCode && notificationOptions.Value.DevelopmentRevealVerificationCode; return Map(x, reveal ? generated.Code : null); }
    public async Task<RepeatUseDto> VerifyCodeAsync(string id, string code, CancellationToken ct) { var x = await Find(id, ct); EnsureLive(x); var c = await db.CustomerConfirmations.SingleOrDefaultAsync(v => v.RepeatUseApprovalRequestId == x.Id, ct) ?? throw new InvalidOperationException("Request a verification code first."); var now = DateTime.UtcNow; if (c.ConfirmedAtUtc.HasValue) throw new InvalidOperationException("The code was already used."); if (c.ExpiresAtUtc <= now || c.AttemptCount >= c.MaximumAttempts) { c.FailedAtUtc = now; Audit(x, "ExcessVerificationAttempt", null); await db.SaveChangesAsync(ct); throw new InvalidOperationException("The verification code expired or has too many attempts."); } c.AttemptCount++; if (!codes.Verify(code, c.CodeHash)) { Audit(x, "CustomerConfirmationFailed", null); await db.SaveChangesAsync(ct); throw new ArgumentException("The verification code is invalid."); } c.ConfirmedAtUtc = now; x.CustomerConfirmedAtUtc = now; Transition(x, x.RequiresSupervisorApproval && !x.SupervisorApproved ? RepeatUseApprovalStatus.CustomerConfirmed : RepeatUseApprovalStatus.Approved, null, "CustomerConfirmationSucceeded", null); await notifications.CreateAsync(new(NotificationType.CustomerConfirmationSucceeded, $"customer-confirmed:{x.Id}", new Dictionary<string, string> { { "Title", "Customer confirmation succeeded" }, { "Body", "Customer confirmation was completed successfully." } }, [], NotificationPriority.High, x.CorrelationId, "RepeatUseApprovalRequest", x.PublicApprovalRequestId), ct); await db.SaveChangesAsync(ct); if (x.Status == RepeatUseApprovalStatus.Approved) await Finalize(x, ct); return Map(x); }
    public async Task<RepeatUseDto> DecideAsync(string id, Guid merchantId, Guid actor, Guid? supervisorId, bool approve, string? reason, CancellationToken ct) { var x = await Scoped(id, merchantId, null, supervisorId, false, ct); EnsureLive(x); if (x.CreatedByUserId == actor) throw new UnauthorizedAccessException("A cashier cannot approve their own request."); if (!approve) { x.SupervisorDecisionAtUtc = DateTime.UtcNow; x.SupervisorUserId = actor; Transition(x, RepeatUseApprovalStatus.Denied, actor, "ApprovalDenied", reason); await db.SaveChangesAsync(ct); return Map(x); } x.SupervisorApproved = true; x.SupervisorDecisionAtUtc = DateTime.UtcNow; x.SupervisorUserId = actor; Transition(x, x.RequiresCustomerConfirmation && !x.CustomerConfirmedAtUtc.HasValue ? RepeatUseApprovalStatus.SupervisorApproved : RepeatUseApprovalStatus.Approved, actor, "SupervisorApproved", reason); await db.SaveChangesAsync(ct); if (x.Status == RepeatUseApprovalStatus.Approved) await Finalize(x, ct); return Map(x); }
    async Task Finalize(RepeatUseApprovalRequest x, CancellationToken ct) { if (x.FinalizedAtUtc.HasValue) return; var phone = await db.CustomerPhoneReferences.FindAsync([x.CustomerPhoneReferenceId], ct) ?? throw new InvalidOperationException(); var result = await wallet.ConfirmPurchaseAsync(x.MerchantId, x.CreatedByUserId, x.CashierId, nameof(UserRole.Cashier), $"approved:{x.Id}", new(x.QrReference, x.MerchantLocationId, x.PurchaseAmount, x.CurrencyCode, null, encryption.Decrypt(phone.EncryptedPhoneNumber), x.Id), ct); x = await db.RepeatUseApprovalRequests.SingleAsync(a => a.Id == x.Id, ct); x.RelatedPurchaseTransactionId = result.TransactionId; x.FinalizedAtUtc = DateTime.UtcNow; History(x, RepeatUseApprovalStatus.Approved, RepeatUseApprovalStatus.Approved, null, "PurchaseFinalizedAfterApproval", null); await db.SaveChangesAsync(ct); }
    async Task<(Creator Creator, Guid PartnershipId, DateOnly Date)> Resolve(Guid merchant, Guid actor, Guid cashier, string role, string payload, Guid locationId, CancellationToken ct) { var valid = await qr.ValidateAsync(payload, locationId, merchant, actor, role, cashier, null, ct); if (!valid.IsValid) throw new InvalidOperationException(valid.Message); var creator = await db.Creators.SingleAsync(x => x.PublicCreatorId == valid.CreatorPublicId, ct); var l = await db.MerchantLocations.SingleAsync(x => x.Id == locationId && x.MerchantId == merchant && x.IsActive, ct); TimeZoneInfo zone; try { zone = TimeZoneInfo.FindSystemTimeZoneById(l.TimeZoneId); } catch { throw new InvalidOperationException("The merchant location timezone is invalid."); } return (creator, valid.PartnershipId!.Value, DateOnly.FromDateTime(TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, zone))); }
    Task<bool> Used(Guid m, Guid c, string h, DateOnly d, CancellationToken ct) => db.PurchaseTransactions.AnyAsync(x => x.MerchantId == m && x.CreatorId == c && x.CustomerPhoneHash == h && x.MerchantLocalDate == d && x.Status == TransactionStatus.Confirmed, ct);
    RepeatUseApprovalStatus Initial() => policy.RequireCustomerOtpForRepeatUse ? RepeatUseApprovalStatus.AwaitingCustomerConfirmation : RepeatUseApprovalStatus.AwaitingSupervisorApproval;
    async Task<RepeatUseApprovalRequest> Find(string id, CancellationToken ct) => await db.RepeatUseApprovalRequests.SingleOrDefaultAsync(x => x.PublicApprovalRequestId == id, ct) ?? throw new KeyNotFoundException();
    async Task<RepeatUseApprovalRequest> Scoped(string id, Guid? merchant, Guid? cashier, Guid? supervisor, bool admin, CancellationToken ct) { var x = await Find(id, ct); if (!admin && (x.MerchantId != merchant || (cashier.HasValue && x.CashierId != cashier))) throw new KeyNotFoundException(); if (supervisor.HasValue && !await db.SupervisorLocationAssignments.AnyAsync(a => a.SupervisorId == supervisor && a.MerchantLocationId == x.MerchantLocationId && a.IsActive, ct)) throw new UnauthorizedAccessException("The request is outside the supervisor's assigned locations."); return x; }
    void EnsureLive(RepeatUseApprovalRequest x) { if (x.ExpiresAtUtc <= DateTime.UtcNow) { x.Status = RepeatUseApprovalStatus.Expired; throw new InvalidOperationException("The approval request expired."); } if (x.Status is RepeatUseApprovalStatus.Denied or RepeatUseApprovalStatus.Cancelled or RepeatUseApprovalStatus.Expired || x.FinalizedAtUtc.HasValue) throw new InvalidOperationException("The approval request cannot be changed."); }
    void Transition(RepeatUseApprovalRequest x, RepeatUseApprovalStatus next, Guid? actor, string action, string? reason) { var old = x.Status; x.Status = next; History(x, old, next, actor, action, reason); Audit(x, action, actor); }
    void History(RepeatUseApprovalRequest x, RepeatUseApprovalStatus? old, RepeatUseApprovalStatus next, Guid? actor, string action, string? reason) => db.RepeatUseApprovalHistories.Add(new() { Id = Guid.NewGuid(), RepeatUseApprovalRequestId = x.Id, PreviousStatus = old, NewStatus = next, ActorUserId = actor, Action = action, Reason = reason, OccurredAtUtc = DateTime.UtcNow, CreatedAtUtc = DateTime.UtcNow });
    void Audit(RepeatUseApprovalRequest x, string type, Guid? actor) => db.MerchantAuditEvents.Add(new() { Id = Guid.NewGuid(), MerchantId = x.MerchantId, ActorUserAccountId = actor, EventType = type, Detail = $"ApprovalRequestId={x.PublicApprovalRequestId}", CreatedAtUtc = DateTime.UtcNow });
    static RepeatUseDto Map(RepeatUseApprovalRequest x, string? code = null) => new(x.PublicApprovalRequestId, x.Status.ToString(), x.MaskedPhoneNumber, [.. (x.RequiresCustomerConfirmation && !x.CustomerConfirmedAtUtc.HasValue ? ["CustomerOtp"] : Array.Empty<string>()), .. (x.RequiresSupervisorApproval && !x.SupervisorApproved ? ["SupervisorApproval"] : Array.Empty<string>())], x.ExpiresAtUtc, x.Status == RepeatUseApprovalStatus.Approved ? "Repeat use approved." : "Approval required before purchase confirmation.", x.PurchaseAmount, x.CurrencyCode, x.MerchantLocationId, x.CreatorId, x.CashierId, DevelopmentCode: code);
}
