using CreatorPay.Application.Authentication;
using CreatorPay.Application.Earnings;
using CreatorPay.Domain.Enums;
using CreatorPay.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace CreatorPay.Api.Earnings;

public static class EarningsEndpoints
{
    public static IEndpointRouteBuilder MapEarningsEndpoints(this IEndpointRouteBuilder e)
    {
        var c = e.MapGroup("/api/v1/creator").RequireAuthorization("CreatorOnly"); c.MapGet("/earnings", (string? status, ICurrentUserService u, ICreatorEarningsService s, CancellationToken ct) => Run(() => s.GetEarningsAsync(u.CreatorId!.Value, status, ct))); c.MapGet("/earnings/summary", (ICurrentUserService u, IUtcClock clock, ICreatorEarningsService s, CancellationToken ct) => Run(() => s.GetSummaryAsync(u.CreatorId!.Value, clock.UtcNow, ct))); c.MapGet("/earnings/{id:guid}", (Guid id, ICurrentUserService u, ICreatorEarningsService s, CancellationToken ct) => Run(() => s.GetEarningAsync(u.CreatorId!.Value, id, ct))); c.MapGet("/ads/performance", (ICurrentUserService u, IUtcClock clock, ApplicationDbContext db, CancellationToken ct) => Run(() => CreatorAds(db, u.CreatorId!.Value, clock.UtcNow, ct))); c.MapGet("/payouts", (ICurrentUserService u, ICreatorEarningsService s, CancellationToken ct) => Run(() => s.GetPayoutsAsync(u.CreatorId, ct))); c.MapGet("/payouts/{id:guid}", (Guid id, ICurrentUserService u, ICreatorEarningsService s, CancellationToken ct) => Run(() => s.GetPayoutAsync(u.CreatorId, id, ct)));
        var a = e.MapGroup("/api/v1/admin").RequireAuthorization("AdminOperationsOnly"); a.MapGet("/payout-cycles/creators", (ApplicationDbContext db, IUtcClock clock, CancellationToken ct) => Run(() => Cycle(db, clock.UtcNow, false, ct))); a.MapGet("/payout-cycles/shoppers", (ApplicationDbContext db, IUtcClock clock, CancellationToken ct) => Run(() => Cycle(db, clock.UtcNow, true, ct))); a.MapGet("/payout-cycles/platform-revenue", (ApplicationDbContext db, IUtcClock clock, CancellationToken ct) => Run(() => Revenue(db, clock.UtcNow, ct))); a.MapGet("/payout-history/creators", (ApplicationDbContext db, string? search, DateTime? fromUtc, DateTime? toUtc, string? status, int? page, int? pageSize, CancellationToken ct) => Run(() => CreatorHistory(db, search, fromUtc, toUtc, status, page ?? 1, pageSize ?? 25, ct))); a.MapGet("/payout-history/shoppers", (ApplicationDbContext db, string? search, DateTime? fromUtc, DateTime? toUtc, string? status, int? page, int? pageSize, CancellationToken ct) => Run(() => ShopperHistory(db, search, fromUtc, toUtc, status, page ?? 1, pageSize ?? 25, ct))); a.MapGet("/payout-batches", (ICreatorEarningsService s, CancellationToken ct) => Run(() => s.GetBatchesAsync(ct))); a.MapPost("/payout-batches", (CreatePayoutBatchRequest r, ICurrentUserService u, IUtcClock clock, ICreatorEarningsService s, CancellationToken ct) => Run(() => s.CreateBatchAsync(r, u.UserAccountId!.Value, clock.UtcNow, ct), 201)); a.MapGet("/payout-batches/{id:guid}", (Guid id, ICreatorEarningsService s, CancellationToken ct) => Run(() => s.GetBatchAsync(id, ct))); a.MapPost("/payout-batches/{id:guid}/process", (Guid id, ICurrentUserService u, IUtcClock clock, ICreatorEarningsService s, CancellationToken ct) => Run(() => s.ProcessBatchAsync(id, u.UserAccountId!.Value, clock.UtcNow, ct))); a.MapPost("/payout-batches/{id:guid}/cancel", (Guid id, ICurrentUserService u, IUtcClock clock, ICreatorEarningsService s, CancellationToken ct) => Run(() => s.CancelBatchAsync(id, u.UserAccountId!.Value, clock.UtcNow, ct)));
        a.MapGet("/payouts", (ICreatorEarningsService s, CancellationToken ct) => Run(() => s.GetPayoutsAsync(null, ct))); a.MapGet("/payouts/{id:guid}", (Guid id, ICreatorEarningsService s, CancellationToken ct) => Run(() => s.GetPayoutAsync(null, id, ct))); a.MapPost("/payouts/{id:guid}/submit", (Guid id, SubmitPayoutRequest r, ICurrentUserService u, IUtcClock clock, ICreatorEarningsService s, CancellationToken ct) => Run(() => s.SubmitAsync(id, r, u.UserAccountId!.Value, clock.UtcNow, ct))); a.MapPost("/payouts/{id:guid}/mark-paid", (Guid id, ICurrentUserService u, IUtcClock clock, ICreatorEarningsService s, CancellationToken ct) => Run(() => s.MarkPaidAsync(id, u.UserAccountId!.Value, clock.UtcNow, ct))); a.MapPost("/payouts/{id:guid}/mark-failed", (Guid id, FailPayoutRequest r, ICurrentUserService u, IUtcClock clock, ICreatorEarningsService s, CancellationToken ct) => Run(() => s.MarkFailedAsync(id, r, u.UserAccountId!.Value, clock.UtcNow, ct))); a.MapPost("/payouts/{id:guid}/retry", (Guid id, ICurrentUserService u, IUtcClock clock, ICreatorEarningsService s, CancellationToken ct) => Run(() => s.RetryAsync(id, u.UserAccountId!.Value, clock.UtcNow, ct))); a.MapPost("/payouts/{id:guid}/cancel", (Guid id, ICurrentUserService u, IUtcClock clock, ICreatorEarningsService s, CancellationToken ct) => Run(() => s.CancelPayoutAsync(id, u.UserAccountId!.Value, clock.UtcNow, ct))); a.MapPost("/earnings/mature", (ICurrentUserService u, IUtcClock clock, ICreatorEarningsService s, CancellationToken ct) => Run(() => s.MatureAsync(clock.UtcNow, u.UserAccountId!.Value, ct))); return e;
    }
    static async Task<PayoutHistoryPage> CreatorHistory(ApplicationDbContext db, string? search, DateTime? from, DateTime? to, string? status, int page, int pageSize, CancellationToken ct)
    {
        page = Math.Max(1, page); pageSize = Math.Clamp(pageSize, 1, 100); var q = from p in db.CreatorPayouts.AsNoTracking() join b in db.PayoutBatches.AsNoTracking() on p.PayoutBatchId equals b.Id join c in db.Creators.AsNoTracking() on p.CreatorId equals c.Id select new { p, b, c };
        if (!string.IsNullOrWhiteSpace(search)) { var s = search.Trim().ToLower(); q = q.Where(x => x.c.DisplayName.ToLower().Contains(s) || x.c.CreatorCode.ToLower().Contains(s) || x.c.PublicCreatorId.ToLower().Contains(s) || x.p.PublicPayoutId.ToLower().Contains(s) || x.b.PublicBatchId.ToLower().Contains(s)); }
        if (from.HasValue) q = q.Where(x => x.p.ScheduledAtUtc >= from.Value); if (to.HasValue) q = q.Where(x => x.p.ScheduledAtUtc < to.Value); if (!string.IsNullOrWhiteSpace(status) && Enum.TryParse<CreatorPayoutStatus>(status, true, out var parsed)) q = q.Where(x => x.p.Status == parsed);
        var total = await q.CountAsync(ct); var totalPaid = await q.Where(x => x.p.Status == CreatorPayoutStatus.Paid).SumAsync(x => (decimal?)x.p.Amount, ct) ?? 0m;
        var rows = await q.OrderByDescending(x => x.p.ScheduledAtUtc).Skip((page - 1) * pageSize).Take(pageSize).Select(x => new PayoutHistoryRow(x.c.DisplayName, string.IsNullOrWhiteSpace(x.c.CreatorCode) ? x.c.PublicCreatorId : x.c.CreatorCode, x.b.CutoffAtUtc.AddDays(-7), x.b.CutoffAtUtc, x.p.PaidAtUtc ?? x.p.ScheduledAtUtc, x.p.Amount, x.p.Status == CreatorPayoutStatus.Paid ? x.p.Amount : 0m, x.p.Status.ToString(), x.p.PublicPayoutId, x.b.PublicBatchId)).ToListAsync(ct);
        return new(rows, page, pageSize, total, totalPaid);
    }
    static async Task<PayoutHistoryPage> ShopperHistory(ApplicationDbContext db, string? search, DateTime? from, DateTime? to, string? status, int page, int pageSize, CancellationToken ct)
    {
        page = Math.Max(1, page); pageSize = Math.Clamp(pageSize, 1, 100); var q = from p in db.CustomerPayoutRequests.AsNoTracking() join c in db.Customers.AsNoTracking() on p.CustomerId equals c.Id select new { p, c };
        if (!string.IsNullOrWhiteSpace(search)) { var s = search.Trim().ToLower(); q = q.Where(x => x.c.DisplayName.ToLower().Contains(s) || x.c.PublicCustomerId.ToLower().Contains(s) || x.p.PublicPayoutId.ToLower().Contains(s)); }
        if (from.HasValue) q = q.Where(x => x.p.RequestedAtUtc >= from.Value); if (to.HasValue) q = q.Where(x => x.p.RequestedAtUtc < to.Value); if (!string.IsNullOrWhiteSpace(status) && Enum.TryParse<CustomerPayoutStatus>(status, true, out var parsed)) q = q.Where(x => x.p.Status == parsed);
        var total = await q.CountAsync(ct); var totalPaid = await q.Where(x => x.p.Status == CustomerPayoutStatus.Paid).SumAsync(x => (decimal?)x.p.Amount, ct) ?? 0m;
        var raw = await q.OrderByDescending(x => x.p.RequestedAtUtc).Skip((page - 1) * pageSize).Take(pageSize).Select(x => new { x.p, x.c }).ToListAsync(ct);
        var rows = raw.Select(x => { var start = new DateTime(x.p.RequestedAtUtc.Year, x.p.RequestedAtUtc.Month, 1, 0, 0, 0, DateTimeKind.Utc); var cutoff = new DateTime(x.p.RequestedAtUtc.Year, x.p.RequestedAtUtc.Month, DateTime.DaysInMonth(x.p.RequestedAtUtc.Year, x.p.RequestedAtUtc.Month), 23, 59, 59, DateTimeKind.Utc); return new PayoutHistoryRow(string.IsNullOrWhiteSpace(x.c.DisplayName) ? x.c.PublicCustomerId : x.c.DisplayName, x.c.PublicCustomerId, start, cutoff, x.p.PaidAtUtc ?? x.p.RequestedAtUtc, x.p.Amount, x.p.Status == CustomerPayoutStatus.Paid ? x.p.Amount : 0m, x.p.Status.ToString(), x.p.PublicPayoutId, null); }).ToList();
        return new(rows, page, pageSize, total, totalPaid);
    }
    static async Task<PayoutCycleReport> Cycle(ApplicationDbContext db, DateTime now, bool shoppers, CancellationToken ct)
    {
        var setting = await db.PlatformFinancialSettings.AsNoTracking().SingleOrDefaultAsync(x => x.CurrencyCode == "ETB", ct); var schedule = await db.PayoutScheduleVersions.AsNoTracking().Where(x => x.CurrencyCode == "ETB" && x.EffectiveFromUtc <= now).OrderByDescending(x => x.EffectiveFromUtc).ThenByDescending(x => x.VersionNumber).FirstOrDefaultAsync(ct);
        var cutoffDay = shoppers ? schedule?.ShopperCutoffDay ?? setting?.ShopperCutoffDay ?? 0 : (int)(schedule?.CreatorCutoffDay ?? setting?.CreatorCutoffDay ?? DayOfWeek.Friday); var cutoffTime = shoppers ? schedule?.ShopperCutoffTime ?? setting?.ShopperCutoffTime ?? TimeSpan.Zero : schedule?.CreatorCutoffTime ?? setting?.CreatorCutoffTime ?? TimeSpan.Zero; var payoutDay = shoppers ? schedule?.ShopperPayoutDay ?? setting?.ShopperPayoutDay ?? 1 : (int)(schedule?.CreatorPayoutDay ?? setting?.CreatorPayoutDay ?? DayOfWeek.Saturday);
        var start = shoppers ? PayoutSchedule.PreviousMonthlyCutoff(now, cutoffDay, cutoffTime) : PayoutSchedule.PreviousWeeklyCutoff(now, (DayOfWeek)cutoffDay, cutoffTime); var cutoff = shoppers ? PayoutSchedule.NextMonthly(now, cutoffDay, cutoffTime) : PayoutSchedule.NextWeekly(now, (DayOfWeek)cutoffDay, cutoffTime); var payout = shoppers ? PayoutSchedule.NextMonthly(now, payoutDay, TimeSpan.Zero) : PayoutSchedule.NextWeekly(now, (DayOfWeek)payoutDay, cutoffTime);
        if (!shoppers)
        {
            var earnings = await db.CreatorEarnings.AsNoTracking().Where(x => x.CurrencyCode == "ETB" && x.EarnedAtUtc >= start && x.EarnedAtUtc < cutoff && x.Status != CreatorEarningStatus.Reversed).ToListAsync(ct); var payouts = await db.CreatorPayouts.AsNoTracking().Where(x => x.CurrencyCode == "ETB" && x.CreatedAtUtc >= start && x.CreatedAtUtc < cutoff).ToListAsync(ct); var creatorIds = earnings.Select(x => x.CreatorId).Concat(payouts.Select(x => x.CreatorId)).Distinct().ToArray(); var names = await db.Creators.AsNoTracking().Where(x => creatorIds.Contains(x.Id)).ToDictionaryAsync(x => x.Id, ct); var lines = creatorIds.Select(id => { var creatorEarnings = earnings.Where(x => x.CreatorId == id).ToList(); var latest = payouts.Where(x => x.CreatorId == id).OrderByDescending(x => x.CreatedAtUtc).FirstOrDefault(); var eligible = creatorEarnings.Where(x => x.Status is CreatorEarningStatus.Pending or CreatorEarningStatus.Available).Sum(x => x.Amount); var reserved = creatorEarnings.Where(x => x.Status == CreatorEarningStatus.ScheduledForPayout).Sum(x => x.Amount); var status = reserved > 0 || eligible > 0 ? "UNPAID" : latest?.Status == CreatorPayoutStatus.Paid ? "PAID" : "UNPAID"; return new PayoutCycleLine(names[id].CreatorCode, names[id].DisplayName, eligible, reserved, status, latest?.Id, latest?.PayoutBatchId); }).ToList(); var history = await db.PayoutBatches.AsNoTracking().OrderByDescending(x => x.CutoffAtUtc).Take(24).Select(x => new PayoutCycleHistory(x.CutoffAtUtc.AddDays(-7), x.CutoffAtUtc, x.ScheduledForUtc, x.TotalCreatorCount, x.TotalAmount, x.Status.ToString())).ToListAsync(ct); var creatorLast = await db.CreatorPayouts.Where(x => x.Status == CreatorPayoutStatus.Paid).MaxAsync(x => (DateTime?)x.PaidAtUtc, ct); return new("ETB", start, cutoff, payout, lines.Sum(x => x.EligibleAmount), lines.Sum(x => x.ReservedAmount), payouts.Where(x => x.Status == CreatorPayoutStatus.Paid).Sum(x => x.Amount), lines, history, creatorLast);
        }
        var entries = await db.CustomerCashbackEntries.AsNoTracking().Where(x => x.CurrencyCode == "ETB" && x.EntryType == CustomerCashbackEntryType.Earned && x.CreatedAtUtc >= start && x.CreatedAtUtc < cutoff).ToListAsync(ct); var requests = await db.CustomerPayoutRequests.AsNoTracking().Where(x => x.CurrencyCode == "ETB" && x.RequestedAtUtc >= start && x.RequestedAtUtc < cutoff).ToListAsync(ct); var customerIds = entries.Select(x => x.CustomerId).Concat(requests.Select(x => x.CustomerId)).Distinct().ToArray(); var customers = await db.Customers.AsNoTracking().Where(x => customerIds.Contains(x.Id)).ToDictionaryAsync(x => x.Id, ct); var wallets = await db.CustomerWallets.AsNoTracking().Where(x => customerIds.Contains(x.CustomerId) && x.CurrencyCode == "ETB").ToDictionaryAsync(x => x.CustomerId, ct); var shopperLines = customerIds.Select(id => { var latest = requests.Where(x => x.CustomerId == id).OrderByDescending(x => x.RequestedAtUtc).FirstOrDefault(); var wallet = wallets.GetValueOrDefault(id); var eligible = wallet?.AvailableCashback ?? 0; var reserved = wallet?.ReservedCashback ?? 0; var status = reserved > 0 || eligible > 0 ? "UNPAID" : latest?.Status == CustomerPayoutStatus.Paid ? "PAID" : "UNPAID"; return new PayoutCycleLine(customers[id].PublicCustomerId, string.IsNullOrWhiteSpace(customers[id].DisplayName) ? customers[id].PublicCustomerId : customers[id].DisplayName, eligible, reserved, status, latest?.Id); }).ToList(); var shopperHistory = await db.CustomerPayoutRequests.AsNoTracking().Where(x => x.Status == CustomerPayoutStatus.Paid).GroupBy(x => new { x.RequestedAtUtc.Year, x.RequestedAtUtc.Month }).OrderByDescending(x => x.Key.Year).ThenByDescending(x => x.Key.Month).Take(24).Select(x => new PayoutCycleHistory(new DateTime(x.Key.Year, x.Key.Month, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(x.Key.Year, x.Key.Month, DateTime.DaysInMonth(x.Key.Year, x.Key.Month), 0, 0, 0, DateTimeKind.Utc), x.Max(y => y.PaidAtUtc)!.Value, x.Select(y => y.CustomerId).Distinct().Count(), x.Sum(y => y.Amount), "Paid")).ToListAsync(ct); var shopperLast = await db.CustomerPayoutRequests.Where(x => x.Status == CustomerPayoutStatus.Paid).MaxAsync(x => (DateTime?)x.PaidAtUtc, ct); return new("ETB", start, cutoff, payout, shopperLines.Sum(x => x.EligibleAmount), shopperLines.Sum(x => x.ReservedAmount), requests.Where(x => x.Status == CustomerPayoutStatus.Paid).Sum(x => x.Amount), shopperLines, shopperHistory, shopperLast);
    }
    static async Task<PlatformRevenueReport> Revenue(ApplicationDbContext db, DateTime now, CancellationToken ct)
    { var setting = await db.PlatformFinancialSettings.AsNoTracking().SingleOrDefaultAsync(x => x.CurrencyCode == "ETB", ct); var schedule = await db.PayoutScheduleVersions.AsNoTracking().Where(x => x.CurrencyCode == "ETB" && x.EffectiveFromUtc <= now).OrderByDescending(x => x.EffectiveFromUtc).FirstOrDefaultAsync(ct); var start = PayoutSchedule.PreviousMonthlyCutoff(now, schedule?.ShopperCutoffDay ?? setting?.ShopperCutoffDay ?? 0, schedule?.ShopperCutoffTime ?? setting?.ShopperCutoffTime ?? TimeSpan.Zero); var end = PayoutSchedule.NextMonthly(now, schedule?.ShopperCutoffDay ?? setting?.ShopperCutoffDay ?? 0, schedule?.ShopperCutoffTime ?? setting?.ShopperCutoffTime ?? TimeSpan.Zero); var rows = await (from r in db.PlatformRevenueEntries join p in db.PurchaseTransactions on r.PurchaseTransactionId equals p.Id where r.CurrencyCode == "ETB" && p.TransactionDateUtc >= start && p.TransactionDateUtc < end select r).ToListAsync(ct); var history = await (from r in db.PlatformRevenueEntries join p in db.PurchaseTransactions on r.PurchaseTransactionId equals p.Id where r.CurrencyCode == "ETB" group r by new { p.TransactionDateUtc.Year, p.TransactionDateUtc.Month } into g orderby g.Key.Year descending, g.Key.Month descending select new PlatformRevenueHistory(new DateTime(g.Key.Year, g.Key.Month, 1, 0, 0, 0, DateTimeKind.Utc), new DateTime(g.Key.Year, g.Key.Month, DateTime.DaysInMonth(g.Key.Year, g.Key.Month), 23, 59, 59, DateTimeKind.Utc), g.Select(x => x.PurchaseTransactionId).Distinct().Count(), g.Sum(x => x.Amount))).Take(24).ToListAsync(ct); return new("ETB", start, end, rows.Sum(x => x.Amount), rows.Select(x => x.PurchaseTransactionId).Distinct().Count(), history); }
    static async Task<CreatorAdPerformanceReport> CreatorAds(ApplicationDbContext db, Guid creatorId, DateTime now, CancellationToken ct)
    {
        var relationships = await (from p in db.MerchantCreatorPartnerships.AsNoTracking()
                                   join m in db.Merchants.AsNoTracking() on p.MerchantId equals m.Id
                                   where p.CreatorId == creatorId && (p.Status == PartnershipStatus.Approved || p.Status == PartnershipStatus.Suspended || p.Status == PartnershipStatus.Revoked || p.Status == PartnershipStatus.Expired || p.Status == PartnershipStatus.Blocked)
                                   select new { p.Id, p.MerchantId, BusinessName = m.TradingName, p.Status, p.EndDateUtc }).ToListAsync(ct);
        var relationshipIds = relationships.Select(x => x.Id).ToArray();
        var transactions = await (from earning in db.CreatorEarnings.AsNoTracking()
                                  join transaction in db.PurchaseTransactions.AsNoTracking() on earning.PurchaseTransactionId equals transaction.Id
                                  join merchant in db.Merchants.AsNoTracking() on transaction.MerchantId equals merchant.Id
                                  where earning.CreatorId == creatorId && relationshipIds.Contains(transaction.MerchantCreatorPartnershipId) && (transaction.Status == TransactionStatus.Confirmed || transaction.Status == TransactionStatus.Settled)
                                  orderby transaction.ConfirmedAtUtc descending, transaction.TransactionDateUtc descending
                                  select new CreatorAdTransactionRow(transaction.Id, transaction.MerchantCreatorPartnershipId, transaction.MerchantId, merchant.TradingName, transaction.ConfirmedAtUtc ?? transaction.TransactionDateUtc, "Confirmed", earning.Amount, earning.CurrencyCode)).ToListAsync(ct);
        var totals = transactions.GroupBy(x => x.PartnershipId).ToDictionary(x => x.Key, x => new { Count = x.Count(), Earned = x.Sum(y => y.CreatorEarned), Currency = x.Select(y => y.CurrencyCode).FirstOrDefault() ?? "ETB" });
        var businesses = relationships.Select(x => { var total = totals.GetValueOrDefault(x.Id); var status = x.Status == PartnershipStatus.Approved && x.EndDateUtc > now ? "Active" : x.Status == PartnershipStatus.Approved || x.Status == PartnershipStatus.Expired ? "Expired" : "Deactivated"; return new CreatorAdPerformanceRow(x.Id, x.MerchantId, x.BusinessName, status, x.EndDateUtc, total?.Count ?? 0, total?.Earned ?? 0, total?.Currency ?? "ETB"); }).OrderBy(x => x.Status == "Active" ? 0 : x.Status == "Deactivated" ? 1 : 2).ThenBy(x => x.BusinessName).ToList();
        return new(businesses, transactions);
    }
    private static async Task<IResult> Run<T>(Func<Task<T>> f, int status = 200) { try { var x = await f(); return Results.Json(x, statusCode: status); } catch (KeyNotFoundException x) { return Results.Problem(statusCode: 404, title: "Not found", detail: x.Message); } catch (ArgumentException x) { return Results.Problem(statusCode: 400, title: "Invalid request", detail: x.Message); } catch (InvalidOperationException x) { return Results.Problem(statusCode: 409, title: "Operation rejected", detail: x.Message); } }
}
