using CreatorPay.Application.Authentication;
using CreatorPay.Application.Earnings;

namespace CreatorPay.Api.Earnings;

public static class EarningsEndpoints
{
    public static IEndpointRouteBuilder MapEarningsEndpoints(this IEndpointRouteBuilder e)
    {
        var c = e.MapGroup("/api/v1/creator").RequireAuthorization("CreatorOnly"); c.MapGet("/earnings", (string? status, ICurrentUserService u, ICreatorEarningsService s, CancellationToken ct) => Run(() => s.GetEarningsAsync(u.CreatorId!.Value, status, ct))); c.MapGet("/earnings/summary", (ICurrentUserService u, IUtcClock clock, ICreatorEarningsService s, CancellationToken ct) => Run(() => s.GetSummaryAsync(u.CreatorId!.Value, clock.UtcNow, ct))); c.MapGet("/earnings/{id:guid}", (Guid id, ICurrentUserService u, ICreatorEarningsService s, CancellationToken ct) => Run(() => s.GetEarningAsync(u.CreatorId!.Value, id, ct))); c.MapGet("/payouts", (ICurrentUserService u, ICreatorEarningsService s, CancellationToken ct) => Run(() => s.GetPayoutsAsync(u.CreatorId, ct))); c.MapGet("/payouts/{id:guid}", (Guid id, ICurrentUserService u, ICreatorEarningsService s, CancellationToken ct) => Run(() => s.GetPayoutAsync(u.CreatorId, id, ct)));
        var a = e.MapGroup("/api/v1/admin").RequireAuthorization("PlatformAdminOnly"); a.MapGet("/payout-batches", (ICreatorEarningsService s, CancellationToken ct) => Run(() => s.GetBatchesAsync(ct))); a.MapPost("/payout-batches", (CreatePayoutBatchRequest r, ICurrentUserService u, IUtcClock clock, ICreatorEarningsService s, CancellationToken ct) => Run(() => s.CreateBatchAsync(r, u.UserAccountId!.Value, clock.UtcNow, ct), 201)); a.MapGet("/payout-batches/{id:guid}", (Guid id, ICreatorEarningsService s, CancellationToken ct) => Run(() => s.GetBatchAsync(id, ct))); a.MapPost("/payout-batches/{id:guid}/process", (Guid id, ICurrentUserService u, IUtcClock clock, ICreatorEarningsService s, CancellationToken ct) => Run(() => s.ProcessBatchAsync(id, u.UserAccountId!.Value, clock.UtcNow, ct))); a.MapPost("/payout-batches/{id:guid}/cancel", (Guid id, ICurrentUserService u, IUtcClock clock, ICreatorEarningsService s, CancellationToken ct) => Run(() => s.CancelBatchAsync(id, u.UserAccountId!.Value, clock.UtcNow, ct)));
        a.MapGet("/payouts", (ICreatorEarningsService s, CancellationToken ct) => Run(() => s.GetPayoutsAsync(null, ct))); a.MapGet("/payouts/{id:guid}", (Guid id, ICreatorEarningsService s, CancellationToken ct) => Run(() => s.GetPayoutAsync(null, id, ct))); a.MapPost("/payouts/{id:guid}/submit", (Guid id, SubmitPayoutRequest r, ICurrentUserService u, IUtcClock clock, ICreatorEarningsService s, CancellationToken ct) => Run(() => s.SubmitAsync(id, r, u.UserAccountId!.Value, clock.UtcNow, ct))); a.MapPost("/payouts/{id:guid}/mark-paid", (Guid id, ICurrentUserService u, IUtcClock clock, ICreatorEarningsService s, CancellationToken ct) => Run(() => s.MarkPaidAsync(id, u.UserAccountId!.Value, clock.UtcNow, ct))); a.MapPost("/payouts/{id:guid}/mark-failed", (Guid id, FailPayoutRequest r, ICurrentUserService u, IUtcClock clock, ICreatorEarningsService s, CancellationToken ct) => Run(() => s.MarkFailedAsync(id, r, u.UserAccountId!.Value, clock.UtcNow, ct))); a.MapPost("/payouts/{id:guid}/retry", (Guid id, ICurrentUserService u, IUtcClock clock, ICreatorEarningsService s, CancellationToken ct) => Run(() => s.RetryAsync(id, u.UserAccountId!.Value, clock.UtcNow, ct))); a.MapPost("/payouts/{id:guid}/cancel", (Guid id, ICurrentUserService u, IUtcClock clock, ICreatorEarningsService s, CancellationToken ct) => Run(() => s.CancelPayoutAsync(id, u.UserAccountId!.Value, clock.UtcNow, ct))); a.MapPost("/earnings/mature", (ICurrentUserService u, IUtcClock clock, ICreatorEarningsService s, CancellationToken ct) => Run(() => s.MatureAsync(clock.UtcNow, u.UserAccountId!.Value, ct))); return e;
    }
    private static async Task<IResult> Run<T>(Func<Task<T>> f, int status = 200) { try { var x = await f(); return Results.Json(x, statusCode: status); } catch (KeyNotFoundException x) { return Results.Problem(statusCode: 404, title: "Not found", detail: x.Message); } catch (ArgumentException x) { return Results.Problem(statusCode: 400, title: "Invalid request", detail: x.Message); } catch (InvalidOperationException x) { return Results.Problem(statusCode: 409, title: "Operation rejected", detail: x.Message); } }
}
